### ISSUE TITLE
Problem in setup fonts for  Russian and Chinese

### ISSUE THREAD

**Issue by anbangli** [reutenauer/polyglossia#100]
Hi, All,

I have a problem  in setup fonts for a document containning Russian and Chinese. 

I write the following statements to set up fonts for Russian, and it is OK:

\setmainlanguage{russian}
\setotherlanguages{english,Chinese˜Simplified} 
\defaultfontfeatures{Mapping=tex-text}  % 启用tex风格字符
\setmainfont{Times New Roman}           % 英文缺省字体

Since the font "Times New Roman" does not support chinese, I have to set another font for Chinese. According polyglossia's manual (c:\texlive\2014\texmf-dist\doc\latex\polyglossia\polyglossia.pdf), I wrote the following statement: 
    \newfontfamily\chinesefont[language=Chinese˜Simplified]{Microsoft YaHei}
but I got the following error message:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/key-unknown"
! 
! The key 'fontspec/language' is unknown and is being ignored.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

l.17 ...uage=Chinese˜Simplified]{Microsoft YaHei}

Are there any advise?

**Comment by eg9** [comment]
There is currently no support for Chinese in Polyglossia. You should use xeCJK.

This space is for bringing up issues with Polyglossia, and this isn't one.

**Comment by jspitz** [comment]
Not a polyglossia bug. Please close ticket.
