### ISSUE TITLE
Setting main language russian brokes hyphenchar setting of fontspec

### ISSUE THREAD

**Issue by Lenchik** [reutenauer/polyglossia#106]
```tex
% !TeX program = lualatex
\documentclass[a4paper]{report}
\usepackage{polyglossia}
\setmainlanguage{russian}
\newfontfamily\cyrillicfont{Linux Libertine O}

\begin{document}
    \def\text{\fbox{\parbox{1.55cm}{%
    EXAMPLE HYPHENATION%
    }}\qquad\qquad\null\par\bigskip}
    
    \fontspec{Linux Libertine O}
    \addfontfeature{HyphenChar=None}
    \text
    \addfontfeature{HyphenChar={+}}
    \text
    \addfontfeature{HyphenChar={"002D}}
    \text
\end{document}
```
While ```\setmainlanguage{russian}``` is set and this example is compiled by **LuaLaTeX** all three sample texts looks same --- no hyphenation. **XeLaTeX** affected too.

Another example:
```tex
\documentclass[a4paper]{report}
\usepackage{polyglossia}
\setmainlanguage{russian}
\setotherlanguage{english} 
\newfontfamily\cyrillicfont{Linux Libertine O}

\begin{document}
    \def\text{\fbox{\parbox{1.55cm}{%
    EXAMPLE HYPHENATION%
    }}\qquad\qquad\null\par\bigskip}
\begin{english}    
    \fontspec{Linux Libertine O}
    \addfontfeature{HyphenChar=None}
    \text
    \addfontfeature{HyphenChar={+}}
    \text
    \addfontfeature{HyphenChar={"002D}}
    \text
\end{english}    
    \def\textrus{\fbox{\parbox{1.55cm}{%
    Предложение с~переносом слова-теста еле-еле.%
    }}\qquad\qquad\null\par\bigskip}
\begin{russian}
    \fontspec{Linux Libertine O}
    \addfontfeature{HyphenChar=None}
    \textrus
    \addfontfeature{HyphenChar={+}}
    \textrus
    \addfontfeature{HyphenChar={"002D}}
    \textrus
\end{russian} 
    
\end{document}
```
Result of XeLaTeX compilation: 
![xelatex-example2](https://cloud.githubusercontent.com/assets/2931130/9197842/6ed89674-4040-11e5-8c9e-d5f5c892584c.png)
Result of LuaLaTeX compilation: 
![lualatex-example2](https://cloud.githubusercontent.com/assets/2931130/9197849/7f4e58d6-4040-11e5-8210-9424b28a4f0e.png)

Notice difference in hyphenation (because of compiler selection) and no effect of HyphenChar setting (despite compiler selection and language settings) on russian text.

**Comment by reutenauer** [comment]
Thanks for the report, there is something strange going on indeed.  I’ll run some more tests and will get back to you.

**Comment by eg9** [comment]
Here is the output of the Russian test when I omit the `\fontspec` instruction:

<img width="157" alt="screen shot 2015-08-13 at 10 43 42" src="https://cloud.githubusercontent.com/assets/302839/9245928/4a5c0920-41a8-11e5-8f8a-7ed94f2b8e6e.png">

**Comment by reutenauer** [comment]
Thanks Enrico; it does seem quite likely that the bug is with fontspec.  I’ll narrow it down and submit a report to fontspec.

**Comment by Lenchik** [comment]
Any updates in narrowing bug?
