### ISSUE TITLE
define latinalph for all language

### ISSUE THREAD

**Issue by maieul** [reutenauer/polyglossia#108]
Hi, now, some language, as tibetan, define a \@latinalph let to \@alph.

It should be nice to define a general \@latinalph for all language, let to \alph. It will allow to do some setting for other package in the preamble independently of the language. I also thinks it will be sure, because if I call tibetan after a language which has not the standard definition of \@alph, \@latinalph won't have the standard definition too. And that was the aim.

**Comment by jspitz** [comment]
`\@latinalph` is  centrally defined in polyglossia.sty.

This ticket can be closed.
