### ISSUE TITLE
use LuaTeX's new \hyphenationmin

### ISSUE THREAD

**Issue by eroux** [reutenauer/polyglossia#111]
LuaTeX [implemented](https://foundry.supelec.fr/scm/viewvc.php?view=rev&root=luatex&revision=5299) [\hyphenationmin](http://tracker.luatex.org/view.php?id=930), and XeTeX might (who knows?). It would be great if polyglossia could take advantage of it. In order for things to be backward-compatible, I propose to change the `hyphenmin` option to have 5 arguments: 
- _left_ (same as current)
- _right_ (same as current)
- _total_ (argument of \hyphenationmin, defaults to 1)
- _leftIfTotal_ (lefthyphenmin in the case where `\hyphenationmin` is available, default to _left_)
- _rightIfTotal_ (same for righthyphenmin)

What do you think?

**Comment by jspitz** [comment]
>     * _leftIfTotal_ (lefthyphenmin in the case where `\hyphenationmin` is available, default to _left_)
> 
>     * _rightIfTotal_ (same for righthyphenmin)

I don't understand these two. Could you give examples?

As to the implementation, I think it would be easier to add another key (`nohyphenlen`?)

**Comment by jspitz** [comment]
I've now implemented a new `totalhyphenmin` gloss option. It is set to 5 for spanish (other than stated in the LuaTeX manual, the value is the number of characters from which on hyphenation will be done,
so `4` would still hyphenate _come_, while `5` doesn't)

**Comment by eroux** [comment]
excellent, thanks a lot!

**Comment by eg9** [comment]
I'm not sure why the implementation has
```
   \ifluatex
     % Set \totalhyphenmin if specified
     \prop_get:NxNTF \polyglossia@langsetup {#2/totalhyphenmin} \l_tmpa_tl
     {
        \xpg@warning{totalhyphenmin: '\l_tmpa_tl'}
        \expandafter\hyphenationmin \l_tmpa_tl%
     }%
     {}%
```
with `\xpg@warning` instead of `\xpg@info`. This results in annoying and useless warnings, see https://tex.stackexchange.com/q/632192/4427

**Comment by jspitz** [comment]
> with `\xpg@warning` instead of `\xpg@info`. This results in annoying and useless warnings, see https://tex.stackexchange.com/q/632192/4427

Agreed, changed.
