### ISSUE TITLE
Polyglossia should offer the possibility of disabling the automatic spacing feature for French in certain contexts

### ISSUE THREAD

**Issue by ArchangeGabriel** [reutenauer/polyglossia#113]
I’m having trouble with space before colons in bibliographic elements (e.g. `135(1) :88–90` instead of `135(1):88–90`).

With Babel I can use `\NoAutoSpaceBeforeFDP` to handle this (though with pdflatex this isn’t even necessary since `\string:` is used, but this seems not to work with Lua/XeLaTeX).

It would be nice to have a way to do this with polyglossia (maybe it exists, but then I wasn’t able to find anything about this).

Thanks!

**Comment by hugoroy** [comment]
This would be useful also when using the European Case Law Identifier system which uses ":" as a separator https://en.wikipedia.org/wiki/European_Case_Law_Identifier

**Comment by jspitz** [comment]
Could you please test if the gloss-french.ldf file here does what you want?
https://github.com/jspitz/polyglossia/blob/master/tex/gloss-french.ldf

It introduces two commands `\AutoSpacing` and `\NoAutoSpacing` to disable/enable the automatic spacings locally and a new french option `autospacing=false` to disable in globally.
