### ISSUE TITLE
Spurious space in gloss-arabic.ldf

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#115]
In gloss-arabic there is a comment char missing in the definition of \captionsarabic:

~~~~~
\def\captionsarabic{%
  \def\prefacename{\@ensure@RTL{مدخل}}%
  \def\refname{\@ensure@RTL{المراجع}}    %<---------- here
  \def\abstractname{\@ensure@RTL{ملخص}}%

~~~~~

Edit: actually there is a second spurious space in the same command:

~~~~~
\def\contentsname{\@ensure@RTL{المحتويات}}
~~~~~

**Comment by reutenauer** [comment]
Thanks Ulrike, I’ve pushed a fix for that and will see about a CTAN update soonish.

P-S: Got to that bug faster than XeTeX bug no. 117! ;-)
