### ISSUE TITLE
Add Latin transliteration as script option to Sanskrit

### ISSUE THREAD

**Issue by ppasedach** [reutenauer/polyglossia#118]
See http://tex.stackexchange.com/questions/271703/adding-default-hyphenation-for-transliterated-sanskrit#comment655741_271703 . Latin transliteration does work, but cannot explicitly be set as a script, thus using both devanagari and latin for sanskrit in one file is only possible with one font for both.

**Comment by jspitz** [comment]
It seems this has been implemented at 75d55d7a. You can now set `Script=Latin` (among other script options).
