### ISSUE TITLE
Feature request: duplicate babel's `bbl@loaded` macro

### ISSUE THREAD

**Issue by plk** [reutenauer/polyglossia#120]
The title says it all really - could this macro be implemented in polyglossia or is there an equivalent? There is a need in biblatex to obtain a (preferably csv) list of loaded languages at the end of the preamble. In babel you can just expand `bbl@loaded`.

**Comment by plk** [comment]
I see that you merged the pull request - do you know when a new version will be released?

**Comment by reutenauer** [comment]
Since it depends entirely on me making an upload to CTAN, the answer is, as usual, “whenever I’ll make an upload to CTAN”.  I’m a little busy at the moment, sorry.  But you can make an upload with just that change if you want.

**Comment by plk** [comment]
That's kind but I am not so familiar with the polyglossia packaging and I don't want to make a mistake ...

**Comment by reutenauer** [comment]
OK, I'll try to make a release around Christmas then.

**Comment by jspitz** [comment]
This is (long) resolved, right?

**Comment by reutenauer** [comment]
Yes, it should be.
