### ISSUE TITLE
Feature request: accented mathematical operators in Spanish

### ISSUE THREAD

**Issue by esteban-mendoza** [reutenauer/polyglossia#123]
Operators such as lim/lím, max/máx, min/mín, inf/ínf, etc. are usually accented in Spanish. It would be useful to have an option that accents or unaccents operators like the `\accentedoperators` or `\unaccentedoperators` commands in `babel`.

**Comment by jspitz** [comment]
Can someone give a complete list of those operators (preferably with their default definition)? Then we can implement this along the line of https://tex.stackexchange.com/a/282233/19291 (rather than the complex `babel` approach)

**Comment by jspitz** [comment]
I've implemented something similar to `babel-spanish`
