### ISSUE TITLE
Bug in polyglossia-frpt.lua

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#124]
Line 122 of the file is

```
  [byte('>')] = {left,  thinspace},
```

while it should be

```
[byte('›')] = {left,  thinspace},
```

(compare with the corresponding line for the left single guillemet).

Reference: http://tex.stackexchange.com/questions/288180/

**Comment by reutenauer** [comment]
I wonder if I didn’t at some point see this line, squinted, and
decided to gloss over it.  Clearly a typo.

  Anyway, thanks as always, Enrico, I just pushed a fix, and this will
make its way to CTAN ... at some point.

	Best,

		Arthur

**Comment by jspitz** [comment]
So this can be closed as well, right?

**Comment by jspitz** [comment]
> So this can be closed as well, right?

And this ;-)
