### ISSUE TITLE
\disablehyphenation in preamble

### ISSUE THREAD

**Issue by hmenke** [reutenauer/polyglossia#125]
This problem is isolated to `xetex`, since for `luatex` the hyphenation disabling works in another way.  In `xetex`, the `\disablehyphenation` command sets `\language=255`.  For a preamble like this

```
\usepackage{polyglossia}
\setdefaultlanguage{german}
\disablehyphenation
```

this does not work as expected, because `\setdefaultlanguage` overwrites `\language` via `\AtBeginDocument`.  The solution is to place `\disablehyphenation` either after `\begin{document}` or inside `\AtBeginDocument` in the preamble _after_ any `\setdefaultlanguage`.

This in turn raises another problem:  If one says `\disablehyphenation` once in the preamble _and_ after `\begin{document}` the effect vanishes.  That is due to the fact that `\disablehyphenation` in the preamble sets `\booltrue{xpg@hyphenation@disabled}`, then `\setdefaultlanguage` overwrites `\language` at `\begin{document}`, but the subsequent `\disablehyphenation` does not trigger as `xpg@hyphenation@disabled` is already set to true.  The following example illustrates the issue.

```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{german}
\disablehyphenation
%\AtBeginDocument{\boolfalse{xpg@hyphenation@disabled}}
\begin{document}
\disablehyphenation
Er hörte leise Schritte hinter sich. Das bedeutete nichts Gutes. Wer
würde ihm schon folgen, spät in der Nacht und dazu noch in dieser
engen Gasse mitten im übel beleumundeten Hafenviertel? Gerade jetzt,
wo er das Ding seines Lebens gedreht hatte und mit der Beute
verschwinden wollte! Hatte einer seiner zahllosen Kollegen dieselbe
Idee gehabt, ihn beobachtet und abgewartet, um ihn nun um die Früchte
seiner Arbeit zu erleichtern?
\end{document}
```

I see two possible resolutions for this:
1. Don't use `\ifbool{xpg@hyphenation@disabled}` inside of `\disablehyphenation`, but rather `\ifnum\language=\l@nohyphenation`.
2. Let `\setdefaultlanguage` track `xpg@hyphenation@disabled` to not override `\disablehyphenation`.

**Comment by jspitz** [comment]
Thanks for the report. `\disablehyphenation` is now postponed if used in preamble.
