### ISSUE TITLE
\xpg@main@language undefined for ngerman

### ISSUE THREAD

**Issue by plk** [reutenauer/polyglossia#132]
When polyglossia can't find a `*-gloss.ldf` file, it uses the macro `\xpg@nogloss` which doesn't set
`\xpg@main@language`. This makes the language string which users chose unavailable to other packages like biblatex. Can we put

```
  \gdef\xpg@main@language{#1}%
```

as the first line in `\xpg@nogloss`? Polyglossia doesn't fail in such cases, it just falls back on, for example, german.

**Comment by jspitz** [comment]
How about the idea in https://github.com/reutenauer/polyglossia/issues/112#issuecomment-524533512

**Comment by jspitz** [comment]
As of 1.46, polyglossia will understand all babel names (and load the correct language/variant/script).
