### ISSUE TITLE
\begin{otherlanguage}: Conflicting pattern ignored

### ISSUE THREAD

**Issue by Witiko** [reutenauer/polyglossia#136]
Consider the following document:

``` latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguages{german, czech, slovak}
\begin{document}
foo bar

\begin{otherlanguage}{czech}
  foo bar
\end{otherlanguage}

\begin{otherlanguage}{slovak}
  foo bar
\end{otherlanguage}

\begin{otherlanguage}{german}
  foo bar
\end{otherlanguage}
\end{document}
```

Compiling the document with LuaLaTeX from the latest TeX Live release available in the Debian _unstable_ repository (2015.20160320-1) results in the following error:

```
! Conflicting pattern ignored.
\xpg@set@language@luatex@ii ...e l@#1\endcsname )}
                                                  \fi \fi 
l.12 \begin{otherlanguage}{slovak}
```

Other notable parts of the output include:

```
(/usr/share/texlive/texmf-dist/tex/latex/polyglossia/gloss-english.ldf)
(/usr/share/texlive/texmf-dist/tex/latex/polyglossia/gloss-german.ldf

Package polyglossia Warning: \setlocalhyphenmin useless for unknown language ger
man on input line 6.


Package polyglossia Warning: You asked for `ngerman' but only `german' hyphenati
on is available! on input line 68.

(/usr/share/texlive/texmf-dist/tex/latex/polyglossia/babelsh.def))
(/usr/share/texlive/texmf-dist/tex/latex/polyglossia/gloss-czech.ldf

Package polyglossia Warning: No hyphenation patterns were loaded for `Czech'
(polyglossia)                I will use \language=\l@nohyphenation instead on in
put line 7.


Package polyglossia Warning: \setlocalhyphenmin useless for unhyphenated languag
e czech on input line 7.

) (/usr/share/texlive/texmf-dist/tex/latex/polyglossia/gloss-slovak.ldf

Package polyglossia Warning: No hyphenation patterns were loaded for `Slovak'
(polyglossia)                I will use \language=\l@nohyphenation instead on in
put line 7.


Package polyglossia Warning: \setlocalhyphenmin useless for unhyphenated languag
e slovak on input line 7.
```

The XeLaTeX format is unaffected. Downgrading to the previous version of TeX Live from the _testing_ Debian repository (2015.20160223-1) fixes the issue.

**Comment by eg9** [comment]
A possible workaround, until the issue due to changes in babel is solved, is adding `\usepackage[base]{babel}`.

    \documentclass{article}
    \usepackage[base]{babel}
    \usepackage{polyglossia}
    \setmainlanguage{english}
    \setotherlanguages{german, czech, slovak}
    \begin{document}
    foo bar \languagename=\the\language
    
    \begin{otherlanguage}{czech}
      foo bar \languagename=\the\language
    \end{otherlanguage}
    
    \begin{otherlanguage}{slovak}
      foo bar \languagename=\the\language
    \end{otherlanguage}
    
    \begin{otherlanguage}{german}
      foo bar \languagename=\the\language
    \end{otherlanguage}
    \end{document}

<img width="202" alt="screen shot 2016-03-25 at 12 17 23" src="https://cloud.githubusercontent.com/assets/302839/14043344/8f727f80-f283-11e5-91c3-88811814d307.png">

**Comment by reutenauer** [comment]
Thanks @eg9.  I’ve just made an upload to CTAN that should fix most of the problems.  @Witiko, please test when you get a chance; the new version is 1.42.4, dated today 25 March 2016.

**Comment by Witiko** [comment]
@reutenauer The update fixed the issue.

**Comment by reutenauer** [comment]
Great, glad to know that.  I’ll leave this issue open for a few days just in case.

**Comment by jspitz** [comment]
Can be closed now, right?

**Comment by reutenauer** [comment]
Yes it can, thanks.
