### ISSUE TITLE
\ifx warning when English language variant is "british"

### ISSUE THREAD

**Issue by jguaschi** [reutenauer/polyglossia#140]
Compiling the following document:

\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}

\begin{document}
Test.
\end{document}

with XeLaTeX yields a warning "\end occurred when \ifx on line 5 was incomplete". This warning disappears if "variant=british" is replaced by "variant=uk". This is a little reminiscent of issue #86.

I am running XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015), with polyglossia.sty 2015/03/25 v1.42.4.

**Comment by reutenauer** [comment]
That’s strange, I thought I had corrected that one with last month’s update.  I’ll investigate.

In any case, it’s a completely different issue than #86.

**Comment by jspitz** [comment]
This is fixed in head.

**Comment by jspitz** [comment]
Someone who can please close this ticket.
