### ISSUE TITLE
French space for guillemets

### ISSUE THREAD

**Issue by maieul** [reutenauer/polyglossia#141]
The @hugoroy commit 6bcba5a1899dca30d62f665cead8b00cb5a4be2e breaks the csquotes french guillemets

Cf this MWE

_\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}
\usepackage[french=guillemets]{csquotes} \MakeOuterQuote{"}
\begin{document}
\enquote{s}

"s"

\enquote{x}

«x»_
\end{document}
Before the commit
[before.pdf](https://github.com/reutenauer/polyglossia/files/217227/before.pdf)

After the commit 

[after.pdf](https://github.com/reutenauer/polyglossia/files/217228/after.pdf)

cf @aurelberra

**Comment by reutenauer** [comment]
Hum, that’s bad, thanks for the report.  I’ll have a look.

**Comment by maieul** [comment]
I think the problem is that ` \MakeOuterQuote{"}` already insert a space,

cf 

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}
\usepackage[french=guillemets]{csquotes} \MakeOuterQuote{"}
\makeatletter
\apptocmd{\french@punctuation}{%
     \XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace}% "«  " -> "«~"
     \XeTeXinterchartoks 255 \french@punctguillend = {\xpg@unskip\nobreakspace}% "  »" -> "~»"  
}{}{}
\makeatother
\begin{document}
\enquote{s}

"s"

\enquote{x}

« x »

" s "

«x»
\end{document}
```

**Comment by reutenauer** [comment]
Yes, clearly there’s a conflict between the two requirements.  It’s really not clear to me what’s the best choice is.

**Comment by aurelberra** [comment]
Indeed. Uncommenting the lines which deal with 255 + quotes in
gloss-french.ldf solves the problem, I think.

A.

**Comment by maieul** [comment]
@aurelberra it solve us problem, but reinstall @hugoroy  problem :-)

**Comment by aurelberra** [comment]
Yes, sorry: I had missed the motivation for the commit. But isn't it a
clear logical principle to simplify input (" or «) or make it semantic
(\enquote) rather than mix it with content («\space) ?

**Comment by maieul** [comment]
> Yes, sorry: I had missed the motivation for the commit. But isn't it a
> clear logical principle to simplify input (" or �) or make it semantic
> (\enquote) rather than mix it with content (�\space) ?
> 

yes indeed, but it should be to automatically clean the �\space, and I think Arthur will find the way ;-)

**Comment by maieul** [comment]
hi @reutenauer some news about this issue ?

**Comment by maieul** [comment]
`     \XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace\ignorespaces}% "«  " -> "«~"`
seems to be the good one. Allow both <code>« s »</code> and  <code>«s»</code>

**Comment by maieul** [comment]
ah thats does not work for <code>" s "</code>

**Comment by maieul** [comment]
but for <code>" s "</code> concerned csquotes, and so it is a bug in this one. So I suggest to integrate my solution, and I will open an issue for csquotes.

**Comment by hugoroy** [comment]
> \XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace\ignorespaces}% "« " -> "«~"
> seems to be the good one. Allow both « s » and «s»

No because it does not work for «~s~»

**Comment by maieul** [comment]
hum,  in this case I afraid the only solution will be to add an option.
But the default one should be the historical behavior: automatically inserting space.

**Comment by hugoroy** [comment]
Wouln't be better fixed in csquotes? If I understand correctly, everything works fine except in combination with csquotes.

**Comment by maieul** [comment]
hum… maybe we should test for <code>«~s~»</code> in csquotes.

**Comment by hugoroy** [comment]
Yes I think so, especially because this facilitates compatibility with document written with babel/latex in mind and probably other contexts as well.
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by aurelberra** [comment]
I also think that this is to be dealt with in the `csquotes` issue opened by @maieul.

**Comment by maieul** [comment]
The csquotes mainteners close the issue.

I suggest to revert the commit @hugoroy and to come back to the previous behavior. No one should add space around guillemet in the code.

Maybe we could get the code of @hugoroy as an option, but not the default behavior.

**Comment by aurelberra** [comment]
I fully agree with @maieul's proposal. Such spaces should be an option.

**Comment by aurelberra** [comment]
I would like to know if there has been any progress on this problem. Cf. #145.

**Comment by ArchangeGabriel** [comment]
I’m not sure what this issue is about, but I personally type thing as `« s »` or `« s »` when thin unbreakable spaces are not supported by the other people working with me on a doc. Because I want my source code to already be the most typographically right as possible.

Anyway, I’ve been using Babel for a long time now since it now seems to be superior to polyglossia, at least for my use.

**Comment by maieul** [comment]
I think that is a bad idea. The code should be as simple as possible, and the engines should make the result typographically right.

**Comment by ArchangeGabriel** [comment]
I’m concerned about being able to extract my “code” and use it in something else than a LaTeX document without having to run a script on it or modify things by hand. But anyway, I’m not an user of polyglossia, so if you’re all fine with that then it’s your right. ;)

**Comment by jspitz** [comment]
This problem is apparently solved in current master. The MWE
```
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}
\usepackage[french=guillemets]{csquotes}
\MakeOuterQuote{"}

\begin{document}
	\enquote{x}
	
	"x"
	
	\enquote{x}
	
	«x»
	
	« x »
\end{document}
```
comes out with the same spacing in all quote variants (see
[texstudio_fFbKBr.pdf](https://github.com/reutenauer/polyglossia/files/3539610/texstudio_fFbKBr.pdf)).

@maieul if this output looks correct to you, please close the ticket.

**Comment by maieul** [comment]
yes, of course, I did the pull request. @jspitz are you the new maintener for polyglossia?

**Comment by reutenauer** [comment]
No, he’s just a volunteer.
