### ISSUE TITLE
tags 1.42.x + file date

### ISSUE THREAD

**Issue by maieul** [reutenauer/polyglossia#142]
Looking for writing a short article on #141, I was:
- not able to find tags for the 1.42x release, and so let know when the problem appears publicly in CTAN
- see that the handbook on CTAN tell "2015/03/25" as date and not "2016/03/25"

**Comment by reutenauer** [comment]
* I just pushed the tags for 1.42.1 to 1.42.4, but note only 1.42.4 was uploaded to CTAN
* 2015 was a typo in the source, it’s fixed on master.

**Comment by maieul** [comment]
thanks. An other point which is stange for me : your master branch don't include the 1.42.4 change, only your attempt-at-a-v1.42.4-wip branch. is it normal ? if yes, maybe you could add some little comment in you README on the way you manage branch ?

**Comment by reutenauer** [comment]
I don’t use any special way to manage branches and I usually only make uploads to CTAN that reflect some stage of `master`; it’s only that the latest update was a little chaotic and I really had to work in different branches so as not to risking breaking master :-)  I just rebased master off `attempt-at-v1.42.4-wip`.
