### ISSUE TITLE
Open guillemet does not inhibit a line break

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#143]
The following example (source http://tex.stackexchange.com/questions/307174/xelatex-french-guillemets-non-breaking-space-best-practice)

```
\documentclass[12pt]{article}
\usepackage[paperwidth=14cm,paperheight=20.5cm]{geometry}
\usepackage{libertine}% use this font and geometry width to reproduce bad break
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{french}

\begin{document}

%\makeatletter
%\XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace}
%\makeatother

Je n'ai rien à dire --- mais je le dis bien : je suis un « beau parleur ».

\end{document}
```

produces a line break after the open guillemet. If I uncomment the three lines, the output is correct.

The corresponding line (number 52)  in `gloss-french.ldf` is commented out.

**Comment by reutenauer** [comment]
Many thanks Enrico, I’ll deal with that together with the other recent bugs opened for French.

**Comment by jspitz** [comment]
This is fixed meanwhile (at https://github.com/reutenauer/polyglossia/commit/5bb76bbe7f3aa2cd3e21930709c74db0a2830488, but also already before, apparently).

Ticket can be closed.
