### ISSUE TITLE
Setting hyphenmins via Polyglossiasetup doesn't work

### ISSUE THREAD

**Issue by ppasedach** [reutenauer/polyglossia#148]
See also [here](http://tex.stackexchange.com/questions/294936/how-to-set-the-minimum-characters-for-hyphenation):

```
\documentclass[12pt]{article}

\usepackage{fontspec}
\usepackage{polyglossia}
\tracingparagraphs=1
\setdefaultlanguage{sanskrit}
\setotherlanguage{english}

\PolyglossiaSetup{sanskrit}{
  hyphenmins={1,1},
}

\newfontfamily\sanskritfont{TeX Gyre Pagella}
\newfontfamily\englishfont{TeX Gyre Pagella}

\begin{document}

anaikāntikatvam asambhavīti cet | yady evam arthasākṣātkāritvamātrasyendiryavadālokādhīnatvam upalabdham iti na santamase xx paśyeyur ulūkādayaḥ | atha vyabhicāradarśanād ālokasyāvyāpakatvam, vyabhicāraśaṅkayā tarhīndriyasyāpy avyāpakatvam | vyāptyā śaṅkā khaṇḍyata iti cet | śaṅkāsambhavād vyāptir evāsambhavinī yadi prathamata eva vyāptiḥ, vyabhicāro 'pi na dṛśyeta | 


\end{document}
```

If I get it correct, then

```
\PolyglossiaSetup{sanskrit}{
  hyphenmins={1,1},
}
```

Should set a minimum of one character at either end of the word to be hyphenatable, but it doesn't seem to have any effect.

**Comment by jspitz** [comment]
The reason is that we use `\providehyphenmins` in `\setlocalhyphenmins` in order to set the hyphenmins value. And `\providehyphenmins` is ignored if it has already been set for a given language.

If we want to provide the possibility to override the value as requested here, we can use
`\@namedef{#1hyphenmins}{{#2}{#3}}`
instead of
`\providehyphenmins{#1}{#2#3}`

Do we want that, @reutenauer, @bastien-roucaries?

**Comment by reutenauer** [comment]
My initial reaction is no.  `\PolyglossiaSetup` is an internal command, not meant for end users’ documents (unless they’re development the `gloss` file themselves, of course).  On the other hand, we could provide an equivalent to Babel’s `\babelhyphenation` for document-level changes.

**Comment by jspitz** [comment]
`\babelhyphenation` is for hyphenation exceptions, this is a different issue (see #18).
Document-level changes can be done with `\lefthyphenmin` and `\righthyphenmin`, but this gets overwritten on any language change.

Of course the OP can simply do
`\renewcommand*{sanskrithyphenmins}{{1}{1}}`
for his purpose.

Given that this is probably a very rare usecase, I would be fine with this and with closing this ticket as WONTFIX.

**Comment by reutenauer** [comment]
Sorry, I didn’t mean to confuse the issue by adding hyphenation exceptions to the mix, I meant that we could provide a command in Polyglossia that overrides hyphenmins on a language basis, and I thought that Babel already had such a command (but clearly it’s not `\babelhyphenation`).

WONTFIX is fine by me.

**Comment by jspitz** [comment]
So be it, then.

No, babel does not have such a command either AFAIK.

**Comment by wehro** [comment]
> Of course the OP can simply do
> `\renewcommand*{sanskrithyphenmins}{{1}{1}}`
> for his purpose.

This possibility suffices, but it should be documented in the manual.
Who is the “OP”, by the way?

**Comment by jspitz** [comment]
> This possibility suffices, but it should be documented in the manual.

Go for it!

> Who is the “OP”, by the way?

The original poster (or post, depending on context). See https://en.wikipedia.org/wiki/Internet_forum#Thread

**Comment by bastien-roucaries** [comment]
On Sun, Sep 1, 2019 at 11:43 AM wehro <notifications@github.com> wrote:
>
> Of course the OP can simply do
> \renewcommand*{sanskrithyphenmins}{{1}{1}}
> for his purpose.

I really prefer
\sethyphenminlang[option including lang]{{1}{2}}

It will work with BCP47

Please do not add something like #1 name

**Comment by jspitz** [comment]
This is not added by me. This is part of the hyphenation code we use (coming from babel).

**Comment by bastien-roucaries** [comment]
On Sun, Sep 1, 2019 at 3:56 PM Jürgen Spitzmüller
<notifications@github.com> wrote:
>
> This is not added by me. This is part of the hyphenation code we use (coming from babel).

Yes and it will break horribly with bcp47...

**Comment by jspitz** [comment]
Maybe. But I have nothing to do with that.

**Comment by jspitz** [comment]
> I really prefer \sethyphenminlang[option including lang]{{1}{2}} It will work with BCP47 Please do not add something like #1 name

FYI something similar to this has been implemented at https://github.com/reutenauer/polyglossia/commit/9d87c43f07dc3f070a1d7e617bb270d66a2b1069
