### ISSUE TITLE
Incorrect decimal mark in Spanish

### ISSUE THREAD

**Issue by aguadopd** [reutenauer/polyglossia#149]
Hello! Thanks for this great package. I noticed that the decimal mark for Spanish, is not rendering as a ',' but as a '.'. I understand that the package should change them correctly, as `babel` does. I'm using LuaTeX, Version 0.95.0 (MiKTeX 2.9 64-bit) .
Here's an example:

```
\documentclass[]{article}
\usepackage{polyglossia}
\setdefaultlanguage[]{spanish}

\begin{document}
    In text mode, a decimal separator is: 1.234

    In inline math mode, a decimal separator is: $ 1.234 $ 

    In display mode, a decimal separator is:
    \[ 1.234 \]


\end{document}
```

**Comment by jspitz** [comment]
This requires the implementation of shorthands in Spanish, which is not done yet.

**Comment by jspitz** [comment]
I really doubt the usefulness of this. Babel is messing a lot with active characters to provide this, and it is only provided for Spanish (although other languages also have different decimal separators).

I'd say that using `siunitx` or a similar package is the recommendable approach here.

**Comment by reutenauer** [comment]
Agreed, I don’t think Babel is doing the right thing here.
