### ISSUE TITLE
Strange comma placement with \setotherlanguage{} and RTL language

### ISSUE THREAD

**Issue by matthew-tucker** [reutenauer/polyglossia#150]
Apologies if this is desired behavior in some way, but I can't see how it could be. The following MWE illustrates the problem, which I can only describe as "a comma in an LTR language will render as though it were RTL after a parentheses which contains a real number with a decimal part." It doesn't occur with parentheses containing integers, a single full stop, text, or anything else I've tested.

Relevant MWE:

```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{arabic}

\begin{document}

Here we have a normal comma, then we have (a comma after parentheses), and 
we can see that it's fine.

But then a comma after this parenthesis (4.5), is placed badly.

None of the following have this issue: (4), comma 
after single numeral. Or (.), comma after only 
a parenthesis with a period.

\end{document}

```

The result is a comma placed _before_ the parenthesis, as in this sample output:

[mwe.pdf](https://github.com/reutenauer/polyglossia/files/356614/mwe.pdf)

This seems like an attempt to place a comma as though I had called `\textarabic{}`, but obviously that's not the case and this seems like odd behavior.

**Comment by vafa** [comment]
This is a polyglossia bug. Do not hope that it gets fixed because the maintainer has failed to do it for several years.

**Comment by reutenauer** [comment]
@matthew-tucker, this is certainly not the desired behaviour. [In another recent issue](https://github.com/reutenauer/polyglossia/issues/155) about Polyglossia and bidi, it has been reported that upgrading the latter to its most recent version (20.0) corrected the problem.  Can you please try that?

Best,

Arthur

**Comment by matthew-tucker** [comment]
@reutenauer thank you very much. I had been semi-regularly attempting new versions but stopped at a certain point when work got busy. It does in fact work as expected with the newest version of both packages from TeXLive.

**Comment by reutenauer** [comment]
Great to hear, sorry I wasn’t more reactive when you originally opened the issue.
