### ISSUE TITLE
Request for Japanese support

### ISSUE THREAD

**Issue by GreekFellows** [reutenauer/polyglossia#151]
There isn't a `gloss-japanese` yet, and I think it'd be great if we have one.

Professor Iwase of Kyushu University, Japan seems to have written a `gloss-japanese` (Euro-American style) and a `gloss-nihongo`. Here's a [link](http://user.math.kyushu-u.ac.jp/?iwase%2Fitoniki), but external access to the latest versions is forbidden.

I will also try to see what I can do, maybe write on my own and then do a pull request.

**Comment by jspitz** [comment]
There is a gloss-japanese.ldf in polyglossia as of https://github.com/reutenauer/polyglossia/commit/3d43ce007a8a3e5aeae3c22be7e2d093029a4547

I am closing this. Please file separate tickets if there are bugs or enhancement requests concerning this module.
