### ISSUE TITLE
Exposing Polyglossia language variants to other packages like Biblatex.

### ISSUE THREAD

**Issue by JohnLukeBentley** [reutenauer/polyglossia#154]
I detail a problem when using Polyglossia with Biblatex: http://tex.stackexchange.com/questions/324849/how-do-we-get-polyglossia-language-variants-to-work-with-biblatex-bibliographies

> In summary, with my MWE, `babel` and `polyglossia` work as expected with `biblatex` when using `\usepackage[*mainlanguage*]{babel}` and `\setdefaultlanguage{*mainlanguage*}` respectively. But `polyglossia` doesn't work when using `\setdefaultlanguage[variant=*somevariantlanguage*]{english}`. 

From the comments so far received it seems that `polyglossia` doesn't yet properly expose language variants to other packages. Whatever the cause my specific interest is in getting `biblatex` to properly work with `polyglossia` language variants, as detailed in my tex stackexchange post. So I raise this as a feature request.

@plk mentions "I think I submitted a patch for polyglossia to make it report the variant". Perhaps this is [Better loaded lang/variant macros #122](https://github.com/reutenauer/polyglossia/pull/122). I don't know enough to assess the relationship between that patch and the current issue.

**Comment by reutenauer** [comment]
That code by Philip wrote has been released, but as I noted in the comments to the pull request it didn’t really work, and even though I tried to correct it, I still can’t guarantee it works as expected.

**Comment by JohnLukeBentley** [comment]
Thanks Arthur.

Is, therefore, that pull request code something you'd like:

* @plk, Philip, to have another go at;  
* you want to have another go at; or 
* be left open for any interested third party to have a go at (alas I wouldn't have the skills for it).

?

(For my own circumstances I can readily work around the issue by using babel - so if the issue was left open as a low priority it wouldn't be a personal roadblock).

**Comment by wehro** [comment]
> Language variants are now accessible via `\languagevariant` and `\mainlanguagevariant`

Could you add some documentation to the manual?

**Comment by jspitz** [comment]
I have added a section to the manual. `\languagename` and `\mainlanguagename` weren't documented either.

**Comment by wehro** [comment]
Thank you for the documentation.
I think `\languagevariant` and `\mainlanguagevariant` are only useful for package authors if they contain the default variant if the user did non select another one. For example, the values should be `german` and `american` for German and English, respectively, rather than empty.
