### ISSUE TITLE
gloss-french.ldf: redefinition of \@makefntext should be optional

### ISSUE THREAD

**Issue by emarsden** [reutenauer/polyglossia#157]
The French support currently redefines \@makefntext at the end of gloss-french.ldf. This makes it extremely difficult for the user to customize the appearance of footnotes, using packages such as footmisc. (User is required to use \AtBeginDocument to remove the polyglossia interference). 

Request: make the changes to standard LaTeX formatting commands a language option, rather than an obligation.

**Comment by cmfwyp** [comment]
I think this is fixed by 12fe5aa.

**Comment by jspitz** [comment]
Someone who can please close this ticket.
