### ISSUE TITLE
\datewelsh inserts a \par token.

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#158]
The definition of \datewelsh in gloss-welsh.ldf contains an empty line. This means that every language switch to welsh forces a new paragraph.  See https://tex.stackexchange.com/questions/325953/switching-to-welsh-in-polyglossia-starts-new-paragraph for an example.

**Comment by reutenauer** [comment]
Hum ...  Yes, it seems like some debugging code made it to master when it shouldn't have.  I'll fix in the next few days.

Thanks for the bug report, as usual, @u-fischer
