### ISSUE TITLE
Some Hebrew fonts don't break after section

### ISSUE THREAD

**Issue by yotamDvir** [reutenauer/polyglossia#159]
Consider:

``` latex
\documentclass[11pt]{article}

\usepackage{polyglossia}

\setdefaultlanguage{hebrew}
\newfontfamily\hebrewfont[Script=Hebrew]{Times New Roman}

\begin{document}
\section{שלום}
וברכה
\end{document}
```

As it is there is no problem, but replace `Times New Roman` with some of the other Hebrew fonts, e.g. `Raanana`, and `וברכה` will print right after `שלום`, without a line break (or even a space).

Pretty strange that the choice of font could affect the layout in this way.

_Compiling with XeLaTeX (LaTeX 2016) on a Mac (10.11.6). Ask for more information if necessary, not familiar enough with LaTeX to know what information is relevant._

**Comment by vafa** [comment]
If you look at the definition of `\section` for instance, you will see something like this in `article.cls`:

````latex
\newcommand\section{\@startsection {section}{1}{\z@}%
                                   {-3.5ex \@plus -1ex \@minus -.2ex}%
                                   {2.3ex \@plus.2ex}%
                                   {\normalfont\Large\bfseries}}
````
As you can see the units used here is `ex`.  So what is `ex`? According to page 60 in the TeXBook

> `ex` is the "x-height" of the current font

Hence, the reason for the problem you described is that the font that you are using has a negative x-height. So you either have to correct the font or redefine `\section` and use some other units than `ex`.

**Comment by yotamDvir** [comment]
Alright, makes sense, `x-height` might be `0` as these fonts don't have English letters at all (as opposed to `Times New Roman`).

I don't intend to try out your solution as it is too much of a hassle. Mainly just wanted to report what I thought was a bug. This may prove helpful to others though. Regardless, thank you!
