### ISSUE TITLE
month name incorrect in hebrewcal.sty

### ISSUE THREAD

**Issue by AriBrodsky** [reutenauer/polyglossia#16]
The Hebrew spelling of the month name Heshvan is חשון, not השון.  This should be corrected at line 58 of hebrewcal.sty.  I reported it here http://tug.org/pipermail/xetex/2011-November/022221.html and there was some follow-up discussion about a possible [marcheshvan] option, but at least the basic spelling should be corrected.

**Comment by jspitz** [comment]
So the only pending issue here is documentation of the "marcheshvan" option?
