### ISSUE TITLE
Spurious output and false error with verbatim and non-Latin script under LuaTeX

### ISSUE THREAD

**Issue by gmilde** [reutenauer/polyglossia#160]
W

hen
• compiling with LuaTeX,
• using polyglossia, and
• defining a language requiring a non-Latin script (e.g. Russian, Ukrainian, or Greek)
the verb and url macros trigger an error and the output contains spurious text.
Examples:
Verbatim: \FontspecSetCheckBoolTrue \FontspecSetCheckBoolTrue \FontspecSetCheckBoolTrue \Fontspec
URL: \FontspecSetCheckBoolTrue \FontspecSetCheckBoolTrue http:
//www.lyx.org/.
Greek URL: \FontspecSetCheckBoolTrue \FontspecSetCheckBoolTrue
http://www.lyx.org/.

Example:

\documentclass{article}

\usepackage{fontspec}
\setmainfont{FreeSerif}
\setsansfont{FreeSans}
\setmonofont{FreeMono}

\usepackage{parskip}
\usepackage{url}
\usepackage[colorlinks,linkcolor=blue]{hyperref}

\usepackage{polyglossia}

% uncommenting any one of these triggers the problem
\setdefaultlanguage{greek}
% \setdefaultlanguage{russian}
% \setdefaultlanguage{ukrainian}

% these settings "do not harm"
% \setotherlanguage{greek}
%\setotherlanguage{russian}
%\setotherlanguage{ukrainian}

\begin{document}

This document uses FreeMono, a monospaced font that works without error also
for Greek and Cyrillic:

monospaced \texttt{word-λογοσ-слово}

However, when 
\begin{itemize}
  \item compiling with LuaTeX, 
  \item using polyglossia, and
  \item defining a language requiring a non-Latin script 
        (e.g. Russian, Ukrainian, or Greek)
\end{itemize}
the \texttt{verb} and \texttt{url} macros trigger an error and the output
contains spurious text.

Examples:

Verbatim: \verb+\href+

URL: \url{http://www.lyx.org/}.

Greek URL: \textgreek{\url{http://www.lyx.org/}.}

If the conditions are met, there is the text
\texttt{\textbackslash FontspecSetCheckBoolTrue
\textbackslash FontspecSetCheckBoolTrue} (Greek) respectively.
\texttt{\textbackslash FontspecSetCheckBoolTrue \textbackslash
FontspecSetCheckBoolFalse} (Russian, Ukrainian)

around the examples.

No problem occures
\begin{itemize}
  \item with languages using the Latin script,
  \item with an URL given as "href":
    \texttt{\href{http://www.lyx.org/}{http://www.lyx.org/}},
  \item if compiling with XeTeX,
  \item if using Babel instead of Polyglossia,
  \item for text parts in a secondary language, if the main language uses
  Latin Script:

```
    \begin{greek}
  Greek Verbatim: \verb+\href+
    \end{greek}

    Greek URL: \textgreek{\url{http://www.lyx.org/}.}
```

\end{itemize}

\end{document}

**Comment by jspitz** [comment]
Bug not reproducable with the current version. Günter, please verify.

**Comment by gmilde** [comment]
On 23.08.19, Jürgen Spitzmüller wrote:
> Bug not reproducable with the current version. Günter, please verify.

Also with a standard Debian/stable installation, the problem is no longer
visible.

Versions:

This is LuaTeX, Version 0.95.0 (TeX Live 2016/Debian)  
  (format=lualatex 2019.5.8)  25 AUG 2019 11:14

Package: polyglossia 2015/03/25 v1.42.4 Alternative to Babel for
	 XeLaTeX and LuaLaTeX

Package:    fontspec 2017/02/12 v2.6 Font selection for XeLaTeX and LuaLaTeX
Lua module: fontspec 2017/02/12 2.6 Font selection for XeLaTeX and LuaLaTeX
Package:    fontspec-luatex 2017/02/12 v2.6 Font selection for XeLaTeX and
	    LuaLaTeX

Dez 13  2016 FreeMono.otf


So, any of the updates must have solved the problem.

Günter

**Comment by jspitz** [comment]
Cool. Could you close this ticket? I don't have the permissions to do so.
