### ISSUE TITLE
Question regarding sffamily on Cyrillic fonts

### ISSUE THREAD

**Issue by korusdipl** [reutenauer/polyglossia#164]
Hi! I'm new to polyglossia, and tried some ways to deal with english and russian at the same time, but when I try the following code, I failed to retrieve the correct font [PragmaticaC] for Russian sffamily while roman cyrillic works fine. Reversing the order of english and russian setlanguage would result in failing to print english sf font. Your generous guidance is needed. Thanks.

The result output can be found [here](https://github.com/korusdipl/sandbox/blob/master/latex-questions/polyglossia-engrus-sffamily-test.pdf)

```
\documentclass{article}
\usepackage{xltxtra}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{russian}

\setmainfont{PalatinoLTPro-Roman}
\setromanfont{PalatinoLTPro-Roman} 
\setsansfont{PalatinoSansLTPro-Regular}

\newfontfamily{\cyrillicfont}{PalatinoNovaW1G-Regular} 
\newfontfamily{\cyrillicfontrm}{PalatinoNovaW1G-Regular}
\newfontfamily{\cyrillicfontsf}{PragmaticaC}

\begin{document}

\textsf{Sans Serif Typing Test}

Привет Мир! \foreignlanguage{english}{Hello world!}

\begin{english}
Hello world!
\end{english}

\textsf{Русский Без засечек}

\selectlanguage{english}
Hello world!

\end{document}
```

**Comment by eg9** [comment]
This is not a issue in Polyglossia, but in your code. The `\cyrillicfontsf` font is only selected if the current language is Russian, which is never the case in your code, because the declared main language is English.

**Comment by reutenauer** [comment]
Thank you @eg9 for the note.  @korusdipl, you need to switch the language in order for `\cyrillicfont` to be selected.

**Comment by korusdipl** [comment]
Thank you for your answer, @eg9.  I tried to do it again with some foreign language command after reading manuals to set a 'current language block', but the cyrillic sf font specified still doesn't seem to be set on a otherlanguage block. (I've changed some fonts to system ones for easy testing) Please check the result [here](https://github.com/korusdipl/sandbox/blob/master/latex-questions/polyglossia-engrus-sffamily-test-2.pdf).

```
\documentclass{article}
\usepackage{xltxtra}
\usepackage[english,russian]{babel}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{russian}

\setmainfont{Palatino Linotype}
\setromanfont{Palatino Linotype} 
\setsansfont{Arial}

\newfontfamily{\cyrillicfont}{Palatino Linotype} 
\newfontfamily{\cyrillicfontrm}{Palatino Linotype}
\newfontfamily{\cyrillicfontsf}{Candara}

\begin{document}

Hello world!

\textsf{Sans Serif Typing Test}

\begin{russian}
Премьер-министр России Дмитрий Медведев заявил, что санкции не являются главной проблемой отечественной экономики. Такое мнение он высказал в интервью Первому каналу, \textsf{расшифровка которого опубликована в воскресенье}, 2 октября, на сайте правительства.
\end{russian}

\end{document}
```

Please correct me. Thank you!

**Comment by jspitz** [comment]
Right, this seems to be a bug.
