### ISSUE TITLE
extra \else with some main and other language variants

### ISSUE THREAD

**Issue by dryo** [reutenauer/polyglossia#167]
Hi there!

I stumbled across a bug, tried to narrow it down but without success. Example code:
```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
\documentclass{article}

\usepackage{ifxetex}
 
\ifxetex
    \usepackage{polyglossia}
%    \setmainlanguage[variant=british]{english}  %1
    \setmainlanguage[spelling=new]{german}       %2
    \setotherlanguage[variant=british]{english}  %3
%    \setotherlanguage{english}                  %4
\else
    \usepackage[T1]{fontenc}
\fi
 
\begin{document}
    Text goes here.
\end{document}
```

This leads to XeTeX error '! Extra \else.'

Commenting out the line marked %3 and uncommenting %4 (thus removing variant 'british') leads to no errors.
It also works fine when uncommenting %1 and commenting %2-4 out, setting en-uk as the main language.
Setting main language to en-uk and otherlanguage to de-new also works.

Any ideas?

**Comment by u-fischer** [comment]
It could be related to this problem:

```
\documentclass{book}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}

\begin{document}
abnc
\end{document}

```
which gives the message 

`(\end occurred when \ifx on line 7 was incomplete)`

(line 7 is the line of \begin{document}). Other variants than british seems to work fine.

**Comment by dryo** [comment]
I just saw this is already documented in #163

**Comment by jspitz** [comment]
Could you try again with the recent development version? #163 seems to be fixed, maybe this one is as well.

**Comment by jspitz** [comment]
I've verified that this is fixed.

Someone who can please close this ticket.
