### ISSUE TITLE
Option [variant=swiss] does not change the spelling of cleveref's "Fußnote" to "Fussnote", as it should

### ISSUE THREAD

**Issue by fmatter** [reutenauer/polyglossia#170]
Swiss Standard German has some spelling differences to German German, among other things, we don't use the graph <ß>.

I am not sure if this is a polyglossia or a cleveref problem as I don't exactly know how they interact.

**Comment by jspitz** [comment]
This is a cleveref problem, as it does define the strings.

**Comment by eg9** [comment]
As @jspitz says, this is a `cleveref` issue. The package doesn't explicitly support `polyglossia`; in the case of

    \setmainlanguage[variant=swiss]{german}

it infers the language is German and sets the fixed labels accordingly.

You can fix it manually:

    \documentclass{article}
    \usepackage{polyglossia}
    \usepackage{cleveref}
    
    \setmainlanguage[variant=swiss,spelling=new]{german}
    \AtBeginDocument{%
      \Crefname{footnote}{Fussnote}{Fussnoten}%
      \crefname{footnote}{Fussnote}{Fussnoten}%
    }
    
    \begin{document}
    
    Worte\footnote{Fussnote\label{f}}
    
    \Cref{f} und \cref{f}
    
    \end{document}

<img width="267" alt="screen shot 2016-12-13 at 23 41 10" src="https://cloud.githubusercontent.com/assets/302839/21162446/a914282e-c18d-11e6-83a6-7e83979e4f9b.png">

**Comment by fmatter** [comment]
@eg9 thank you! Is the \AtBeginDocument{} necessary and what does it do?

**Comment by eg9** [comment]
It's necessary because `cleveref` sees “German” and acts on consequence, knowing nothing about Swiss German. So we need to appropriately countermand the declarations made by `cleveref`, which are done at begin document.

**Comment by jspitz** [comment]
Please close this. Note a polyglossia bug.

**Comment by jspitz** [comment]
Someone who can please close this ticket.
