### ISSUE TITLE
Spurious space in `gloss-norsk.ldf`

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#171]
The file `gloss-norsk.ldf` ends with

    \def\datenorsk{%   
       \def\today{\number\day.~\ifcase\month\or
        januar\or februar\or mars\or april\or mai\or juni\or
        juli\or august\or september\or oktober\or november\or desember
        \fi\space\number\year}%
        }

and a `%` is missing after `desember`.

Reference: http://tex.stackexchange.com/questions/342863/extra-space-in-today-command-with-polyglossia

**Comment by reutenauer** [comment]
Or we could see it as `desember` being on the wrong line ;-)  Thanks for the report, I just pushed a commit to master.
