### ISSUE TITLE
Marathi-a typo in ldf file is causing an error

### ISSUE THREAD

**Issue by rdholkar** [reutenauer/polyglossia#179]
The file gloss-marathi.ldf has a typo in the line
\PolyglossiaSetup{marathi}{
  script=Devaganari,
;
the word Devanagari is typed as Devaganari.

This typo is causing the fontenc error "Kernel choice unknown" along with a suggestion to type H for more information. When typed H, one get the message "The key 'fontspec-opentype/Script' only accepts predefined values, and 'Devaganari' is not one of these."

**Comment by jspitz** [comment]
This has been fixed by https://github.com/reutenauer/polyglossia/commit/eabfde31

Please close the ticket.
