### ISSUE TITLE
Defining hyphenation exceptions

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#18]
It would be nice if Polyglossia had a facility for defining hyphenation exceptions in the various languages used in a document. If there's only one language, then a plain `\hyphenation` command suffices, but for more than one it's necessary to change language. A possibility could be to provide

```
\newcommand{\sethyphenation}[3][]{%
  \sbox\z@{\begin{otherlanguage}[#1]{#2}\hyphenation{#3}\end{otherlanguage}}}
```

so that a user can say

```
\sethyphenation[variant=<variant>]{<language>}{<space separated list of hyphenation exceptions>}
```

Using the `hyphenrules` environment rather than `otherlanguage` would be better, but it doesn't appear to work correctly in Polyglossia.

**Comment by floriandk** [comment]
This mechanism is [now (vers. 3.9) implementet in `babel`.](http://tex.stackexchange.com/questions/37934/specifying-multiple-hyphenation-exception-lists-for-multi-lingual-documents/107431#107431) It would be nice if syntax and functionality would be the same in `polyglossia`.

**Comment by jspitz** [comment]
I went for `\pghyphenation`, as `\sethyphenation` was already defined by several other packages.
