### ISSUE TITLE
polyglossia + lualatex: French punctuation spacing remains enabled after \textfrench{}

### ISSUE THREAD

**Issue by ndlecic** [reutenauer/polyglossia#182]
Hi,

Please take a look at this example:
```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{french}
\setmainfont{CMU Serif}
\begin{document}
Lorem: ipsum; dolor sit amet? Consectetur adipiscing elit!

\textfrench{Bonjour!}

%\directlua{polyglossia.desactivate_frpt()}

Sed: do; eiusmod: tempor; incididunt? Ut! Labore!?
et dolore magna aliqua. Ut: enim ad minim veniam; quis.
\end{document}
```
As you can see, after `\textfrench{}` spaces before punctuation don't disappear. If you uncomment the `\directlua` line, the spaces disappear. 

Since this example works with xelatex as expected, it's either polyglossia's behaviour with lualatex, or lualatex itself. If it's the later, please let me know and I'll write to luatex ml.

**Comment by ELLIOTTCABLE** [comment]
Ran into exactly this, today. Didn't realise it was a bug, spent a while banging my head against it.

https://tex.stackexchange.com/questions/389917/why-is-a-single-inline-french-quote-with-csquotes-causing-all-the-following-punc?noredirect=1#comment967897_389917
