### ISSUE TITLE
\disablehyphenation transcends groups 

### ISSUE THREAD

**Issue by Flupp** [reutenauer/polyglossia#187]
Putting `\disablehyphenation` in a LaTeX group leaves hyphenation disabled after leaving the group.
```
This text is hyphenated.
{\disablehyphenation
	This text is not hyphenated.
	{\disablehyphenation
		This text is not hyphenated.
	}
	This text is not hyphenated.
}
This text is not hyphenated, but it should be.
```

Note: I am using LuaLaTeX.

**Comment by svenper** [comment]
Seems related to wspr/fontspec#344.

Maybe `\disablehyphenation` could take inspiration from `\nohyphenation` in `biblatex.sty` (I don’t know about multi script support):

```tex
\providerobustcmd*{\nohyphenation}{%
  \lefthyphenmin\@m}
```

**Comment by moewew** [comment]
`biblatex`'s `\nohyphenation` is essentially broken if not used at the beginning of a paragraph: https://github.com/plk/biblatex/issues/772. If anyone has a better idea to suppress hyphenation I'd love to hear about it.

**Comment by jspitz** [comment]
Note that everything works fine with XeTeX. Also it strikes me that `\enablehyphenation` does not work either with LuaTeX. @eroux?

**Comment by jspitz** [comment]
@wehro do you have an idea here? Something's fishy with enablehyphenation in lua.

**Comment by wehro** [comment]
It is not quite clear from the manual if these commands are meant globally or locally.
The Lua functions `disable_hyphenation()` and `enable_hyphenation()` act globally. They are not able to notice the end of a TeX group.
If the commands should only operate locally, we have to abolish these two Lua functions and just switch to the “nohyphenation” language.
Shall I prepare a pull request?

**Comment by bastien-roucaries** [comment]
Le dim. 1 sept. 2019 à 21:00, wehro <notifications@github.com> a écrit :

> It is not quite clear from the manual if these commands are meant globally
> or locally.
> The Lua functions disable_hyphenation() and enable_hyphenation() act
> globally. They are not able to notice the end of a TeX group.
> If the commands should only operate locally, we have to abolish these two
> Lua functions and just switch to the “nohyphenation” language.
> Shall I prepare a pull request?
>

I préfet the nohyphenation stuff, with bcp47 it will means
langatg-x-nohyphenatio

Could you try a pull request will review

**Comment by reutenauer** [comment]
@bastien-roucaries I think that at this stage it would be good if you could explain what you have in mind for BCP 47, it will be more useful than to discuss it piecemeal over many issues on GitHub.  For example, you mention `x-nohyphenation` as a subtag: it sounds like a nice idea to disable hyphenation, but that’s the first time I’m hearing about it.  I’m all for it in principle, but we do need some overview before we start coding (and it can’t be `nohyphenation` because it has to be 5 to 8 letters long).

**Comment by bastien-roucaries** [comment]
On Mon, Sep 2, 2019 at 11:39 AM Arthur Reutenauer <notifications@github.com>
wrote:

> @bastien-roucaries <https://github.com/bastien-roucaries> I think that at
> this stage it would be good if you could explain what you have in mind for
> BCP 47, it will be more useful than to discuss it piecemeal over many
> issues on GitHub. For example, you mention x-nohyphenation as a subtag:
> it sounds like a nice idea to disable hyphenation, but that’s the first
> time I’m hearing about it. I’m all for it in principle, but we do need some
> overview before we start coding (and it can’t be nohyphenation because it
> has to be 5 to 8 letters long).
>

 For no hypehnation we could also use unicode extension
-u-lw-keepal
for loose setting
-u-lw-loose

Therefore we could track hyphenation using lualang
