### ISSUE TITLE
Spurious space with \text<…> and datetime2

### ISSUE THREAD

**Issue by Socob** [reutenauer/polyglossia#188]
I’m not sure whose “fault” this is, but polyglossia has an easily accessible issue tracker (as opposed to datetime2), so I’m posting this here 😉

Combining the datetime2 package with the `\text<…>` commands of polyglossia (e. g. `\textgerman`, `\textspanish`) results in additional (spurious) spaces in the output.

This minimal example document:
```tex
\documentclass{scrartcl}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{german}
\setotherlanguage{spanish}

\usepackage{datetime2}

\begin{document}
	a\textspanish{a}a\textgerman{a}a
\end{document}
```
inserts a space before the second “a” (from `\textspanish{a}`) while the following second example
```tex
\documentclass{scrartcl}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{german}
\setotherlanguage{spanish}

\usepackage[useregional]{datetime2}

\begin{document}
	a\textspanish{a}a\textgerman{a}a
\end{document}
```
not only inserts the aforementioned space, but also an even larger space before the fourth “a” (from `\textgerman{a}`).

Version info: polyglossia v1.42.4, datetime2 v1.5.2.

**Comment by eg9** [comment]
The bugs are in `datetime2`.

There is an unprotected end-of-line at the very end of `datetime2-spanish.ldf`:

    223     {\DTMsetstyle{spanish-numeric}}
    224   }%
    225 }%
    226 \endinput

that should be

    223     {\DTMsetstyle{spanish-numeric}}% <----- HERE
    224   }%
    225 }%
    226 \endinput

There are two unprotected spaces in `datetime2-german.ldf`. One at line 134

    132      }%
    133      {}%
    134     }
    135    }%

that should be

    132      }%
    133      {}%
    134     }% <----- HERE
    135    }%

and one at line 271

    267   \csdef{date\CurrentTrackedDialect}{%
    268     \DTMifcaseregional
    269     {}% do nothing
    270     {\DTMsetstyle{german}}%
    271     {\DTMsetstyle{german-numeric}}
    272   }%
    273 }%
    274 \endinput

that should be

    267   \csdef{date\CurrentTrackedDialect}{%
    268     \DTMifcaseregional
    269     {}% do nothing
    270     {\DTMsetstyle{german}}%
    271     {\DTMsetstyle{german-numeric}}% <------ HERE
    272   }%
    273 }%
    274 \endinput

**Comment by SFr682k** [comment]
I fixed this issue in `datetime2-german` v2.1 (2017-11-13) and uploaded the current version to my GitHub repository ([https://github.com/sfr682k/datetime2-german](https://github.com/sfr682k/datetime2-german))  
Currently the files get prepared for an upload to CTAN.

**Comment by svenper** [comment]
This is an issue in many languages (some unmaintained), so I think a centralized fix would be appropriate.

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{EB Garamond}
\usepackage{polyglossia}
\setmainlanguage{danish}
\setotherlanguage{english}
\setotherlanguage{french}
\setotherlanguage{greek}
\setotherlanguage{spanish}
\setotherlanguage{russian}
\setotherlanguage{serbian}
\setotherlanguage{german}
\setotherlanguage{turkish}
\setotherlanguage{finnish}
\setotherlanguage{swedish}
\setotherlanguage{slovenian}
\setotherlanguage{vietnamese}
\setotherlanguage{latin}
\setotherlanguage{portuges}
\usepackage{datetime2}
\begin{document}

Without extra space:

hello --\textenglish{hello}-- hello\par
hello --\textspanish{hola}-- hello\par
hello --\textportuges{olá}-- hello\par
hello --\textgerman{hallo}-- hello\par
hello --\textturkish{selam}-- hello\par
hello --\textfinnish{moi}-- hello\par
hello --\textslovenian{ahoj}-- hello\par
hello --\textvietnamese{chào}-- hello\par

\vspace{\baselineskip}\hrule\vspace{\baselineskip}

With extra space:

hello --\textfrench{bonjour}-- hello\par
hello --\textgreek{γεια}-- hello\par
hello --\textlatin{salve}-- hello\par
hello --\textswedish{hej}-- hello\par
hello --\textrussian{привет}-- hello\par
hello --\textserbian[script=Latin]{ћао}-- hello\par
hello --\textserbian[script=Cyrillic]{здраво}-- hello\par

\end{document}
```

![3](https://user-images.githubusercontent.com/15199675/37595884-9dd583b0-2b7a-11e8-84f9-9c8b91d3ef3a.png)

**Comment by nlct** [comment]
I am working my way through the datetime2 language modules (including 
the unmaintained ones) but it's taking time. It can't be done in a 
centralised manner because the spurious space is in each .ldf file. It's 
not a fault with polyglossia.

**Comment by Socob** [comment]
I’m closing this here because the issue is in `datetime2`.
