### ISSUE TITLE
KOMA-script compatibility with Russian language

### ISSUE THREAD

**Issue by MaksimZh** [reutenauer/polyglossia#189]
Two macros in `tex/gloss-russian.ldf` overwrite the commands used for section title generation (see links below). This disables KOMA-script commands controlling title appearance (e.g. `\sectionformat` macro is never used).

https://github.com/reutenauer/polyglossia/blob/bbf79c6351ad0c3ae63511f5692da645300434ca/tex/gloss-russian.ldf#L172
https://github.com/reutenauer/polyglossia/blob/bbf79c6351ad0c3ae63511f5692da645300434ca/tex/gloss-russian.ldf#L217

**Comment by reutenauer** [comment]
Closing as pull request #190 has been merged.  And thanks again!
