### ISSUE TITLE
hyphenrules broken

### ISSUE THREAD

**Issue by aurelberra** [reutenauer/polyglossia#191]
The `hyphenrules` environment does not work anymore with `polyglossia`. According to [this SE discussion](https://tex.stackexchange.com/questions/400986/hyphenrules-environment-no-longer-works-with-polyglossia) the bug is inherited from `babel`. The temporary fix suggested on this forum works for me: adding `\usepackage[base]{babel}`.

**Comment by jspitz** [comment]
The issue is fixed.

Someone who can please close this ticket.
