### ISSUE TITLE
Wrong accent

### ISSUE THREAD

**Issue by rl1234567890** [reutenauer/polyglossia#193]
Hello,

In gloss-greek.ldf 

  \def\seename{ὃρα}%

should actually be

  \def\seename{ὅρα}%

(acute accent instead of grave). Thank you for your work!

**Comment by reutenauer** [comment]
Hence `\alsoname` should also be changed, I suppose (to ὅρα ὡσαύτως).  Thanks for the correction!  This is apparently a very old error, Babel also has `\accdasiavaria\textomicron\textrho\textalpha`.

I just pushed a commit with a fix.
