### ISSUE TITLE
Polyglossia and biblatex-apa won't work with Portuguese language

### ISSUE THREAD

**Issue by nunocasteleira** [reutenauer/polyglossia#194]
The new version of biblatex-apa allows the macro `\DefineLanguageMappingSuffix` to inform biblatex to use the language defined as main language in polyglossia.

The problem is, in polyglossia, Portuguese is stated as "portuges" (we say "portugues"). Therefore, we can't use the macro I said, and manually have to declare in bib latex `language=portuguese` and `\DeclareLaguageMapping{portuguese}{portuguese-apa}` for it to work.

As is polyglossia that states the language name wrong, this problem is raised by the polyglossia syntax.

**Comment by jspitz** [comment]
This is fixed now. The language name has been changed to 'portuguese' (portuges still supported as an alias).
