### ISSUE TITLE
Alphabetical numerals rendered incorrectly (affected by default language)

### ISSUE THREAD

**Issue by yoniy0** [reutenauer/polyglossia#196]
(This issue was first [asked on TeX-SE](https://tex.stackexchange.com/q/406719/46339).)

Numerals generated by `\alph{counter}` are rendered in a way that's inconsistent with the current language, when certain languages are default.

An example would be:
```
\documentclass{article}
\usepackage{polyglossia}

\setmainlanguage{hebrew}
\setotherlanguage{english}

\newfontfamily\hebrewfont[Script=Hebrew]{David CLM}
\newfontfamily\englishfont{Times New Roman}

\begin{document}
\newcounter{counter}
\setcounter{counter}{5}

\begin{english}
A number: \alph{counter}
\end{english}

\begin{hebrew}
מספר בעברית:
\alph{counter}
\end{hebrew}
```
which renders the number as `ה` in the English block as well as the Hebrew one. Oddly, if one switches the `main` and `other` languages, this is no longer the case (both render according to set language).

A possible workaround, by @UlrikeFischer on the question I linked to above, is to set Hebrew as the default language, and add
```
\makeatletter
\hebrew@numbers 
\gappto\noextras@hebrew{\let\@alph\@origalph}
\makeatother
```
to the preamble, after `fontfamily` definitions. However, that just moves the problem to files with English set as default.

**Comment by jspitz** [comment]
Fixed with https://github.com/reutenauer/polyglossia/commit/e8aa0c59a6e5ab910984e95b0c78010eb46a10bc

Please someone who can close this ticket.
