### ISSUE TITLE
Mismatched reference labels with Hebrew

### ISSUE THREAD

**Issue by yoniy0** [reutenauer/polyglossia#197]
References to list items in Hebrew blocks always appear as if they point to the last item on the list.

A minimal working example:
```
\documentclass{article}

\usepackage{polyglossia}

\setmainlanguage{hebrew}
\setotherlanguage{english}

\newfontfamily\hebrewfont[Script=Hebrew]{David CLM}
\newfontfamily\englishfont{Times New Roman}

\begin{document}
\begin{hebrew}
\begin{enumerate}
\item
\begin{enumerate}
\item\label{oneA_h}
א'.

\item\label{oneB_h}
ב'.
\end{enumerate}

\end{enumerate}

אנחנו מקשרים לסעיף
\ref{oneA_h}
וסעיף
\ref{oneB_h}.
\end{hebrew}
\end{document}
```
Both references are unfortunately rendered as `1ב`.

See TeX-SE questions [here](https://tex.stackexchange.com/q/264089/46339) and [here](https://tex.stackexchange.com/q/406730/46339). As @UlrikeFischer noted there, counters are incorrectly expanded in the `aux` file.

**Comment by ZvikaZ** [comment]
Hi.
Any news with this bug?
@yoniy0 , have you found a solution, or workaround?

**Comment by jspitz** [comment]
Fixed in master with https://github.com/reutenauer/polyglossia/commit/d5f67391490f7b5b9cd792fa17c4761a817d70fa

Someone who can please close this ticket.

**Comment by yoniy0** [comment]
@jspitz when/how can I test that your commit fixes the issue?

**Comment by jspitz** [comment]
You can get and test the development version of polyglossia from this repository. I have no idea concerning release plans.
