### ISSUE TITLE
Language "ngerman" does not translate the caption names

### ISSUE THREAD

**Issue by sscherfke** [reutenauer/polyglossia#199]
If I use polyglossia with lualatex and set the main language to `ngerman`, captions for, e.g., the table of contents are not translated (e.g., to *Inhaltsverzeichnis*).  It works, however, if I use `german`:
```\documentclass[a4paper]{report}
\usepackage{polyglossia}
\setmainlangauge{ngerman}  % -> "Contents"
\setmainlanguage{german}  % -> "Inhaltsverzeichnis"

\begin{document}

\tableofcontents
\chapter{Hello, world!}
Ohai

\end{document}
```

However, using `german` does not work on Fedora 26 (but on Fedora 27).

See: https://github.com/sphinx-doc/sphinx/issues/4717

**Comment by jspitz** [comment]
@sscherfke since this turned out to be a bug in sphinx, I suggest you close this ticket.
