### ISSUE TITLE
wrong hyphenation of english "relative"

### ISSUE THREAD

**Issue by jknaus** [reutenauer/polyglossia#2]
Hello,

I just realized that the english word "relative" receives the wrong hyphenation by polyglossia. It's hyphenated rel-ative. That's wrong. According to the New Oxford Spelling Dictionary it's rela-tive.

Here's a short example:

\documentclass[]{article}
\usepackage{polyglossia}
\setdefaultlanguage[variant=british, ordinalmonthday=false]{english}
\begin{document}

relative relative relative relative relative relative relative relative really relative relative relative relative relative relative  

\end{document}

What's a proper workaround for this? Adding \hyphenation{Rela-tive} inside the preamble didn't change anything for me. The only solution I found was to type rela-tive explicitly within the text. But that I would have to for every occurrence then...

Thanks for your help.

Johannes

**Comment by bastien-roucaries** [comment]
Solved then close
