### ISSUE TITLE
\setotherlanguage{magyar} overwrites caption format of default language

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [reutenauer/polyglossia#209]
System: XeTeX on OSX

I use magyar as additional language `\setotherlanguage{magyar}` and german as default/main langugae (`\setmainlanguage{german}` or `\setdefaultlanguage{german}`).

If `\setotherlanguage{magyar}` gets rendered, it also affects the output of all other languages by changing the caption format to `\thefigure.~\figurename` (see https://github.com/reutenauer/polyglossia/blob/master/tex/gloss-magyar.ldf#L14).

```latex
\documentclass{article}

\usepackage[babelshorthands]{polyglossia}
\setmainlanguage{german}
\setotherlanguage{magyar}

\begin{document}

\begin{figure}
    \centering
    Test
    \caption{Default language (german)}
\end{figure}

\begin{german}
  \begin{figure}
      \centering
      Test
      \caption{Language: german}
  \end{figure}
\end{german}

\begin{magyar}
  \begin{figure}
      \centering
      Test
      \caption{Language: magyar}
  \end{figure}
\end{magyar}

\end{document}
```

Expected output:
```
Test
Abbildung 1: Default language (german)

Test
Abbildung 2: Language: german

Test
3. ábra: Language: magyar
```

Real output:
```
Test
1. Abbildung: Default language (german)

Test
2. Abbildung: Language: german

Test
3. ábra: Language: magyar
```

**Comment by jspitz** [comment]
Patch here:
[x.diff.txt](https://github.com/reutenauer/polyglossia/files/3529130/x.diff.txt)

I can do a PR once #235 is processed.

**Comment by jspitz** [comment]
PR: #236

**Comment by reutenauer** [comment]
Fixed by @jspitz’s pull request.
