### ISSUE TITLE
\chapterformat undefined with scrartcl class and Russian language

### ISSUE THREAD

**Issue by MaksimZh** [reutenauer/polyglossia#210]
Source:
```latex
% test.txt
\documentclass{scrartcl}
\RequirePackage{polyglossia}
\setdefaultlanguage{russian}
\newfontfamily\cyrillicfont[Script=Cyrillic]{CMU Serif}
\begin{document}
\end{document}
```
Command:
```
xelatex test
```
Error:
```
! LaTeX Error: \chapterformat undefined.
```

**Comment by eg9** [comment]
The problem is in line 173 of `gloss-russian.ldf`

```tex
    173       \renewcommand{\chapterformat}{\prechapter\thechapter\postchapter}%
```

which should be

```tex
\ifdef{\chapterformat}{\renewcommand{\chapterformat}{\prechapter\thechapter\postchapter}}{}%
```

**Comment by komascript** [comment]
Line 227 should also be changed from

       \renewcommand{\chapterformat}{\thechapter\autodot\enskip}%

to

       \ifdef{\chapterformat}{\renewcommand{\chapterformat}{\thechapter\autodot\enskip}}{}%

**Comment by komascript** [comment]
@eg9 There is already a [fix by MaksimZh](https://github.com/reutenauer/polyglossia/pull/211/commits/d2f383ee4b84bbed78a618fc1261f7fb3ccf9447), that also fixes the bug in line 227.

**Comment by MaksimZh** [comment]
The fix has been merged
