### ISSUE TITLE
Finnish does not hyphenate words that has hyphen

### ISSUE THREAD

**Issue by ahomansikka** [reutenauer/polyglossia#212]
Or rather, it hyphenates word only on hyphen. I have changed gloss-finnish.ldf
to work correctly (I think :-). If you are intrested, I can send you the file.

**Comment by reutenauer** [comment]
Thanks for the report.  That’s intentional, compound words with a hyphen generally are hyphenated only at the hyphen in TeX. We can certainly change that just for Finnish, but I’m always loath to change defaults.  Do you have references to support the change?

You can always attach the file to this report, it can be useful for future reference.

**Comment by ahomansikka** [comment]
I did not mean to change the default. I just defined option babelshorthands like in gloss-german.ldf (and copied the shorthands mostly from that file and gloss-dutch.ldf).

Here is the code

`\ProvidesFile{gloss-finnish.ldf}[polyglossia: module for finnish]
\PolyglossiaSetup{finnish}{
  hyphennames={finnish},
  hyphenmins={2,2},
  frenchspacing=true,
  fontsetup=true,
}


\define@boolkey{finnish}[finnish@]{babelshorthands}[true]{}
\ifsystem@babelshorthands
  \setkeys{finnish}{babelshorthands=true}
\else
  \setkeys{finnish}{babelshorthands=false}
\fi
\ifcsundef{initiate@active@char}{%
\input{babelsh.def}%
\initiate@active@char{"}%
}{}

\def\finnish@shorthands{%
  \bbl@activate{"}%
  \def\language@group{finnish}%
  \declare@shorthand{finnish}{"-}{\nobreak-\bbl@allowhyphens}
  \declare@shorthand{finnish}{"|}{\textormath{\penalty\@M\discretionary{-}{}{\kern.03em}}{}}%
  \declare@shorthand{finnish}{""}{\hskip\z@skip}%
  \declare@shorthand{finnish}{"~}{\textormath{\leavevmode\hbox{-}}{-}}%
  \declare@shorthand{finnish}{"=}{\penalty\@M-\hskip\z@skip}%
}

\def\nofinnish@shorthands{%
  \@ifundefined{initiate@active@char}{}{\bbl@deactivate{"}}%
}


\def\captionsfinnish{%
   \def\refname{Viitteet}%
   \def\abstractname{Tiivistelmä}%
   \def\bibname{Kirjallisuutta}%
   \def\prefacename{Esipuhe}%
   \def\chaptername{Luku}%
   \def\appendixname{Liite}%
   \def\contentsname{Sisältö}%
   \def\listfigurename{Kuvat}%
   \def\listtablename{Taulukot}%
   \def\indexname{Hakemisto}%
   \def\figurename{Kuva}%
   \def\tablename{Taulukko}%
   %\def\thepart{}%
   \def\partname{Osa}%
   \def\pagename{Sivu}%
   \def\seename{katso}%
   \def\alsoname{katso myös}%
   \def\enclname{Liitteet}%
   \def\ccname{Jakelu}%
   \def\headtoname{Vastaanottaja}%
   \def\proofname{Todistus}%
   \def\glossaryname{Sanasto}%
   }
\def\datefinnish{%
   \def\today{\number\day.~\ifcase\month\or
    tammikuuta\or helmikuuta\or maaliskuuta\or huhtikuuta\or
    toukokuuta\or kesäkuuta\or heinäkuuta\or elokuuta\or
    syyskuuta\or lokakuuta\or marraskuuta\or joulukuuta\fi
    \space\number\year}}

\def\noextras@finnish{%
  \nofinnish@shorthands%
}

\def\blockextras@finnish{%
  \iffinnish@babelshorthands\finnish@shorthands\fi%
}

\def\inlineextras@finnish{%
  \iffinnish@babelshorthands\finnish@shorthands\fi%
}

\endinput

% TODO ? this is set in babel:
\gappto\blockextrasfinnish{%
  \babel@savevariable\hyphenpenalty\hyphenpenalty=30%
  \babel@savevariable\exhyphenpenalty\exhyphenpenalty=30%
  \babel@savevariable\doublehyphendemerits\doublehyphendemerits=5000%
  \babel@savevariable\finalhyphendemerits\finalhyphendemerits=5000%
  }
`

And here is an example

`
\documentclass[a4paper,12pt]{article}
\usepackage[babelshorthands]{polyglossia}
\setdefaultlanguage[babelshorthands=true]{finnish}
\hyphenrules{finnish}
\begin{document}
xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx
kokonaispinta"-ala.
\end{document}
`

**Comment by reutenauer** [comment]
Thanks, that’s appropriate.  I’ll add a `babelshorthands` options for Finnish.  Can’t make promises as to timeframe, though.
