### ISSUE TITLE
Is it possible to create own hyphenation rules?

### ISSUE THREAD

**Issue by sindzicat** [reutenauer/polyglossia#217]
Hello!
XeTeX cannot make hyphenation for Russian word &laquo;научно-исследовательских&raquo;.

I tried:

```latex
\documentclass[a4paper,14pt]{extreport}

\usepackage{csquotes}

\usepackage{polyglossia}
\setmainlanguage{russian}
\setotherlanguage{english}

\usepackage{fontspec}
\setmainfont{Times New Roman}

\newfontfamily\cyrillicfont{Times New Roman}

\newcommand{\sethyphenation}[2]{%
    \AtBeginDocument{%
        \begin{otherlanguage*}{#1}\hyphenation{#2}\end{otherlanguage*}%
    }%
}

\sethyphenation{russian}{на-у-ч-но-и-с-с-ле-до-ва-те-ль-с-ких}

\begin{document}
    \parbox{0pt}{научно-исследовательских}
\end{document}
```

Result:

![image](https://user-images.githubusercontent.com/33900895/54272714-431e1780-4595-11e9-9e72-27bec5917f34.png)

Is this possible to create own hyphenation rules for polyglossia?

Andrey.

**Comment by eg9** [comment]
TeX never hyphenates words that contain an explicit hyphen. You can enable `babelshorthands` and use `"-` or `"|`
```latex
\documentclass[a4paper]{article}

\usepackage{csquotes}

\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{russian}
\setotherlanguage{english}

\usepackage{fontspec}
\setmainfont{Times New Roman}

\newfontfamily\cyrillicfont{Times New Roman}

\begin{document}

\parbox{0pt}{\hspace{0pt}научно"-исследовательских}\qquad\qquad
\parbox{0pt}{\hspace{0pt}научно"|исследовательских}            

\end{document}
```
<img width="141" alt="Screen Shot 2019-03-13 at 12 21 42 " src="https://user-images.githubusercontent.com/302839/54275309-9b9be780-458a-11e9-8da9-f158ba5b9b4a.png">

**Comment by sindzicat** [comment]
Many thanks! I never heard that TeX doesn't hyphenate such words.  Why so? This is very surprising for me! Where can I read about this? Where can I read more about `"-` and `"|`?

**Comment by hanche** [comment]
@sindzicat The algorithm is described in appendix H of the TeXbook. See near the bottom of p. 454:

> (Since TeX inserts empty discretionaries after explicit hyphens, these rules imply that already-hyphenated compound words will not be further hyphenated by the algorithm.)

As to *why* Knuth chose to do this, I am not really sure. For documentation of the `"-` and `"|` shortcuts, look at some documentation of babel support for individual languages. For example, `texdoc italian` and `texdoc norsk` provide some information.
