### ISSUE TITLE
Enhancement: support for canadian and canadien

### ISSUE THREAD

**Issue by donovaly** [reutenauer/polyglossia#22]
This is no real bug report, but a technical issue:
babel supports the English language variant "canadian" and the French variant "canadien".
Will these variants be supported also by polyglossia in one of the next releases?

**Comment by jspitz** [comment]
These two varieties exist only nominally in babel as well:
* `canadian` is currently just an alias for `usenglish`
* `canadien` (or now: `acadian`) is currently just an alias for `french`

Nevertheless, to be in line with babel, similar (empty) support can be easily added (and later extended if desired).
