### ISSUE TITLE
Change German hyphenation patterns within a document

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#220]
For German there are different hyphenation rules and patterns for traditional and modern orthography. If I try to change the patterns within a document using the interface provided by `polyglossia`, I only get the expected results with `lualatex`, not with `xelatex`. With `xelatex` the patterns stay the same after the `\setkeys` command.

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[spelling=old]{german}

\begin{document}

\showhyphens{backen meiste}

\setkeys{german}{spelling=new}

\showhyphens{backen meiste}

\end{document}
```

Note: The old hyphenations are `backen` and `mei-ste`, the new ones `ba-cken` and `meis-te`.

**Comment by bastien-roucaries** [comment]
Implementing #226 will help

This is linked to #208

**Comment by jspitz** [comment]
Note, though, the the following works:
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[spelling=old]{german}

\begin{document}

\showhyphens{backen meiste}

\selectlanguage[spelling=new]{german}

\showhyphens{backen meiste}

\end{document}
```
The reason that `\setkeys` alone does not work is that `\l@<language>` is only reset in `\select@@language`

I think it is generally not a good idea to encourage users in the documentation to use `\setkeys`

**Comment by wehro** [comment]
> I think it is generally not a good idea to encourage users in the documentation to use `\setkeys`

I agree. A revision of the manual concerning the choice of options without `\setkeys` would be fine.

**Comment by jspitz** [comment]
Can you do it?

**Comment by wehro** [comment]
I have a proposal. But first, I have to await if #258 is accepted.

**Comment by reutenauer** [comment]
I thought you said yourself that #258 wasn’t enough to fix things; and indeed it’s only one line of effective code (since the rest just remove useless code and adds comments).  Anyway, I just accepted it.

**Comment by wehro** [comment]
> I thought you said yourself that #258 wasn’t enough to fix things; and indeed it’s only one line of effective code (since the rest just remove useless code and adds comments). Anyway, I just accepted it.

You are right. But I did not know what to do further and no one gave a comment. I did not withdraw the pull request because the one line of code is however an improvement.

**Comment by jspitz** [comment]
@wehro is there still something pending here after the manual has been corrected?

**Comment by wehro** [comment]
No, without the `\setkeys` command, the problem cannot occur.
