### ISSUE TITLE
Inconsistent french guillemets spaces between XeLaTeX and LuaLaTeX

### ISSUE THREAD

**Issue by gpelouze** [reutenauer/polyglossia#221]
Unicode french guillemets in the source (either with `« M »` or `«M»`) should be rendered with thin (0.25em-wide) non-breaking spaces. This is done correctly in LuaLaTeX, but not in XeLaTeX. 

Test case:

~~~tex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\begin{document}
« M

«M

M »

M»
\end{document}
~~~

Output:

LuaLaTeX | XeLaTeX
-|-
![lualatex-crop](https://user-images.githubusercontent.com/9514702/57785001-2d61d580-7731-11e9-814b-bb0a26e6b887.png) | ![xelatex-crop](https://user-images.githubusercontent.com/9514702/57784987-2935b800-7731-11e9-9ac8-532eb13b0cbe.png) 

While LuaLaTeX consistently produces the correct output, XeLaTeX has two issues :
- the spaces added in XeLaTeX are always too large (they look like regular spaces)
- when the source contains spaces (`« M »`), an extra space is added after **opening** guillemets, but not before **closing** guillemets, which is rather odd.

This seems different from issue #141, and I’m not really sure whether it is a polyglossia or a XeTeX issue.

---

Versions:  
polyglossia.sty    2018/04/07 v1.43  
LuaTeX, Version 1.07.0 (TeX Live 2018/Arch Linux)  
XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018/Arch Linux)

**Comment by wehro** [comment]
The following patch for `gloss-french.ldf` should help to solve the problems.

```
25d24
< \def\xpg@nospace#1{#1}
80c79
<       \XeTeXinterchartoks \french@punctguillstart \z@ = {\nobreakspace}% "«a" -> "« a"
---
>       \XeTeXinterchartoks \french@punctguillstart \z@ = {\thinspace}% "«a" -> "«\,a"
83c82
<       \XeTeXinterchartoks \z@ \french@punctguillend = {\nobreakspace}% "a»" -> "a »"
---
>       \XeTeXinterchartoks \z@ \french@punctguillend = {\thinspace}% "a»" -> "a\,»"
85,86c84,85
<         \XeTeXinterchartoks \french@punctguillstart \xpg@boundaryclass = {\nobreakspace\xpg@nospace\relax}% "«  " -> "«~"
<         \XeTeXinterchartoks \xpg@boundaryclass \french@punctguillend = {\xpg@unskip\nobreakspace}% "  »" -> "~»"
---
>         \XeTeXinterchartoks \french@punctguillstart \xpg@boundaryclass = {\thinspace\ignorespaces}% "«  " -> "«\,"
>         \XeTeXinterchartoks \xpg@boundaryclass \french@punctguillend = {\xpg@unskip\thinspace}% "  »" -> "\,»"
```

**Comment by gpelouze** [comment]
@wehro this indeed seems to fix the issue, thanks a lot!
