### ISSUE TITLE
How do write in three languages??

### ISSUE THREAD

**Issue by HelioGiroto** [reutenauer/polyglossia#223]
Is possible to write a **three languages text** in LaTeX with polyglossia?
English, Greek and Hebrew??
Example:

\documentclass{minimal} 
\usepackage{polyglossia}
\setdefaultlanguage{hebrew}
\setotherlanguage{english}
% AND GREEK ??? 
\setmainfont{Simple CLM}

\begin{document}
באלוהים אנו בוטחים
%\textgreek{Στον θεό που εμπιστευόμαστε}   % ?????
\begin{english}
    \begin{flushright}
        In God we trust
    \end{flushright}
\end{english}
\end{document}

**Thanks!!**

**Comment by HelioGiroto** [comment]
**I got!**
\documentclass{minimal}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguages{hebrew,greek}
% Fonts:
\setmainfont{Simple CLM}
\newfontfamily\greekfont{Arial}

\begin{document}
באלוהים אנו בוטחים

\begin{greek}
  Στον θεό που εμπ ιστευόμαστε
\end{greek}

% \textgreek{Στον θεό που εμπιστευόμαστε} % It works too!

In God we trust

\end{document}

**Comment by reutenauer** [comment]
Hi there,

I’m closing this as it is not really an issue with Polyglossia.  Glad it worked for you!
