### ISSUE TITLE
Enhancement: support for Mongolian

### ISSUE THREAD

**Issue by donovaly** [reutenauer/polyglossia#23]
babel supports the language Mongolian.
Will this language also be supported by polyglossia in one of the next releases?

**Comment by jspitz** [comment]
Uwe, the mongolian-babel package only supports a specific variety of Mongolian (Khalkha) in the Cyrillc script (not the Mongolian script, unfortunately).

Anyway, I have added a gloss that provides similar support for poylglossia.

**Comment by donovaly** [comment]
Many thanks Jürgen. Also many thanks for your impressive work on polyglossia!
