### ISSUE TITLE
No access to current language within Lua code

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#234]
The file `polyglossia.lua` defines the global variables `polyglossia.default_language` and `polyglossia.current_language`. But only the first one returns the correct value. The second variable returns always nil.

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage{french}

\begin{document}
default language: \directlua{tex.sprint(polyglossia.default_language)} % german

\today

language: \directlua{tex.sprint(polyglossia.current_language)} % should be "german", but nothing is output

\selectlanguage{french}
\today

language: \directlua{tex.sprint(polyglossia.current_language)} % should be "french", but nothing is output
\end{document}
```

**Comment by wehro** [comment]
The *current language* occurs in three places in `polyglossia.lua`.

Line 29 declares a local variable:
```
local current_language
```

A function for selecting a language is defined in lines 52 ff. The function code sets the local variable `current_language` to the language name. This function is called from `polyglossia.sty` when the user applies the `\selectlanguage` command.
```
local function select_language(lang, id)
  loadlang(lang, id)
  current_language = lang
  last_language = lang
end
```

Line 162 defines a global variable `polyglossia.current_language`:
```
polyglossia.current_language = current_language
```

When `polyglossia.lua` is read, the following happens:
1. A local variable `current_language` is declared.
2. A function `select_language` is defined, which may be called later.
3. The global variable `polyglossia.current_language` is set to the value of the local variable `current_language`, which is `nil`, as no value has been assigned to this variable so far.

A call of the `select_language` function only assigns a value to the local variable. The global variable is never updated. So the global variable is completely useless in the current code.

**Comment by bastien-roucaries** [comment]
a pull request is welcome for this one.

**Comment by wehro** [comment]
> a pull request is welcome for this one.

Unfortunately, the obvious solution is not the correct one.
The code change #258 only partly fixes the problem.
Now, in the example above, the second access to the current language yields `french`, which is correct, but the first yields nothing in the first TeX run and `french` in the second TeX run (due to something written to the aux file), though it should yield `german`.

**Comment by jspitz** [comment]
@wehro please try the following patch, this fixes the issues for me:
```
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 25e2fb1..e8a8892 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -978,7 +978,10 @@
      \xpg@set@language@nonaux[#2]{#3}%
    }{%
      \xpg@set@language@aux[#2]{#3}%
-   }
+   }%
+   \ifluatex %
+     \directlua{polyglossia.select_language('\luatexluaescapestring{\string#3}', \the\csname l@#3\endcsname)}%
+   \fi %
 }
 
 % Helper to get and register "variant" keyval

```

**Comment by wehro** [comment]
Yes this works.
There is another call of `polyglossia.select_language` in `polyglossia.sty` which seems to be useless after this change. Please have a look.

**Comment by jspitz** [comment]
Yes, thanks, This seems to be not needed anymore indeed.
