### ISSUE TITLE
Use \text_uppercase:n?

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#245]
\tl_upper_case:n was introduced four year ago, and i think we could replace MakeUpperCase by this command, passing the correct language depending of the context.

It will help for some case like nl for instance.

**Comment by josephwright** [comment]
Please keep @latex3 in the loop if you go for this!

**Comment by wehro** [comment]
In which places do you want to use this command?
So far, only `gloss-greek.ldf` uses this command for defining Greek numerals, where it does not really seem necessary.
Some other language moduls redefine `\MakeUppercase`, but do not use it. So the redefinition is obviously meant for the purposes of the user, who cannot use internal commands like `\tl_upper_case:n` anyway.

**Comment by josephwright** [comment]
`\tl_upper_case:n` is _not_ internal: it's code-level meant for implementing document-level features.

**Comment by wehro** [comment]
Sure. I meant *internal* in the sense of *not intended for the use of the document author*. My question is, which document-level features shall be implemented on polyglossia's code-level with this command.

**Comment by bastien-roucaries** [comment]
@wehro arabic redefine blindly MakeUpperCase to identity in order to avoid upercasing title.

This is fragile. Better will be to redefine MakeUpperCase to \tl_upper_case:n (current language)

**Comment by jspitz** [comment]
2020-02-02 kernel release supposedly brings stable versions of `\tl_upper_case:n` and friends (says @josephwright). So I think we can start pondering this change after that happened.

**Comment by jspitz** [comment]
The command to use is `\text_uppercase:n` nowadays, isn't it?

**Comment by josephwright** [comment]
The team will be shifting `\MakeUppercase` to use `\text_uppercase:n` internally - that will I guess close this issue.

**Comment by jspitz** [comment]
Thanks, @josephwright
