### ISSUE TITLE
Bug in font support for Armenian

### ISSUE THREAD

**Issue by donovaly** [reutenauer/polyglossia#25]
Try to compile this document:

---

\documentclass{article}
\usepackage{fontspec}
\setmainfont{DejaVu Serif}
\usepackage{xunicode}
\usepackage{polyglossia}
\setdefaultlanguage{armenian}
\begin{document}
Հա
\end{document}

---

Result: you always get the error that the roman font does not contain Armenian. But this is not true, DejaVu contains these characters and Windows  comes since XP with the font "Sylfaen" that supports this too. The Libertine fonts also support Armenian. But no matter what font you use, you get the error.
You can see that the font supports Armenian, if you replace in my example "armenian" by "albanian" - the Armenian characters are then correctly displayed.

As workaround I can add this
\newfontfamily\armenianfont[Script=Armenian]{DejaVu Serif}
and polyglossia then accepts that the font supports Armenian, but this should not be necessary, according to the polyglossia documentation.

**Comment by jspitz** [comment]
No more reproducible in current master.

**Comment by jspitz** [comment]
Verified that this is fixed in master as opposed to 1.44.

Someone who can please close this ticket.

**Comment by donovaly** [comment]
> No more reproducible in current master.

Many thanks for having a look.
