### ISSUE TITLE
polyglossia, french and verbatim

### ISSUE THREAD

**Issue by jech** [reutenauer/polyglossia#27]
Verbatim formatting is broken in French: \verb|a:b| produces "a :b".

Minimal example: http://www.pps.univ-paris-diderot.fr/~jch/polyglossia-bug.tex

--jch

**Comment by adunning** [comment]
As there's a question on where the bug lies, it's worth pointing out that it's also a problem with `fancyvrb`. It works either way with Babel:

```latex
\documentclass{article}

\usepackage[english, main=french]{babel}

% extra spaces with Polyglossia rather than Babel
% \usepackage{polyglossia}
% \setdefaultlanguage{french}
% \setotherlanguage{english}

\begin{document}

\verb|00:11:43:D4:86:A0|

\selectlanguage{english}
\verb|00:11:43:D4:86:A0|

\selectlanguage{french}
\begin{verbatim}
00:11:43:D4:86:A0
\end{verbatim}

\end{document}
```

**Comment by bastien-roucaries** [comment]
Close by commit c6684010f18a7bfc1059b7978a87361b2dc47359
