### ISSUE TITLE
French punctuation spacing is active even outside French texts

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#270]
With the current development version of polyglossia, the french punctuation spacing is active everywhere in the document if the French language module is loaded, even outside French language environments and even if no French language environment is used.

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage{french}
\begin{document}
abc: def; ghi!
\end{document}
```

The problem has to do with line 75 of `gloss-french.ldf`:
```
\DeclareRobustCommand\french@rmfamilyFB{\french@punctuation\french@rmfamilyORI}
```

**Comment by jspitz** [comment]
This is fixed. @bastien-roucaries can we please rename the new French option `OriginalTypewriter` to `autospacetypewriter`? This seems more transparent to me.
