### ISSUE TITLE
gloss may be package

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#273]
Hi,

A contreversial proposition. Instead of creating your loader, I believe that gloss file shoud be package:

pro:
- easier parsing of option
- simplify code 
Cons:
- gloss file are not really package.

**Comment by bastien-roucaries** [comment]
@jspitz

**Comment by reutenauer** [comment]
Can you give an example of current code that would be simplified?

**Comment by bastien-roucaries** [comment]
@reutenaeur the loaded@language could be removed and the custom made loader could be removed. Moreover other package could use filehook package to load custom code at loading of some language.

**Comment by bastien-roucaries** [comment]
@reutenaeur using l3keys also will vastly simplify the handling of option

**Comment by jspitz** [comment]
The problem with packages is that people think they can load it standalone. I really think it would be more confusing than helpful

**Comment by reutenauer** [comment]
That’s a valid objection @jspitz, but then what about conditionally loading `polyglossia.sty` at the top of every language definition file?  It can be done in only one line.  I completely agree with you that it’s absolutely essential not to make the situation more confusing than it already is for users (what with the choice between Babel and Polyglossia, to start with), but the potential to save developers a lot of repetition and boilerplate code is quite attractive, I have to say.

**Comment by jspitz** [comment]
I really think package is not the right format for what ldf files are. This just cries for all sorts of hassles.

**Comment by bastien-roucaries** [comment]
@reutenaeur: you means inconditionnaly loading

Another solution for avoiding the user pitfall, we could define \xpg@donotloaddirectly and create a thin wrapper when we load the package that redefine to \relax.

Therefore option parsing will be easier and user will not include direclty

**Comment by reutenauer** [comment]
Actually, come to think of it, LaTeX 3 may have convenience methods for loading non-package files, that would void the need for rolling our own.  @bastien-roucaries, do you know anything about that?

Seen your reply while I was typing this one: no, I do mean _conditionally_ loading: load `polyglossia.sty` if and only if it wasn’t already loaded.  No point in loading twice, and it may not be idempotent (although it probably would be a good thing if it was, but I have never tested).

**Comment by bastien-roucaries** [comment]
@reutenaer Moreclear in every gloss do \RequirePackage{polyglossia}

Require package avoid double inclusion. will take a look at exp3

**Comment by reutenauer** [comment]
It strikes that the best of both world would be to be able to use LaTeX package-related commands (`RequirePackage`, etc.) while keeping the names`.ldf`.  @jspitz Would that alleviate your concerns?

**Comment by jspitz** [comment]
Yes, that would be fine with me.

**Comment by bastien-roucaries** [comment]
unfortunately Requirepackage hardcode sty suffix...

We coul try to change suffix but I do not know if it work. Will try
