### ISSUE TITLE
Create a "C" language

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#274]
In order to simplify the language handling we must create a C language.

This language will be loaded in all the case and will be english.

Before other hook at begin of document it will save every command that are needed for restoration by other package and saved it if user does not provide a command in 
\polyglossiaCnameofcommand.

For instance \@arabic should be saved as \polyglossiaClocalnumber

Other package should reference the C variant instead of relying of locally saving/restoring

This behavior should be documented.

**Comment by reutenauer** [comment]
If we’re going to have a default language I really think it should be called `default` or something similar.  Languages in TeX are not POSIX locales.

Actually, come to think it can be simply called `polyglossia`: `\polyglossialocalnumber` etc. :-)

**Comment by bastien-roucaries** [comment]
@reutenaeur C language is only used internally. 

It will allow to register cleanly variant.

Default could means main language. moreover C is well known in the l10n communauty as an alias. I am not striclty attached to the name, more for the principle

**Comment by reutenauer** [comment]
Right, “default” could mean document-level default language, but I’m really not convinced that “C language” will be understood correctly in the TeX community.  Actually, I’m not even sure that I do: is the point to provide hooks for individual language files to implement their own style and commands?  Because in that case `polyglossia` as a prefix would work just as well, I think; for example, I don’t really see what `Clang` brings to the control sequence names in [these two lines](https://github.com/reutenauer/polyglossia/blob/master/tex/polyglossia.sty#L57-L58).  Surely `\polyglossia@@arabic` and `\polyglossia@arabic` would work just as well, no?

**Comment by reutenauer** [comment]
Actually, I’ve meant for a while to reserve a [module prefix](https://github.com/latex3/latex3/blob/master/l3kernel/l3prefixes.csv) as explained in the `expl3` documentation.  What should be choose: `pg` for short?  Or `xpg` to match the `\xpg@...` control sequences?  The full `polyglossia` is too long for my taste.

**Comment by bastien-roucaries** [comment]
@reutenaer the goal is to put the "C" definition in the property list of language thus allowing to define by default some hook, instead of relying to cs@ifundefined, we will call the hook inconditionnaly and we known that the hook is by default correct and the one of the "C" language.

We push the burden to save the default to the C language

I only need a name (or two because I will implement also alias)

**Comment by jspitz** [comment]
Does this mean that every document will load English even if not specified? Or is this language only used internally?

**Comment by reutenauer** [comment]
I think the idea is to use it internally only.  It’s a good, we only need to define the programming interface a bit more precisely.

**Comment by bastien-roucaries** [comment]
Only internally, it could be used extenally for checking that we could restore bare english, but only internally.

@jspitz C will correspond to latex without loading polyglossia or babel. Aka bare latex

**Comment by reutenauer** [comment]
Just realised: then it _has_ to be called LaTeX, not C.  That is the language, after all ;-)

**Comment by jspitz** [comment]
Thanks for the explanation.

**Comment by jspitz** [comment]
> Just realised: then it _has_ to be called LaTeX, not C. That is the language, after all ;-)

I agree. That's also the term LyX uses for this purposes, by the way.

**Comment by bastien-roucaries** [comment]
Ok so will create LaTeX language

**Comment by bastien-roucaries** [comment]
Closed: created latex language.

**Comment by wehro** [comment]
> Actually, I’ve meant for a while to reserve a [module prefix](https://github.com/latex3/latex3/blob/master/l3kernel/l3prefixes.csv) as explained in the `expl3` documentation. What should be choose: `pg` for short? Or `xpg` to match the `\xpg@...` control sequences? The full `polyglossia` is too long for my taste.

I would prefer the full `polyglossia`. Code is more often read than written. Therefore readability is more important than shortness. When I first took a look into to polyglossia code, it took me quite a while to realize what `xpg` means, whereas the meaning of `polyglossia` is obvious.

**Comment by reutenauer** [comment]
`polyglossia` it is, [then](/latex3/latex3/pull/622).  Although I have to say I don’t find the LaTeX 3 style particularly readable.
