### ISSUE TITLE
Polyglossia and nomencl package conflict

### ISSUE THREAD

**Issue by madarexxx** [reutenauer/polyglossia#280]
Polyglossia is really nice and comfortable package, highly appreciated in Russian LaTeX community. 

After updating TeXlive to 2019 I've got severe compile errors on my documents that were written with TeXlive 2018. After some hours of debugging complex documents and getting very useful advice from Russian Linux forum I've been able to locate the error and write MWE. 

```latex
% !BIB TS-program = biber
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{nomencl}

%\usepackage[russian,english]{babel}%Comment entire Polyglossia section and uncomment this line and MWE builds without errors

\usepackage{polyglossia}
\setmainlanguage[]{russian}%set language to english and there is no build error
\setmainfont{Times New Roman}
\setromanfont{Times New Roman} 
\setsansfont{Arial}
\newfontfamily{\cyrillicfont}{Times New Roman} 
\newfontfamily{\cyrillicfontrm}{Times New Roman}
\newfontfamily{\cyrillicfontsf}{Arial}

\defaultfontfeatures{Scale=MatchLowercase, Ligatures=TeX, Mapping=tex-text} 
\begin{document}
Hello world! 
\end{document}
```
Error code:
```
Command \sectionformat undefined. \select@language {french}
Command \subsectionformat undefined. \select@language {french}
Command \subsubsectionformat undefined. \select@language {french}
Command \paragraphformat undefined. \select@language {french}
Command \subparagraphformat undefined. \select@language {french}
Command \sectionformat undefined. \begin{document}
Command \subsectionformat undefined. \begin{document}
Command \subsubsectionformat undefined. \begin{document}
Command \paragraphformat undefined. \begin{document}
Command \subparagraphformat undefined. \begin{document}
```

I have found out that Polyglossia works well with older nomencl version [2018/12/29 v5.0 Nomenclature package]. I am writing here because changing Polyglossia's language settings breaks nomencl. 

Please correct me if I am wrong.

Thanks in advance, and good luck in supporting such great and huge project!

**Comment by jspitz** [comment]
Thanks for the report. Fixed.

A workaround is probably putting the following before polyglossia is loaded

```
\providecommand*{\sectionformat}{}%
\providecommand*{\subsectionformat}{}%
\providecommand*{\subsubsectionformat}{}%
\providecommand*{\paragraphformat}{}%
\providecommand*{\subparagraphformat}{}%
```

**Comment by madarexxx** [comment]
@jspitz 
> Thanks for the report. Fixed.

Is there any information, when CTAN version will receive this fix? 

p.s. Thank you for ultra-fast fix :)

**Comment by jspitz** [comment]
No, but Arthur plans to release a new version soon.
