### ISSUE TITLE
Update change log

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#281]
I wanted to make a release this weekend, but many issues were still actively being worked on, so I postponed it.  We should probably release very soon now, but at least the change log needs to be updated, so that people will have a chance to see the list of improvements.  The README could use brushing up too.

**Comment by jspitz** [comment]
I agree on the plan. I also think we should make a release before the big interface changes (BCP tags etc.) are added. There have been very many bug fixes which warrant a release.

**Comment by jspitz** [comment]
I have added my own contributions now to the changelog.

**Comment by reutenauer** [comment]
Very impressive! :-)

**Comment by wehro** [comment]
Compiling with the current development version of polyglossia, I get a couple of warning messages. It is important to expunge them before a new release.
```
LaTeX Warning: You have requested package `gloss-latex',
               but the package provides `gloss-english'.

Package polyglossia Warning: No hyphenation patterns were loaded for `latex'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 13.

Package polyglossia Warning: \setlocalhyphenmin useless for unknown language la
tex on input line 13.

Package polyglossia Warning: Asking to add empty feature to latin font (Languag
e="German" to langtag "") on input line 3.

Module polyglossia Warning: Language latex not found in language.dat.lua on inp
ut line 13
```

**Comment by jspitz** [comment]
> ```
> LaTeX Warning: You have requested package `gloss-latex',
>                but the package provides `gloss-english'.
> ```

This one's fixed.

**Comment by jspitz** [comment]
> ```
> Package polyglossia Warning: Asking to add empty feature to latin font (Languag
> e="German" to langtag "") on input line 3.
> ```

This is because `gloss-german.ldf` (like most other ldf files) does not have a langtag yet. Adding these is easy but laborious.

BTW these are OpenType language tags, not BCP-47 tags (currently).
https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags

**Comment by jspitz** [comment]
I added all missing tags (except latex language) at https://github.com/reutenauer/polyglossia/commit/0cd5ce92cdea73759f319ca2e7611db64c1b0083

**Comment by bastien-roucaries** [comment]
On Tue, Sep 3, 2019 at 10:32 AM Jürgen Spitzmüller <notifications@github.com>
wrote:

> I added all missing tags (except latex language) at 0cd5ce9
> <https://github.com/reutenauer/polyglossia/commit/0cd5ce92cdea73759f319ca2e7611db64c1b0083>
>

Latex is same than english

**Comment by reutenauer** [comment]
Thanks @jspitz.  I fixed a few: 56181b4 :-)

**Comment by jspitz** [comment]
I have now opened #284 for the gloss-latex issues.

**Comment by reutenauer** [comment]
I now plan to make a release some time next week (starting 16 September); please check in all your changes by then.

**Comment by jspitz** [comment]
luabidi has some changes on which polyglossia depends. Please release luabidi with polyglossia.

**Comment by jspitz** [comment]
We're done :-)
