### ISSUE TITLE
multiple compiling gives multiple writing to aux

### ISSUE THREAD

**Issue by dohyunkim** [reutenauer/polyglossia#288]
When there is language option, each time you compile a tex file, you get the same lines written in aux file. So aux file becomes bigger and bigger in its size upon each compiling. For instance,
```
\documentclass{minimal}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}
\begin{document}
test
\end{document}
```
After compiling the above file twice, the aux file generated is as follows:
```
\relax
\selectlanguage [variant=british]{english}
\@writefile{toc}{\selectlanguage *[variant=british]{english}}
\@writefile{lof}{\selectlanguage *[variant=british]{english}}
\@writefile{lot}{\selectlanguage *[variant=british]{english}}
\selectlanguage [variant=british]{english}
\@writefile{toc}{\selectlanguage *[variant=british]{english}}
\@writefile{lof}{\selectlanguage *[variant=british]{english}}
\@writefile{lot}{\selectlanguage *[variant=british]{english}}
```

**Comment by eg9** [comment]
I can't reproduce the issue; the `.aux` file is
```latex
\relax 
\select@language {english}
\@writefile{toc}{\select@language {english}}
\@writefile{lof}{\select@language {english}}
\@writefile{lot}{\select@language {english}}
```
after any number of runs with either XeLaTeX or LuaLaTeX.

On the other hand, when compiling with XeLaTeX, a warning
```latex
(\end occurred when \ifx on line 4 was incomplete)
```
appears. This is triggered by `variant=british`.

**Comment by reutenauer** [comment]
Are you sure you have the latest version?  This has been corrected in `master`.  It is not on CTAN yet.

**Comment by eg9** [comment]
@reutenauer I've seen that now `variant=` uses choices; much better than nesting `\ifstrequal`.

**Comment by moewew** [comment]
I can reproduce the issue with the `.sty` and `.ldf` files downloaded from `master` (specifically https://github.com/reutenauer/polyglossia/tree/eb977babdb641bded75dff43bfe568173cc60d90, I got the `.zip` from https://github.com/reutenauer/polyglossia/archive/eb977babdb641bded75dff43bfe568173cc60d90.zip). The `.aux` files build up `\selectlanguage` instructions for each XeLaTeX or LuaLaTeX run.

```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}
\begin{document}
test
\end{document}
```

The issue is indeed not present with the release version available on CTAN and present in TeX live and MikTeX.

**Comment by jspitz** [comment]
Typo. Fixed.

**Comment by moewew** [comment]
Thank you very much.
