### ISSUE TITLE
latin glosses

### ISSUE THREAD

**Issue by jspitz** [reutenauer/polyglossia#293]
What is the relation of `gloss-classiclatin.ldf` and `gloss-liturgicallatin.ldf` to `gloss-latin.ldf` with the variant options `classic` and `liturgical?` Only the latter seems to be documented. Does it make any sense to ship the former?

**Comment by reutenauer** [comment]
Probably not; the latter two files were added in a single commit (f397314) and never updated.  I suspect the reason was to be able to load Classical Latin and Liturgical Latin with a single keyword (no variant), as some package writers like to do.  Perhaps @eroux can enlighten us?

**Comment by eroux** [comment]
I honestly can't remember anything about it, sorry...

**Comment by jspitz** [comment]
OK. Done. As to loading with a keyword, we need something more general anyway (see #112)

**Comment by wehro** [comment]
There are several issues with the Latin support of polyglossia. I am working on a totally renewed version of `gloss-latin.ldf`. Please don't change anything before this is completed.

**Comment by wehro** [comment]
No, these files are not needed and may be removed. I suppose they were introduced because the `\PolyglossiaSetup` command does not allow to define several different hyphenation patterns, as needed for Latin.
By the way, the language modules for German and English differ in respect of the `hyphennames` field. The English module uses it, the German not. What shall I do for Latin?

**Comment by jspitz** [comment]
> No, these files are not needed and may be removed. I suppose they were introduced because the `\PolyglossiaSetup` command does not allow to define several different hyphenation patterns, as needed for Latin.

The patterns need to be set in `variant` handling.

> By the way, the language modules for German and English differ in respect of the `hyphennames` field. The English module uses it, the German not. What shall I do for Latin?

You don't need it as you set the patterns in `variant`.

BTW I would strongly advise to rewrite the variant handling using choice key. I rewrote it here like this, but I won't interfere with your changes:
```
\define@choicekey*+{latin}{variant}[\val\nr]{modern,medieval,classic,liturgical}[modern]{%
   \ifcase\nr\relax
     % modern
     \let\latin@variant\l@latin
     \ifluatex
        \xpg@set@language@luatex@iv{latin}
     \fi
     \xpg@info{Option: Modern Latin}%
   \or
     %medieval
     \let\latin@variant\l@latin
     \ifluatex
       \xpg@set@language@luatex@iv{latin}
     \fi
     \medievaltrue\classictrue
     \xpg@info{Option: Medieval Latin}%
   \or
     % classic
     \ifluatex
       \xpg@set@language@luatex@iv{classiclatin}
     \fi
     \xpg@ifdefined{classiclatin}{%
         \let\latin@variant\l@classiclatin
       }{%
         \xpg@nopatterns{Classic Latin}%
         \adddialect\l@classiclatin\l@latin
         \let\latin@variant\l@latin
      }%
     \medievalfalse\classictrue
     \xpg@info{Option: Classic Latin}%
   \or
     % liturgical
     \ifluatex
       \xpg@set@language@luatex@iv{liturgicallatin}
     \fi
     \xpg@ifdefined{liturgicallatin}{%
          \let\latin@variant\l@liturgicallatin%
        }{%
          \xpg@nopatterns{Liturgical Latin}%
          \adddialect\l@liturgicallatin\l@latin
          \def\latin@variant{\l@latin}%
        }%
     \medievaltrue\classicfalse
     \xpg@info{Option: Liturgical Latin}
  \fi
}{\xpg@warning{Unknown Latin variant `#1'}}


```

**Comment by wehro** [comment]
The new version of `gloss-latin.ldf` is ready now.
I will publish a pull request also containing the necessary changes in `gloss-french.ldf` and the external Lua scripts as well as an extended manual as soon as #310 will be accepted.

**Comment by jspitz** [comment]
@reutenauer what are the release plans? Should we include the updated babelsh.def? It allows @wehro to go ahead, but it will require some more time for testing before release.

**Comment by wehro** [comment]
@jspitz If you prefer, I can withdraw #310 and open a new pull request with all files related to the Latin module. Then it would be possible to read and discuss the code (however, it's quite lot).
But I can also wait until the next release. I am not in a hurry.

**Comment by jspitz** [comment]
@wehro I am completely fine with merging the babel code and proceed with Latin. I just want to be sure this does not interfere with @reutenauer 's release plans (and I think we should really release soon, given the massive improvements over 1.44).
