### ISSUE TITLE
Regression (?) with setup of non-latin font

### ISSUE THREAD

**Issue by scottkosty** [reutenauer/polyglossia#295]
The file [mwe.txt](https://github.com/reutenauer/polyglossia/files/3612215/mwe.txt) used to compile for me with XeTeX and LuaTeX as of 6e612ecf. The LuaTeX log with the error is [here](https://github.com/reutenauer/polyglossia/files/3612218/bad_6e612ecf.log) and the log without the error (using the commit just before 6e612ecf) is [here](https://github.com/reutenauer/polyglossia/files/3612219/good_645fbcf5.log).

I know nothing about Korean, polyglossia, or LuaTeX, so I have no idea if this error is intended. Nonetheless I wanted to check in.

Thanks to everyone helping with the recent development!

**Comment by jspitz** [comment]
Yes, it's a regression

**Comment by jspitz** [comment]
Should be fixed. Please text.
