### ISSUE TITLE
Error with Italian

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#3]
If one writes

```
{\selectlanguage{italian}\hyphenation{<word list>}}
```

before \begin{document} in order to set hyphenation exceptions for Italian, an error will pop out; the remedy is to write

```
\let\xpgit@savedvalues\@empty
```

between lines 102 and 103 in gloss-italian.ldf to provide a default definition that will be overridden when executing the \AtBeginPreamble hook.

**Comment by bastien-roucaries** [comment]
Could be closed
