### ISSUE TITLE
\noextras at beginning of the document?

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#301]
So far, polyglossia executes `\noextras@<lang>` at the beginning of the document (via `\xpg@initial@setup`), where `<lang>` is the default language.
Is this really necessary? I would suppose `\noextras` is only necessary at the end of a language environment, not before the beginning of any language environment.

**Comment by jspitz** [comment]
It is necessary at the beginning of new language environments in the case of nested languages.

**Comment by wehro** [comment]
That's right, but it does not mean that it is necessary within `\AtBeginDocument`.

**Comment by jspitz** [comment]
OK, but then we'd need to setup an extra route only for this particular purpose. Does it really harm to issue `\noextras@<lang>` here? Also, if someone sets a different language in the preamble, the `\noextras@<lang>` is supposedly needed.

**Comment by wehro** [comment]
I don't want an extra route, but I think that the code is not clean so far. I have instructed polyglossia to print a message every time it calls `\noextras...` or `\...extras...` including the macro whichin these are called. I used the following simple document:

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}
Test
\end{document}
```
The output after the first run were:
```
xpg@initial@setup: noextras german xpg@initial@setup: noextras german
select@@language: noextras german @select@language: extras german [1]
(./Noextras-Test.aux xpg@initial@setup: noextras german
select@@language: noextras german @select@language: extras german)
xpg@initial@setup: noextras german select@@language: noextras german
@select@language: extras german )
```
I think `\noextras...` is called far too often.

**Comment by jspitz** [comment]
There was one place where it was called unnecessarily: `\xpg@initial@setup`. If your debug code now still returns multiple calls, then remember (1.) it is also called at the end of a document and (2.) from the aux file. So with your MWE above, you should get now 4 calls (rather than 7)

**Comment by wehro** [comment]
I get only three `\noextras` calls, but it looks correct to me.

```
select@@language: noextras german @select@language: extras german [1]
(./Noextras-Test.aux select@@language: noextras german
@select@language: extras german) select@@language: noextras german
@select@language: extras german )

```
