### ISSUE TITLE
Typo about parameters of `\resetdefaultlanguage`

### ISSUE THREAD

**Issue by dohyunkim** [reutenauer/polyglossia#303]
https://github.com/reutenauer/polyglossia/blob/d3646a5e6f1a26dd12dcd51acaa7b9549ad4c0b2/tex/polyglossia.sty#L1013

The first parameter of `\resetdefaultlanguage` is a language option, which is empty by default.
So this typo should be fixed as follows:
```
 \polyglossia@error@iflangnotloaded:n{#2}
```

**Comment by jspitz** [comment]
Thanks, fixed.
