### ISSUE TITLE
Biblatex warnings

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#311]
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\usepackage{biblatex}

\begin{document}
Test
\end{document}
```
This document results in the following warning:
```
Package biblatex Warning: Language 'latex' not supported.
(biblatex)                Using fallback language 'german' on input line 6.
```

**Comment by wehro** [comment]
```
\documentclass{article}
\usepackage{biblatex}
\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}
Test
\end{document}
```
This documents results in the following error message:
`! Package biblatex Error: No default 'polyglossia' language defined.`

**Comment by jspitz** [comment]
> `! Package biblatex Error: No default 'polyglossia' language defined.`

Polyglossia must be loaded before biblatex (see biblatex manual). Or this check must be postponed (in biblatex),

**Comment by jspitz** [comment]
> Package biblatex Warning: Language 'latex' not supported.
> (biblatex)                Using fallback language 'german' on input line 6.

This is fixed.
