### ISSUE TITLE
Language modules and footnote settings

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#315]
The appearance of footnotes should not change within a document (cf. #294).
My conclusion is that only the main language should be allowed to change footnote settings.
However, the following document is typeset with French footnotes even if German is the main language.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage[frenchfootnote]{french}

\begin{document}
German text\footnote{German footnote}
\selectlanguage{french}
French text\footnote{French footnote}
\end{document}
```
![german-french](https://user-images.githubusercontent.com/33468411/66415500-f9e35880-e9fb-11e9-95a6-6106786388eb.png)

The corresponding babel document is typeset with default footnotes for French and German, which I consider as correct.
```
\documentclass{article}
\usepackage[french,german]{babel}

\begin{document}
German text\footnote{German footnote}
\selectlanguage{french}
French text\footnote{French footnote}
\end{document}
```
![german-french-babel](https://user-images.githubusercontent.com/33468411/66416070-53985280-e9fd-11e9-8b8d-9dd4b4505c41.png)

I came across this topic because the `ecclesiastic` package, a supplement to `babel-latin`, defines a footnote style similiar to the French one, but not identical, as the first line of a footnote is not indented here. The redefinition of `\@makefntext` by the `ecclesiastic` package is something equivalent to
```
\parindent 1em
\noindent
\hbox{\normalfont\@thefnmark.}
\enspace #1
```
All ecclesiastical documents and liturgical books using footnotes I consulted do not use this style, but something very similar to the default LaTeX footnotes. However, I would like to offer this style as an option in the new Latin language module (using the boolean key `ecclesiasticfootnotes`), as I suppose it was introduced to the `ecclesiastic` package for good reason. Maybe it was used in older liturgical books or in certain regions.
The `ecclesiastic` package has decided to enable the footnote style within the `extras` command and to switch to the saved default style within the `noextras` command.
As stated above, the footnote style should not change within the document, so this implementation is not desirable.
The French language module of `polyglossia` sets the footnote style as soon as the `frenchfootnote` option is called. This implementation is better, but it should only apply if French is the main language of the document.

By the way, why was `frenchfootnote` chosen as key name? I think the plural from `frenchfootnotes` would be more natural. In `babel-french`, it's called `FrenchFootnotes`.

**Comment by jspitz** [comment]
Fixed.
I didn't change the option name for backwards compatibility reasons.
