### ISSUE TITLE
Warning with German language module

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#316]
The following document yields a warning message with LuaLaTeX.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}
Test
\showhyphens{Silbentrennung}
\end{document}
```
```
Package polyglossia Warning: No hyphenation patterns were loaded for `german'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 7.
```

**Comment by wehro** [comment]
With the code above, I now get the following warning multiple times.

`warning  (hyphenation): a conflicting pattern has been ignored`

**Comment by jspitz** [comment]
No idea where that comes from.

**Comment by wehro** [comment]
Can you confirm the warning I get?
I think it means that different sets of hyphenation patterns are loaded simultaneously.

**Comment by jspitz** [comment]
The warnings seem to be gone after 4024d4e.

**Comment by wehro** [comment]
Confirmed.
