### ISSUE TITLE
Latin language variant selecting error

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#318]
The following document yields an error message both with the current Latin gloss file and with my new version of this file (which is not yet published).
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[variant=classic]{latin}

\begin{document}
\today
\end{document}
```
```
Runaway argument?
variant=classic@xpg@langvariant\relax \__clist_map_function:Nw \__clist_map_1:w
 \ETC.
! File ended while scanning use of \xpg@parsevariantkeyvalue.

```

**Comment by jspitz** [comment]
Works for me with current master. Obviously I can't help with your revised file, but I guess you need to update it to the recent changes.

**Comment by jspitz** [comment]
(but of course you can also post the file here if you need help)

**Comment by wehro** [comment]
You are right, it works with the current file (I should have tried two TeX runs).
I found out that the problem is the active `=` character (needed for prosodic shorthands as provided by `babel-latin`).
It already took me a lot of effort to avoid problems with active characters, but obviously, I am still not at the end. I will see if this one can be fixed.

**Comment by jspitz** [comment]
OK, so we can close this. Tell me if I can help.
