### ISSUE TITLE
Improve czech support

### ISSUE THREAD

**Issue by jarda-wien** [reutenauer/polyglossia#32]
There are some special rules regarding line endings in the czech language which polyglossia doesn't seem to support.

1) a single character word can't be left alone at the end of a line and has to be put on the beginning of the next line (for now manually using a non breaking space).

2) hyphenation that breaks a word on to two pages is not allowed, that is, a page cannot end with a hyphenated word.

3) if there is a hyphen in the word to be split, there has to be a hyphen at the end of the line and a second one on the begining of the next line. For example: "matematicko-fyzikalni" -> "matematicko-\n-fyzikalni"

Would these rules be complicated to implement?

**Comment by jspitz** [comment]
Servus, @jarda-wien, sorry for the very late reply.

>     1. a single character word can't be left alone at the end of a line and has to be put on the beginning of the next line (for now manually using a non breaking space).

There are (meanwhile) some external package that help with this. For LuaTeX, there is the dedicated `luavlna` package (see https://ctan.org/pkg/luavlna) as well as the quite similar cstypo (https://ctan.org/pkg/cstypo) and the more general `impnattype` package with the `nosingleletter` option (see https://ctan.org/pkg/impnattypo). For XeTeX, there is xevlna (https://ctan.org/pkg/xevlna).

I am not sure we should include this functionality to polyglossia, but we can document the use of these packages.

Maybe you can report back here if one of these fits your needs.

>     2. hyphenation that breaks a word on to two pages is not allowed, that is, a page cannot end with a hyphenated word.

With traditional LaTeX, this is not possible, see https://tex.stackexchange.com/a/212915/19291. It seems to be doable with LuaTeX, see https://tex.stackexchange.com/a/493060/19291

>     3. if there is a hyphen in the word to be split, there has to be a hyphen at the end of the line and a second one on the begining of the next line. For example: "matematicko-fyzikalni" -> "matematicko-\n-fyzikalni"

This is what the `splithyphens` option of `babel-czech` does. We can port that to polyglossia. Note, however, that the option is also off by default with babel, as the active `-` causes trouble with other packages (such as booktabs).

**Comment by jspitz** [comment]
> There are (meanwhile) some external package that help with this. For LuaTeX, there is the dedicated `luavlna` package (see https://ctan.org/pkg/luavlna) as well as the quite similar cstypo (https://ctan.org/pkg/cstypo) and the more general `impnattype` package with the `nosingleletter` option (see https://ctan.org/pkg/impnattypo). For XeTeX, there is xevlna (https://ctan.org/pkg/xevlna).
> 
> I am not sure we should include this functionality to polyglossia, but we can document the use of these packages.

This is now done.

**Comment by jarda-wien** [comment]
Hi @jspitz , I am affraid that I no longer use any typesetting system since mi university days are over. Because of this, I can not comment on the current landscape and czech support within that.

At least having a hint in the documentation is a good step forward. I will leave up to you if you want to have this ticket still open to track some of the ideas or if you just close it.

Cheers.

**Comment by jspitz** [comment]
Thanks, @jarda-wien. We leave this open, since it's a sensible request.

**Comment by jspitz** [comment]
splithyphens will be supported with the next version of `luavlna`. I think we should not implement the babel splithyphens approach, as it does more harm than good. I have extended the manual on Czech. I think that's all we can do for now.

**Comment by jspitz** [comment]
I just learned that `splithyphens` can be implemented quite easily in XeTeX via `\XeTeXinterchartoks`. The following patch seems to work, and it doesn't seem to badly interfere neither with math nor with dashes in commands (e.g. labels or booktabs `\cmidrule`):
```diff
diff --git a/tex/gloss-czech.ldf b/tex/gloss-czech.ldf
index 970ebba..397c040 100644
--- a/tex/gloss-czech.ldf
+++ b/tex/gloss-czech.ldf
@@ -12,6 +12,12 @@
 
 \define@boolkey{czech}[czech@]{splithyphens}[true]{}
 
+\ifluatex
+\else
+  \newXeTeXintercharclass\czech@hyphen % -
+\fi
+
+
 \ifsystem@babelshorthands
   \setkeys{czech}{babelshorthands=true}
 \else
@@ -24,11 +30,15 @@
   \shorthandoff{"}%
 }{}
 
-\def\cs@splithyphen{%
-  \kern\z@\discretionary{-}{\char\hyphenchar\the\font}{-}%
+\def\cs@@splithyphen#1{%
+  \kern\z@\discretionary{-}{\char\hyphenchar\the\font}{#1}%
   \nobreak\hskip\z@%
 }
 
+\def\cs@splithyphen{%
+  \cs@@splithyphen{-}%
+}
+
 \def\czech@shorthands{%
   \bbl@activate{"}%
   \def\language@group{czech}%
@@ -43,6 +53,26 @@
   \@ifundefined{initiate@active@char}{}{\bbl@deactivate{"}}%
 }
 
+\def\czech@hyphens{%
+    \ifluatex
+      \xpg@warning{The splithyphens option only works for XeLaTeX.\MessageBreak
+                   Please use the luavlna package to enable the feature for LuaLaTeX}
+    \else
+      \XeTeXinterchartokenstate=1
+      \XeTeXcharclass `\- \czech@hyphen
+      \XeTeXinterchartoks \z@ \czech@hyphen = {\cs@@splithyphen}% "-" -> "\cs@@splithyphen-"
+    \fi
+}
+
+\def\noczech@hyphens{%
+    \ifluatex
+    \else
+      \XeTeXcharclass `\- \z@
+      \XeTeXinterchartokenstate=0
+    \fi
+}
+
+
 \def\captionsczech{%
    \def\refname{Reference}%
    \def\abstractname{Abstrakt}%
@@ -78,14 +108,17 @@
 
 \def\noextras@czech{%
   \noczech@shorthands%
+  \noczech@hyphens%
 }
 
 \def\blockextras@czech{%
-  \ifczech@babelshorthands\czech@shorthands\fi
+  \ifczech@babelshorthands\czech@shorthands\fi%
+  \ifczech@splithyphens\czech@hyphens\fi%
 }
 
 \def\inlineextras@czech{%
-  \ifczech@babelshorthands\czech@shorthands\fi
+  \ifczech@babelshorthands\czech@shorthands\fi%
+  \ifczech@splithyphens\czech@hyphens\fi%
 }
 
 \endinput
```

For LuaTeX, we can simply instruct users to use the `luavlna` package, which will implement splithyphens for LuaTeX in its next release (see https://github.com/michal-h21/luavlna/issues/4)

**Comment by jspitz** [comment]
The options `splithyphens` and `vlna` are now implemened for XeTeX. For LuaTeX, this is not necessary, as the `luavlna` package is available (which is documented in Polyglossia).

**Comment by ivankokan** [comment]
Looking at Czech and Slovak babel extensions...

> split, nosplit
> These options control whether hyphenated words are automatically split
> according to Czech typesetting rules. With the split option “je-li” is
> hyphenated as “je-/-li”. The nosplit option disables this behavior.
>
> The use of this option is strongly discouraged, as it breaks too many
> common things—hyphens cannot be used in labels, negative arguments
> to TEX primitives will not work in horizontal mode (use \minus as a
> workaround), and there are a few other peculiarities with using this
> mode.

Does such recommendation hold for polyglossia or the feature is here implemented in a better way compared to babel?

**Comment by jspitz** [comment]
The latter (better implementation)

**Comment by ivankokan** [comment]
Any special reason for having it disabled by default (except the consistency with babel)?

**Comment by jspitz** [comment]
Yes, backwards compatibility. We do not want the documents of users to change without their approval.

**Comment by ivankokan** [comment]
Actually, the defaults in polyglossia are set to enabled. I misread the manual. :)
https://github.com/reutenauer/polyglossia/issues/454#issuecomment-725241452
