### ISSUE TITLE
Switching problems with English hyphenation patterns

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#322]
The following document has two different problems.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}

\begin{document}
This text is hyphenated.
\showhyphens{hyphenation}
\disablehyphenation
This text is not hyphenated.
\showhyphens{hyphenation}
\selectlanguage[variant=british]{english}
This text should not be hyphenated, but it is.
\showhyphens{hyphenation}
\end{document}
```

1. After the switch to British, hyphenation is enabled, but it should stay disabled according to the manual.
2. After two runs, the British patterns apply even to the first part of the document. Note that `hy-phen-a-tion` is the result of the British patterns, whereas the American patterns yield `hy-phen-ation`.

**Comment by jspitz** [comment]
>     2. After two runs, the British patterns apply even to the first part of the document. Note that `hy-phen-a-tion` is the result of the British patterns, whereas the American patterns yield `hy-phen-ation`.

This one's fixed.

**Comment by jspitz** [comment]
First issue fixed as well.

**Comment by dohyunkim** [comment]
The real cause seems to be the unnecessary call of `\xpg@set@hyphenation@patterns` at line 1352. So the following patch also solves the problem.
```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 14e5157..2a711b6 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -285,7 +285,6 @@
 \newcommand*\polyglossia@setup@language@patterns[1]{%
   \ifbool{xpg@hyphenation@disabled}{%
     \xdef\xpg@lastlanguage{\the\csname l@#1\endcsname}%
-    \language=\l@nohyphenation%
   }{%
     \cs_if_eq:cNTF{l@#1}{\l@nohyphenation}{%
         \language=\l@nohyphenation%
@@ -1349,7 +1348,7 @@
        }%
     \fi
     \polyglossia@check@ifdefined:NTF{#1}%
-       {\xpg@set@hyphenation@patterns{#1}#2}%
+       {#2}%
        {#3}%
 }%

```

**Comment by jspitz** [comment]
If you have carefully tested this, please provide a PR. It's of course better than my fix.
