### ISSUE TITLE
Compiling the manual

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#324]
Trying to compile the manual with XeTeX, I first get the following warning:
```
Package bidi Warning: Patching '\begin' failed!
(bidi)                '\bidi@AtBeginEnvironment' will not work.
```
And thereafter an error message:
```
! Package polyglossia Error: The current latin font EzraSIL(0) does not contain
 the "Arabic" script!
(polyglossia)                Please define \arabicfont with \newfontfamily comm
and.

See the polyglossia package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.973 So please use this with care.}

```
I suppose this is a problem of my personal system. Can someone help me to get rid of it? I am using TeX Live 2019 with all current updates.
The messages don't occur with LuaLaTeX, but with this engine there are others.

**Comment by jspitz** [comment]
Is this with your revised gloss-latin?

**Comment by jspitz** [comment]
> ```
> Package bidi Warning: Patching '\begin' failed!
> (bidi)                '\bidi@AtBeginEnvironment' will not work.
> ```

This is a bidi bug: https://github.com/bidi-tex/bidi/issues/10

**Comment by jspitz** [comment]
Do you have the respective `\arabicfont` (Amiri) installed?

**Comment by wehro** [comment]
> Is this with your revised gloss-latin?

With and without. My changes have no influence. The file `gloss-latin.ldf` itself is not loaded anyway.

**Comment by wehro** [comment]
> Do you have the respective `\arabicfont` (Amiri) installed?

It seems yes:
```
$ fc-list | grep 'Amiri'
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/Amiri-Regular.ttf: Amiri:style=Regular
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/Amiri-BoldSlanted.ttf: Amiri:style=Bold Slanted
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/AmiriQuran.ttf: Amiri Quran:style=Regular
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/Amiri-Slanted.ttf: Amiri:style=Slanted
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/AmiriQuranColored.ttf: Amiri Quran Colored:style=Regular
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/amiri/Amiri-Bold.ttf: Amiri:style=Bold

```

**Comment by jspitz** [comment]
Does Amiri work in other (MWE) documents?

**Comment by wehro** [comment]
> Does Amiri work in other (MWE) documents?

Yes, I can compile the following document with XeTeX without problems.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{arabic}
\newfontfamily\arabicfont{Amiri}

\begin{document}
\today
\end{document}
```

**Comment by jspitz** [comment]
Then I suggest you do classical bisecting: Cut the manual by half, check, if the error persists, cut the next half, if not, use the other half ...

**Comment by wehro** [comment]
The minimal example producing the problem is the following.
```
\documentclass{ltxdoc}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{arabic}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}
\MakeShortVerb{\¦}
\footnote{¦\textarabic{2010}¦}
\end{document}
```
The error message is:
```
! Package polyglossia Error: The current latin font Amiri(0) does not contain t
he "Arabic" script!
(polyglossia)                Please define \arabicfont with \newfontfamily comm
and.

See the polyglossia package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 \footnote{¦\textarabic{2010}¦}
```
If I remove the `\footnote{}` command around `¦\textarabic{2010}¦`, no error occurs.

**Comment by jspitz** [comment]
Does the following help also in the manual?
```tex
\newfontfamily\arabicfonttt[Script=Arabic]{Amiri}
```

**Comment by jspitz** [comment]
I think I found the cuplrit. Could you test if it compiles after ae5cd95?

**Comment by wehro** [comment]
Well, the minimal example runs with your change and the cited error message disappears when compiling the whole manual. But now I get on the screen during compilation:
```
xdvipdfmx:fatal: This font using the "seac" command for accented characters...

No output PDF file written.
```
The last two lines of the log file are:
```
Error 256 (driver return code) generating output;
file polyglossia.pdf may not be valid.
```

**Comment by jspitz** [comment]
I fear you need to to another bisecting, or start to substitute the fonts and see if a specific font is causing this. What OS is this BTW?

**Comment by wehro** [comment]
Here is another minimal example, producing the fatal error mentioned above.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{greek}

\setmonofont[Scale=MatchLowercase]{DejaVu Sans Mono}

\begin{document}
\begin{verbatim}
\begin{greek}[variant=ancient]
Ἀτρεί̈δης
\end{greek}
\end{verbatim}
\end{document}
```
The problem is the diaresis above the iota (nearly unvisible).
My operating system is Ubuntu 18.04.

**Comment by jspitz** [comment]
Works for me, so it's probably an issue with your fonts. I have DejaVu v. 2.37 installed here.

**Comment by wehro** [comment]
Obviously, I have DejaVu three times installed:
```
$ fc-list | grep 'DejaVu Sans Mono' | sort
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/dejavu/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/dejavu/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/local/texlive/2019/texmf-dist/fonts/type1/public/dejavu/DejaVuSansMono-BoldOblique.pfb: DejaVu Sans Mono:style=Bold Oblique
/usr/local/texlive/2019/texmf-dist/fonts/type1/public/dejavu/DejaVuSansMono-Bold.pfb: DejaVu Sans Mono:style=Bold
/usr/local/texlive/2019/texmf-dist/fonts/type1/public/dejavu/DejaVuSansMono-Oblique.pfb: DejaVu Sans Mono:style=Oblique
/usr/local/texlive/2019/texmf-dist/fonts/type1/public/dejavu/DejaVuSansMono.pfb: DejaVu Sans Mono:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
```
There is a Truetype version of TeX Live, a Type 1 version of TeX Live, and a Truetype Version delivered with the operating system. The first two have version number 2.34, the latter 2.37.
How can I find out which version is used by XeTeX or influence this?

**Comment by jspitz** [comment]
I don't know how to find out which font is used, but I think XeTeX will use OS fonts (the ones in `/usr/share/fonts/` rather than TeXLive fonts if no path is given [via the `Path` argument of `\setmainfont`]).

Does it help if you locally install the ttf fonts (to your OS) from the TeXLive tree?

**Comment by wehro** [comment]
> Does it help if you locally install the ttf fonts (to your OS) from the TeXLive tree?

This is not necessary. If the TeX Live fonts would not be installed locally, the would not appear in the output of the `fc-list` command.

My minimal example works if I select one of the Truetype versions explicitly:
`\setmonofont[Scale=MatchLowercase,Path=/usr/local/texlive/2019/texmf-dist/fonts/truetype/public/dejavu/]{DejaVuSansMono.ttf}`
or
`\setmonofont[Scale=MatchLowercase,Path=/usr/share/fonts/truetype/dejavu/]{DejaVuSansMono.ttf}`

Selecting the Type 1 versions produces the error:
`\setmonofont[Scale=MatchLowercase,Path=/usr/local/texlive/2019/texmf-dist/fonts/type1/public/dejavu/]{DejaVuSansMono.pfb}
`
For one reason or another, XeTeX seems to choose this version if no path is given. I should somehow uninstall it.

**Comment by jspitz** [comment]
> > Does it help if you locally install the ttf fonts (to your OS) from the TeXLive tree?
> 
> This is not necessary. If the TeX Live fonts would not be installed locally, the would not appear in the output of the `fc-list` command.

I thought that they would be preferred to others than, as ~/.local/shared/fonts/ is probably the first path in the hierarchy.

> For one reason or another, XeTeX seems to choose this version if no path is given. I should somehow uninstall it.

Odd. Anyhow, good to see the issue is solved now.
