### ISSUE TITLE
Russian language and test for a KOMA-Script class

### ISSUE THREAD

**Issue by cgnieder** [reutenauer/polyglossia#325]
The file
```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{russian}
\usepackage{scrlfile}
\begin{document}
Just some text
\end{document}
```
gives the error
```latex
! LaTeX Error: Command \sectionformat undefined.
```
because `gloss-russian.ldf` tests for a KOMA-Script class with `\ifdef{\KOMAScript}`, i.e., it tests for the KOMA-Script logo. A better test would probably be `\ifdef{\KOMAClassName}`

-------

See https://tex.stackexchange.com/questions/512929/ for a reference.

**Comment by jspitz** [comment]
This bug was fixed differently at ec1d4343ec935f1: We now generally check whether `\sectionformat `and friends are defined before attempting to redefine them.

I get a different error with the MWE, but this seems to been an issue in the filehook package:
```
LaTeX Warning: Command \InputIfFileExists   has changed.
               Check if current package is valid.

) (/usr/local/texlive/2019/texmf-dist/tex/latex/filehook/filehook-scrlfile.sty
Package: filehook-scrlfile 2011/01/03 v0.1 filehook patch for scrlfile package


! Package filehook Error: Detected 'scrlfile' package with unknown definition o
f \InputIfFileExists.
```

**Comment by cgnieder** [comment]
> We now generally check whether `\sectionformat` and friends are defined before attempting to redefine them.
OK, why not… (but then the check for `\KOMAScript` isn't necessary anymore, is it?) :)

> I get a different error with the MWE, but this seems to been an issue in the filehook package:
In my MWE the `filehook` package is not loaded?! (But yes, there is a conflict between `filehook` and `scrlfile`, see https://github.com/cgnieder/xsim/issues/50)

The warning due to `\InputIfFileExists` doesn't occur any more with `scrlfile 2019/10/12 v3.27`.

**Comment by jspitz** [comment]
> OK, why not… (but then the check for `\KOMAScript` isn't necessary anymore, is it?) :)

No, it isn't. But it still guards us from doing too many individual checks if not necessary.

> The warning due to `\InputIfFileExists` doesn't occur any more with `scrlfile 2019/10/12 v3.27`.

I see. This doesn't seem to have made it to all CTAN mirrors (I have updated TL today).

**Comment by jspitz** [comment]
Hm, and `\listfiles` reports
> scrlfile.sty    2019/10/12 v3.27 KOMA-Script package (loading files)

while the warning persists.
