### ISSUE TITLE
Adjust  error message "Oops! you have loaded package "package_name" after bidi package" for polyglossia   

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#328]
For RTL language polyglossia call bidi  Implicitly, if we add some packages patched from bidi after `\setdefaultlanguage{<RTL language>}` we obtain error 

> Oops! you have loaded package "package_name" after bidi package

The bidi package is hidden within polyglossia so user can't find it, I think with polyglossia the error message better if it is (or something similar):

> You need to place \setdefaultlanguage after packages call 

**Not working example**

```latex
\documentclass[12pt]{article}
\usepackage{polyglossia}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\setdefaultlanguage{arabic}

\usepackage{lipsum}
\usepackage{mwe}
\usepackage{caption} % patched with bidi 

\begin{document}
text 
\end{document}
```

**Working example**

```latex
\documentclass[12pt]{article}
\usepackage{polyglossia}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\usepackage{lipsum}
\usepackage{mwe}
\usepackage{caption} % patched with bidi 
\setdefaultlanguage{arabic}
\begin{document}
text 
\end{document}
```

**Comment by bastien-roucaries** [comment]
Suggest bidi to use filehooks. Polyglossia use it for bidi is it safe and allow to be load order indifferent

**Comment by jspitz** [comment]
Did I understand you correctly, @bastien-roucaries , that you also think this is something to be solved in bidi, not polyglossia?

**Comment by seloumi** [comment]
Or  may be a reminder for  users in the manual about that (\setdefaultlanguage should be placed after packages call in case of RTL languages) ?

**Comment by jspitz** [comment]
Good idea. Done.

**Comment by bastien-roucaries** [comment]
@jspitz  it should be solved in bidi but we could add the setdefaultlanguage trick

**Comment by seloumi** [comment]
@jspitz  how about inserting bidi inside `\AtEndPreamble`  implicitelly in polyglossia with RTL languages 

```
\documentclass{article}
\usepackage{polyglossia}

\AtEndPreamble{% should be done implicitelly  with RTL languages
\setdefaultlanguage{arabic}
}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\usepackage{xcolor}            
\usepackage{caption}
            
\begin{document}
\huge\color{red}
تجريب

\end{document}
```
