### ISSUE TITLE
Text area and margins disarranged when using \setdefaultlanguage{arabic}

### ISSUE THREAD

**Issue by HaMaMue** [reutenauer/polyglossia#33]
When compiling this test.tex

%xelatex --no-pdf test.tex
%xdvipdfmx test

\documentclass{book}
\usepackage{xcolor}

\usepackage{xltxtra}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\usepackage{polyglossia}
\setdefaultlanguage{arabic}

\usepackage{showframe}
\begin{document}
A\newpage B\newpage C
\end{document}

it becomes obvious that showframe does not recognize text area and margins correctly when
\setdefaultlanguage{arabic}
is used. This problem is not restricted to the showframe package but to packages using the information about the page layout in general, of course, for example the thumbs package.
![Screen shot of two sided pdf](https://f.cloud.github.com/assets/3619215/165222/0805c564-792a-11e2-9d03-6ab2e761adab.PNG)

**Comment by jspitz** [comment]
Not a polyglossia bug. Moved to https://github.com/bidi-tex/bidi/issues/6
