### ISSUE TITLE
Regression: Language loading via macro broken in v1.45?

### ISSUE THREAD

**Issue by dirtyhawk** [reutenauer/polyglossia#331]
Dear maintainers,

this morning, I updated `polyglossia` to v1.45 via the TeX live package manager. Since then, a document I'm working on won't compile. The issue seems to be that I define a macro holding the language, to be loaded with `\setdefaultlanguage{}`, like in the following minimal example:

```latex
\documentclass{article}
\def\mylang{english}
\usepackage{polyglossia}
\setdefaultlanguage{\mylang}
\begin{document}
 Here comes text.
\end{document}
```

Compiling this document with either `XeLaTeX` or `LuaLaTeX` leads to the following error messages:
```
! Package polyglossia Error: Could not retrieve key frenchspacing for language "english".
! Package polyglossia Error: Could not retrieve key direction for language "english".
! Package polyglossia Error: Could not retrieve key indentfirst for language "english".
! TeX capacity exceeded, sorry [input stack size=5000].
````

Naturally, when I replace `\setdefaultlanguage{\mylang}` with `\setdefaultlanguage{english}`, everything works as expected.

Is this intentional behaviour of `polyglossia`, and I'm just mislead that it should be possible to load languages saved inside a macro; or should this considered a regression/bug in v1.45?

Kind regards
Bela

**Comment by jspitz** [comment]
I'd say this was never officially supported (at least I don't remember this was stated anywhere), so it worked just by chance. Maybe we can expand the argument of `\setdefaultlanguage`, but I am not sure about the negative effects.

For the time being, you can expand it yourself, using
```tex
\begingroup\edef\x{\endgroup\noexpand\setdefaultlanguage{\mylang}}\x%
```
instead of
```tex
\setdefaultlanguage{\mylang}
```

**Comment by dirtyhawk** [comment]
Hi @jspitz ,
> I'd say this was never officially supported (at least I don't remember this was stated anywhere), so it worked just by chance. Maybe we can expand the argument of `\setdefaultlanguage`, but I am not sure about the negative effects.
> 
> For the time being, you can expand it yourself, using
> [...]

thanks for the workaround, it works like a charm, as to be expected.

Still, I would suggest to do the expansion on `polyglossia`'s side. I'm pretty sure not to be the only one writing a wrapper package/class that's supposed to set the language using `polyglossia`. Feel free, of course, to see this as a feature request instead of a regression/bug. Note that this also affects `\setotherlanguage`.

Thanks and kind regards
Bela

**Comment by reutenauer** [comment]
I’m tempted to call this a misfeature, and I think that if we choose to keep the argument to `\setdefaultlanguage` unexpanded, it should be printed as such in error messages, so that it would read

    ! Package polyglossia Error: Could not retrieve key frenchspacing for language "\mylang ".

As they are now, the messages are misleading.

**Comment by jspitz** [comment]
> I’m tempted to call this a misfeature

What exactly? Non-expanding or previous expanding?

**Comment by reutenauer** [comment]
Non-expanding.  But what bothers me more is that we seem to enter an infinite loop (as hinted by`[input stack size=5000]`)v

**Comment by jspitz** [comment]
The following seems to work:
```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 34b22f3..3b8935b 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -667,7 +667,7 @@
 }
 
 \cs_new_nopar:Nn{\polyglossia@lang@frenchspacing:n}{
-  \prop_get:NnNTF \polyglossia@langsetup {#1/frenchspacing} \l_tmpa_tl
+  \prop_get:NxNTF \polyglossia@langsetup {#1/frenchspacing} \l_tmpa_tl
       {
         \str_case_e:nnF{\l_tmpa_tl}{
           {true}{\frenchspacing}
@@ -682,7 +682,7 @@
 }
 
 \cs_new_nopar:Nn{\polyglossia@lang@indentfirst:n}{
-  \prop_get:NnNTF \polyglossia@langsetup {#1/indentfirst} \l_tmpa_tl
+  \prop_get:NxNTF \polyglossia@langsetup {#1/indentfirst} \l_tmpa_tl
       {
         \str_case_e:nnF{\l_tmpa_tl}{
           {true}{\french@indent}
@@ -698,7 +698,7 @@
 
 
 \cs_new:Nn{\polyglossia@lang@setpardirection:n}{
-  \prop_get:NnNTF \polyglossia@langsetup {#1/direction} \l_tmpa_tl
+  \prop_get:NxNTF \polyglossia@langsetup {#1/direction} \l_tmpa_tl
       {
         \polyglossia@setpardirection:n{\l_tmpa_tl}
       }
@@ -710,7 +710,7 @@
 
 
 \cs_new:Nn{\polyglossia@lang@settextdirection:nn}{
-  \prop_get:NnNTF \polyglossia@langsetup {#1/direction} \l_tmpa_tl
+  \prop_get:NxNTF \polyglossia@langsetup {#1/direction} \l_tmpa_tl
       {
         \polyglossia@settextdirection:n{\l_tmpa_tl}{#2}
       }
@@ -1032,7 +1032,7 @@
     \polyglossia_load_lang_definition:nn{#1}{#2}
     % define environment and command (except for internal latex language)
     \ifstrequal{#2}{latex}{}{%
-      \polyglossia@define@language@cmd:n{#2}
+      \exp_args:Ne\polyglossia@define@language@cmd:n{#2}
     }%
     \csgdef{#2@loaded}{}%
   }
@@ -1221,7 +1221,7 @@
     \global\edef\xpg@loaded{#2\ifx\xpg@loaded\@empty\else,\xpg@loaded\fi}%
     \polyglossia_load_lang_definition:nn{#1}{#2}
     % define environment and command
-    \polyglossia@define@language@cmd:n{#2}
+    \exp_args:Ne\polyglossia@define@language@cmd:n{#2}
     \csgdef{#2@loaded}{}%
     % If a variant is set, store it.
     \gdef\otherlanguagevariant{}
```

But since I am still quite a novice at l3, I'd like to get some review before I commit.

**Comment by reutenauer** [comment]
Thanks, I tried something similar but couldn’t make it work.  I’ll comment on your pull request.

**Comment by jspitz** [comment]
@dirtyhawk could you test polyglossia.sty from https://raw.githubusercontent.com/jspitz/polyglossia/master/tex/polyglossia.sty?

**Comment by dirtyhawk** [comment]
Sorry, I'm showing up late to the party, ain't I?

> @dirtyhawk could you test polyglossia.sty from https://raw.githubusercontent.com/jspitz/polyglossia/master/tex/polyglossia.sty?

I can confirm that the issue is fixed for `\setdefaultlanguage` and `\setotherlanguage`; however, it seems that the problem persists for the (probably far less used) `\setotherlanguages`:

```LaTeX
\documentclass{article}
\def\mylang{english}
\def\myotherlang{german,french}
\usepackage{./polyglossia}
\setdefaultlanguage{\mylang}
\setotherlanguages{\myotherlang}
\begin{document}
 Here comes text.
\end{document}
```
The code above produces:
```
! LaTeX3 Error: The key 'polyglossia/\myotherlang/hyphenmins' requires a
(LaTeX3)        value.
The key 'polyglossia/\myotherlang/hyphenmins' must have a value.
No value was present: the key will be ignored.
```

**Comment by jspitz** [comment]
`\setotherlanguages` should be fixed now as well in master. Please verify.

**Comment by dirtyhawk** [comment]
Hi,
> `\setotherlanguages` should be fixed now as well in master. Please verify.

confirmed. All three `\set*` commands now work with macros as arguments, as far is my test show:
```LaTeX
\documentclass{article}
\def\mylang{english}
\def\myotherlangs{german,french}
\def\myfourthlang{spanish}
\usepackage{polyglossia}
\setdefaultlanguage{\mylang}
\setotherlanguages{\myotherlangs}
\setotherlanguage{\myfourthlang}
\begin{document}
 Here comes text.
\end{document}
```
Thanks very much to all of you for the quick help!

Regards
Bela
