### ISSUE TITLE
Audit LuaTeX support

### ISSUE THREAD

**Issue by jspitz** [reutenauer/polyglossia#337]
For the following languages, we currently report that LuaTeX is not supported:
- [ ] Arabic
- [ ] Bengali
- [ ] Divehi
- [ ] Hebrew
- [ ] Kannada
- [ ] Lao
- [ ] Malayalam
- [ ] Marathi
- [ ] Persian
- [ ] Sanskrit
- [ ] Syriac
- [ ] Tamil
- [ ] Telugu
- [ ] Thai
- [ ] Urdu

We should audit these cases and check whether this statement is still true, and if so, elaborate what is actually missing.

**Comment by moewew** [comment]
Some of this may be tied to font rendering on the LuaTeX side, see for example https://tex.stackexchange.com/q/454031/35864, and might not be something `polyglossia` can fix. Fortunately, there is work underway to make HarfBuzz usable with LuaTeX in TeX live 2020, which should help a lot with currently unsupported scripts (https://github.com/latex3/luaotfload/pull/102)

**Comment by reutenauer** [comment]
On Wed, Oct 30, 2019 at 12:45:44AM -0700, moewew wrote:
> Some of this may be tied to font rendering on the LuaTeX side, see for example https://tex.stackexchange.com/q/454031/35864, and might not be something `polyglossia` can fix.

  Font and script rendering is the only issue.  Polyglossia can’t fix
it, but we need to report about it.

**Comment by reutenauer** [comment]
On Tue, Oct 29, 2019 at 11:47:38PM -0700, Jürgen Spitzmüller wrote:
> For the following languages, we currently report that LuaTeX is not supported:
> - [ ] Arabic
> - [ ] Bengali
> - [ ] Divehi
> - [ ] Hebrew
> - [ ] Kannada
> - [ ] Lao
> - [ ] Malayalam
> - [ ] Marathi
> - [ ] Persian
> - [ ] Sanskrit (see #336)
> - [ ] Syriac
> - [ ] Tamil
> - [ ] Telugu
> - [ ] Thai
> - [ ] Urdu
> We should audit these cases and check whether this statement is still true, and if so, elaborate what is actually missing. 

  Off the top of my head, I’d say that only South-East Asian and Indic
scripts with the exception of Devanagari are still unsupported, that
means: Bengali, Divehi, Kannada, Lao, Malayalam, Syriac, Telugu, and
Thai.  Arabic-script languages have always been well supported by
LuaTeX; I’m not sure why I wrote that they weren’t when I first ported
Polyglossia to LuaTeX -- possibly because I hadn’t tested.  Obviously
everything should be tested.

**Comment by jspitz** [comment]
I'd figure that some limitations of RTL scripts might also be caused by `luabidi` vs. `bidi` limitations.

**Comment by jspitz** [comment]
For the record, `luahbtex` is already availabe for testing in current TeXLive via `lualatex-dev`.

**Comment by jspitz** [comment]
It has been confirmed that Marathi is still wrong (TL 2019).

**Comment by zareami10** [comment]
Well as mentioned Persian/Arabic seems broken in LuaTex and also Polyglossia by default, unless you use arabluatex (characters are rendered separately in wrong order etc, as shown below, besides getting errors and such (not being able to set an environment for Persian/Arabic to begin with)). 
![Screenshot from 2019-12-21 21-57-54](https://user-images.githubusercontent.com/59122438/71312184-2aecfa00-243d-11ea-82af-12d5715bc9a2.png)

And since I'm not fully familiar with different packages I was wondering where the status stands considering the recent comments and whether I can help with testing.

**Comment by jspitz** [comment]
It shouldn't be that broken. Can you post a minimal example file?

**Comment by zareami10** [comment]
> It shouldn't be that broken. Can you post a minimal example file?

Sure, the following tex file works perfectly with XeLaTex but gives errors with LuaLaTex. (it does use polyglossia but even if you comment it out, XeLatex still renders the Persian text fine despite the general direction of the sentence being LTR instead of RTL (LuaLaTex doesn't even render single words correctly)).

In another unrelated note, although "farsi" works, "Persian" or "persian" parameters don't seem to work despite aliases apparently being there.
[test.zip](https://github.com/reutenauer/polyglossia/files/3992597/test.zip)

**Comment by jspitz** [comment]
This is the result of your file with lualatex for me: [main.pdf](https://github.com/reutenauer/polyglossia/files/3994083/main.pdf). I can't read persian, but it looks identical to XeTeX output. This is with `polyglossia` 1.46.

Persian also works as intended, but note that this has only been introduced in `polyglossia` 1.45. And up to `polyglossia` 1.46, the `persian` environment is only available if you load `persian` (rather than `farsi`) in `\selectmainlanguage` or `\selectotherlanguage` (as of `polyglossia` 1.47 both will be really mutually interchargeable)

**Comment by jspitz** [comment]
BTW overleaf has TeXLive 2018 with `polyglossia 2018/04/07 v1.43`, so this is utterly outdated.

**Comment by zareami10** [comment]
> This is the result of your file with lualatex for me: [main.pdf](https://github.com/reutenauer/polyglossia/files/3994083/main.pdf). I can't read persian, but it looks identical to XeTeX output. This is with `polyglossia` 1.46.
> 
> Persian also works as intended, but note that this has only been introduced in `polyglossia` 1.45. And up to `polyglossia` 1.46, the `persian` environment is only available if you load `persian` (rather than `farsi`) in `\selectmainlanguage` or `\selectotherlanguage` (as of `polyglossia` 1.47 both will be really mutually interchargeable)

The result seems to be correct, I just checked and my package version seems to be 1.44, so that's probably what causes the problem.
Sorry for not noticing the outdated package (I didn't really expect it to be outdated on Fedora).

**Comment by jspitz** [comment]
Now that TL 2020 with `lualatex` having `HarfBuzz` as default engine (is about to be) released, the time seems to have come to check all those languages again.

**Comment by jspitz** [comment]
According to @NiranjanTambe Marathi, Sanskrit and Bengali are still not working properly with LuaLaTeX and TL20, see https://github.com/reutenauer/polyglossia/issues/405#issuecomment-614129976

**Comment by NiranjanTambe** [comment]
@jspitz Adding my further comments here.

LuaLaTeX support is relatively better now. If I remember correctly last time all the diacritics were typeset incorrectly. Now it is showing all the diacritics correctly, but there is problem with `्` this character for Devanagari and `্` for Bengali. Both of them trigger conjunction of two consonants. So basically conjunct characters are not correctly shown. You can check it from the following.

[Marathi and Bengali.zip](https://github.com/reutenauer/polyglossia/files/4482463/Marathi.and.Bengali.zip)

**Comment by moewew** [comment]
@NiranjanTambe Does it look any better when you actually use `Renderer=Harfbuzz`?
```latex
\documentclass[12pt]{book}
\usepackage{polyglossia}
\setdefaultlanguage{marathi}
\setmainfont[Renderer=Harfbuzz, Script=Devanagari, Mapping=devanagarinumerals]{Shobhika_Regular.otf}
\newfontfamily{\gal}[Renderer=Harfbuzz, Script=Bengali, Mapping=bengalinumerals]{Galada-Regular.ttf}

\begin{document}
नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे नमस्कार माझे नाव निरंजन विकास तांबे 

\gal
নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে নমস্কার আমার নাম নিরঞ্জন বিকাস তাম্বে
\end{document}
```

**Comment by NiranjanTambe** [comment]
@moewew Yes! It does! It gives me the perfect output. Glad to know that LuaLaTeX can support Devanagari now :-)

**Comment by jspitz** [comment]
@moewew I was on the (apparently wrong) track that LuaLaTeX uses Harfbuzz by default with TL20.

**Comment by NiranjanTambe** [comment]
@jspitz  & @moewew I just spot another small issue. Please shed some light. When we use `Mapping=devanagarinumerals` with `XeLaTeX`, numbers are automatically changed to Devanagari ones (even without `polyglossia`). The same is not happening with `LuaLaTeX`. Numerals are still Arabic. Any solution?

**Comment by moewew** [comment]
@jspitz I am absolutely the wrong person to ask here, but as far as I understood TeX live 2020's `lualatex` binary has HarfBuzz support built-in, but if you want to actually use HarfBuzz (for your fonts) you need to activate it explicitly with `Renderer=Harfbuzz` in `fontspec` font definitions (or some other more low-level `luaotfload` syntax if you load fonts that way). I'm guessing backwards compatibility considerations stopped making `Harfbuzz` the default as there are (probably subtle) differences between the Harfbuzz and the old standard font setup.

**Comment by jspitz** [comment]
> @jspitz & @moewew I just spotted another small issue. Please shed some light. When we use `Mapping=devanagarinumerals` with `XeLaTeX`, numbers are automatically changed to Devanagari ones (even without `polyglossia`). The same is not happening with `LuaLaTeX`. Numerals are still Arabic. Any solution?

Can you please open a separate ticket for this?

**Comment by NiranjanTambe** [comment]
> Can you please open a separate ticket for this?

Sure, but where should I open this issue? On `polyglossia`, `Harfbuzz` or `LuaLaTeX`? Please guide me.

**Comment by jspitz** [comment]
> > Can you please open a separate ticket for this?
> 
> Sure, but where should I open this issue? On `polyglossia`, `Harfbuzz` or `LuaLaTeX`? Please guide me.

Here on this tracker.

**Comment by NiranjanTambe** [comment]
Ok.

**Comment by jspitz** [comment]
Thanks @moewew. @reutenauer should we consider to load HarfBuzz in the background with the scripts that need it, or should we simply document its use?

**Comment by reutenauer** [comment]
We should set it ourselves, in the different language definition files for the scripts that need it.  Actually, I would even be in favour of using the LuaTeX HarfBuzz renderer by default in Polyglossia.  It is, after all, the same as XeTeX’s.

**Comment by wspr** [comment]
Just to confirm that there are currently no plans in fontspec to automatically make HarfBuzz the default. That might change in time depending on how LuaTeX's development, luaotfload's development, and the longer term integration with Harfbuzz go.

**Comment by jspitz** [comment]
@wspr am I right that
```tex
\addfontfeatures{Renderer=Harfbuzz}
```
does not work? At least I seem to get a different output than with
```tex
\setmainfont[Renderer=Harfbuzz]{...}
```

I am looking for a way to set the renderer automatically via `polyglossia` on top users' font settings.

**Comment by jspitz** [comment]
Playing a bit more, it seems that
```tex
\defaultfontfeatures{Renderer=Harfbuzz}
```
seems to be the way to go.

@wspr is this right?

**Comment by jspitz** [comment]
> We should set it ourselves, in the different language definition files for the scripts that need it. Actually, I would even be in favour of using the LuaTeX HarfBuzz renderer by default in Polyglossia. It is, after all, the same as XeTeX’s.

I proposed something along these lines in #426

**Comment by wspr** [comment]
@jspitz — yes, the Renderer should only be specified before the font is first loaded. Using `\defaultfontfeatures` seems possibly a bit much given it will affect ALL fontspec fonts loaded from then on. Is there a way you can just insert it into the options of the fonts you need to load through polyglossia?

**Comment by jspitz** [comment]
> @jspitz — yes, the Renderer should only be specified before the font is first loaded. Using `\defaultfontfeatures` seems possibly a bit much given it will affect ALL fontspec fonts loaded from then on. 

Yes, but that's exactly the plan.

> Is there a way you can just insert it into the options of the fonts you need to load through polyglossia?

Polyglossia does not have its own font loading interface. Users are supposed to load fonts via `\setmainfont`, `\newfontfamily` and friends (the only thing it provides is setting of some options, such as `Script`, for the respective language, and an automatic handling of `\newfonfamily`'s if the name equals a language, or script). What we want to achieve is that all these (by default) use the `Harfbuzz` renderer, without people having to specify this.

In my proposal, polyglossia introduces an option `luatexrenderer`, defaulting to `Harfbuzz`, where this can be globally adjusted (including `none` to opt-out completely).

I understand that people can also locally override this for a given font by using the `Renderer` option of the font selection commands).

**Comment by jspitz** [comment]
Done.
