### ISSUE TITLE
Devanagari: Waiting too long for an error message

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#338]
If I try to set a Devanagari font which does not exist, XeTeX seems to enter an infinite loop at first glance. The error message only appears after 4 minutes (on my admittedly slow machine). I think the error message should appear earlier.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{sanskrit}
\newfontfamily\devanagarifont{nonexistingfont}

\begin{document}
Test
\end{document}
```

**Comment by jspitz** [comment]
`\newfontfamily` is a `fontspec` command. There is nothing we can do in polyglossia. Maybe file a report at `fontspec`.
