### ISSUE TITLE
Unescaped left brace in makepolyglossiadtx.pl

### ISSUE THREAD

**Issue by tamas-ferenci** [reutenauer/polyglossia#342]
I am no expert in this topic, so it might be easily my mistake, but when I naively try to run `./makectanzip`, it'll report an error saying that

```
Unescaped left brace in regex is deprecated
```

and then it locates the position. (It appears in lines 285, 345, 378, 383, 452, 456.)

It seems to be similar to [this problem](https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated).

**Comment by jspitz** [comment]
Thanks, fixed.

**Comment by tamas-ferenci** [comment]
You're welcome @jspitz ! Just as a sidenote: strictly speaking only *left* braces need to be escaped. (Although I don't know if it makes any problem that you escaped right ones too, I don't know perl.)

**Comment by jspitz** [comment]
I am not very familiar with perl either, but it seems to work with escaped right braces.
