### ISSUE TITLE
Language magyar not found warning with Hungarian language

### ISSUE THREAD

**Issue by tamas-ferenci** [reutenauer/polyglossia#343]
Consider the following MWE:

```
\documentclass{book}
\usepackage{polyglossia}
\setmainlanguage[]{hungarian}
\begin{document}
a
\end{document}
```

When compiled, it'll report a warning saying

```
Module polyglossia Warning: Language magyar not found in language.dat.lua on input line 9
```

despite the fact that I've never ever referred to Hungarian as `magyar` in the document (which is the correct way according to the manual).

**Comment by jspitz** [comment]
This is not a bug. We search for the _hyphenation pattern_ `magyar` and `hungarian` from within `gloss-hungarian`. Both names are used. Nowadays, `hungarian` seems to be more common, so we can switch the order, and you won't see the warning anymore (maybe others will instead).

**Comment by tamas-ferenci** [comment]
Thanks!
