### ISSUE TITLE
Chapter Headings with Hungarian

### ISSUE THREAD

**Issue by tamas-ferenci** [reutenauer/polyglossia#344]
I was surprised to see that when the following MWE is compiled...

```
\documentclass{book}
\usepackage{polyglossia}
\setmainlanguage[]{hungarian}
\begin{document}
a
\chapter{Fejezet}
b
\end{document}
```

...even the chapter numbering is wrong. (It says `fejezet 1` which literally means `chapter 1`, however, in Hungarian it should be `1. fejezet`.)

This is so fundamental that I was wondering if I made a mistake somewhere, or simply the support of `polyglossia` is so immature (yet?) for Hungarian. (Especially as compared to `babel` which correctly handles even vastly more minuscule question of Hungarian grammar and typesetting.)

**Comment by jspitz** [comment]
Any help to improve the glosses is most welcome.

**Comment by jspitz** [comment]
BTW the `babel` approach to modify chapter heading does not seem to be very stable. It works with some book classes (standard, `KOMA`, `AMS`) but not with others (`memoir`) and even breaks some (`tufte`). So I suppose it will not be trivial a task to implement this properly.

**Comment by jspitz** [comment]
> BTW the `babel` approach to modify chapter heading does not seem to be very stable.

And it also seems to badly interfere with other languages:
https://tex.stackexchange.com/questions/247251/hungarian-babel-makes-english-headers-strange

**Comment by tamas-ferenci** [comment]
Actually I was only looking for a confirmation whether this is indeed not working or its just my mistake (I thought that it is so fundamental that even the latter is entirely possible), so thanks for the detailed explanation!

**Comment by pts** [comment]
Indeed `fejezet 1` is incorrect (and looks very unprofessional if printed in a Hungarian book), the correct version would be `1. fejezet`.

**Comment by jspitz** [comment]
I have a half-finished patch, but I am currently travelling.

**Comment by jspitz** [comment]
Implemented now (part/chapter headings as well as running headers). Tested with standard `book` class, `memoir`, `scrbook` and `tufte-book `as well as packages `titlesec`, `fancyhdr`, and `caption`.

@tamas-ferenci, @pts, testing would be highly appreciated.
