### ISSUE TITLE
missing number, treated as zero

### ISSUE THREAD

**Issue by joostkremers** [reutenauer/polyglossia#346]
After updating my TeXLive 2019 installation the other day, I suddenly find `polyglossia` gives me an error when I set the main language to `german`. Minimal example:

```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}

Test.

\end{document}

```

The error I get:

```
ERROR: Missing number, treated as zero.

--- TeX said ---
<to be read again> 
                   \l@ngerman 
l.6 \begin{document}
```

If I run LaTeX again, jumping to the error takes me to the `.aux` file:

```
\relax 
\catcode `"\active 
\selectlanguage *{german}
\@writefile{toc}{\selectlanguage *{german}}
\@writefile{lof}{\selectlanguage *{german}}
\@writefile{lot}{\selectlanguage *{german}}
```

with the cursor right after `{german}`. (Jumping to the error after the first TeX run, when no `.aux` file exists yet, takes me to the `\begin{document}`line).

I'm running LaTeX (specifically, `xelatex`) from Emacs (AUCTeX), but running it from the command line gives me the same error.

`polyglossia` version is 2019/10/27 v1.45 (as per the file `polyglossia.sty`).

**Comment by jspitz** [comment]
I cannot reproduce the problem.

**Comment by joostkremers** [comment]
> I cannot reproduce the problem.

I don't want to exclude the possibility that the problem is on my end, of course. If I need to provide more details about my system, I'd be happy to do so.

I just noticed a warning put out by `polyglossia` that might be relevant:

    Package polyglossia Warning: No hyphenation patterns were loaded for `german'
    (polyglossia)                I will use \language=\l@nohyphenation instead on input line 8.

That doesn't look right to me...

Below is the full output from running xelatex on the minimal working example above (called `samp.tex`). I can also post the log file if necessary.

Note that the problem does not occur if I set the main language to `english`. (I haven't tested any other languages.)

```
joost@Swift:~/tmp/samp$ xelatex samp.tex 
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./samp.tex
LaTeX2e <2019-10-01> patch level 1
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/polyglossia.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/makecmds/makecmds.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2019/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2019/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/local/texlive/2019/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/local/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3-code.tex
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/l3deprecation.def))
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def
))) (/usr/local/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/tuenc.def))
(/usr/local/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/local/texlive/2019/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/local/texlive/2019/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/local/texlive/2019/texmf-dist/tex/generic/iftex/ifxetex.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
 (/usr/local/texlive/2019/texmf-dist/tex/latex/filehook/filehook.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/gloss-latex.ldf))
(/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/gloss-german.ldf

Package polyglossia Warning: No hyphenation patterns were loaded for `german'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 8.

(/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/babelsh.def))
No file samp.aux.
! Missing number, treated as zero.
<to be read again> 
                   \l@ngerman 
l.6 \begin{document}
                    
? x
No pages of output.
Transcript written on samp.log.

```

**Comment by wehro** [comment]
TeX seems not to be able to find the German hyphenation patterns. Please report all lines containing `ngerman` in files `language.dat` (maybe also in your personal tree) and `language-local.dat` (if existing).

**Comment by jspitz** [comment]
As @wehro said, it looks like a problem with the `ngerman` hyphenation patterns on your end. On the other hand, though, `polyglossia` should not fail in this case but simply warn about patterns not found and use `nohyphenation`.

I can reproduce the problem by using a nonsense pattern name and I have found the bug in the code.

As to your local problem: this probably existed before as well, but you only got a waning which you probably missed.

**Comment by jspitz** [comment]
The polyglossia problem described above is fixed. If you need help with your local problem, we can try to solve this here.

**Comment by joostkremers** [comment]
> As to your local problem: this probably existed before as well, but you only got a waning which you probably missed.

Yes, probably. I just checked my local installation and found that for some reason, I didn't have any German hyphenation patterns installed. Installing them fixed the problem for me, even before updating `polyglossia`.

> I can reproduce the problem by using a nonsense pattern name and I have found the bug in the code.

In that case, I don't feel entirely ashamed for bothering you guys with a problem that's essentially of my own making... :relieved:

**Comment by jspitz** [comment]
Not at all, Joost. You reported a real bug. Thanks for that.
