### ISSUE TITLE
Missing % in new code added in version 1.45

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#347]
Code from `polyglossia.sty` version 1.45
```latex
   1566 \renewenvironment{otherlanguage}[2][]
   1567 {
   1568   \xpg@set@group@aux%
   1569   \selectlanguage[#1]{#2}
   1570 }
   1571 {\xpg@unset@group@aux}
```
It should be
```latex
   1566 \renewenvironment{otherlanguage}[2][]
   1567 {%
   1568   \xpg@set@group@aux
   1569   \selectlanguage[#1]{#2}%
   1570 }
   1571 {\xpg@unset@group@aux}
```
It's true that `otherlanguage` should be used between paragraphs, so the spaces would not be an issue, but…

The `%` is obviously not needed in line 1568 (but it does no harm).

**Comment by wehro** [comment]
All these comments are superfluous as we use Expl3 syntax.

**Comment by jspitz** [comment]
Thanks for spotting this, Enrico. Fixed.
