### ISSUE TITLE
expl3 use with \xpg@pop@language

### ISSUE THREAD

**Issue by wspr** [reutenauer/polyglossia#348]
The fontspec test suite is run using expl3's `[check-declarations]` package option to ensure the internal coding is consistent. This now fails in a polyglossia test with the following error:

```
! LaTeX3 Error: The variable \xpg@pop@language has not been declared on line
(LaTeX3)        14.

For immediate help type H <return>.
 ...                                              
                                                  
l.14 \begin{document}
                     

This is a coding error.

Checking is active, and you have tried do so something like:
  \tl_set:Nn \xpg@pop@language { ... }
without first having:
  \tl_new:N \xpg@pop@language

LaTeX will create the variable and continue.
```

This appears to be related to changes made from v1.44 to v1.45. From a quick look at the code, possibly best to turn this back into 2e syntax unless you want to go a bit further in expl-ising here.

**Comment by jspitz** [comment]
@dohyunkim this was introduced with 04a6f8e8. I suppose we should define` \xpg@pop@language` via `\tl_new` and afterwards clear it with `\tl_clear_new` rather than the current `\let\xpg@pop@language\relax`. What do you think?

**Comment by jspitz** [comment]
> @dohyunkim this was introduced with [04a6f8e](https://github.com/reutenauer/polyglossia/commit/04a6f8e81cd4d89ee49cebb8f06e5722bab2072c). 

e2e5e02e9f4bd952 for that matter.

**Comment by dohyunkim** [comment]
@jspitz Yes, that is a solution. As I'm caught by another job for now, could you please go ahead and commit a patch?

BTW as an alternative solution, we can just define `\xpg@pop@language` with `\cs_set_nopar:Npx`.
```
\cs_set_nopar:Npx \xpg@pop@language { \exp_not:N \xpg@pop@language@i {#2} {#3} }
```

Otherwise, as Will suggests, we can go back to the 2e (actually plain tex) syntax.
```latex
\edef\xpg@pop@language{\noexpand\xpg@pop@language@i{#2}{#3}}
```

**Comment by bastien-roucaries** [comment]
I can get a glimpse. Coule de wait

**Comment by jspitz** [comment]
> Coule de wait

Whatever that means ;-) I'll let you handle this.

**Comment by jspitz** [comment]
@wspr could you provide a MWE that reproduces this issue?

**Comment by wspr** [comment]
@jspitz Apologies I didn't include that in the first place!

```
\documentclass{article}
\usepackage[check-declarations]{expl3}
\usepackage{polyglossia}
\begin{document}
abc
\end{document}

```

**Comment by jspitz** [comment]
Thanks. I went now with @dohyunkim's suggestion to unbreak it.

I'll leave this open for you @bastien-roucaries, in case you want to fix it differently.

**Comment by jspitz** [comment]
Polyglossia 1.46 is now released with the fix. Closing this. Refactoring is always possible.
