### ISSUE TITLE
Failure to load when filehook not installed

### ISSUE THREAD

**Issue by cdlm** [reutenauer/polyglossia#350]
While trying to install a minimal set of packages on top of a scheme-basic TeXlive, I noticed loading polyglossia fails when `filehook.sty` is not installed.

Since there is indeed a `\RequirePackage{filehook}` in `polyglossia.sty`, so it looks like this dependency is simply missing from the CTAN package metadata —or whatever `tlmgr` uses to install dependencies.

**Comment by reutenauer** [comment]
Thanks for the report, that seems to be a simple oversight, indeed.  We’ll let the CTAN maintainers know.

**Comment by cdlm** [comment]
While we're at it, luatexbase is also needed… let me iterate on our build, I'll let you know if there are more.

BTW, I expected there to be some kind of package metadata in this repo, but I really don't know how CTAN works and your comment suggests dependencies are maintained separately? Can I do a pull request somewhere to help?

**Comment by reutenauer** [comment]
No, the infrastructure that defines dependencies is maintained by TeX Live (and MiKTeX has something equivalent, but I don’t know the details).  I don’t know why I wrote CTAN above, they have no part in this :-)  Mostly it’s done manually, I just emailed Karl Berry, the main TeX Live maintainer about `filehook`; I’ll wait until you’re done checking to follow up on the other dependencies.

For [another package](/hyphenation/tex-hyphen) I co-maintain, we upload the text-based metadata file that TeX Live uses to CTAN, but that is not common practice.

**Comment by cdlm** [comment]
OK… so I only had to install `ulem` after `filehook` and `luatexbase`, but that's specific to our document.

**Comment by reutenauer** [comment]
Thanks, I’ll forward it.

**Comment by bastien-roucaries** [comment]
Filehook is needed so please add thé depends

Le ven. 8 nov. 2019 à 14:26, Damien Pollet <notifications@github.com> a
écrit :

**Comment by jspitz** [comment]
I understand this is resolved.
