### ISSUE TITLE
Punctuation and brackets

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#352]
For punctuation in brackets like `(?)`, XeTeX does not insert any additional space for French and ecclesiastic Latin, which I consider correct. But LuaTeX inserts spaces here, as `polyglossia-punct.lua` has no test for brackets so far.
Furthermore, XeTeX takes care only for round brackets, square brackets, and braces. It does not take into account angle brackets (U+27E8 and U+27E9). However, things like `⟨?⟩` might be needed for some special purposes.
Furthermore, XeTeX does not insert a space if a closing bracket is followed by closing guillemet. This is not correct as a quotation might end in a bracket. For ecclesiastical Latin, XeTeX does not even insert a space before `!`, `?`, `:`, and `;` if they are preceded by a closing bracket.

I tested with the following document.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainfont{Libertinus Serif}
\setmainlanguage{french}
\setotherlanguage[variant=ecclesiastic]{latin}
\setotherlanguage{german}

\begin{document}
(!) (?) (;) (:) («) (»)

\selectlanguage{latin}
(!) (?) (;) (:) («) (»)

\selectlanguage{german}
(!) (?) (;) (:) («) (»)

\selectlanguage{french}
⟨!⟩ ⟨?⟩ ⟨;⟩ ⟨:⟩ ⟨«⟩ ⟨»⟩

\selectlanguage{latin}
⟨!⟩ ⟨?⟩ ⟨;⟩ ⟨:⟩ ⟨«⟩ ⟨»⟩

\selectlanguage{german}
⟨!⟩ ⟨?⟩ ⟨;⟩ ⟨:⟩ ⟨«⟩ ⟨»⟩

\selectlanguage{french}
(abc)! (abc)? (abc); (abc): (abc)«abc (abc)»

\selectlanguage{latin}
(abc)! (abc)? (abc); (abc): (abc)«abc (abc)»

\selectlanguage{german}
(abc)! (abc)? (abc); (abc): (abc)«abc (abc)»
\end{document}
```

Summary:
1. LuaTeX should not insert spaces around bracketed punctuation.
2. Angle brackets should be treated the same way as other types of brackets.
3. XeTeX should insert a space before a closing guillemet, even if it is preceded by a closing bracket.
4. XeTeX should insert a space before high punctuation for ecclesiastical Latin, even if it is preceded by a closing bracket.

Currently, I don't have time to work on this. Perhaps someone else wants to.

**Comment by jspitz** [comment]
>     2. Angle brackets should be treated the same way as other types of brackets.
> 
>     3. XeTeX should insert a space before a closing guillemet, even if it is preceded by a closing bracket.
> 
>     4. XeTeX should insert a space before high punctuation for ecclesiastical Latin, even if it is preceded by a closing bracket.

These should be fixed. Please check.

**Comment by jspitz** [comment]
LuaTeX should be fixed now as well. In the long run, the hardcoding of brackets should probably be replaced by the possibility to define individual exception pairs.

Also, since these are my first lines of lua code, some double-checking would be welcome.

@wehro I'll let you close this if all issues are resolved.

**Comment by wehro** [comment]
All these bracket problems are fixed now. Thank you, Jürgen.
