### ISSUE TITLE
Release v1.46 breaks fonts in header

### ISSUE THREAD

**Issue by jakobmoss** [reutenauer/polyglossia#355]
After the release of `v1.46`, the font family selection for the information "marks" in headers (e.g. `\leftmark`) seems to be broken. I have attached two MWE's using two different classes. 

Compiling with `luatex `1.10.0` and `polyglossia v1.45` produces the expected output; however, after updating to `v1.46` the font is no longer correct. The font is switched to standard roman instead of the desired sans. Other font commands (e.g. colors and boldface) works fine.

Removing `polyglossia` or switching to `babel` resolves the issue as well.

MWE with the `book` class:
```latex
\documentclass[12pt,twoside,a4paper]{book}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\makeatletter
\def\@evenhead{\thepage\hfil\sffamily\leftmark}%
\def\@oddhead{{\sffamily\rightmark}\hfil\thepage}%
\makeatother

\usepackage{lipsum}
\begin{document}
\chapter{The Title of the Chapter}
\lipsum
\end{document}
```

MWE with the `memoir` class:
```latex
\documentclass[12pt,twoside,a4paper]{memoir}

\usepackage{polyglossia}
\setdefaultlanguage{english}

\usepackage{xcolor}
\makepagestyle{jtest}
\makeevenhead{jtest}{\sffamily\color{red}\leftmark}{}{}
\pagestyle{jtest}

\usepackage{lipsum}
\begin{document}
\chapter{The Title of the Chapter}
\lipsum
\end{document}
```

Compilation of the two MWE's yield (left is `v1.45` [correct] and right is `v1.46` [incorrect]):

![Screenshot 2019-11-18 at 08 27 03](https://user-images.githubusercontent.com/9656902/69054940-ef5dab00-0a0c-11ea-8c3e-2fa4198a3c96.png)

![Screenshot 2019-11-18 at 08 38 45](https://user-images.githubusercontent.com/9656902/69054947-f2589b80-0a0c-11ea-8a11-d34ed87cedc5.png)

**Comment by reutenauer** [comment]
Thank you for the bug report.  It is a side-effect of a change that fixes a [long-standing issue](/reutenauer/polyglossia/issues/24), but evidently we missed something.  We’ll go back to this, but as a workaround you can use `\familytype{sf}\selectfont` instead of `\sffamily` in the definition of the marks.  Sorry for the inconvenience!

**Comment by jakobmoss** [comment]
Thank you for the swift reply!

**Comment by jspitz** [comment]
The issue here is that the involved commands are (and need to be) defined as robust commands,
so `\let` does not work. Also we need to re-patch after `\resetfontlatin`.
