### ISSUE TITLE
Option-less German environment fails to set \babelname

### ISSUE THREAD

**Issue by moewew** [reutenauer/polyglossia#357]
Consider
```latex
\listfiles
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage[spelling=new]{german}
\setotherlanguage{dutch}

\begin{document}
foo \today\ \textbf{\babelname}

\begin{german} foo \today\ \textbf{\babelname} \end{german}

\begin{german}[spelling=new] foo \today\ \textbf{\babelname} \end{german}

\begin{german}[variant=austrian] foo \today\ \textbf{\babelname} \end{german}

\begin{german} foo \today\ \textbf{\babelname} \end{german}
\end{document}
```

which produces

>foo 21 novembre 2019 french
>foo 21. November 2019 dutch
>foo 21. November 2019 ngerman
>foo 21. November 2019 naustrian
>foo 21. November 2019 dutch

So `\begin{german}...\end{german}` does not seem to set `\babelname` as expected. If we exchange `dutch` for any other language the result is similar.

**Comment by jspitz** [comment]
Thanks, the problem here was the use of pointers rather than copies.

**Comment by moewew** [comment]
Thank you very much. The example and some other tests look good now.
