### ISSUE TITLE
Guillemet and punctuation spacing

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#358]
There are still some inconsistencies between XeTeX and LuaTeX concerning guillemet and punctuation spacing for French, Latin, and Sanskrit.
If
1. a question mark or exclamation mark is followed by another one,
2. a guillemet is followed by another one (if a quotation begins with or ends in an inner quotation),
3. a question mark or exclamation mark is followed by a colon or semicolon (which might occur in rare cases)

LuaTeX inserts a space, XeTeX does not.

Consider the following document:
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setmainfont{Libertinus Serif}

\begin{document}
abc?? def!! ghi!?!
«abc ‹def›»
«‹ghi› jkl»
abc?; def!: ghi
\end{document}
```
The XeTeX output is:
![spacing_XeTeX](https://user-images.githubusercontent.com/33468411/69500520-3f9ca780-0efc-11ea-8e70-e7169a00222e.png)
The LuaTeX output:
![spacing_LuaTeX](https://user-images.githubusercontent.com/33468411/69500528-4b886980-0efc-11ea-9112-4a714c50861b.png)

I think XeTeX is correct in the above mentioned case 1, whereas LuaTeX is correct in the cases 2 and 3.
I will try to implement the desirable behaviour if no one objects my assumptions.

**Comment by jspitz** [comment]
Is your own evaluation based on intuition only or did you check back with French typographic literature?

**Comment by wehro** [comment]
It's based on intuition. I'm not an expert on French typography and I have no I idea where to find rules for these special cases. The _Lexique des règles typographiques en usage à l'Imprimerie nationale_, cited several times in the babel-french manual, does not treat these cases.

**Comment by jspitz** [comment]
So shouldn't we try and ask somebody who knows?

**Comment by jspitz** [comment]
@bastien-roucaries, @maieul, do you have informed opinions here?

**Comment by maieul** [comment]
not me

**Comment by reutenauer** [comment]
I believe @wehro is right: spaces are generally set as they normally would in all cases, except in case 1; but let me check references over the weekend.

**Comment by jspitz** [comment]
I had a look at some references, but alas none handles the cases in question (intuitively, I'd also agree with @wehro). One information I could find several times, and that we probably need to check, is that Canadien French differs from French French as far as punctuation spacing is concerned. So there might be reason for variant differentiation.

**Comment by jspitz** [comment]
FYI this is how babel does it. 
With PDFLaTeX:
![image](https://user-images.githubusercontent.com/4538783/69608971-c9e22a00-1028-11ea-8f4c-24a297204930.png)
With XeTeX/LuaTeX:
![image](https://user-images.githubusercontent.com/4538783/69609064-fdbd4f80-1028-11ea-923b-134cb10fc93c.png)
Not consistent either (except for the inner quotation mark)

**Comment by reutenauer** [comment]
Swiss French has also some different conventions, for example with guillemets, that are not separated by spaces from the text that they surround, «like this».  That’s also used for German in Switzerland, i.e. the guillemets, when they’re used, are in this opposite direction as in Germany (and possibly Austria too?), where they’re set »like this«.

**Comment by ivankokan** [comment]
Consult Guide du typographe (now in 7th edition) for Swiss. https://fr.wikipedia.org/wiki/Guide_du_typographe

**Comment by jspitz** [comment]
According to https://fr.wikipedia.org/wiki/Comparatif_des_diff%C3%A9rents_codes_typographiques_francophones guillemets and high punctuation have preceding non-breakable thin space in Swiss French (as opposed to Swiss German, where no space is used). Canadian (Québecois) French use a non-breakable thin space (or no space) befor high punctuation.

**Comment by reutenauer** [comment]
Yes, but they mention that the thin space may be narrower in Switzerland and even disappear entirely.  I’ve had requests to support that, but they never made it to this tracker.

**Comment by ivankokan** [comment]
> Consult _Guide du typographe_ (now in 7th edition) for Swiss. https://fr.wikipedia.org/wiki/Guide_du_typographe
> 
> Few years ago I edited French Wikipedia page on punctuation in French variants, having few pages from the mentioned Book scanned by my friend. I will share them later.

This is the page I edited in March 2018: https://fr.wikipedia.org/wiki/Ponctuation#En_fran%C3%A7ais.

And here are the scanned pages:
[guide-du-typographe-106-108.zip](https://github.com/reutenauer/polyglossia/files/3890728/guide-du-typographe-106-108.zip)

I communicated with Daniel Flipo (`babel-french`) on Swiss specifics in March 2018. The decision was not to implement `swiss` variant, as the only recognized difference was the space before the colon, and for the Swiss way that can be easily achieved by `\frenchsetup{ThinColonSpace}`.

**Comment by jspitz** [comment]
> Yes, but they mention that the thin space may be narrower in Switzerland and even disappear entirely. I’ve had requests to support that, but they never made it to this tracker.

For this, we have `autospaceguillemets` and `autospacing`. I understand the thin space is omitted since the usage of thin spaces is not convenient in office programs (same for Canadian)

> The decision was not to implement swiss variant, as the only recognized difference was the space before the colon, and for the Swiss way that can be easily achieved by \frenchsetup{ThinColonSpace}.

Now that's Franco-centrism at its best ;-)

**Comment by jspitz** [comment]
> And here are the scanned pages:
> [guide-du-typographe-106-108.zip](https://github.com/reutenauer/polyglossia/files/3890728/guide-du-typographe-106-108.zip)

Thanks! They also recomment non-breakable thin space (_Espace fine insécable_), which corresponds to LaTeX `\,` (see https://fr.wikipedia.org/wiki/Espace_fine_ins%C3%A9cable)

**Comment by jspitz** [comment]
As a start, I have added `variant=swiss` at a0860d223d16c with currently `thincolonspace=true` preset. We can adjust this as we see fit.

**Comment by jspitz** [comment]
> I believe @wehro is right: spaces are generally set as they normally would in all cases, except in case 1; but let me check references over the weekend.

Did your research reveal something?

**Comment by reutenauer** [comment]
> Did your research reveal something?

  Unfortunately not, we’ll have to go with our gut feeling here :-)

**Comment by jspitz** [comment]
OK. Then go ahead, @wehro.
