### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#363]
The notion of a “default value” of an option can have two different meanings which should be distinguished carefully.

1. The “default value” can refer to a value that applies if the user does not use the option at all. For example `\setmainlanguage{english}` means the same as `\setmainlanguage[variant=american]{english}` as `american` is the default value of the `variant` option for English, and `\setmainlanguage{french}` means the same as `\setmainlanguage[thincolonspace=false]{french}` as `false` is the default value of the `thincolonspace` option.
2. Furthermore, the “default value” can refer to a value that applies if the user uses the option without any value. For example `\setmainlanguage[thincolonspace]{french}` means the same as `\setmainlanguage[thincolonspace=true]` as `true` is the default value of this Boolean option, and `\setmainlanguage[spanishoperators]{spanish}` means the same as `\setmainlanguage[spanishoperators=all]{spanish}` as `all` is the default value in this second meaning.

The second optional argument of `\define@key` and friends refers to the second meaning stated above. Now there are several cases of key definitions in the gloss files where I consider a default value of this kind as useless. It is possible for German to say `\setmainlanguage[spelling]{german}` or `\setmainlanguage[variant]{german}` as the `spelling` and the `variant` option are defined with default values, but this use is not intuitive and should not be allowed. In my opinion, default values of the second kind make only sense for Boolean options and some other (semi-Boolean) ones as `spanishoperators`.
Furthermore, the definitions in the gloss files are not consistent so far. As opposed to German, it is not possible to say `\setmainlanguage[variant]{english}` for English.

Another problem refers to the manual. At the beginning of section 6, it states “The default value of each option is given in italic.” It is not clear here, to which of the two meanings above this refers. The use of italic type in the following subsections lets me assume that the first meaning is meant here, but sometimes there are confusing statements like

> **frenchfootnote** = true or *false* (default value = true)

The manual should be cleared up in this respect. A possible solution is shown by the manual of the cnltx package. Default values of the first kind are stated explicitly at the end of the line containing the option description, default values of the second type are underlined if existing (look e.g. on page 21 of `cnltx_en.pdf`). By the way, this package also provides an interface to document options the same way.

**Comment by jspitz** [comment]
I agree that the manual should be revised with respect to this. And I think both defaults should be spelled out. I think actually that the `frenchfootnote` case is how it should be. We should only make it clearer that

> The preset value of each option is given in italic. The default value (if the option key is used without explicit value) is given in parantheses.

I don't agree that having a default for `variant` is a bad thing. It's just a shorthand for `variant=default`. It should not be documented and encouraged, though.

If you feel like revising the manual, go for it.

**Comment by jspitz** [comment]
> Furthermore, the definitions in the gloss files are not consistent so far. As opposed to German, it is not possible to say `\setmainlanguage[variant]{english}` for English.

English was the only exception. This is fixed at 06d3168a76e6.

**Comment by wehro** [comment]
The default option (type 2) of a Boolean option should always be true. But we have:
```
gloss-ukrainian.ldf:\define@boolkey{ukrainian}[ukrainian@]{babelshorthands}[false]{}
gloss-slovenian.ldf:\define@boolkey{slovenian}[slovenian@]{localalph}[false]{%
gloss-russian.ldf:\define@boolkey{russian}[russian@]{babelshorthands}[false]{}
gloss-german.ldf:\define@boolkey{german}[german@]{latesthyphen}[false]{}
gloss-mongolian.ldf:\define@boolkey{mongolian}[mongolian@]{babelshorthands}[false]{}
gloss-belarusian.ldf:\define@boolkey{belarusian}[belarusian@]{babelshorthands}[false]{}
hebrewcal.sty:\define@boolkey{hebrew}[@hebrew@]{fullyear}[false]{}
```

**Comment by jspitz** [comment]
> The default option (type 2) of a Boolean option should always be true. But we have:
> 
> ```
> gloss-ukrainian.ldf:\define@boolkey{ukrainian}[ukrainian@]{babelshorthands}[false]{}
> gloss-slovenian.ldf:\define@boolkey{slovenian}[slovenian@]{localalph}[false]{%
> gloss-russian.ldf:\define@boolkey{russian}[russian@]{babelshorthands}[false]{}
> gloss-german.ldf:\define@boolkey{german}[german@]{latesthyphen}[false]{}
> gloss-mongolian.ldf:\define@boolkey{mongolian}[mongolian@]{babelshorthands}[false]{}
> gloss-belarusian.ldf:\define@boolkey{belarusian}[belarusian@]{babelshorthands}[false]{}
> hebrewcal.sty:\define@boolkey{hebrew}[@hebrew@]{fullyear}[false]{}
> ```

Yes, that's true. But changing this will cause backwards compatibility issues.

**Comment by wehro** [comment]
> Yes, that's true. But changing this will cause backwards compatibility issues.

Every bug fix hurts backwards compatibility. Changing this will possibly make some users unhappy having used an undocumented “feature” of polyglossia, but will make happy all future users trying to use these options intuitively.

**Comment by wehro** [comment]
The following Boolean keys lack a default `[true]`:
```
gloss-russian.ldf:\define@boolkey{russian}[russian@]{indentfirst}{
gloss-bengali.ldf:\define@boolkey{bengali}[bengali@]{changecounternumbering}{
```

**Comment by wehro** [comment]
> If you feel like revising the manual, go for it.

I will publish a proposal within the next days.

**Comment by jspitz** [comment]
> ```
> gloss-russian.ldf:\define@boolkey{russian}[russian@]{indentfirst}{
> gloss-bengali.ldf:\define@boolkey{bengali}[bengali@]{changecounternumbering}{
> ```

These are fixed.

**Comment by jspitz** [comment]
> Every bug fix hurts backwards compatibility.

I don't think that's an adequate statement.

**Comment by jspitz** [comment]
> The default value (type 2) of a Boolean option should always be true. But we have:
> 
> ```
> gloss-ukrainian.ldf:\define@boolkey{ukrainian}[ukrainian@]{babelshorthands}[false]{}
> gloss-slovenian.ldf:\define@boolkey{slovenian}[slovenian@]{localalph}[false]{%
> gloss-russian.ldf:\define@boolkey{russian}[russian@]{babelshorthands}[false]{}
> gloss-german.ldf:\define@boolkey{german}[german@]{latesthyphen}[false]{}
> gloss-mongolian.ldf:\define@boolkey{mongolian}[mongolian@]{babelshorthands}[false]{}
> gloss-belarusian.ldf:\define@boolkey{belarusian}[belarusian@]{babelshorthands}[false]{}
> hebrewcal.sty:\define@boolkey{hebrew}[@hebrew@]{fullyear}[false]{}
> ```

I propose to change this with an appropriately clear note in the Changelog. See #365.

@reutenauer what do you think?

**Comment by reutenauer** [comment]
I was going to say that I think it’s a good idea.  I note that you did something similar with e.g. the `marcheshvan` option of `hebrewcal.sty` and `gloss-hebrew.ldf`.

**Comment by jspitz** [comment]
Yes, that's true. I'll merge the thing.
