### ISSUE TITLE
Expose language options to other packages

### ISSUE THREAD

**Issue by moewew** [reutenauer/polyglossia#364]
Context https://github.com/plk/biblatex/issues/938.

Since I saw https://github.com/reutenauer/polyglossia/issues/363 just now, I thought it might be the right moment to pester you with another `biblatex`-flavoured request regarding language options.

For some use cases it would be nice to be able to check for the presence of additional language options. At the moment the implementation of language options is left to the gloss files and as far as I can see there is no unified way to query the selected/currently active language options from the outside (most declarations certainly follow a pattern, but there is some variation: `\ifslovak@vlna` vs `\if@german@blackletter`).

`babel` also allows for different language modifiers (with Boolean values) and the presence of those can be queried with `\bbl@ifattributeset`.

The specific use case I have in mind at the moment is Serbian and its ijekavica/ekavica split (https://github.com/plk/biblatex/issues/937), but `babel-serbian` has more options like this (for example for the date format). This might also be interesting for Spanish and `spanishoperators` so packages defining relevant operators can decide whether or not to use accents in their definitions.

How it works with `babel`
```latex
\documentclass{article}
\usepackage[serbian.ijekav]{babel}

\makeatletter
\begin{document}
\bbl@ifattributeset{serbian}{ijekav}{T}{F}
\end{document}
```

An official interface for the following would be nifty in `polyglossia`
```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[spanishoperators=all]{spanish}
\usepackage{csquotes}

\makeatletter
\begin{document}
\begin{spanish}
\ifspanish@accentedoperators
T
\else
F
\fi
\end{spanish}
\end{document}
```

----

Now I must admit that I'm not sure what an interface would look like and I could accept that the answer to this question is *use the internal implementation of the options*, but in that case it would be good if this were somehow officially endorsed as 'good practice' and would mean that the internal implementation of the options should be considered as part of the interface (i.e. should ideally be stable) to avoid breaking other packages in internal refactoring.

**Comment by jspitz** [comment]
I have added a test `\iflanguageoption{<lang>}{<key>}{<val>}{T}{F}` at c8cf3f0fde9af.

This does only consider the options explicitly set via language selector (including aliases), not the preset options of a language (if not explicitly re-set). It would be considerably more tricky to include all the default settings.

Does this suit your needs?

**Comment by moewew** [comment]
Thank you for the quick response. I will have a look at `\iflanguageoption` when I have time later this week.

**Comment by moewew** [comment]
> This does only consider the options explicitly set via language selector (including aliases), not the preset options of a language (if not explicitly re-set).

That is actually a bit of an issue. `biblatex` needs to know the active options, whether they were set as preset options without user intervention or explicitly. Essentially the use case that started this was https://github.com/plk/biblatex/issues/937. In `babel-serbian` there are several options that control small aspects of the translation (ekavian vs ijekavian spelling, the `datei` option). While `polyglossia` doesn't seem to support similar options at the moment, it is quite conceivable that it will do so in the future and then it would be useful if other packages like `biblatex` could query the status of these options and act accordingly.

In theory it would be possible for `biblatex` to detect situations where all tests yield false and conclude that this means that the preset value is active. But that requires knowledge about all possible values and the preset value. It would be nicer if `polyglossia` could do that.

Since the preset values (cf. #363, #367) are documented, it seems that the knowledge about these settings is part of `polyglossia`. I have no idea how feasible that is, but it might be possible to give the preset values in the gloss file and initialise each setkey call with that list of options before user-supplied options are given. After processing the preset and user-set options, all values should be good.

```latex
\documentclass{article}
\usepackage{polyglossia}
\usepackage{csquotes}

\setmainlanguage{spanish}
\setotherlanguage{english}

\begin{document}
\iflanguageoption{spanish}{spanishoperators}{false}{T}{F}

\begin{english}
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\begin{english}[ordinalmonthday=true]
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}

\begin{english}[ordinalmonthday=false]
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{document}
```

**Comment by jspitz** [comment]
> Since the preset values (cf. #363, #367) are documented, it seems that the knowledge about these settings is part of `polyglossia`. I have no idea how feasible that is, but it might be possible to give the preset values in the gloss file and initialise each setkey call with that list of options before user-supplied options are given. After processing the preset and user-set options, all values should be good.

Yes, that would be the only way to achieve that. But this is quite some manual work, and I cannot guarantee that people who contribute/edit gloss files later will remember to do that.

**Comment by moewew** [comment]
> Yes, that would be the only way to achieve that. But this is quite some manual work, and I cannot guarantee that people who contribute/edit gloss files later will remember to do that.

Absolutely. But since you will presumably also expect contributors to document the preset values in the docs, I figured that the additional overhead would be manageable and that people who forget would probably be reminded in a review before merging.

**Comment by jspitz** [comment]
Please try after 7472bf69ab2

**Comment by moewew** [comment]
Very nice!

There is just one thing: The default for missing option values are not picked up correctly.

Consider
```latex
\documentclass{article}
\usepackage{polyglossia}
\usepackage{csquotes}

\setmainlanguage[ordinalmonthday=false]{english}

\begin{document}
0 \today\
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}

\begin{english}
1 \today\
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\begin{english}[ordinalmonthday]
2 \today\
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\begin{english}[ordinalmonthday=true]
3 \today\
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}

\begin{english}[ordinalmonthday=false]
4 \today\
\iflanguageoption{english}{ordinalmonthday}{true}{T}{F}
\iflanguageoption{english}{ordinalmonthday}{false}{T}{F}
\end{english}
\end{document}
```

No. 2 should be equivalent to no. 3, but takes the `\iflanguageoption`s from the default (no. 0).

**Comment by jspitz** [comment]
Sorry, the latter is not possible. The same counts for alias options (`spelling=new` and `spelling=1996` will be recorded differently, although they are synonyms). I suppose all could be supported with much effort, but I don't have the energy for this now.

**Comment by wehro** [comment]
By the way, contrary to what the manual says, `spelling=1996` is actually not implemented. Only `new`, `old`, and `1901` work.

**Comment by jspitz** [comment]
If anybody has an idea how to retrieve default values of a given key from xkeyval, please let me know. There is `\<prefix>@<family>@<key>@default`, but this does not return the value, but the processed key macro.

**Comment by jspitz** [comment]
> By the way, contrary to what the manual says, `spelling=1996` is actually not implemented. Only `new`, `old`, and `1901` work.

Fixed at dc88f94ea4d0b70

**Comment by jspitz** [comment]
> There is just one thing: The default for missing option values are not picked up correctly.

This should be fixed (alas, we had to patch `xkeyval` for that).

One thing that still does not work are alias options (`spelling=new` and `spelling=1996`). Can you live with that?

**Comment by moewew** [comment]
Thanks for the effort.

> One thing that still does not work are alias options (`spelling=new` and `spelling=1996`). Can you live with that?

*I* can live certainly with using only the preferred option values (at least as long it is clear from the documentation, which value that is). It is also good enough for me that I will not hesitate to use`\iflanguageoption` when we need it for `biblatex` and if people complain about it then I can just point them here ;-)

**Comment by jspitz** [comment]
Alias values are supported now as well.

**Comment by moewew** [comment]
Neat. Thank you very much for all the work.
