### ISSUE TITLE
Conflict with package graphics

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#368]
As reported [on the TeX Live list](https://tug.org/pipermail/tex-live/2019-December/044540.html).

**Comment by jspitz** [comment]
For convenience:

With latest TL I'm getting a weird error where I have no idea who could
be the culprit:

When I run this MWE

```tex
\documentclass{article}
\usepackage[babelshorthands]{polyglossia}
\setdefaultlanguage{german}
\usepackage{graphicx}
\begin{document}
Test
\end{document}
```

through lualatex I get in the .log:

```
(c:/Programme1/texlive/2019/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
Package: epstopdf-base 2019-11-30 v2.9 Base part for package epstopdf
[\directlua]:1: unexpected symbol near '\'.
l.165       \directlua{require("pdftexcmds")}
                                           
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.
```

The error disappears, when I either

- remove [babelshorthands]
- comment \setdefaultlanguage{german}
- comment \usepackage{graphicx}

**Comment by jspitz** [comment]
However, I cannot reproduce the error with current master and the recipe given above. Can you, @reutenauer?

**Comment by jspitz** [comment]
Well, actually I can reproduce. The solution is to activate the language (`\setdefaultlanguage`) after all packages have been loaded, as we advise in the docs.

I don't think there is much we can do besides this advise.

**Comment by jspitz** [comment]
One thing that works is to use `\AfterPreamble` rather than `\AtBeginDocument` to pass the `\AtBeginDocument` hook `graphicx` seems to use and that is executed after `polyglossia`'s `\AtBeginDocument` if `graphicx` is loaded later (`\AfterPreamble` is expanded after any `\AtBeginDocument`).

```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index f3a0e4a..1921ad6 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -74,7 +74,7 @@
   % If hyphenation disabling has been requested in preamble, do it now
   \polyglossia@AtBeginDocument@hyphenation:
 }
-\AtBeginDocument{
+\AfterEndPreamble{
   \polyglossia@AtBeginDocument:
 }

```
This seems to work without problems with the MWE and the polyglossia docs. But it's not sure that this shifting has unwanted effects.

**Comment by jspitz** [comment]
Here is a more careful variant which only shifts the `\selectlanguage` and `\disablehyphenation` commands that cause the shorthand activation at issue here:
```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index f3a0e4a..76038b7 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -69,14 +69,20 @@
   \xpg@initial@setup
   % apply \familydefault changes
   \xpg@set@familydefault
+}
+
+\AtBeginDocument{
+  \polyglossia@AtBeginDocument:
+}
+
+% The following needs to go after any \AtBeginDocument (also of packages
+% loaded after \set[main|other]language
+\AfterEndPreamble{
   % now we have the C locale definition: select the language
   \polyglossia@AtBeginDocument@selectlanguage:
   % If hyphenation disabling has been requested in preamble, do it now
   \polyglossia@AtBeginDocument@hyphenation:
 }
-\AtBeginDocument{

```

**Comment by u-fischer** [comment]
With babel the " is active too when the file is read, but babel's definition of `\active@prefix` seems to be safer.

**Comment by jspitz** [comment]
We actually use babel's code for shorthands, so I wonder why the difference.
