### ISSUE TITLE
Extraneous spaces with \begin{lang}\end{lang}

### ISSUE THREAD

**Issue by emarsden** [reutenauer/polyglossia#369]
With polyglossia 2019/11/15 v1.46, using the local language-switching environments introduces extra spaces that were not present in previous versions. 

```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{french}
\setotherlanguage{english}
\begin{document}
.\begin{english}foo\end{english}.
\end{document}

```
Spaces are inserted between the "." and foo (before and after). Tested with lualatex and xelatex.

**Comment by jspitz** [comment]
Thanks for the report. This is already fixed in master (see #356)
