### ISSUE TITLE
Support for Devanagari script and marathi language.

### ISSUE THREAD

**Issue by NiranjanTambe** [reutenauer/polyglossia#370]
Package `polyglossia` currently does not support Devanagari script unless a font is loaded. If one loads language Marathi, and enters some text in Devanagari, `XeLaTeX` shows some errors like "the current Roman font does not contain Devanagari characters". This is a request for package-managers to include Devanagari fonts with the package. At the moment there are two fonts available in all the weights and slanted version of the same. Both are free and open source. The fonts are namely [`Yashovenu`](https://github.com/RajyaMarathiVikasSanstha/Yashovenu) and [`Yashomudra`](https://github.com/RajyaMarathiVikasSanstha/Yashomudra). I also have a small suggestion if these fonts are found helpful. Both the fonts are made by the same developer, but the difference is of strokes. First one is Sans-serif and the other one is Serif. For Marathi both these styles are important and used in different domains. Also there are two fonts for writing old style text in Devanagari. Jaini and Jaini-Purva are their names. If these fonts are included as the default fonts for Devanagari, please also provide a command `\setfontstyle` with a compulsory argument and the arguments will be `serif`, `sans-serif`, `traditional` or `old`. The arguments of this command will lead to the selection of a font from these four. The default will be sans-serif. Serif will lead to the selection of Yashomudra, traditional to Jaini and old to Jaini Purva. These fonts must be loaded with the following options - `Script=Devanagari, Mapping=devanagarinumerals, Language=Marathi`.

Additionally there are some necessities for Devanagari typesetting which needs to be added to `gloss-marathi.ldf`. They are as follows.

1. `\renewcommand{\baselinestretch}{1.2}` - for better handling of the diacritics.
2. Corrections in some pre-existing definitions in `gloss-marathi.ldf`. There are some spelling-mistakes in the ldf file. I have corrected them.
3. On line 85 of the `ldf` I have renewed the 2nd level item as it is absent in some Devanagari fonts.
4. Devanagari numbers in words were not defined, I've added till 100. 
Courtesy - Alann Munn's stackexchange [answer](https://tex.stackexchange.com/a/374440/174620)
5. Some additional character definitions for nested enumerate are added.

Files attached contain -

- Yashovenu with all it's varients
- Yashomudra with all it's varients
- Jaini and Jaini Purva font
- Corrected `gloss-marathi.ldf` with a test `.tex` file

[Yashovenu.zip](https://github.com/reutenauer/polyglossia/files/3961245/Yashovenu.zip)
[Yashomudra.zip](https://github.com/reutenauer/polyglossia/files/3961246/Yashomudra.zip)
[Jaini.1.001.zip](https://github.com/reutenauer/polyglossia/files/3961249/Jaini.1.001.zip)
[marathi.zip](https://github.com/reutenauer/polyglossia/files/3961255/marathi.zip)

**Comment by jspitz** [comment]
Thank you very much for this work! We do not ship fonts in `polyglossia,` so you would need to setup a separate package for that.

As to the ldf file: there have been many additions to the ldf files in master. Could you please re-add your changes to a current version, i.e., https://github.com/reutenauer/polyglossia/blob/master/tex/gloss-marathi.ldf ? Most preferably in a github fork, via a pull request.

Also, the `\baselinestretch` change should not be done globally, but in `\inlineextras@marathi` and `\blockextras@marathi` (and undone in `\noextras@marathi`). Please refer to tibetan, thai or khmer for a model.

**Comment by NiranjanTambe** [comment]
Thanks for the suggestions :)
Can you please elaborate more on `baselinestretch` problem?

I found this in `gloss-thai.ldf`, but did not understand it's meaning.
```
   \let\orig@baselinestrech\baselinestretch%
   \renewcommand{\baselinestretch}{1.2}%
}
\def\noblockextras@thai{%
%%TODO \XeTeXlinebreaklocales "en"%
   \let\baselinestrech\orig@baselinestretch%
```

It would be great if you explain what this is.

**Comment by NiranjanTambe** [comment]
Can you please elaborate more on why `\baselinestretch` should not be global?

```
\def\noextras@marathi{%
\nomarathi@eol%
\ifcsname xpg@orig@baselinestretch\endcsname\renewcommand{\baselinestretch}{\xpg@orig@baselinestretch}\fi %
}

\def\inlineextras@marathi{%
\xdef\xpg@orig@baselinestretch{\ifcsname baselinestretch\endcsname \baselinestretch \else 1\fi}%
\renewcommand{\baselinestretch}{1.2}%
\marathi@eol%
}

\def\blockextras@marathi{%
\xdef\xpg@orig@baselinestretch{\ifcsname baselinestretch\endcsname \baselinestretch \else 1\fi}%
\renewcommand{\baselinestretch}{1.2}%
\marathi@eol%
}
```

I have formed this, can you please review?

**Comment by jspitz** [comment]
> Can you please elaborate more on why `\baselinestretch` should not be global?

Because if it was, it would apply to the whole document (incl. other languages). Consider an English document which just switches temporarily to Marathi.

> ```
> \def\noextras@marathi{%
> \nomarathi@eol%

You don't need the `\nomarathi@eol` and `\marathi@eol `statements. These serve a different purpose in Thai.

> \ifcsname xpg@orig@baselinestretch\endcsname\renewcommand{\baselinestretch}{\xpg@orig@baselinestretch}\fi %
> }
> 
> \def\inlineextras@marathi{%
> \xdef\xpg@orig@baselinestretch{\ifcsname baselinestretch\endcsname \baselinestretch \else 1\fi}%
> \renewcommand{\baselinestretch}{1.2}%
> \marathi@eol%
> }
> 
> \def\blockextras@marathi{%
> \xdef\xpg@orig@baselinestretch{\ifcsname baselinestretch\endcsname \baselinestretch \else 1\fi}%
> \renewcommand{\baselinestretch}{1.2}%
> \marathi@eol%
> }
> ```
> 
> I have formed this, can you please review?

Otherwise it looks good.

**Comment by NiranjanTambe** [comment]
Hello.
As per your instructions, I edited my ldf file, but unfortunately it gives me the following errors -

```
Package xkeyval Error: `bcp47' undefined in families `marathi'. }
Package xkeyval Error: `localnumeral' undefined in families `marathi'. }
Undefined control sequence. \setlanguagealias
Missing \begin{document}. \setlanguagealias*
```

What must be the reason?

**Comment by jspitz** [comment]
The reason is probably that you do not use polyglossia.sty from master.

**Comment by NiranjanTambe** [comment]
Oh yes! I think I should update my complete polyglossia package. I thought it would be better to put-up a new pull request. This time I have kept everything intact :)

**Comment by jspitz** [comment]
OK, I see.

**Comment by jspitz** [comment]
One comment from the close pull request: The `\makeatletter` and `\makeatother` is not needed in the gloss file. You can just remove these two lines.

**Comment by NiranjanTambe** [comment]
Ok. I did it

**Comment by jspitz** [comment]
The changes have been merged.

**Comment by NiranjanTambe** [comment]
Thanks, where can I see the new file? [This](https://github.com/NiranjanTambe/polyglossia/blob/master/tex/gloss-marathi.ldf) file is still doesn't show the changes.

**Comment by jspitz** [comment]
You can see the file [here](https://github.com/reutenauer/polyglossia/blob/master/tex/gloss-marathi.ldf). If you want to merge the changes into your own fork, follow:
[this advise](https://gist.github.com/CristinaSolana/1885435)

**Comment by NiranjanTambe** [comment]
Ok, one last question.
I am currently using the following tex version.

```
TeX 3.14159265 (TeX Live 2019)
kpathsea version 6.3.1
```

Can I replace my current polyglossia folder with latest one (with the new `.sty` file) or it has some dependencies with the older version?

**Comment by jspitz** [comment]
If you replace the whole polyglossia folder, (all `sty` and `ldf` files) it should work.

**Comment by NiranjanTambe** [comment]
Ok thank you :)

**Comment by NiranjanTambe** [comment]
I am facing two errors with the updated version.
On line 2151 of `polyglossia.sty` we have
```
\setmainlanguage{latex}
```

This was resulting in the following error - 
```
LaTeX3 Error: The key 'polyglossia/latex/hyphenmins' requires a value. \setmainlanguage{latex}
```

Commenting the line resulted in the correct output, but I would like to know why is this happening.

Second issue -

This is the block that we added.

```
\def\blockextrasmarathi{%
  \let\xpg@orig@baselinestretch\baselinestrech%
  \renewcommand{\baselinestretch}{1.2}%
   \renewcommand{\labelitemii}{$\rightarrow$}%
}
```
Unfortunately it does not work. When I select default language marathi, my `baselinestretch` should be 1.2, it doesn't happen. (try changing the number to 5 instead of 1.2) Also the second level item is still `\textendash` and not how I defined. Can you please explain why is this change not working?

PS - Is it allowed to ask questions on a closed issue? If not I'll ask in a separate one.

**Comment by jspitz** [comment]
Please post a minimal example file that exhibits this error.

**Comment by NiranjanTambe** [comment]
See this MWE. If I run it with the current `polyglossia.sty` file, it shows the above mentioned error. You can see the log [here](https://pastebin.com/JK88wR9M). Also the `baselinestretch` is not correct.

```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{marathi}
\setmainfont[Script=Devanagari]{Yashomudra}

\begin{document}
	नमस्कार! ही देवनागरी लिपीत लिहिली जाणारी मराठी भाषा आहे.
	\begin{itemize}
		\item पहिला मुद्दा
		\begin{itemize}
			\item दुसरा मुद्दा
			\begin{itemize}
				\item तिसरा मुद्दा
				\begin{itemize}
					\item चौथा मुद्दा
				\end{itemize}
			\end{itemize}
		\end{itemize}
	\end{itemize}
\end{document}
```

**Comment by jspitz** [comment]
As to the error: I don't get this, and your log indicates that: 1.) you are using `polyglossia` 1.46 rather than master, which will not work with the recent `gloss-marathi.ldf`, and 2.) your installation seems incomplete (`gloss-latex.ldf` is not found but should be there).

**Comment by jspitz** [comment]
The other issues should be fixed in master at dc33d27e2850 (it needs to be `\blockextras@marathi` and `\noextras@marathi` rather than `\blockextrasmarathi` and `\noextrasmarathi`)

**Comment by NiranjanTambe** [comment]
Ok, I'll try reinstalling. Thanks for your help :)

**Comment by NiranjanTambe** [comment]
Hello,

I tried reinstalling the `polyglossia`. I replaced the entire folder. I had to move all the files from folder `tex` to the master folder `polyglossia` as the system couldn't detect `polyglossia.sty`. After it I compiled the document which I have attached as zip. On it's log it still says version 1.46 but I don't understand why, because the path which it mentions on line 26 is the exact file downloaded from the master. Also I am getting partial changes (in the old definitions) which is a weird part. If you see the pdf output, my re-definitions for `enumerate` are working properly as you can see `(अ)` on the second level and not the `(a)`, but I am not getting the `$\rightarrow$` on the second level in `itemize`. Also the `baselinestretch` is not working. When I compiled this document, I changed the `baselinestretch` from 1.2 to 4 for visible changes, but it is observed nowhere. Can you please guide me how to get rid of this problem.

[MWE.zip](https://github.com/reutenauer/polyglossia/files/4013898/MWE.zip)

**Comment by jspitz** [comment]
Please put the whole content of tex/ from master to `~/texmf/tex/latex/polyglossia` (where `~` represents your HOME directory). When you enter `kpsewhich polyglossia.sty` and `kpsewhich gloss-marathi.ldf` to a terminal, the path to this home directory should be output in both cases.

Assure that you use the files from here, not your own clone of the repo.

Happy New Year!

**Comment by NiranjanTambe** [comment]
> Happy New Year!

Happy new year to you too :)

> Assure that you use the files from here, not your own clone of the repo.

I am sure that I am not using the clone from my repository. (One clear evidence is I can clearly see some new changes which are not present in the clone.)

> When you enter kpsewhich polyglossia.sty and kpsewhich gloss-marathi.ldf to a terminal, the path to this home directory should be output in both cases.

Yes. I did it.

Still I am getting the second level itemize bullet and `baselinestretch` wrong. What if you compile the document using the master? Do you get the second level itemize bullet as defined? (ie. $\rightarrow$) Do you get the baselinestretch right?

**Comment by jspitz** [comment]
> What if you compile the document using the master? Do you get the second level itemize bullet as defined? (ie. $\rightarrow$) Do you get the baselinestretch right?

Yes. [This](https://github.com/reutenauer/polyglossia/files/4014152/MWE.pdf)  is the output I get.

**Comment by jspitz** [comment]
Please look again at your log file which gloss-marathi.ldf file is being used.
