### ISSUE TITLE
polyglossia-punct.lua: attempt to index a nil value (local 'fontparameters')

### ISSUE THREAD

**Issue by emarsden** [reutenauer/polyglossia#374]
Compiling the following with luatex generates a Lua error ...e/texmf-dist/tex/latex/polyglossia/polyglossia-punct.lua:217: attempt to index a nil value (local 'fontparameters'). At the point of error, current.font is equal to 0. 

```
\documentclass{article}
\usepackage{tikz}
\usepackage{polyglossia}
\setdefaultlanguage{french}
\begin{document}
  \begin{tikzpicture}
    ;
  \end{tikzpicture}
\end{document}
```

**Comment by jspitz** [comment]
@wehro I suppose we need to check (at several places) whether `fontparameters` is non-null befroe attempting to use it as a pointer

**Comment by wehro** [comment]
@emarsden, I am not sure what use case you have in mind. A single semicolon in a `tikzpicture` environment is useless. Note that the following code works.
```
\documentclass{article}
\usepackage{tikz}
\usepackage{polyglossia}
\setdefaultlanguage{french}
\begin{document}
  \begin{tikzpicture}
    \draw (0,0)--(5,0);
  \end{tikzpicture}
\end{document}
```
However, I will implement a check for `fontparameters`.

**Comment by emarsden** [comment]
It's true that this tikz syntax is functionally useless (I encountered this problem due to a harmless mistake in my document), but this syntax is accepted by xetex but (with current polyglossia) rejected by luatex, which I assume is not intended behaviour. Thanks.
