### ISSUE TITLE
Superfluous warning message concerning ecclesiasticfootnotes

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#376]
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage{latin}

\begin{document}
abc
\end{document}
```
This code yields the warning 
```
Package polyglossia Warning: The option "ecclesiasticfootnotes" is ineffective
(polyglossia)                on line 6 as Latin is not the main language.
```
even if the `ecclesiasticfootnotes` option is not used at all.
This is triggered by `\xpg@initialize@gloss@options{latin}` in `gloss-latin.ldf`.

@jspitz, do you have a suggestion what to do?

**Comment by jspitz** [comment]
Yes, issue the warning only if the user attemps to activate the feature.
