### ISSUE TITLE
Language environment dumps language name into text

### ISSUE THREAD

**Issue by moewew** [reutenauer/polyglossia#379]
Consider the following MWE compiled with `polyglossia` from current `master`

```latex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{english}

\begin{document}
A\begin{english}B\end{english}C
\end{document}
```

It produces

> AenglishBC

instead of the expected

> ABC

If I'm not mistaken this issue was introduced in https://github.com/reutenauer/polyglossia/commit/c5adc4eef3c5297797355048b1799d251e8b9e4b.

---

*edit* I now understand why that change causes the issue.

With the new definition `\newcommand*{\xpg@set@group@aux}{...}` `\xpg@set@group@aux` no longer takes the language name as argument (previously it was defined with `newcommand*{\xpg@set@group@aux}[1]{...}`), but the call to it in `\renewenvironment{otherlanguage}` still passes the language name.

**Comment by jspitz** [comment]
Thanks, fixed. How embarassing.
