### ISSUE TITLE
polyglossia brakes with new babel (3.9b)

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#38]
The new babel version (on CTAN but not yet distribuated with miktex) is not compatible with polyglossia. 

To reproduce the problem, install the base-folder of the new babel. Recreate the xelatex format (which will use the hyphen.cfg of babel), then run the following document:

\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}
blub
\end{document}

This gives the error

(D:\MiKTeX2.9\tex\xelatex\polyglossia\gloss-german.ldf
File: gloss-german.ldf polyglossia: module for german

(D:\MiKTeX2.9\tex\xelatex\polyglossia\babelsh.def
File: babelsh.def 2009/05/07 Babel common definitions for shorthands
 Taken verbatim from babel.def (2008/07/06 v3.8l)
)
! Undefined control sequence.
\@initiate@active@char ...e }}{}\else \@activated 
                                                  {#1}\@namedef {normal@char...
l.59 }{}

Obviously the babelsh.def file will need to be adapted.

Ulrike Fischer

**Comment by bastien-roucaries** [comment]
Done
