### ISSUE TITLE
Hungarian quotation

### ISSUE THREAD

**Issue by voroskoi** [reutenauer/polyglossia#384]
I try to use hungarian quotation marks with polyglossia. With babel I had to use ``quoted text >> quoted within quoted << quoted again''

Expected result:

Quote:
„ – opening quotation mark (99 down) (ANSI: 0132, UNICODE: 201E, &#8222;)
” – closing quotation mark (99 up) (ANSI: 0148, UNICODE: 201D, &#8221;)

Inner quote:
» – opening inner quotation mark (>> style) (ANSI: 0187, UNICODE: 00BB, &#187;)
« – closing inner quotation mark (<< style) (ANSI: 0171, UNICODE: 00AB, &#171;)

I have tried the following based on german quotes, but does not work:

```
\def\hungarian@shorthands{%
  \def\language@group{hungarian}%
  \declare@shorthand{hungarian}{"`}{„}%
  \declare@shorthand{hungarian}{"'}{”}%
  \declare@shorthand{hungarian}{"<}{«}%
  \declare@shorthand{hungarian}{">}{»}%
}
```

**Comment by jspitz** [comment]
`babelshorthands` are not yet implemented in gloss-hungarian. That's a general feature request.

**Comment by jspitz** [comment]
BTW the following works for me:
```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{hungarian}
\begin{document}

``quoted text >>quoted within quoted<< quoted again''
	
\end{document}
```

and produces
![image](https://user-images.githubusercontent.com/4538783/72874645-ca2e3700-3cf2-11ea-8bf8-ae344a363eac.png)

If this doesn't work for you, try if adding
```tex
\defaultfontfeatures{Ligatures=TeX}
```
at the end of the preamble helps.

**Comment by jspitz** [comment]
Note, though, that correct Hungarian quotes would need two commas `,,` as opening quotation mark:
```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{hungarian}
\begin{document}

,,quoted text >>quoted within quoted<< quoted again''
	
\end{document}
```
![image](https://user-images.githubusercontent.com/4538783/72875491-aa980e00-3cf4-11ea-951b-bf618615fb59.png)

**Comment by jspitz** [comment]
And in general, I'd advise to use `csquotes` (to the same result):
```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{hungarian}
\usepackage[autostyle=once]{csquotes}
\begin{document}

\enquote{quoted text \enquote{quoted within quoted} quoted again}
	
\end{document}
```

**Comment by voroskoi** [comment]
The ,,quote'' method is fine for me, I just used to the babel method. Also, thanks for the csquote hint.
