### ISSUE TITLE
missing % in gloss-english

### ISSUE THREAD

**Issue by davidcarlisle** [reutenauer/polyglossia#386]
https://tex.stackexchange.com/questions/525567/polyglossia-textenglish-produces-extra-spaces-while-textspanish-works-pro/525569#525569

```
\def\english@language{%
   \polyglossia@setup@language@patterns{\english@variant}
}%
```

is missing a `%` at eol causing extra space as noted in the above tex.sx question.

**Comment by jspitz** [comment]
Thanks for the report. This has already been fixed in master at b670d3e0.
