### ISSUE TITLE
Additional whitespace before Japanese

### ISSUE THREAD

**Issue by doughertyt** [reutenauer/polyglossia#387]
This issue is similar to, but distinct from #356.

When using Japanese text within a document where `\setmainlanguage` is `english`, excessive extra space is inserted before Japanese text.

```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{japanese}

\newfontfamily\japanesefont{Noto Serif JP}

\begin{document}
Hello, world! \textjapanese{ハロー・ワールド！} Haroo waarudo!

\end{document}
```

Identical behavior is found with the `japanese` environment:

```
Hello, world! %
\begin{japanese}%
ハロー・ワールド！%
\end{japanese}%
Haroo waarudo!
```

When `\setmainlanguage` is `japanese`, no extra spaces are inserted before `\textenglish`. Compare the following MWE:
```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{japanese}
\setotherlanguage{english}

\newfontfamily\japanesefont{Noto Serif JP}

\begin{document}
\textenglish{Hello, world!} ハロー・ワールド！\textenglish{Haroo waarudo!}

\end{document}
```

This makes me think it's something similar to what was going on with #356, but is somewhere in the handling of Japanese.

**Comment by jspitz** [comment]
Should be fixed. Testing would be appreciated.

**Comment by doughertyt** [comment]
Yep, that fixed it.

Before:
![polyglossia-ja-fix-before](https://user-images.githubusercontent.com/11002090/73339819-9e90dc80-421d-11ea-8147-f32d384fc997.png)

After:
![polyglossia-ja-fix-after](https://user-images.githubusercontent.com/11002090/73339824-a18bcd00-421d-11ea-8d53-e0e67ca2becd.png)

Thanks.
