### ISSUE TITLE
French footnote overriding biblatex-chicago

### ISSUE THREAD

**Issue by pcdi** [reutenauer/polyglossia#391]
I have run into some unexpected behavior in combination with [`biblatex-chicago`](https://ctan.org/pkg/biblatex-chicago). Footnote marks are redefined by `biblatex-chicago` to be inline (not superscript) with a trailing dot.

In case 1 (see MWE below), this works as expected. 
In case 2, footnote marks are reset to the standard LaTeX format, that is superscript. It seems that `polyglossia` is overriding the option set through `biblatex-chicago`.
Case 3 also works as expected.
Case 4 shows the same behavior as case 2, so again, `polyglossia` overrides `biblatex-chicago` and we end up with a superscript again.

Naturally, the option `frenchfootnote` can only be set if French is the main language ([6.13](https://ctan.kako-dev.de/macros/latex/contrib/polyglossia/polyglossia.pdf#1d)), therefore it is not possible to get inline footnote numbers through `biblatex-chicago` when french is an `otherlanguage`.

```TeX
\documentclass{article}

\usepackage{polyglossia}

\setdefaultlanguage{english}% Case 1: inline

% \setdefaultlanguage{french}% Case 2: superscript

% \setdefaultlanguage[frenchfootnote=true]{french}% Case 3: inline

% \setdefaultlanguage{english}% Case 4: superscript
% \setotherlanguage{french}

\usepackage{biblatex-chicago}

\begin{document}

\footnote{Footnote}

\end{document}
```

**Comment by pcdi** [comment]
The problem lies in the definition of `frenchfootnote`, because it first saves the original footnote definition and then restores it _after_ the preamble, thus overwriting all changes that were made to the definition in the preamble.

https://github.com/reutenauer/polyglossia/blob/5322336375286debd9dfd9845478e7e7e2746d6d/tex/gloss-french.ldf#L78-L98

A workaround is to first load `polyglossia`, then load `biblatex-chicago` and then set French as a language, because it then saves the definition that had already been changed through `biblatex-chicago`.

```TeX
\usepackage{polyglossia}

\usepackage{biblatex-chicago}

\setdefaultlanguage{english}
\setotherlanguage{french}
```

However, I think that this is neither ideal nor wanted.

**Comment by jspitz** [comment]
Well, generally it is advised to set the languages always after all packages have been loaded (see the advise in sec. 2.1 of the manual). But I agree that this should not happen.

**Comment by jspitz** [comment]
Can you please test if the following change fixes all your cases?
```diff
diff --git a/tex/gloss-french.ldf b/tex/gloss-french.ldf
index bff7d4b..6d347b8 100644
--- a/tex/gloss-french.ldf
+++ b/tex/gloss-french.ldf
@@ -76,7 +76,9 @@
 \def\xpg@unskip{\ifhmode\ifdim\lastskip>\z@\unskip\fi\fi}
 
 % Save original footnote definition
-\let\xpg@orig@makefntext\@makefntext
+\AtEndPreamble{%
+  \let\xpg@orig@makefntext\@makefntext
+}
 
 \define@boolkey{french}[french@]{frenchfootnote}[true]{%
   \AfterPreamble{%

```

**Comment by jspitz** [comment]
The same problem existed with Latin. I've now tested and pushed the fix, but I'd appreciate feedback.

**Comment by pcdi** [comment]
I tested with c4dfb8de4a57575422f6eb33ff4e6993172fe7f4, and the issue is resolved for me.

**Comment by jspitz** [comment]
Please leave this open until 1.48 is released.

**Comment by jspitz** [comment]
(and, of course, thanks for testing!)
