### ISSUE TITLE
Error witn Serbian Language in Polyglossia 1.47

### ISSUE THREAD

**Issue by dejanziv** [reutenauer/polyglossia#392]
I get an error with Polyglossia 1.47
! Undefined control sequence.
\noextras@serbian ->\ifserbian@numerals 
                                        \noserbian@numbers \fi 

using MikTex and the following code:

\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{unicode-math} % For math support
\usepackage{polyglossia}
\setdefaultlanguage[script=Latin]{serbian}
\begin{document}
Proba \ldots
\end{document}

**Comment by jspitz** [comment]
Thanks for the report, fixed for 1.48.
You can easily fix the problem yourself in gloss-serbian.ldf by replacing all `\ifserbian@numerals` by `\ifcyrillic@numerals`

**Comment by dejanziv** [comment]
Thanks a lot!

Best regards,
Dejan Zivkovic
