### ISSUE TITLE
Error: Undefined control sequence with MikTeX

### ISSUE THREAD

**Issue by enteente** [reutenauer/polyglossia#393]
When I tried to compile a document using polyglossia the compile process exited with an undefined control sequence error. No pdf was created.
The error occurs with english as default language, too. The error seems to be unrelated to the choosen documentclass.

My version used is:
MikTex = 2.9.6350 (Windows 10)
xelatex = 3.14159265-2.6-0.99998
fontspec = v2.7i
polyglossia = v1.47

Minimal example:
```
\documentclass{book}

\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage{german}

\begin{document}
	foo
\end{document}
```

Used command for compiling:
```
xelatex.exe -synctex=1 -shell-escape  -output-driver="xdvipdfmx -z 0" -interaction=nonstopmode %.tex
```

Error message:
```
("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\polyglossia\gloss-latex.ldf"
File: gloss-latex.ldf polyglossia: module for default language

! Undefined control sequence.
<argument> \str_lowercase:n 
                            latin
l.8 }
     
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

Attached log-file:
[minimalbsp.log](https://github.com/reutenauer/polyglossia/files/4241207/minimalbsp.log)

**Comment by jspitz** [comment]
You seem to have an outdated version of expl3 in your local tree (`C:\Users\aboesema\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\expl3.sty`). Your version is 2019-11-07, the recent version (in MikTeX) is 2020-02-21.

Also see #383.

**Comment by enteente** [comment]
Thanks for the indication. Updating MikTex packages solved the problem.
