### ISSUE TITLE
nolocalmarks option does the opposite of what it should

### ISSUE THREAD

**Issue by jfbu** [reutenauer/polyglossia#395]
There is a bug (extra `{}`)  in https://github.com/reutenauer/polyglossia/blob/69c1a16572452d6c2522fb376699758d9f5b700d/tex/polyglossia.sty#L2174-L2176

As a result, using `nolocalmarks` option (for example) results in the `\enable@local@marks` to get executed, opposite of user intent. And using `localmarks` does nothing.

As an aside in https://github.com/reutenauer/polyglossia/blob/69c1a16572452d6c2522fb376699758d9f5b700d/tex/polyglossia.sty#L970 and similar lines are fragile agints user wrapping of `\leftmark/\rightmark` in `\MakeUppercase`.

**Comment by reutenauer** [comment]
Thank you for the report, the first part was clearly an oversight.

**Comment by jspitz** [comment]
> As an aside in
> 
> https://github.com/reutenauer/polyglossia/blob/69c1a16572452d6c2522fb376699758d9f5b700d/tex/polyglossia.sty#L970
> and similar lines are fragile agints user wrapping of `\leftmark/\rightmark` in `\MakeUppercase`.

Could you please provide a MWE for this? I think we can work around that by lowercasing the language argument, but as I never used `localmarks`, I am unsure how to test it.

**Comment by jfbu** [comment]
> Could you please provide a MWE for this? I think we can work around that by lowercasing the language argument, but as I never used `localmarks`, I am unsure how to test it.

It is a bit artificial, but perhaps more frequent than a user definiing own `\ps@...` macros to set `\@oddfoot` etc... in terms of `\leftmark` and `\rightmark`.

Admittedly, user using only `\markboth` interface should not encounter this problem. It is however imaginable that some document class (thesis template?) somewhere does things like `\Makeuppercase{\leftmark}` and at the same time allows user usage of `\markboth`.

```latex
\documentclass{book}
% This is with polyglossia 2020/01/29 v1.47 but once
% #395 is fixed it should be with localmarks option here
\usepackage[nolocalmarks]{polyglossia}
\setmainlanguage{english}

\usepackage{fancyhdr}
\fancyhead{}
\fancyhead[C]{\MakeUppercase{\leftmark}}

\begin{document}
\tableofcontents

\chapter{First}
\pagestyle{fancy}

\section{A}
\section{B}

\chapter{Second}

\section{A}
\section{B}

\end{document}
% Local Variables:
% TeX-engine: xetex
% End:
```

error:
```
Chapter 1.
[3]

./polyglossiamarks.tex:20: Package polyglossia Error: language ENGLISH is not l
oaded. Please load it before using it..

See the polyglossia package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 \chapter
             {Second}
This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.
```

**Comment by jspitz** [comment]
Hm, I don't get an error with this MWE with current master (even with `localmarks` option rather than `nolocalmarks`)

**Comment by jfbu** [comment]
@jspitz Try with

```
\usepackage[localmarks=true]{polyglossia}
```

I don't know why `=true` is needed, you may need to ask L3 team advice as it seems polyglossia is using their key interface.

**Comment by jspitz** [comment]
> I don't know why `=true` is needed

That was another bug, fixed now at cb8ee50ab78

**Comment by jfbu** [comment]
Using `\lowercase{\foreignlanguage{##1}}` (three times) in `\enable@local@marks` fixes the test case, however are language identifiers always lowercased?

**Comment by jfbu** [comment]
By the way the code for `\def\markright####1` is utterly bizarre. Here is for example what `\markright{Hello}`  involves putting in `\mark{....stuff...}`:

```latex
Chapter 1.
> {\protect \@@ensure@maindir {\lowercase {\protect \foreignlanguage {english}}{\protect \@@ensure@maindir {\protect \MakeUppercase  {Chapter\ 1. \ First}}}}}{\protect \@@ensure@maindir {\lowercase {\protect \foreignlanguage {english}}{\protect \@@ensure@maindir {Hello}}}}.
\markright ...\@temptokena }\showthe \@temptokena 
                                                  \endgroup \if@nobreak \ifv...l.20 \markright{Hello}
```

This is with this where I only added the `\lowercase` as mentioned before
```
\def\enable@local@marks{
      \xpg@info{Option:~ localmarks}%
      \def\local@marks##1{%
         \def\markboth####1####2{%
            \begingroup
               \let\label\relax \let\index\relax \let\glossary\relax
               \unrestored@protected@xdef\@themark
         {{\lowercase{\foreignlanguage{##1}}{%
            \protect\@@ensure@maindir{####1}}}%
          {\lowercase{\foreignlanguage{##1}}{%
      \protect\@@ensure@maindir{####2}}}}%
               \@temptokena \expandafter{\@themark}%
%\showthe\@temptokena
               \mark{\the\@temptokena}%
            \endgroup
            \if@nobreak\ifvmode\nobreak\fi\fi}%
            \def\markright####1{%
               \begingroup
                  \let\label\relax \let\index\relax \let\glossary\relax
                  \expandafter\@markright\@themark
      {\lowercase{\foreignlanguage{##1}}{\protect\@@ensure@maindir{####1}}}%
                  \@temptokena \expandafter{\@themark}%
                  \mark{\the\@temptokena}%
\showthe\@temptokena
                \endgroup
               \if@nobreak\ifvmode\nobreak\fi\fi}%
            \def\@markright####1####2####3{\@temptokena{\protect\@@ensure@maindir{####1}}%
               \unrestored@protected@xdef\@themark{{\the\@temptokena}%
               {\protect\@@ensure@maindir{####3}}}}}%
}
```

and modifying test case into

```
\chapter{First}
%\pagestyle{fancy}
\markright{Hello}
```

**Comment by jspitz** [comment]
> Using `\lowercase{\foreignlanguage{##1}}` (three times) in `\enable@local@marks` fixes the test case, however are language identifiers always lowercased?

Yes, all polyglossia names are lowercased, and polyglossia names is what should be used exclusively here.

I'd probably go with `\str_lowercase:n` rather than `\lowercase`. The following seems to fix the text case for me as well:
```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 4129f5b..f2f855a 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -967,9 +967,9 @@
             \begingroup
                \let\label\relax \let\index\relax \let\glossary\relax
                \unrestored@protected@xdef\@themark
-         {{\foreignlanguage{##1}{%
+         {{\str_lowercase:n\foreignlanguage{##1}{%
             \protect\@@ensure@maindir{####1}}}%
-          {\foreignlanguage{##1}{%
+          {\str_lowercase:n\foreignlanguage{##1}{%
       \protect\@@ensure@maindir{####2}}}}%
                \@temptokena \expandafter{\@themark}%
                \mark{\the\@temptokena}%
@@ -979,7 +979,7 @@
                \begingroup
                   \let\label\relax \let\index\relax \let\glossary\relax
                   \expandafter\@markright\@themark
-      {\foreignlanguage{##1}{\protect\@@ensure@maindir{####1}}}%
+      {\str_lowercase:n\foreignlanguage{##1}{\protect\@@ensure@maindir{####1}}}%


```

The whole localmarks definition is probably messy. That's why it is no longer used by default (and probably we should more strongly discourage its use).

**Comment by jfbu** [comment]
> The whole localmarks definition is probably messy.

The `\markright` re-defintion is certainly buggy.

**Comment by jspitz** [comment]
As a start, I fixed the indentation in ce74c1a175ef3e to make the function a bit more readable

**Comment by jspitz** [comment]
The lowercasing is in at a8952e5a301.

I'll let you handle the `\markright` fixing, @jfbu.

**Comment by jspitz** [comment]
> The lowercasing is in at [a8952e5](https://github.com/reutenauer/polyglossia/commit/a8952e5a301949f3dbe5b9f34d45f23b589a1aaa).

and reverted at ff8caf2 (didn't work)

**Comment by jfbu** [comment]
> > The lowercasing is in at [a8952e5](https://github.com/reutenauer/polyglossia/commit/a8952e5a301949f3dbe5b9f34d45f23b589a1aaa).
> 
> and reverted at [ff8caf2](https://github.com/reutenauer/polyglossia/commit/ff8caf2cfd81ccc45f5f514d4d5cd459b65fc9e3) (didn't work)

You need to wrap all of `\foreignlanguage{####1}` as argument.

As per



> I'll let you handle the `\markright` fixing, @jfbu.

I hope I did not speak too early and too affirmatively, because right now I am handling several things at once. But I will return later today to clarify what I meant.

**Comment by jspitz** [comment]
> You need to wrap all of `\foreignlanguage{##1}` as argument.

I've re-done now using `\lowercase` at e4403bf8ccfe3

> I hope I did not speak too early and too affirmatively, because right now I am handling several things at once. But I will return later today to clarify what I meant.

Fair enough. Any pointer will be helpful.

**Comment by jfbu** [comment]
> ```diff
> -      {\foreignlanguage{##1}{\protect\@@ensure@maindir{####1}}}%
> +      {\str_lowercase:n\foreignlanguage{##1}{\protect\@@ensure@maindir{####1}}}%
> ```

ah I did not see you were using `\str_lowercase:n` whose interface3 says 
```
Converts the input ⟨tokens⟩ to their string representation, as described for \tl_to_str:n, and then to the lower or upper case representation using a one-to-one mapping as described by the Unicode Consortium file UnicodeData.txt.
```
This looks like a mouthful. And I vainly looked in interface3 for the actual TeX primitive.

But one can always grep the LaTeX3 sources: it is called `\tex_lowercase:D`. But I gather `D` means "do not use". One wonders why... once LaTeX3 makes undefined the TeX primitives it will become a close world ejecting all legacy coding.

**Comment by jfbu** [comment]
Besides `str_lowercase:n` as per its description changes catcodes.

```latex
\documentclass{article}

\begin{document}

\ExplSyntaxOn
\edef\foo{\str_lowercase:n{Jean}}
\ExplSyntaxOff

\def\bar{jean}
\ifx\foo\bar OK\else Catcodes!\fi

\edef\bar{\detokenize{jean}}
\ifx\foo\bar OK\else Catcodes!\fi

\end{document}
```
It may or may not cause problem: no problem if output is only to serve inside a `\csname...`.

In your use case `\foreignlanguage` as a macro should not be in scope of `\str_lowercase:n`.

**Comment by jspitz** [comment]
Remainder is in #396
