### ISSUE TITLE
\defineshorthand broken: not all logic imported to babelsh.def

### ISSUE THREAD

**Issue by Quoor8ee** [reutenauer/polyglossia#399]
I try to rebuild babel's `\defineshorthand` customisation of quotation mark shorthands with polyglossia, but the MWE
```
%!lualatex %
\documentclass{minimal}
\usepackage{polyglossia}
\setdefaultlanguage[babelshorthands=true]{german}

\defineshorthand{"`}{L}
\defineshorthand{"'}{R}

\begin{document}
"`Text in Anführungszeichen"'
\end{document}
```

dies with
```
! Undefined control sequence.
\\defineshorthand ...p@space #1 \@empty }\bbl@for 
                                                  \bbl@tempb \bbl@tempa {\if...

l.6 \defineshorthand{"`}{L}
```
when loading `tex/latex/polyglossia/babelsh.def`. It turns out the definition of the macro `\bbl@for` and others are missing indeed (cf. [TL SVN](http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/polyglossia/babelsh.def?sortby=date&r1=52808&r2=52807&pathrev=52808)). Whatever the criteria are what to import from `generic/babel/babel.def`, were obviously a bit too restrictive.

I'm following the TL2020 pretest with the latest polyglossia v1.47, and have a limited number of previous update states available. On v1.44, the MWE runs well and correctly.

I didn't want to mess around by myself within the diff between the original babel.def and polyglossia's import, but it might be fixable that way.

**Comment by jspitz** [comment]
I've added the necessary helper commands. Your example works now. Note that the optional argument of \defineshorthand still doesn't, but I think we do not intend to fully support that.

**Comment by Quoor8ee** [comment]
Thank you so much for the rapid fix! My polyglossia setup works now as intended.

Just for completeness, adding `% lines 110 to 116 from babel.def` helps reconstructing what has happened here, and where code comes from.

Is there a chance that the current dev changes find their way to CTAN in the next days? TeXLive 2020 code freeze [is planned for next friday](https://tug.org/pipermail/tex-live/2020-March/045134.html).

**Comment by jspitz** [comment]
> Just for completeness, adding `% lines 110 to 116 from babel.def` helps reconstructing what has happened here, and where code comes from.

Indeed. Done.

> Is there a chance that the current dev changes find their way to CTAN in the next days? TeXLive 2020 code freeze [is planned for next friday](https://tug.org/pipermail/tex-live/2020-March/045134.html).

That's the plan, yes. But that's @reutenauer's call.

**Comment by reutenauer** [comment]
On Sun, Mar 22, 2020 at 07:51:25AM -0700, Jürgen Spitzmüller wrote:
> That's the plan, yes. But that's @reutenauer's call.

  I’ll make an upload to CTAN tonight.

	Arthur
