### ISSUE TITLE
\farsidigits bug with grouping

### ISSUE THREAD

**Issue by ghost** [reutenauer/polyglossia#4]
\farsidigits{987{878}} gets printed as "٩٨٧78٨" while it should be printed as "۹۸۷۷۸۸".

**Comment by bastien-roucaries** [comment]
\roman{1{23}} fail so I consider that grouping should fail.

**Comment by bastien-roucaries** [comment]
Should be bug to bug like \roman

**Comment by jspitz** [comment]
> \roman{1{23}} fail so I consider that grouping should fail.

`\roman{1{23}}` fails since `\roman` takes a counter, not a numeral; `\roman{1}` fails as well.

`{\romannumeral 1{23}}` outputs 

> i23

so the behavior of \farsidigits is identical here (and IMHO expected).

BTW what does "bug to bug" mean?

**Comment by bastien-roucaries** [comment]
On Sun, Sep 1, 2019 at 11:56 AM Jürgen Spitzmüller <notifications@github.com>
wrote:

> \roman{1{23}} fail so I consider that grouping should fail.
>
> \roman{1{23}} fails since \roman takes a counter, not a numeral; \roman{1}
> fails as well.
>
> {\romannumeral 1{23}} outputs
>
> i23
>
> so the behavior of \farsidigits is identical here (and IMHO expected).
>
> BTW what does "bug to bug" mean?
>

I fixed it some time ago.

**Comment by jspitz** [comment]
> I fixed it some time ago.

To which part of my statement does this refer? (Actually it does not seem to make sense for me WRT anyone)

**Comment by jspitz** [comment]
Closing.
