### ISSUE TITLE
Please change the Finnish \contentsname to "Sisällys"

### ISSUE THREAD

**Issue by tlikonen** [reutenauer/polyglossia#403]
In the Finnish language the most common name for table of contents is "Sisällys" (sometimes longer form "Sisällysluettelo"). However, Polyglossia package defines name ”Sisältö" which means the same but is rarely used in this context.

I suggest changing the definition of `\contentsname` command to "Sisällys".

**Comment by tlikonen** [comment]
I filed the same issue to Babel: https://github.com/latex3/babel/issues/61

**Comment by reutenauer** [comment]
Thanks for the report, I’ve just fixed it and it will be in the next release of Polyglossia (date to be decided).
