### ISSUE TITLE
Portuguese (brazilian variant)

### ISSUE THREAD

**Issue by gilsonolegario** [reutenauer/polyglossia#404]
After this [commit](https://github.com/reutenauer/polyglossia/commit/e1c043de59892df4ccf384b694920d851aacf5d9)

and following the recommendations of the manual. In order to use the brazilian variant of portuguese we have to set: 

```
\usepackage{polyglossia}
\setmainlanguage[variant=brazilian]{portuguese}
```

But, if done so, the following error appears:

```
Package polyglossia Warning: No hyphenation patterns were loaded for "Portugues
e (Brazil)"
(polyglossia)                I will use the standard patterns for Portuguese in
stead on input line 5.

./Untitled-2.tex:5: Undefined control sequence.
\adddialect ...####1####2####3####4{}\fi }\bbl@cs 
                                                  {languages}\endgroup 
l.5 ...mainlanguage[variant=brazilian]{portuguese}
                                                  
? 
```

This is a problem with polyglossia or with lualatex? 

MWE:

```
\documentclass[a4paper,12pt]{article}
\usepackage{polyglossia}
\setmainlanguage[variant=brazilian]{portuguese}
\setotherlanguage[variant=american]{english}
\setotherlanguage{polish}

\begin{document}
Teste
\end{document}
```

**Comment by jspitz** [comment]
The error is #400. This is fixed in polyglossia 1.49; please update. If you can't update, add this to your preamble:
```tex
\makeatletter
\def\bbl@cs#1{\csname bbl@#1\endcsname}
\makeatother
```
The warning can be ignored. There are no specific Brazilian patterns (and have never been), so Standard Portuguese is used. We routinely check for brazil patterns since Babel does as well, in the hope such patterns will exist eventually.

But as the warning always triggers, we could also change it to an Info message. @reutenauer?

**Comment by gilsonolegario** [comment]
The update solved the problem. Thanks.

There is no difference between the hyphenation patterns in the portuguese of Portugal and the brazilian one. Maybe even the Info message is unnecessary.

The following warning can be ignored too?

```
Module polyglossia Warning: Language brazil not found in language.dat.lua on in
put line
```

**Comment by jspitz** [comment]
> The update solved the problem. Thanks.

Good. Closing this, then.

> There is no difference between the hyphenation patterns in the portuguese of Portugal and the brazilian one. Maybe even the Info message is unnecessary.

OK. I'll remove it, then.

> The following warning can be ignored too?
> 
> ```
> Module polyglossia Warning: Language brazil not found in language.dat.lua on in
> put line
> ```

Yes, that's basically the same issue.

**Comment by reutenauer** [comment]
Actually, there are [hyphenation patterns](https://extensions.libreoffice.org/extensions/vero-verificador-ortografico-e-hifenizador-em-portugues-do-brasil) for Brazilian Portuguese.  They seem a little more exhaustive than the ones we have for Portuguese.  I could add them to `hyph-utf8`.

**Comment by jspitz** [comment]
> Actually, there are [hyphenation patterns](https://extensions.libreoffice.org/extensions/vero-verificador-ortografico-e-hifenizador-em-portugues-do-brasil) for Brazilian Portuguese. They seem a little more exhaustive than the ones we have for Portuguese. I could add them to `hyph-utf8`.

Obviously I am unable to comment on the quality of those patterns, so I cannot say anything helpful. If they are going to be added, we should re-introduce the check, of course.

**Comment by gilsonolegario** [comment]
> Actually, there are [hyphenation patterns](https://extensions.libreoffice.org/extensions/vero-verificador-ortografico-e-hifenizador-em-portugues-do-brasil) for Brazilian Portuguese. They seem a little more exhaustive than the ones we have for Portuguese. I could add them to `hyph-utf8`.

Both, the "[Brazilian Portuguese spellchecking dictionary and hyphenator](https://extensions.libreoffice.org/extensions/vero-verificador-ortografico-e-hifenizador-em-portugues-do-brasil)" [1] and the "[[Portuguese (Portugal) spellchecker and thesaurus](Portuguese (Portugal) spellchecker and thesaurus)](https://extensions.libreoffice.org/extensions/corretor-ortografico-para-portugues-de-portugal)" [2] follows the Portuguese Spelling Agreement. [1] "Brazilian Portuguese spellchecking dictionary and hyphenator. Supports the new Portuguese Spelling Agreement intended to provide the spelling unification for several Portuguese-spoken countries" [2] "Portuguese (Portugal) spellchecker and thesaurus, conforming with the 1990 Ortographic Agreement (Acordo Ortográfico de 1990)." If they do differ, they _have to be_ only on a matter of exhaustibility. That said, from a practical/technical point of view, you can, better than me, decide what to do.

**Comment by reutenauer** [comment]
Thanks for checking.  The list of patterns is clearly quite different, it must be a different implementation of the rules.  There is also an amusing additional pattern for `pt-PT`, that doesn’t fit with any other one: `.ex1e4m3p2l2o.`, i. e. hyphenate ex-am-plo (which otherwise would be e-xam-plo, or exam-plo with `\lefthyphenmin > 1`).  Can you comment on that?

**Comment by gilsonolegario** [comment]
Strange addition indeed. And the first one that list. But the official sources lists ex**e**mplo ["ex**a**mplo" doesn't exist] hyphenated in the same way, as it have to be:

[e.'xem.plo](https://voc.cplp.org/index.php?action=lemma&id=99183)
[e·xem·plo](http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=99183)

**Comment by reutenauer** [comment]
Sorry, my mistake, I did mean exemplo.  Well, let’s forget about that one, then.  I’ll install the patterns for Brazilian Portuguese (that don’t have that pattern) in `hyph-utf8` in the next few weeks, I’d be happy for you to test how they compare the ones we currently have.
