### ISSUE TITLE
gloss-marathi.ldf giving me some errors.

### ISSUE THREAD

**Issue by NiranjanTambe** [reutenauer/polyglossia#405]
This is a question, I don't know how to add the tag myself, hence mentioned it here.

I installed TeX on my system through an ISO provided on [this](http://mirrors.rit.edu/CTAN/systems/texlive/Images/) page. As the TeX-distributions do not contain the latest `polyglossia`, I replaced my `polyglossia` folder with the current GitHub repository and ran `texhash`. Here are some specifications.

TeX version
```
TeX 3.14159265 (TeX Live 2019)
kpathsea version 6.3.1
```
Output of `kpsewhich polyglossia.sty`
```
/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/polyglossia.sty
```
This is the `polyglossia.sty` downloaded from GitHub.

Output of `kpsewhich gloss-marathi.ldf`
```
/usr/local/texlive/2019/texmf-dist/tex/latex/polyglossia/gloss-marathi.ldf
```

[This](https://github.com/reutenauer/polyglossia/files/4475715/MWE.zip) is a collection two MWEs. One with `polyglossia` loaded and one without it. For immediate visual recognition effect, I changed `baselinestretch` to 5 in `gloss-marathi.ldf` on line 143 & in the `nopolyglossia.tex` manually by `renewcommand`. If we check the outputs of both the files, `baselinestretch` seems to be working only for some domains in the polyglossia file. Also I get two `Undefined control sequence` errors for line 24 of the `gloss-marathi.ldf`.

I am unable to know what is happening. Can somebody please help me?

**Comment by reutenauer** [comment]
TeX Live actually does contain the latest version of Polyglossia (except for one change in the Portuguese file), if you want to diagnose problems I suggest you update it with `sudo tlmgr update` before diving deeper into the issue.

**Comment by reutenauer** [comment]
Sorry, just realised you’re still on TeX Live 2019 for some reason.  Are you sure you’re using the installation made from the ISO image?  In any case I’d recommend the [net install](http://tug.org/texlive/acquire-netinstall.html) which always gives you the latest version of packages.

**Comment by NiranjanTambe** [comment]
Yes I am sure I am using the installation made from the iso image. Is there any chance of repairing the current `polyglossia` with some new files? Because of slow connection it's difficult for me to do a net install again.

**Comment by NiranjanTambe** [comment]
Also `tlmgr update polyglossia` returned this error -

```
/usr/local/texlive/2019/bin/x86_64-linux/tlmgr: unexpected return value from verify_checksum: -5
```

**Comment by reutenauer** [comment]
Can you please check again?  I see in your log file that the versions of `fontspec` and `expl3` in your installation are from March and April 2019, respectively.  It really looks like you’re actually using TeX Live 2019 with a `polyglossia.sty` from 2020.  That won’t work.

**Comment by NiranjanTambe** [comment]
Oh it got updated on 6th April. I installed it only two days before. The latest version was 2019 then. I will reinstall full TeX system now, which will hopefully solve the problem, but on a side-note isn't there any way to make the latest `polyglossia.sty` work with an older version?

**Comment by jspitz** [comment]
Your `example.log` reveals that your version of `expl3` is too old. You need to update this package. You have `expl3 2019-04-06`, recent version on TL 2019 is `expl 3 2020-02-25`.

**Comment by NiranjanTambe** [comment]
Thank you for your help. Now I have the 2020 version which is giving me an error-less output, but still the problem with `baselinestretch` continues. See the two output files (example.pdf & nopolyglossia.pdf) attached by me in this zip.

[MWE2.zip](https://github.com/reutenauer/polyglossia/files/4480048/MWE2.zip)

Why is it happening?

**Comment by jspitz** [comment]
Can you please restate what (you think) the problem with baselinestretch is? I do not see anything obvious in the files.

**Comment by NiranjanTambe** [comment]
When I renew the `baselinestretch` in `nopolyglossia.tex` it is applied globally. Thus the spacing between the paragraph lines is also changed, but in example.tex only the distance between the chapter heading and the paragraph is changed according to the redefinition, space between the lines in a paragraph is still the default one. Isn't it a problem?

**Comment by jspitz** [comment]
I cannot reproduce. With the current version of your example file:
```tex
% !TeX TS-program = xelatex
\documentclass{book}
\usepackage{polyglossia}
\setdefaultlanguage{marathi}
\setmainfont[Script=Devanagari,Mapping=devanagarinumerals]{Noto Sans Devanagari}
\renewcommand{\baselinestretch}{5}

\begin{document}
	\chapter{नमस्कार}
	\begin{enumerate}
		\item नमस्कार
		\begin{enumerate}
			\item नमस्कार
			\begin{enumerate}
				\item नमस्कार
			\end{enumerate}
		\end{enumerate}
	\end{enumerate}
	नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. नमस्कार. 
\end{document}
```
I get this output: 
[example.pdf](https://github.com/reutenauer/polyglossia/files/4480907/example.pdf)

**Comment by jspitz** [comment]
Apart from that, of course (per your changes to the gloss file at c832f1aa97fbc) Marathi always resets the baselinestretch to `1.2` when the language is activated. This value is probably font-dependent. So instead of a hard-coded value, I'd add an option to change that (defaulting to `1.2`)

**Comment by NiranjanTambe** [comment]
> per your changes to the gloss file at c832f1a

Yes I agree, but that's what I said in my [question](url) -

> I've changed `baselinestretch` to 5 in gloss-marathi.ldf on line 143

As I've changed the value to 5 and selected default language Marathi, it should remain 5 everywhere. Of course you will get the correct output as you have added `\renewcommand{baselinestretch}{1.2}` in your preamble (that's what I've done in nopolyglossia.tex). Please understand that the reason for having a redefinition of `baselinestretch` in the ldf itself was Devanagari script always needs it and not every user is aware of these tiny details of typesetting. I wanted to set the `baselinestretch` globally so that every Marathi polyglossia user will get it automatically without having to learn much about it.

Now what can be done to set it globally? Please explain.

**Comment by jspitz** [comment]
A yes, right, setting `\baselineskip` this way does not work (it only works after a font change). Actually I have no idea what to do here (`\setstretch` only works in the preamble)

**Comment by NiranjanTambe** [comment]
What if we make this setting global? As I had initially planned redefinition of `baselinestretch` was not local (as it is right now). It was a global command affecting the text from other languages, but you [recommended](https://github.com/reutenauer/polyglossia/issues/370#issuecomment-565537127) me to make it local for the sake of multilingual documents. The problem is it looks really ugly when a Devanagari is written without extra `baselinestretch` as it has ligatures with more heights, but as far as I know English text written with some extra `baselinestretch` won't look "ugly", right? Correct me if I am wrong. If I am right at this then there is no harm in making this change global. It would make `baselinestretch` of all the text uniform even in your example of a multilingual document. Any thoughts?

**Comment by jspitz** [comment]
Actually I don't like at all the idea that `polyglossia` interferes with line spacing. As said, this is definitely depending on the selected font, but also taste, and I don't think we should hardwire a specific value that looks good with a specific font, even less so if it affects other scripts as well.

Maybe `fontspec` should provide an option to alter the line spacing of specific font families (for specific scripts). In any case, doing finger-painting with `polyglossia` here just doesn't look right.

**Comment by NiranjanTambe** [comment]
Okay. Thanks for helping me with the distribution issue :)

I am closing this ticket.

**Comment by jspitz** [comment]
@NiranjanTambe while I have your attention: Could you check whether Marathi works now with LuaLaTeX (with TeXLive 2020 and HarfBuzz)? Particularly, does the font render correctly in the output (see #337)? If you are able to audit any of the other languages listed there, your help would be greatly appreciated.

**Comment by NiranjanTambe** [comment]
It is still not working. I know Marathi, Sanskrit and Bengali. No need to mention Sanskrit separately, as it uses the same script (Devanagari). Same problems will arise for Sanskrit too. Please check this zip file.

[Marathi and Bengali.zip](https://github.com/reutenauer/polyglossia/files/4482342/Marathi.and.Bengali.zip)

**Comment by jspitz** [comment]
OK, many thanks for checking!

**Comment by NiranjanTambe** [comment]
Wait a minute. I think it is relatively better. If I remember correctly last time all the diacritics were typeset incorrectly. Now it is showing all the diacritics correctly, but there is problem with `्` this character for Bengali and Devanagari. This character triggers conjunction of two consonants.
