### ISSUE TITLE
LuaLaTeX does not support Devanagari numerals.

### ISSUE THREAD

**Issue by NiranjanTambe** [reutenauer/polyglossia#406]
When a Devanagari font is loaded with package `fontspec` with `[Renderer=Harfbuzz,Script=Devanagari,Mapping=devanagarinumerals]` options, `XeLaTeX` correctly replaces all the Arabic numbers to Devanagari ones. This is not happening with `LuaLaTeX` You can test it with a simple example.

```
\documentclass[12pt]{book}
\usepackage{polyglossia}
\setdefaultlanguage{marathi}
\setmainfont[Renderer=Harfbuzz,Script=Devanagari,Mapping=devanagarinumerals]{Shobhika}

\begin{document}
\chapter{चाचणी}
नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. नमस्कार हा देवनागरीत लिहिलेला मराठी मजकूर आहे. ह्यातील सर्व अक्षरे व्यवस्थित दिसत आहेत. 
\end{document}
```

**Comment by jspitz** [comment]
@wspr is this a fontspec issue?

**Comment by wspr** [comment]
No. `Mapping` is not supported in LuaTeX. Doesn't fontspec give a warning about that?

**Comment by jspitz** [comment]
Oh yes, it does. Thanks for clarification.
While I have your attention, could you briefly comment on the issue discussed at https://github.com/reutenauer/polyglossia/issues/337#issuecomment-614440563?

**Comment by NiranjanTambe** [comment]
@jspitz Can we do it in `gloss-marathi.ldf`?

**Comment by jspitz** [comment]
If LuaTeX does not support mapping, there is nothing we can do. We already have the `numerals` option for Marathi which outputs Devanagari numbers, but we cannot do mapping.

**Comment by wspr** [comment]
Well… you can probably do some LuaTeX magic to make it work. See section "Custom font features” in the fontspec manual for a toy example.

**Comment by reutenauer** [comment]
For sure @wspr, but I’d rather leave that to others as it isn’t really Polyglossia’s job :-)  If someone makes a TECKit equivalent in LuaTeX, it will hopefully be generic enough for fontspec to use.

@NiranjanTambe, I’m afraid that at this point your only choice is to use XeTeX if you want the `Mapping` option.
