### ISSUE TITLE
Missing command in code taken from babel

### ISSUE THREAD

**Issue by jbezos** [reutenauer/polyglossia#408]
Well, I'm not sure, but just in case. If it works for you with the development version of `babel` after recreating the formats, just ignore and close this issue.

I've created a couple of test files for `polyglossia` based on examples in Overleaf and the following error is now raised:

```
ty) (c:/ [snip] /polyglossia/babelsh.def
! Undefined control sequence.
\@initiate@active@char ...ime #1\fi \bbl@usehooks
```
It seems the code copied from `babel` missed that (which may have been working previously just by chance).

**Comment by jspitz** [comment]
I have not tested, but from reading the code the following seems needed:
```diff
diff --git a/tex/babelsh.def b/tex/babelsh.def
index 61c3e6d..a96a9e7 100644
--- a/tex/babelsh.def
+++ b/tex/babelsh.def
@@ -216,6 +216,22 @@
 %
 % ------------------------------------------------------------------------------
 %
+% lines 293 to 301 from babel.def
+%
+% ------------------------------------------------------------------------------
+%
+\def\bbl@usehooks#1#2{%
+  \def\bbl@elt##1{%
+    \bbl@cs{hk@##1}{\bbl@cs{ev@##1@#1@}#2}}%
+  \bbl@cs{ev@#1@}%
+  \ifx\languagename\@undefined\else % Test required for Plain (?)
+    \def\bbl@elt##1{%
+      \bbl@cs{hk@##1}{\bbl@cl{ev@##1@#1}#2}}%
+    \bbl@cl{ev@#1}%
+  \fi}
+%
+% ------------------------------------------------------------------------------
+%
 % lines 443 to 558 from babel.def
 %
 % ------------------------------------------------------------------------------

```

**Comment by jbezos** [comment]
I'm not sure, but very likely. Or define it to 'do nothing', or just remove the macro from the copied code.

**Comment by jspitz** [comment]
@jbezos can you test whether adding the above code fixes the issue in your test files?

For convenience, here is the changed babelsh.def file (zipped only to make github accept the upload):
[babelsh.zip](https://github.com/reutenauer/polyglossia/files/4498537/babelsh.zip)

**Comment by jbezos** [comment]
Now the undefined macro is `\bbl@cl`.

**Comment by jspitz** [comment]
OK, the we probably really use a void def:
```tex
\def\bbl@usehooks#1#2{}
```
does this work?

**Comment by jbezos** [comment]
Works for me. I created the test file by myself by copying randomly some examples from Overleaf to your test file. Let's cross the fingers.

**Comment by jspitz** [comment]
Thanks, Javier. I committed the fix.

Is there already an ETA for the respective babel release?

**Comment by jbezos** [comment]
In 8-10 days.

**Comment by jspitz** [comment]
OK, so we need to push a release as well by then, @reutenauer

**Comment by reutenauer** [comment]
I was planning to releasing sometimes soon anyway, thanks for pointing it out, and to Javier for the report.

**Comment by jspitz** [comment]
> I was planning to releasing sometimes soon anyway, thanks for pointing it out, and to Javier for the report.

Time to do that now? The respected babel release happened quite some time ago.

**Comment by jbezos** [comment]
Fortunately, I provided a dummy definition in `hyphen.cfg`. But it has to be eventually removed. So, yes, please, it's time to do it 🙂.
