### ISSUE TITLE
gloss-portuguese.ldf does not exist

### ISSUE THREAD

**Issue by jmigueldelgado** [reutenauer/polyglossia#412]
Hi. I am obtaining the following warning:
> Package polyglossia Warning: File gloss-portuguese.ldf does not exist!

In my texlive installation I can only see `gloss-portuges.ldf`. Unfortunately pandoc is looking for the right spelling `gloss-portuguese.ldf` when I set `lang: pt` in the preamble.

Is there a reason for the different spelling of the ldf file?

**Comment by jspitz** [comment]
portuges was the old name (inherited from babel). In current polyglossia, `gloss-portuguese.ldf` is the main file, `gloss-portuges.ldf` is only a portmanteau file that loads the former (for backwards compatibility reasons).

In any case, with a current release of polyglossia, you should have both:
```
juergen@linux-9zah:~> kpsewhich gloss-portuges.ldf
/usr/local/texlive/2020/texmf-dist/tex/latex/polyglossia/gloss-portuges.ldf

juergen@linux-9zah:~> kpsewhich gloss-portuges.ldf
/usr/local/texlive/2020/texmf-dist/tex/latex/polyglossia/gloss-portuges.ldf
```

**Comment by jspitz** [comment]
Closing this, as this seems to concern an older version of polyglossia and is fixed in current release.
