### ISSUE TITLE
Issue in beamer class with gloss-marathi.ldf.

### ISSUE THREAD

**Issue by NiranjanTambe** [reutenauer/polyglossia#414]
I had redefined `\labelitemii` in gloss-marathi.ldf, as very few Marathi fonts have that symbol. The redefinition of the same can be found from line 143-151 of `gloss-marathi.ldf` file. It needs to be removed as it gives error when used with `\documentclass{beamer}`. The error says `\labelitemii` is undefined. Hence I request that this redefinition gets removed.

**Comment by jspitz** [comment]
I meant you should provide a separate pull request (separate from the `\AuthAnds` definitions).

**Comment by NiranjanTambe** [comment]
Oops! My bad. Sorry for the noise here. I am closing this ticket.
