### ISSUE TITLE
Typo in Hindi

### ISSUE THREAD

**Issue by ajaysajay** [reutenauer/polyglossia#416]
While few Hindi typo are reported and fixed in #202, I encountered the following incorrect typo:

      \def\partname{खणड}%

Correct is:

      \def\partname{खण्ड}%

**Comment by reutenauer** [comment]
Thanks for the report!  It’s fixed in `master` and will be uploaded to CTAN shortly.

**Comment by ajaysajay** [comment]
Thank you... that was too fast!
