### ISSUE TITLE
gloss-bengali.ldf is corrupted

### ISSUE THREAD

**Issue by SharifMinhazul** [reutenauer/polyglossia#417]
I think the \bengalinumeral macro from file tex/gloss-bengali.ldf is not working. Consider this:
```
\documentclass[12pt]{memoir}
\usepackage{polyglossia}
\setmainlanguage[numerals=Bengali]{bengali}
\newfontfamily\bengalifont[Script=Bengali]{Kalpurush}

\begin{document}
\chapter{Hello}
\end{document}
```

This results in error 
```
/usr/share/texmf-dist/tex/latex/polyglossia/gloss-bengali.ldf:26: Undefined control sequence.
<argument> \str_lowercase:n 
                            Bengali
l.26 }
```
when I set option changecounternumbering=true I get bunch of more errors like this, as the options uses the \bengalinumeral several times.

Any idea what is happening wrong? Please look into the issue.

**Comment by jspitz** [comment]
The error indicates that your version of `expl3` is too old. Please try and update this package.

Also assure you do not have an outdated version of expl3 in your local tree.

Also see #383.

**Comment by SharifMinhazul** [comment]
Yes. It was backdated `exlp3`. In Arch Linux `texlive` in the repository is old. So, I thought I am updated. I didn't noticed that. I am sorry about that.
