### ISSUE TITLE
Polyglossia error with htlatex for Kannada language

### ISSUE THREAD

**Issue by diwakarshastri** [reutenauer/polyglossia#419]
Hello,
I am trying to use tex4ebook for Kannada book. I am getting the following error. I have tried on Windows with Miktex and on Ubuntu with TexLive. Initially, I got a similar error in windows, but for some unknown reason, I am getting a different error. 
[Example.zip](https://github.com/reutenauer/polyglossia/files/4640618/Example.zip)

I have attached the .tex and the screenshot of the error. 

I used the `tex4ebook -x kannada.tex`  command to convert the .tex to ebook format. I have also attached font Tunga.ttf which I have used in the document.

**Comment by jspitz** [comment]
I don't know why this does not work with `tex4ht` (might be a problem or limitation of `tex4ht`), but it seems to help to add the following line:
```tex
\newfontfamily\kannadafont[Script=Kannada]{Tunga}
```
At least compilation succeeds then.

**Comment by jspitz** [comment]
As to the problem I suggest you file a report at `tex4ht`'s tracker:
https://puszcza.gnu.org.ua/bugs/?group=tex4ht

It seems that the `Script` option in `\setmainfont` is not yet supported in `tex4ht` (at least the examples given by the package maintainer suggest that)

**Comment by jspitz** [comment]
@michal-h21 is the assumption correct that `tex4ht` currently does not consider the `Script` option of `polyglossia`'s `\setmainlanguage`/`\setdefaultlanguage` and `\setotherlanguage` but rather requires `fontspec`'s `\newfontfamily\<script>font`?

If so, is this worth a feature request at the `tex4ht` tracker?

**Comment by michal-h21** [comment]
@jspitz you are right, the `script` option didn't have an effect. I've just added the support to TeX4ht sources, so it should work after TL update.

**Comment by jspitz** [comment]
Cool, thanks @michal-h21.

**Comment by diwakarshastri** [comment]
@michal-h21 and @jspitz  Thank you for the update. Although now the book is compiling, I am still getting the same error at places where I have used tables.

**Comment by jspitz** [comment]
@diwakarshastri please report this to the tex4ht tracker.

**Comment by diwakarshastri** [comment]
@jspitz Ok thank you
