### ISSUE TITLE
bcp47 error present in version on CTAN

### ISSUE THREAD

**Issue by docum3nt** [reutenauer/polyglossia#420]
I just installed polyglossia 1.49 2020-04-08 from CTAN and it dies on

`! Package xkeyval Error: `bcp47' undefined in families `english'.`

while reading gloss-english.ldf _during installation_ (by processing polyglossia.dtx with xelatex.

**Comment by reutenauer** [comment]
Thanks for the report, I’ll look into that, but for curiosity’s sake, why do you install from CTAN?  TeX Live always has the latest CTAN version, with a delay of 24 hours at most.

**Comment by docum3nt** [comment]
Because I use texlive-full from Ubuntu and I don't use tlmgr because I tried once and it hopelessly screwed up my entire installation of TeX. On the very rare occasions I need an updated package, I unzip it into ~/texmf/tex/latex where I know it will be seen first by kpse. I'm not sure I even know how to extract and download a package from TL.

(you did ask :)

**Comment by docum3nt** [comment]
But it gets worse. I downloaded polyglossia-master.zip from here, unzipped it, and kept the tex tree which looked like the right bits (I have no idea what the rest of the stuff is for). Now I get this when I try to use xelatex on a document

`! LaTeX error: "kernel/invalid-variant"`

`! Variant form 'eeenn' invalid for base form
! '\polyglossia_ii_localnumeral:nnnnn'.`

at polyglossia.sty line 658.

Where do I get a working copy?

**Comment by docum3nt** [comment]
FYI, I did try to see if tlmgr worked, but it fails with

`(running on Debian, switching to user mode!)
/usr/bin/tlmgr: open(/home/peter/texmf/tlpkg/texlive.tlpdb) failed: No such file or directory at /usr/share/texlive/tlpkg/TeXLive/TLPDB.pm line 420.`

so basically it's non-functional.

**Comment by jspitz** [comment]
@reutenauer Isn't the problem here that we do not have a `polyglossia.ins` file that assures that the style files are generated first from the `dtx` before the documentation is being processed?

**Comment by jspitz** [comment]
@reutenauer a closer look revealed that the `makepolyglossiadtx.pl` script was buggy: `polyglossia.sty` and a bunch of other files (basically all `*.sty` and `*.def`) files where not added to the `dtx` at all due to the erroneous resetting of the list index.

I have fixes this at 69c33898b39b86

**Comment by jspitz** [comment]
There was another problem in the script that prevented successful compilation of `polyglossia.dtx`. Fixed at d3227eefb6d00.

This should now work as expected.

**Comment by jspitz** [comment]
So effectively the polyglossia package currently on CTAN is incomplete and dysfunctional. I wonder why all files are nonetheless there in TeXLive. Probably they pull the files from elsewhere.

In any case, this warrants a very quick release.

**Comment by docum3nt** [comment]
OTT I know, but I'm curious to know what bcp47 was. A checkpoint ID?

**Comment by jspitz** [comment]
`bcp47` is a new tag we introduced. It holds the language's `BCP47` identifier. See https://en.wikipedia.org/wiki/IETF_language_tag
In polyglossia, this allows you to use now `en_GB` instead of `[variant=british]{english}`

**Comment by reutenauer** [comment]
On Thu, Jun 04, 2020 at 06:13:50AM -0700, Jürgen Spitzmüller wrote:
> So effectively the polyglossia package currently on CTAN is incomplete and dysfunctional. I wonder why all files are nonetheless there in TeXLive. Probably they pull the files from elsewhere.

  From the .tds.zip file in the upload.  That’s been the case for years.

**Comment by jspitz** [comment]
I see. Forgot about that. OK, the the case is only critical for people getting polyglossia from CTAN directly.

**Comment by reutenauer** [comment]
Specifically, from people wanting to compile the DTX, of which I don’t think there are many.  I’ll remove it in the next upload, I’ve been wanting to do it for a very long time.

**Comment by jspitz** [comment]
The downside of the removal, of course, is that we pollute CTAN with hundreds of single files. And now the dtx works again.

**Comment by docum3nt** [comment]
Many thanks, I didn't know about the IETF adoption of the tags.

P
