### ISSUE TITLE
Polyglossia vs. Csquotes

### ISSUE THREAD

**Issue by DenMesh** [reutenauer/polyglossia#421]
```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{russian}
\setotherlanguage{english}
\defaultfontfeatures{Ligatures=TeX}

\setmainfont{Liberation Serif}
\setsansfont{Liberation Sans}
\setmonofont{Liberation Mono}

\usepackage{csquotes}
	\MakeOuterQuote{"}

\begin{document}

\enquote{в кавычках}% line 1

"ещё в кавычках"% line 2

\end{document}
```
Line 1 produces expected results; line 2 outputs two ". If I change the style (ex. using the style option for package) it correctly changes line 1 but still ignores line 2.

Polyglossia 2020/04/08 v1.49
Csquotes 2019-12-06 v5.2j

Log file attached
[debug.log](https://github.com/reutenauer/polyglossia/files/4656791/debug.log)

I first reported this behavior to the Csquotes issues josephwright/csquotes#44 , but was told it was Polyglossia overwriting Csquote's settings. Am I doing something wrong in the MWE or is this (somehow) intended behavior?

**Comment by jspitz** [comment]
You can't use `"` as active quote character with polyglossia language that feature `babelshorthands` (such as Russian), as this also activates the `"` char.

Long term, we need to find a way to only activate it if `babelshorthands` are actually used. But currently, this is not possible.

**Comment by DenMesh** [comment]
Can I manually disable babelshorthands then? Or somehow force csquote's activation over polyglossia's?

**Comment by jspitz** [comment]
You can remove or comment out the following block from gloss-russian.ldf:
```tex
\ifcsundef{initiate@active@char}{%
  \input{babelsh.def}%
  \initiate@active@char{"}%
  \shorthandoff{"}%
}{}
```

**Comment by jspitz** [comment]
Actually, the fix was easier than I thought. Fixed at af00c264a4c69 for next polyglossia version.

**Comment by jspitz** [comment]
The bug was that we used `\deactivate@char{"}` in `\noextras@russian` and friends unconditionally. This changed the active state that was set by `csquotes`.

Now we only do that if `babelshorthands=true`.

**Comment by DenMesh** [comment]
Manually updated the lines I needed and yep, works as a charm. Thanks!
