### ISSUE TITLE
Spurious spaces in Danish

### ISSUE THREAD

**Issue by Derek61** [reutenauer/polyglossia#424]
This is similar to #423. Consider
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguages{spanish,danish}

\begin{document}
A\textdanish{B}C
A\textspanish{B}C
\end{document}
```
The result is
![x](https://user-images.githubusercontent.com/887722/83552295-609f1000-a4be-11ea-80fb-8e0ab8ec4ed5.png)

**Comment by jspitz** [comment]
Thanks. Will be fixed in the next release.
