### ISSUE TITLE
Can we have hyphenrules back?

### ISSUE THREAD

**Issue by moewew** [reutenauer/polyglossia#427]
From https://github.com/plk/biblatex/issues/1015

It was never officially documented in the manual, but until recently `polyglossia` supported a `hyphenrules` environment to just switch the hyphenation patterns.

I'm guessing the environment was simply inherited from the bits of `babel` that were compiled into the LaTeX kernel, but that recent changes in https://github.com/latex3/babel/issues/57 removed `hyphenrules` from the format.

Can we have something that works like `hyphenrules` back, please?

MWE
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{german}

\begin{document}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}

\begin{hyphenrules}{german}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}
\end{hyphenrules}
\end{document}
```
compare with `babel`
```latex
\documentclass{article}

\usepackage[ngerman,english]{babel}

\begin{document}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}

\begin{hyphenrules}{german}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}
\end{hyphenrules}
\end{document}
```

**Comment by jspitz** [comment]
Please try with fc0ca6e.

As opposed to the removed `babel` environment, this now also features language options (varieties) and aliases (babel names, bcp47).
