### ISSUE TITLE
ttfamily in the chapter title of Korean language document

### ISSUE THREAD

**Issue by albert-github** [reutenauer/polyglossia#428]
Directly from texexchange: https://tex.stackexchange.com/questions/550407/ttfamily-in-the-chapter-title-of-korean-language-document

> When having a Korean document and we have `\ttfamily` in a `\chapter` (or other section command) we get an error in respect to etoolbox, and a crash on the line after the `\tableofcontents` (independent of what is after the `\tableofcontents`).
> 
> The MWE:
> ```
> \documentclass[twoside]{book}
> 
> \usepackage{polyglossia}
> \setdefaultlanguage{korean}
> \setmainfont{Noto Sans CJK KR}
> \setmonofont{Noto Sans CJK KR}
> \newfontfamily\hangulfont{Noto Sans CJK KR}
> \newfontfamily\hangulfonttt{Noto Sans CJK KR}
> \usepackage{sectsty}
> \allsectionsfont{%
>   \fontseries{bc}\selectfont%
> }
> 
> \usepackage[titles]{tocloft}
> \setcounter{tocdepth}{3}
> \setcounter{secnumdepth}{5}
> \usepackage{etoc}
> 
> \begin{document}
> 
> \tableofcontents
> Just some text
> 
> \chapter{\ttfamily 1}
> \end{document}
> ```
> when running `xelatex` twice over this MWE we get:
> ```
> Package polyglossia Warning: Failed to patch part for Korean on input line 22.
> 
> 
> ! Package etoolbox Error: Toggle 'korean@use@script@fonttt' undefined.
> 
> See the etoolbox package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...
> 
> l.22 J
>       ust some text
> ```
> which is in my opinion due to the result of the `\ttfamily` in the in the chapter title.

Comment from Ulrike Fischer:
> polyglossia redefines `\ttfamily` so that it is no longer robust and titletoc doesn't like this. Use `\protect\ttfamily`. And open an issue at the polyglossia bug tracker

**Comment by jspitz** [comment]
Inviting @dohyunkim

**Comment by jspitz** [comment]
I believe this is fixed with https://github.com/reutenauer/polyglossia/commit/6eb8e21ad9c4a5a7acce731faee82bf3e087511d

**Comment by jspitz** [comment]
It turns out this change was inappropriate. We need to use `\let` and robustify afterwards. Otherwise cases like the following (who use aliases for families) break:
```tex
\documentclass[a4paper,english,hebrew,numbers=noenddot]{scrarticle}

\usepackage{polyglossia}

\newfontfamily\hebrewfont[Script=Hebrew]{FreeSans}
\newfontfamily\hebrewfonttt[Script=Hebrew]{FreeSans}
\newfontfamily\hebrewfontsf[Script=Hebrew]{FreeSans}

\setdefaultlanguage{hebrew}
\setotherlanguage{english}


\begin{document}
\begin{hebrew}

\section{לכלכל}
שלום \textenglish[variant=american]{abcd}

\section{יחיח}\end{hebrew}

\end{document}
```

This yields:
```
Missing character: There is no י (U+05D9) in font [lmsans10-bold]:mapping=tex-t
ext;!
Missing character: There is no ח (U+05D7) in font [lmsans10-bold]:mapping=tex-t
ext;!
Missing character: There is no י (U+05D9) in font [lmsans10-bold]:mapping=tex-t
ext;!
Missing character: There is no ח (U+05D7) in font [lmsans10-bold]:mapping=tex-t
ext;!
```
