### ISSUE TITLE
\abjad  macro issue

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#431]
Hi, the result of `\alph` macro  which use `\abjad` command in arabic language is correct from 1 to 10 but with 11 the macro give `يا` but it supposed to give us `ك` 
The method to create the sequence come from https://en.wikipedia.org/wiki/Abjad_numerals but how if we need to create the consecutive arabic sequence like english from first letter of alphabet to the last like this 
`ا ب ج د ه‍ و ز ح ط ي ك ل م ن س ع ف ص ق ر ش ت ث خ ذ ض ظ غ `        

```latex
\documentclass{article}
\usepackage{pgffor}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\newcounter{foo}
\stepcounter{foo}

\foreach \i in {1,2,...,28}
{\alph{foo}\stepcounter{foo} }

\end{document}
```
**Result**

![image](https://user-images.githubusercontent.com/8249073/86488361-0fa26600-bd61-11ea-8eb7-0b96e7bf884f.png)

**Comment by jspitz** [comment]
So you want an optional numbering that just cycles the Arabic alphabet _in addition_ to the abjad numbering currently available, right?

Would you also call that abjad or is there anoher term common for this?

**Comment by seloumi** [comment]
The method used to create abjad sequence (see the link) is named "jumal" (جُمل) so may be this can  added  as option like this
`\setdefaultlanguage[jumal=true] {arabic}`The default is `jumal=false` which create cycle of Arabic sequence like with English `\alph` .

**Comment by jspitz** [comment]
Another questions: what happens with numbers > 28?

**Comment by seloumi** [comment]
Like in English error message "counter too large" if one will need more he can use `jumal=true`.

**Comment by jspitz** [comment]
Please try with https://github.com/reutenauer/polyglossia/commit/369dc96efe81ab428ee6effad707b6d0874f17e3. I did not change the definition of `\abjad` for backwards compatibility reasons, but I introduced a new macro `\abjadalph` for Arabic that should do what you want.

Please test. As I do not read Arabic, it is possible I screwed it up.

**Comment by seloumi** [comment]
This give the desired sequence  remains only how to redefine `\alph` with this new  `\abjadalph` in arabic context
Another thing the third letter `ج` it must be replaced with command `\abjad@three`  which take two forms depending on `abjadjimnotail`

```latex
\documentclass{article}
\usepackage{pgffor}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\makeatletter
\let\@alph\abjadalph
\let\@Alph\abjadalph
\makeatother

\newcounter{foo}
\stepcounter{foo}

\foreach \i in {1,2,...,28}
{\alph{foo}\stepcounter{foo} }

\end{document} 
```
![image](https://user-images.githubusercontent.com/8249073/86518398-1a78fb80-be32-11ea-827a-afcf730d14c5.png)

**Comment by jspitz** [comment]
> Another thing the third letter `ج` must be replaced with command `\abjad@three` which take two forms depending on `abjadjimnotail` option like in `\abjad` command.

This is done at https://github.com/reutenauer/polyglossia/commit/1b3482571a2b84c4bbadccd198c7b8ed886eec4c. Please verify.

**Comment by jspitz** [comment]
> This give the desired sequence remains only how to redefine `\alph` with this new `\abjadalph` in arabic context

I have added an option `abjadalph` at https://github.com/reutenauer/polyglossia/commit/2c28b6e1a332f7e6be2909191a27e11ffb575f4c

This defaults to false, and I won't change that for backwards compatibility reasons. But if you set it to true, you get the dsired behavior. Please test.

**Comment by seloumi** [comment]
Thanks this work fine 👍.
