### ISSUE TITLE
indentfirst adds newlines between bibliography items

### ISSUE THREAD

**Issue by matsievskiysv** [reutenauer/polyglossia#433]
`\setmainlanguage[indentfirst=true]{...}` adds newlines between bibliography items.

Minimal working example:
```latex
\documentclass[a4paper]{memoir}

\usepackage{polyglossia}

%%% Test options
% \setmainlanguage{russian} % No spaces
\setmainlanguage[indentfirst=true]{russian} % Extra spaces
%%%

\setotherlanguage{english}
\setmonofont{CMU Typewriter Text}
\newfontfamily\cyrillicfonttt{CMU Typewriter Text} \defaultfontfeatures{Ligatures=TeX}
\setmainfont{CMU Serif}
\newfontfamily\cyrillicfont{CMU Serif}
\setsansfont{CMU Sans Serif}
\newfontfamily\cyrillicfontsf{CMU Sans Serif}

\usepackage{csquotes}
\usepackage[%
backend=biber,%
bibencoding=utf8,%
sorting=none,%
style=gost-numeric,%
language=autobib,%
autolang=other,%
clearlang=true,%
defernumbers=true,%
sortcites=true,%
doi=false,%
isbn=false,%
]{biblatex}

\addbibresource{biblio.bib}

\DeclareSourcemap{ %
    \maps{%
        \map{%
            \step[fieldset=media, fieldvalue=text]
        }
    }
}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

Source files:
[mwe.zip](https://github.com/reutenauer/polyglossia/files/4897238/mwe.zip)

Build:
```bash
unzip mwe.zip
cd mwe
# build version without extra spaces
latexmk -pdflua -jobname=without source.tex
patch source.tex edit.patch
# build version with extra spaces
latexmk -pdflua -jobname=with source.tex
```

### with `indentfirst=true`

Red arrows indicate extra vertical space between bibliography items. There's about 10 extra newlines in this 200+ bibliography.

![image](https://user-images.githubusercontent.com/26824900/87047334-0b63c600-c203-11ea-9c75-c5e2584ec003.png)

### without `indentfirst=true`

There's no extra vertical space between bibliography items.

![image](https://user-images.githubusercontent.com/26824900/87047850-b2e0f880-c203-11ea-93d6-a253e80757df.png)

**Versions**

 - OS Linux 5.7.0-1-amd64 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux; Debian bullseye/sid
 - TeXLive [texlive-full 2020.20200629-1](https://packages.debian.org/bullseye/texlive-full)
 - polyglossia.sty 2020/04/08 v1.49

**Comment by jspitz** [comment]
Thanks, fixed for the next version.
