### ISSUE TITLE
language-specific customization of hyphenmin values

### ISSUE THREAD

**Issue by lemzwerg** [reutenauer/polyglossia#435]
By default, the German hyphenation patterns use
```
\lefthyphenmin=2
\righthyphenmin=2
```
However, it is quite common – and in most cases even highly recommended for texts that have not too short line lengths – to change those values to
```
\lefthyphenmin=3
\righthyphenmin=3
```
How can I set up that globally? Issue #148 is tagged as 'wontfix' – I don't know polyglossia well enough to have an educated opinion, but I would like to see an 'official' solution to this problem in the polyglossia manual, whatever it is.

**Comment by wehro** [comment]
``\renewcommand*{\germanhyphenmins}{33}``
(Taken from dehyph-exptl.doc, page 24).

**Comment by lemzwerg** [comment]
Well, since I'm one of the authors of 'dehyph-exptl', I know this very well :-)

You can't expect people interested in polyglossia expect to look up a completely different document...

**Comment by wehro** [comment]
That's right, but having this documented in `dehyph-exptl.pdf` is better than having it not documented at all.
I have already proposed to add this to polyglossia's documentation in #148, but @bastien-roucaries did object, so nothing happened.

**Comment by jspitz** [comment]
@wehro please add the documentation (otherwise I'll do it after my vacations)

**Comment by jspitz** [comment]
I went ahead and implemented a dedicated command, as suggested by @bastien-roucaries in https://github.com/reutenauer/polyglossia/issues/148#issuecomment-526920403:
```tex
\setlanghyphenmins[⟨options⟩]{⟨lang⟩}{⟨l⟩}{⟨r⟩}
```
This is not only clearer syntax, but contrary to `\⟨lang⟩hyphenmins`, it also
- supports restriction to language varieties (via `[⟨options⟩]`)
- supports the use of aliases (babelnames, BCP-47) in `{⟨lang⟩}`
- can be set repeatedly and at any time also in the document body

**Comment by lemzwerg** [comment]
Great, thanks!
