### ISSUE TITLE
\AtBeginDocument changed with recent updates 

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#438]
I have texlive 2020 on my pc, after updates I have noticed that  `\AtBeginDocument` produce unexpected result with right to left document (arabic), even if I specified the main language as arabic text inserted inside the command appear from left to right, same with font it is not used just after `\begin{document}`!

```latex
\documentclass[12pt]{article}
\usepackage{xcolor}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic,Color=red]{Amiri}

\AtBeginDocument{Text from right to left\par }
\begin{document}

Text from right to left

\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/91843975-ee71cf00-ec56-11ea-9dec-29c0a0dda0ad.png)

## Log file 

[test.log](https://github.com/reutenauer/polyglossia/files/5154823/test.log)

**Comment by jspitz** [comment]
This is by design. Poylglossia does language loading now `\AfterEndPreamble`, which is after any `\AtBeginDocument`. This is necessary to fix loading order problems such as #368.

This the following works:
```tex
\documentclass[12pt]{article}
\usepackage{xcolor}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic,Color=red]{Amiri}

\AfterEndPreamble{Text from right to left\par }
\begin{document}

Text from right to left

\end{document}
```
