### ISSUE TITLE
Hebrew: wrong placement of bracket and full-stop

### ISSUE THREAD

**Issue by ZvikaZ** [reutenauer/polyglossia#441]
Hi.

In older versions (two, or three, years ago) this issue hadn't occurred.
Now, with updated packages, in all Hebrew text, in some occasion the bracket `[`, or full-stop `.` are misplaced.

See MWEs:

	\documentclass[12pt]{article}

	\usepackage{polyglossia}
	\setdefaultlanguage{hebrew}	
	\setmainfont[Mapping=tex-text]{Times New Roman}

	\begin{document}
	% wrong: misplaced bracket:
	[א 1-2]

	% good: bracket in place:
	[א 1 2]
	\end{document}

And:

	\documentclass[12pt]{article}

	\usepackage{polyglossia}
	\setdefaultlanguage{hebrew}	
	\setmainfont[Mapping=tex-text]{Times New Roman}

	\begin{document}
	% wrong: misplaced full-stop:
	עמוד 1-2.

	% good: full-stop in place:
	עמוד 1 2.
	\end{document}

In all of these, the `[` and `.` should have been at the end of text, to the left.

Thanks

**Comment by jspitz** [comment]
Thanks for the report. This is the result of 6fc83e98983b4 which is needed to fix directionality of decimal numbers in Hebrew (see #401 for instance), but the fix was too brute.

This should be cured via 8c642fc94a657. Please verify if you can.

**Comment by ZvikaZ** [comment]
I've replaced `C:\Users\Zvika\AppData\Local\Programs\MiKTeX\tex\latex\polyglossia` with the updated `polyglossia\tex` 
It's indeed working, thanks.

Please update when the fix will be officially available, without need to such hacks...

**Comment by jspitz** [comment]
We'll close this ticket only if if the fixed version has been published, so you will be informed.
