### ISSUE TITLE
xpg@bloaded does not record \setotherlanguage

### ISSUE THREAD

**Issue by moewew** [reutenauer/polyglossia#443]
The following MWE
```latex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{italian}
\setotherlanguage{english}
\setotherlanguage{dutch}


\begin{document}
  \csmeaning{xpg@bloaded}
  \csmeaning{xpg@loaded}

  Lorem \textenglish{ipsum}.
  
  \csmeaning{xpg@bloaded}
  \csmeaning{xpg@loaded}
\end{document}
```
produces

> macro:->italian macro:->dutch,english,italian

for me.

Somehow it seems that only the `\setmainlanguage` is recorded in `xpg@bloaded`, but not the `\setotherlanguage` calls.

**Comment by jspitz** [comment]
Right. Same for `\xpg@bcp@loaded`. Should be fixed with https://github.com/reutenauer/polyglossia/commit/a6840405340d17adb5a3234d5fdc7cf0be7e8737.

**Comment by moewew** [comment]
Thanks for the quick fix! It seems to be working in all my tests now.

I'm a bit confused why the order of the languages in `xpg@bloaded` and `xpg@loaded` is different. Not that it matters of course.

**Comment by jspitz** [comment]
> I'm a bit confused why the order of the languages in `xpg@bloaded` and `xpg@loaded` is different. Not that it matters of course.

There was a redundant call to `\polyglossia@register@language:nn` at a point where the babelname was not yet accessible. I removed this call, now the order is conform.

**Comment by jspitz** [comment]
> There was a redundant call to `\polyglossia@register@language:nn` at a point where the babelname was not yet accessible. I removed this call, now the order is conform.

Note that this had to be reverted due to #461.
