### ISSUE TITLE
Invalid value of glyph node with LuaLaTeX

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#448]
The following document compiles without errors if you replace `\usepackage{polyglossia}` by `\usepackage{fontspec}` or if you use the default Latin Modern font instead of TeX Gyre Pagella.
But in the form shown below, the following error message is issued:

```
warning  (node filter): error: ...texlive/2020/texmf-dist/tex/luatex/nodetree/n
odetree.lua:343: bad argument #1 to 'char' (invalid value)
```

```
\documentclass{article}
\usepackage{polyglossia}
\usepackage{nodetree}
\setmainfont{TeX Gyre Pagella}

\begin{document}
\textsc{a}
\end{document}
```

I don't think this is a nodetree issue, because `polyglossia-punct.lua` complains about the same error if you load a language variant using it.
And I don't think this is an error of TeX Gyre Pagella, because the otf file on my system is from 2018.
So there is most likely something wrong with the polyglossia (Lua) code.

**Comment by jspitz** [comment]
The document compiles for me (this is with polyglossia 1.50dev, not 1.49 as indicated in the list)
```
*File List*
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
polyglossia.sty    2020/04/08 v1.49 Modern multilingual typesetting with XeLaTeX
 and LuaLaTeX
etoolbox.sty    2020/08/24 v2.5j e-TeX tools for LaTeX (JAW)
makecmds.sty    2009/09/03 v1.0a extra command making commands
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
fontspec.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2020-05-15 L3 Experimental document command parser
   expl3.sty    2020-09-24 L3 programming layer (loader) 
l3backend-luatex.def    2020-09-24 L3 backend support: PDF output (LuaTeX)
xparse-generic.tex
fontspec-luatex.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
fontspec.cfg
   iftex.sty    2020/03/06 v1.0d TeX engine tests
l3keys2e.sty    2020-05-15 LaTeX2e option processing using LaTeX3 keys
filehook.sty    2020/02/03 v0.7 Hooks for input files
luatexbase.sty    2015/10/04 v1.3 luatexbase interface to LuaTeX 
ctablestack.sty    2015/10/01 v1.0 Catcode table stable support
gloss-latex.ldf    polyglossia: module for default language
nodetree.sty    2020/05/29 v2.0 Visualize node lists in a tree view
nodetree.tex
kvoptions.sty    2019/11/29 v3.13 Key value format for package options (HO)
 ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
 ***********
```

Although the log has the following error message:
```
Module luatexbase Error: Attempt to use callback.register() directly
(luatexbase)             on input line 47

stack traceback:
	[C]: in function 'error'
	...ocal/texlive/2020/texmf-dist/tex/latex/base/ltluatex.lua:109: in upvalue 'mo
dule_error'
	...ocal/texlive/2020/texmf-dist/tex/latex/base/ltluatex.lua:116: in upvalue 'lu
atexbase_error'
	...ocal/texlive/2020/texmf-dist/tex/latex/base/ltluatex.lua:331: in function 'c
allback.register'
	...texlive/2020/texmf-dist/tex/luatex/nodetree/nodetree.lua:1409: in upvalue 'r
egister_callback'
	...texlive/2020/texmf-dist/tex/luatex/nodetree/nodetree.lua:1442: in function '
nodetree.register_callbacks'
	[\directlua]:1: in main chunk.
l.47 }
    
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.
```

Here's the log file: 
[448.log](https://github.com/reutenauer/polyglossia/files/5286423/448.log)

**Comment by jspitz** [comment]
Does look related to https://github.com/Josef-Friedrich/nodetree/issues/6

**Comment by wehro** [comment]
> The document compiles for me (this is with polyglossia 1.50dev, not 1.49 as indicated in the list)

My file list is exactly the same and I also use the most recent development version of `polyglossia.sty`. But I get the error message mentioned above.

> Does look related to [Josef-Friedrich/nodetree#6](https://github.com/Josef-Friedrich/nodetree/issues/6)

Yes, I think so.
If I use `\usepackage[luatexrenderer=Node]{polyglossia}` instead of `\usepackage{polyglossia}`, it works fine without errors or warnings.
So Harfbuzz is the the culprit, not polyglossia.
You may close.

**Comment by reportaman** [comment]
@wehro @jspitz "HarfBuzz is the culprit, not polyglossia"... FYI: In https://github.com/Josef-Friedrich/nodetree/issues/6, the conclusion isn't that HarfBuzz has any inherent/internal problem. The root of the problem is this: people have been using `.char` field of glyph nodes as if char is unicode codepoint, that worked because that might be true in some cases & scripts. Khaled recommends not using 'char' field, read this: https://github.com/Josef-Friedrich/nodetree/issues/6#issuecomment-697952744

**Comment by jspitz** [comment]
Thanks @reportaman. Since I am not very familiar with our Lua code, I let @wehro comment on whether this concerns our own use of `.char` in `polyglossia-punct.lua`

**Comment by reportaman** [comment]
@jspitz You are welcome.  @wehro  Retrieving true chars in HarfBuzz is very easy, with Node renderer is slightly convoluted. Please review https://github.com/Josef-Friedrich/nodetree/issues/6#issuecomment-699117954, and solution by Marcel on TeX.SE: https://tex.stackexchange.com/a/564164/192717

**Comment by wehro** [comment]
This issue is already solved, see #449.

**Comment by jspitz** [comment]
> This issue is already solved, see #449.

I thought that was just a workaround. Are we using `.char` properly?

**Comment by wehro** [comment]
@jspitz, I am sorry, I lost this issue from my mind.
You are right, the current solution is not entirely satisfactory.

Based on the advice given by Khaled Hosny I implemented the following code in the Lua module of babel-latin (look [the repository](https://github.com/wehro/babel-latin/blob/fd19844bb3178410f9ee31905bb2eeab18cb1efd/latin.dtx#L2009) for more context or try `texdoc babel-latin`):
```
%    We try to obtain the character of the current node from its property
%    table, which is the most reliable way as the same character may be
%    rendered by different glyphs with different code numbers.
%    \begin{macrocode}
                local char = get_property(current) and get_property(current).glyph_info
%    \end{macrocode}
%    If the |glyph_info| property is not available, we use the node's |char|
%    field to obtain the character, which is however only possible for numbers
%    up to 10FFFF\textsubscript{16}.
%    \begin{macrocode}
                if not char and current.char <= 0x10FFFF then
                    char = utf8.char(current.char)
                end
                local leftspace, rightspace
                if char then
                    leftspace  = left_space[char]
                    rightspace = right_space[char]
                end
```
This works as expected. That means the character is determind by `glyph_info` if the Harfbuzz renderer is used and by `utf8.char` in other cases.

I have tried to implement the same solution for polyglossia, but it did not work. Here is the diff for the file `polyglossia-punct.lua` which I tried, including some lines of code for testing purposes:
[diff.txt](https://github.com/reutenauer/polyglossia/files/7028009/diff.txt)

My test document was this one:
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[variant=ecclesiastic]{latin}

\begin{document}
abc:
\end{document}
```
Testing shows that the `get_property` function and its `glyph_info` field are not available, even if Harfbuzz is polyglossia’s default renderer. The character can only be determined by `utf8.char`. I don’t see the reason.
Can anyone please investigate?

**Comment by jspitz** [comment]
@dohyunkim can you help?

**Comment by dohyunkim** [comment]
As the line 331 of polyglossia-punct.lua shows:
```lua
            add_to_callback(callback_name, process, "polyglossia-punct.process", 1)
```
the function `process()` occupies the first position (because of the last argument `1`) before any other functions provided by other packages including luaotfload; so when `process()` is working, we have no `glyph_info` property yet which will be inserted much later by luaotfload-harf-plug.lua. 

I don't see what is the issue about the current implementation of polyglossia-punct.lua. The original MWE suggested by @wehro last year is now compiled without problem with up-to-date TeX Live 2021 distribution. @wehro, would you please provide another MWE that shows the issue?

**Comment by wehro** [comment]
Thank you for your comments, @dohyunkim.
You are obviously right. If I remove the last argument of the `add_to_callback` command, the `glyph_info` property is there. Possibly an implementation without this last argument `1` would be superior.

> I don't see what is the issue about the current implementation of polyglossia-punct.lua. The original MWE suggested by @wehro last year is now compiled without problem with up-to-date TeX Live 2021 distribution. @wehro, would you please provide another MWE that shows the issue?

I fear I can’t. Theoretically problems would occur if a character to be spaced (`:`, `!` and the like) would have a code number greater than 10FFFF(16).

**Comment by dohyunkim** [comment]
@wehro Yes, it's possible a character to have its `char` number > 0x10FFFF.  But, owing to the last argument `1` mentioned above, `process` function of polyglossia runs before the function of luaotfload and only at this later stage conversion of `char` number to the one greater than 0x10FFFF will occur.  As far as the `process` function is concerned, therefore, we need not worry about the out-of-range `char` number.

**Comment by dohyunkim** [comment]
> As far as the `process` function is concerned, therefore, we need not worry about the out-of-range `char` number.

Well, the only exception seems to be `\unhbox` or `\unhcopy` situation:
```latex
\setbox0\hbox{abc:} \unhbox0
```
In this case the character `:` can have its `char` number > 0x10FFFF (for instance when the font is `{Noto Sans CJK KR}[Script=Hangul, Language=Korean]`).  But as we now check the range of number at line 237:
```lua
                  if current.char <= 0x10FFFF then 
```
the remainder of the code will be skipped and we are still safe. In this case the space between `c` and `:` inserted by polyglossia at the earlier stage of `hpack_filter` callback is preserved intact.

**Comment by wehro** [comment]
OK, so we can leave everything as is.
Thank you, @dohyunkim.
