### ISSUE TITLE
Please release new version to CTAN

### ISSUE THREAD

**Issue by LSinev** [reutenauer/polyglossia#450]
There are plenty of issues [FIXED IN DEV](https://github.com/reutenauer/polyglossia/issues?q=is%3Aopen+label%3A%22FIXED+IN+DEV%22) for half a year passed since the previous release. Can you please update the CTAN version for users to update their installations in the usual manner?

**Comment by jspitz** [comment]
We'll release as soon as we can (@reutenauer who is doing the relase is currently busy).
