### ISSUE TITLE
shorthandoff/shorthandon don't work inside a custom environment

### ISSUE THREAD

**Issue by intractabilis** [reutenauer/polyglossia#451]
The code below produces `Argument of \language@active@arg" has an extra }` error. It works if `\begin{newenv}/\end{newenv}` are removed.

```LaTeX
\documentclass[12pt, letterpaper]{scrbook}

\usepackage{polyglossia}
\usepackage{tikz}
\usepackage{xparse}

\setdefaultlanguage[babelshorthands = true]{russian}
\SetLanguageKeys{russian}{
    hyphenmins  = {2, 2}
  , indentfirst = true
  }

\setmainfont{FreeSerif}
\newfontfamily\cyrillicfont{FreeSerif}
\setsansfont{FreeSans}
\newfontfamily\cyrillicfontsf{FreeSans}
\setmonofont{FreeMono}
\newfontfamily\cyrillicfontmono{FreeMono}

\KOMAoptions{fontsize = 12, BCOR = 8.25mm}
\KOMAoptions{DIV = 14}

\usetikzlibrary{quotes}

\NewDocumentEnvironment{newenv}{+b}{\par #1}{\par}

\begin{document}
    \begin{newenv}
        \shorthandoff{"}
        \tikz \draw (0,0) edge ["left", ->] (2,0);
        \shorthandon{"}
    \end{newenv}
\end{document}
```

**Comment by jbezos** [comment]
`b` first collects the body and then executes it. Once collected, catcodes cannot be changed, which means `\shorthandoff{"}` must be placed before the environment.

**Comment by intractabilis** [comment]
That sounds like a guillotine to cure headache. An environment can have thousands lines of real text that uses shorthand codes besides `\tikz`.

**Comment by jspitz** [comment]
> `b` first collects the body and then executes it. Once collected, catcodes cannot be changed, which means `\shorthandoff{"}` must be placed before the environment.

So nothing we can do.

**Comment by josephwright** [comment]
@intractabilis In general an environment is exactly right for long blocks of content, where catcode changes might be needed. However, the moment you use a `b`-type argument to grab the tokens up-front, you are necessarily tokenizing them. This is useful for some cases, for example where you want to turn an environment into a macro argument. But it's likely inappropriate for a longer block, catcode changes or not. You don't say why you are collecting tokens: as it stands, it's hard to give more advice.

**Comment by eg9** [comment]
You might use `\par\scantokens{#1}\par`. But the doubt on the usefulness of the `b` argument type remains.
