### ISSUE TITLE
Clash with bidi/filehook/quran

### ISSUE THREAD

**Issue by Shubbak** [reutenauer/polyglossia#453]
Hi there!
I had a beautifully working German and Arabic document using XeLaTeX and polyglossia.
On the 12. october I updated all my packages using MikTeX.
When I then compiled my document it didn't work anymore.

This is the original preambel (which used to work)

    \documentclass[12pt,a4paper]{article}
    
    \usepackage{fontspec}
    
    \usepackage{polyglossia}
    \usepackage{amsmath}
    \usepackage{amsfonts}
    \usepackage{amssymb}
    \usepackage{eurosym}
    \usepackage{wasysym}
    \usepackage{enumitem}
    \usepackage[
	colorlinks=true,
	linkcolor=blue,
	citecolor=cyan
    ]{hyperref}
    \usepackage{graphicx}
    \usepackage[
	left=2cm,
	right=2cm,
	top=2cm,
	bottom=2cm
    ]{geometry}
    \usepackage[uthmani, nopar, transde]{quran}
    
    \setlength\parindent{0pt}
    
    \renewcommand\LayoutCheckField[2]{#1#2}
    \fboxsep=0pt
    
    \setdefaultlanguage{german}
    \setotherlanguage[numerals=mashriq]{arabic}
    \newfontfamily\arabicfont[Script=Arabic,Mapping=arabicdigits]{Amiri}
    
    \newcommand{\Allah}{Allah \textarabic{\char"FDFB} \textarabic{الله}}
    \newcommand{\Prophet}{Prophet \textarabic{رسول الله \char"FDFA}}

This gives me the following errors now after the update: `! Package polyglossia Error: right-to-left, but (lua)bidi package was not loaded!.`
Here's the log-file:

[log_file_issue_polyglossia1.log](https://github.com/reutenauer/polyglossia/files/5391186/log_file_issue_polyglossia1.log)

I then loaded `bidi` before polyglossia and then lotsw of errors popped up, here's the log:

[log_file_issue_polyglossia2.log](https://github.com/reutenauer/polyglossia/files/5391164/log_file_issue_polyglossia2.log)

All those errors are (according to TeXMaker) in polyglossia.sty

I then tried compiling another document that also had previously worked beautifully and the same errors came.

Help?

**Comment by jspitz** [comment]
Please upload a complete minimal example file (not only the preamble).

**Comment by jspitz** [comment]
Hm it looks like the `filehooks` package is broken again.

`\AtEndOfPackageFile*{bidi}{...}` is not executed. Maybe we should try the now new LaTeX core hooks.

**Comment by Shubbak** [comment]
[Documents.zip](https://github.com/reutenauer/polyglossia/files/5392629/Documents.zip)


Here's a different document that is only arabic. It's smaller and more tidy. The same error occurs as well (though I didn't try anything to fix it like loading `bibi` or something, just checked if it compiles or not.)

**Comment by Shubbak** [comment]
Interesting!
I just found that it may have something to do with the Quran Package.
I compiled an old document that did not need the quran package but did indeed have arabic in it and it worked. In this same document I loaded the quran package and used it for test and indeed: The error popped up.
@javadr maybe look into it?

**Comment by jspitz** [comment]
Maybe a clash of the `quran` and `filehook` packages then.

In any case, as of 4442b778 we got rid of the `filehook` package and use the new core hooks of LaTeX instead. This works with your testcases.

**Comment by Shubbak** [comment]
Awesome, thank you! Any idea when we might expect the update in the CTAN? Or how else could we download it?

**Comment by jspitz** [comment]
Since we just had a release and this only seems to happen with specific package combinations, the new release might take some time (unless more people are hit by it). But you can simply download and replace locally the file [polyglossia.sty](https://github.com/reutenauer/polyglossia/raw/master/tex/polyglossia.sty) from this repository.

It would be good if you could test this and report back if it works for you.

**Comment by Shubbak** [comment]
It worked! Thank you very much!

**Comment by jspitz** [comment]
Great, thanks for testing
