### ISSUE TITLE
Croatian: splithyphens

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#454]
Hi, I am not sure what is actually done about this request for Czech (https://github.com/reutenauer/polyglossia/issues/32):
> 3. if there is a hyphen in the word to be split, there has to be a hyphen at the end of the line and a second one on the begining of the next line. For example: "matematicko-fyzikalni" -> "matematicko-\n-fyzikalni"

The same rule holds in Croatian (based on Croatian Orthography by IHJJ - The Institute of Croatian Language and Linguistics):
https://pravopis.hr/pravilo/spojnica/68/

> 6. Treba izbjegavati rastavljanje stranih riječi i imena, složenih kratica (dipl. ing., d. o. o.), složenih pokrata (CD-RW), mrežnih adresa i riječi koje se pišu sa spojnicom. Ako se riječi koje se pišu sa spojnicom ipak prenose u novi redak, spojnica se zapisuje i na početku novoga retka:
> hrvatsko-
> -engleski rječnik.

Whatever is done for the Czech, can the same be replicated for Croatian? Thanks.

**Comment by jspitz** [comment]
This feature is described in the `polyglossia` manual, Czech and Slovak sections.

Please read that and tell us (1.) if you need only `splithyphens` or also `vlna` and (2.) if these options should be on by default (or opt-in) for Croatian.

**Comment by ivankokan** [comment]
1. `splithyphens` only
2. on by default

Once it becomes available, would there be any changes in suppressing hyphenation, e.g. for `CD-RW`?

Side comment: I think that four available shorthands for quotation marks are aligned with https://github.com/josephwright/csquotes/pull/46. Can you please verify?

**Comment by ivankokan** [comment]
> 1. `splithyphens` only
> 2. on by default
> 
> Once it becomes available, would there be any changes in suppressing hyphenation, e.g. for `CD-RW`?
> 
> Side comment: I think that four available shorthands for quotation marks are aligned with [josephwright/csquotes#46](https://github.com/josephwright/csquotes/pull/46). Can you please verify?

https://github.com/reutenauer/polyglossia/issues/32#issuecomment-724553787
=> off by default

**Comment by jspitz** [comment]
Implemented. I noted that we enable `splithyphens` by default nowadays in Slovak and Czech, so I did that for Croatian as well.

Testing appreciated.

**Comment by jspitz** [comment]
> Once it becomes available, would there be any changes in suppressing hyphenation, e.g. for `CD-RW`?

Use babelshorthands: `CD"~RW`

> Side comment: I think that four available shorthands for quotation marks are aligned with [josephwright/csquotes#46](https://github.com/josephwright/csquotes/pull/46). Can you please verify?

I don't understand what you mean with "aligned with".

**Comment by ivankokan** [comment]
I will test and provide feedback.

"aligned with" = "the same glyphs are being used in both"

**Comment by jspitz** [comment]
The shorthands are aligned with babel, and I think we shouldn't change that (if a shorthand for another quotation mark is needed, we can add it though)
