### ISSUE TITLE
don't fake babel if you don't emulate all the user commands

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#455]
I just run into an error as polyglossia "fakes" babel:

~~~~
%% This is for compatibility with Babel-aware package:
\cslet{ver@babel.sty}{\@empty} % this "fakes" babel
~~~~

This means that a quite standard test to add conditional code failed:

~~~~
\documentclass{article}
\usepackage{polyglossia}

\makeatletter
\@ifpackageloaded{babel}{%
  \AddBabelHook{test}{afterextras}{}}{}
\makeatletter
\begin{document}
abc
\end{document}
~~~~

Please don't do this. If you provide a real emulation of all babel user commands, then ok. But a sort of one-third babel with some commands working and other not only make life for package authors difficult. I don't want to have to double check if babel loaded means really loaded or not.

**Comment by jspitz** [comment]
I don't know why this was added in the first place. @reutenauer?

**Comment by jspitz** [comment]
FWIW this line has been part of the [initial commit](https://github.com/reutenauer/polyglossia/commit/56d63f2b9a8d3b5578863a078544dd8436021850) to this repo, so it has probably been there from the starts.

**Comment by jspitz** [comment]
@reutenauer should we just remove that line and see what happens?

**Comment by reutenauer** [comment]
Sure, I suppose so ...

**Comment by jspitz** [comment]
OK, done.
