### ISSUE TITLE
Albanian: wrong \contentsname?

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#456]
https://github.com/latex3/babel/issues/104#issue-730754062

**Comment by jspitz** [comment]
Please keep us informed what is decided at `babel`.

**Comment by ivankokan** [comment]
> Please keep us informed what is decided at `babel`.

It seems that `babel-albanian` is now fixed.

**Comment by jspitz** [comment]
Good. Fixed in polyglossia as well.

**Comment by ivankokan** [comment]
I do not speak Albanian, so here is a bit of proof: http://qsa.edu.al/site/images/Manjola%20Xhaferri.pdf.

**Comment by reutenauer** [comment]
I had it confirmed independently by a native Albanian speaker.

**Comment by jspitz** [comment]
Thanks for checking.
