### ISSUE TITLE
Wrong part name when selecting french and then english

### ISSUE THREAD

**Issue by Karamaz0V1** [reutenauer/polyglossia#458]
Hi,

there is a strange behavior of polyglossia with french and `\partname` producing part names such as "Part Première partie". This happens when switching from french to english with `\selectlanguage{english}`.

Perhaps this part needs to be changed:
https://github.com/reutenauer/polyglossia/blob/c4dfb8de4a57575422f6eb33ff4e6993172fe7f4/tex/gloss-french.ldf#L329-L335

I see two alternatives:

1. Set back `\thepart` to default when switching back to english (e.g. `\def\thepart{\Roman{part}}`)
2. Maybe remove completely this definition, since it also breaks the default `\tableofcontents` with numbers replaced by long names

**Comment by jspitz** [comment]
Should be fixed at https://github.com/reutenauer/polyglossia/commit/9a93f0fb113cd770bed042f723a7aa17e4a29e9c
