### ISSUE TITLE
Hebrew: additional space after switching to language

### ISSUE THREAD

**Issue by Pavel-Rychetsky** [reutenauer/polyglossia#459]
There is missing % at the end of line 118 at gloss-hebrew.ldf.

Should be:
       \renewcommand*{\DigitsDotDashInterCharToks}{}%
instead of
       \renewcommand*{\DigitsDotDashInterCharToks}{}

Currently it results in extra space when \texthebrew command is used.

**Comment by jspitz** [comment]
Thanks, fixed.
