### ISSUE TITLE
Wrong link in About section

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#460]
![image](https://user-images.githubusercontent.com/1058211/98602289-82f44f80-22e0-11eb-86a7-cfbbc9021145.png)

www.ctan.org/pkg/polyglossia should be used instead

**Comment by jspitz** [comment]
Only @reutenauer can change that.

**Comment by reutenauer** [comment]
I've just done so, thanks for the suggestion.  I've also changed the phrase "Babel replacement" to "alternative to Babel" to match what I've used in other places.
