### ISSUE TITLE
Default language is not immediately added to \xpg@loaded, breaks other packages

### ISSUE THREAD

**Issue by no-preserve-root** [reutenauer/polyglossia#461]
Polyglossia does not record the default language to `\xpg@loaded` prior to `\begin{document}`. This breaks the e.g. the `tracklang` package (and therefore `glossaries`) that relies on `\xpg@loaded` during package loading to detect the document languages. Variant recording works correctly. Commit 6fec81a appears to be responsible at first glance.

### MWE

```latex
% !TeX program = lualatex
\documentclass{minimal}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\makeatletter
\edef\loaded{\xpg@loaded}
\edef\vloaded{\xpg@vloaded}
\begin{document}
    ``\loaded{}'' is not ``\xpg@loaded{}''
    
    ``\vloaded{}'' is ``\xpg@vloaded{}``
\end{document}
```

### Expected Output

> “english” is not “english”
> “us” is “us“

### Actual Output

> “” is not “english”
> “us” is “us“

**Comment by jspitz** [comment]
Thanks, I reverted 6fec81a which was cosmetic only anyway.

**Comment by no-preserve-root** [comment]
Issue appears fixed in current master, thanks!
