### ISSUE TITLE
Switching hyphenation language, leaving the rest as it is

### ISSUE THREAD

**Issue by marc456** [reutenauer/polyglossia#462]
Issue: Polyglossia does not seem to offer a way to switch temporarily the hyphenation language, leaving all the other language settings untouched.

I am writing a French text and polyglossia sets the punctuation spacing accordingly. For instance, an opening guillemot quote is followed by a space.

I want to hyphenate foreign words in the text, but when I use the command `\text<lang>{...}`, it changes also the punctuation spacing. I would like to keep the “French” spacing all along, even with foreign words.

MWE:

```
\documentclass{article}
\usepackage{fontspec,showframe,polyglossia}
\setdefaultlanguage{french}
\setotherlanguage{german}

\begin{document}
\Huge
Voici du «texte»! «Weltanschauung!»
\textit{Mind the punctuation spacing.}\bigskip

Voici du «texte»! \textgerman{«Weltanschauung!»}
Use of \verb+\textgerman+.
\textit{The german word is correctly hyphenated but the punctuation spacing changed.}
\end{document}
```

![Screenshot_20201118_211245](https://user-images.githubusercontent.com/74682216/99582766-dc483700-29e2-11eb-9c14-2742f1ee72c7.png)

**Comment by jspitz** [comment]
Well, the `hyphenrules` environment is supposed to do this (as of polyglossia 1.50). With LuaTeX, this works:
```tex
% !TeX TS-program = lualatex
\documentclass{article}
\usepackage{fontspec,showframe,polyglossia}
\setdefaultlanguage{french}
\setotherlanguage{german}

\begin{document}
\Huge
Voici du «texte»! «Weltanschauung!»
\textit{Mind the punctuation spacing.}\bigskip

Voici du «texte»! \begin{hyphenrules}{german}«Weltanschauung!»\end{hyphenrules}
Use of \verb+\textgerman+.
\end{document}
```
![grafik](https://user-images.githubusercontent.com/4538783/99630137-a08c8c00-2a39-11eb-9cde-830c9f9ede86.png)

In this particular case, also the following works (with LuaTeX) and is probably a bit more convenient:
```tex
Voici du «texte»! «\textgerman{Weltanschauung}!»
```

**However,** it does not work with XeLaTeX. The reason, I think, is that the guillemets tracking mechanism in XeLaTeX (the adding of a non-breakable thin space) messes up hyphenation.

It seems the following change (in `gloss-french`) would fix that:
```diff
-\def\xpg@french@thinsp{\kern 0.5\fontdimen2\font}
+\def\xpg@french@thinsp{\,\nobreak\hskip\z@skip}
```

@wehro what do you think?

**Comment by jspitz** [comment]
Sorry, change should be
```diff
-\def\xpg@french@thinsp{\kern 0.5\fontdimen2\font}
+\def\xpg@french@thinsp{\kern 0.5\fontdimen2\font\nobreak\hskip\z@skip}
```
to preserve the larger spacing introduced with https://github.com/reutenauer/polyglossia/commit/f4e1f70a75d69d02a9246dd0551ff8c31bea55ad

**Comment by marc456** [comment]
Thanks a lot jspitz. Of course for a single word, as in the example, it would be simpler to write something like `«\textgerman{Weltanschauung}!»`. In the real document, however, there are full sentences in multiple languages, with quotes, colons, semicolons, question marks, and so on. I can't close and reopen the `\text<lang>` command everytime I come accross a punctuation sign.

Using the `hyphenrules` environment seems to be the right solution. I tried before and I gave up, because I was using polyglossia 1.49, and the environment was undefined. I thought it was deprecated*. However, I just tried with polyglossia 1.50a, and it works.

(And please, in the future, don't deprecate the _hyphenrules_ environment!)

Thanks again!

* https://tex.stackexchange.com/questions/550978/

**Comment by jspitz** [comment]
Actually, `hyphenrules` was never officially supported before 1.50 (it only worked by coincidence and then broke eventually). So it also was never deprecated. It just ceased to work.

Now that it is supported, we have no reasons to deprecate it.
