### ISSUE TITLE
Greek hyphenation orphans combining accents

### ISSUE THREAD

**Issue by Davislor** [reutenauer/polyglossia#463]
While I was writing a package to convert Greek beta code to Unicode, I discovered that hyphenation does not work correctly for decomposed characters.  The hyphenation algorithm will happily insert a hyphenation point between a base character and its combining accents, leaving the accents orphaned in the margin of the next line.

```
\documentclass{article}
\usepackage{polyglossia}

\setdefaultlanguage[variant=ancient]{greek}

\setmainfont{Libertinus Serif}[Ligatures={Common, Discretionary}, Script=Greek]
\pagestyle{empty}

\begin{document}
\parbox{0pt}{
Hyphenate: % The first word in a paragraph is unhyphenated.
^^^^1faf^^^^03a9^^^^0314^^^^0342^^^^0345
}
\end{document}
```
![hyphtest2](https://user-images.githubusercontent.com/23533519/99784950-6242ab80-2ad1-11eb-8bda-df9e75ebd771.png)

I was able to work around this by having my algorithm convert all characters to precomposed NFC form, but this violates the requirement of [the Unicode standard](https://www.unicode.org/reports/tr15/#Canon_Compat_Equivalence) that all canonically-equivalent characters have the same display and behavior.  Hyphenation should really be disabled before any Unicode combining character, at least by default.

There is a similar bug in Babel, if it makes you feel any better!

**Comment by reutenauer** [comment]
Closing as this is not a Polyglossia issue; [the issue](/hyphenation/tex-hyphen/issues/5) you contributed to on TeX-hyphen will take care of Babel and Polyglossia simultaneously.  If it’s ever solved ...

Note that there is no requirement in Unicode that equivalent sequences be treated the same; it’s simply different mappings Unicode provides.  The only normative requirement is [rule C6](https://www.unicode.org/versions/Unicode13.0.0/ch03.pdf#page=10): A process shall not assume that the interpretations of two canonical-equivalent character sequences are distinct.  That’s obviously an encouragement to treating them the same, but not a requirement.

**Comment by Davislor** [comment]
Unfortunately, reutenauer said not to expect this to be fixed soon.

I think I could lawyer the Unicode standard if we felt like it (in particular, canonical equivalence is now incorporated into section 3.11), but it isn’t really necessary.  I don’t believe anyone seriously disputes that this is a bug.

**Comment by Davislor** [comment]
In the interim, would it be possible to fix the hyphenation patterns? There are about a dozen accents to check for in ancient Greek.

**Comment by jspitz** [comment]
Note that the hyphenation patterns are not under `polyglossia`'s control, so this is not the right place to discuss this.
