### ISSUE TITLE
es-ES an es-MX localizations are the same

### ISSUE THREAD

**Issue by miguescri** [reutenauer/polyglossia#464]
It seems that, even though it is possible to differentiate between `es-ES` and `es-MX` locales, the actual content of both is the same.

I realized that because my tables are refered as "Cuadro", which is not correct in `es-ES`; they should be "Tabla". Maybe there are more differences, but I have not seen them yet.

https://github.com/reutenauer/polyglossia/blob/7cb185c49c722479faad02d0ea333f13706f40d1/tex/gloss-spanish.ldf#L181

**Comment by jbezos** [comment]
@miguescri ‘Table’ is not wrong. On the contrary, see http://www.texnia.com/spanish2.html .

**Comment by jspitz** [comment]
`\tablename` is "Cuadro" in es-ES, "Tabla" in es-MX. That's the only difference currently.

Be invited to propose improvements.

**Comment by jbezos** [comment]
@jspitz 

> `\tablename` is "Cuadro" in es-ES, "Tabla" in es-MX.

Exactly.

**Comment by jspitz** [comment]
And here is the proof:
```tex
% !TeX TS-program = xelatex
\documentclass{minimal}
\usepackage{polyglossia}
\setmainlanguage{spanish}

\begin{document}
	es-ES: \tablename
	
	\selectlanguage[variant=mexican]{spanish}
	es-MX: \tablename
\end{document}
```

![grafik](https://user-images.githubusercontent.com/4538783/100193798-c65fd800-2ef4-11eb-843c-429e6f6cbb9f.png)

**Comment by miguescri** [comment]
My bad. I was laking knowledge both on my own language and in how to read this codebase.

Sorry for wasting your time.
