### ISSUE TITLE
Hooks for NFSS family selecting commands

### ISSUE THREAD

**Issue by h-kitagawa** [reutenauer/polyglossia#471]
Hello, 
LaTeX2e 2020-10-01 provides hooks for NFSS font commands, such as "`rmfamily`" hook for `\rmfamily` (similar for `\sffamily` and `\ttfamily`).
But it seems that these hooks are never executed after `\begin{document}`, when the polyglossia package is loaded.

Example:
```
%#! lualatex
\documentclass{minimal}
\usepackage{fontspec}
\usepackage{polyglossia} % polyglossia 2020/12/08 v1.51
\AddToHook{sffamily}{\typeout{>SF}}
\sffamily % ==> ">SF"
\begin{document}
a\textsf{b}{\sffamily c}
% ==> two ">SF"  only if the polyglossia package is not loaded
\end{document}
```

**Comment by riumutu** [comment]
Specifically this causes incompatibility with Japanese LuaLaTeX (luatexja) package.
According to the developer, it uses the hook for managing fonts for both latin and CJK scripts at once.
Is it possible to modify the polyglossia package to avoid this issue, or are there any other remedies?

**Comment by jspitz** [comment]
Can you please try after c3ac5db98d8ed78?

**Comment by h-kitagawa** [comment]
https://github.com/reutenauer/polyglossia/commit/c3ac5db98d8ed78aefb355253178aa05ab952188 works as expected. Thank you.

**Comment by jspitz** [comment]
Thanks for confirming. Please leave open until this version is released.
