### ISSUE TITLE
No tags for v1.50 and v1.51 releases

### ISSUE THREAD

**Issue by jfbu** [reutenauer/polyglossia#472]
Investigating some issue I see at my updated TeXLive 2020 (2021/02/07) that the version is 

```
Package: polyglossia 2020/12/08 v1.51 Modern multilingual typesetting with XeLaT
eX and LuaLaTeX
```

Opening the manual, I see that the `luatexrenderer` option was introduced at `v1.50`. But I can't know at which date because it seems this repo has no `v1.50` tag or release. Knowing the date would be useful to me...

Also I don't know if `v1.51` is released, but the version string above seems to say so.

By the way the github address is nowhere to be found in the manual but I managed :-) )

**Comment by jspitz** [comment]
I have added those tags now.
