### ISSUE TITLE
Copying pasting or search in PDF of ascii strings from operator names may fail with v1.51 (HarfBuzz related issue)

### ISSUE THREAD

**Issue by jfbu** [reutenauer/polyglossia#473]
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}

\setmainfont{TeX Gyre Termes}

\begin{document}

$\cos x, \sin y, \tan z$

\end{document}
```

when copying pasting from PDF one gets ``􏰒􏰓􏰔x,􏰔􏰆􏰇y,􏰕􏰖􏰇z`` (PDF viewed in Skim.app on mac os x).

Also searching for the string `cos` does not find it.

With TeXLive 2019 it was otherwise. Caused by the ``Renderer=HarfBuzz`` default.

**Comment by jfbu** [comment]
Forgot to say this is with lualatex !!!!

**Comment by jfbu** [comment]
Relates https://github.com/sphinx-doc/sphinx/issues/8846 and possibly https://github.com/latex3/luaotfload/issues/176

**Comment by jspitz** [comment]
So rather an upstream bug.
For the time being, you can locally change the `luatexrenderer`.
