### ISSUE TITLE
Add Changelog.tex to documentation

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#476]
On behalf of @lemzwerg:

“Running

    xelatex polyglossia.dtx

also produces a file `Changelog.tex`.  I suggest to rename this to `Changelog` (or `ChangeLog`; it is a plain-text file) and put it into polyglossia's `doc` folder.

A better solution IMHO would be to integrate the package history into the polyglossia manual as an appendix, but this is up to Arthur :-)”

See https://tug.org/pipermail/tex-live/2021-February/046475.html

**Comment by jspitz** [comment]
I agree we should simply add it to the manual and ditch the changelog txt file.

What's your take, Arthur?

**Comment by reutenauer** [comment]
Agreed :-)

**Comment by jspitz** [comment]
Done. Quite a list.
