### ISSUE TITLE
Rationalise use of fonts in documentation

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#478]
The Polyglossia documentation needs, inevitably, many different fonts.  All of them can be found on the Web, probably even under a free software licence, but they’re not all available in one place, so that when setting up a new working environment (for example a new computer) it can be time-consuming to hunt after all the fonts.  With the latest (pre-freeze) TeX Live 2020 I needed to download no less than nine different fonts.  This can be improved, for example by adding as many fonts as possible in TeX Live, and replacing those that can’t by others.

**Comment by jspitz** [comment]
I've changed the documentation to use fonts that are included in TeXLive, with one exception: There does not seem to be a Syriac otf/ttf font available. The one we use (Serto Jerusalem) is at least included in the x11-fonts collection on Linux, and it can be freely and legally downloaded from the Syriac Institute (as now documented in a comment).

Please check whether this is sufficient.

**Comment by jspitz** [comment]
I detected another font that is not in TeXLive: `GFS Ambrosia`, used for the `Πολυγλωσσία` title. I didn't find a similar font that supports Greek in TeXLive and thus replaced it with `GFS Complutum` (with the nicely matching font file name `GFSPolyglot`).
