### ISSUE TITLE
Croatian: localalph

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#486]
Based on both online and printed editions of Croatian Orthography by IHJJ (The Institute of Croatian Language and Linguistics), the list of alphanumeric counters is shorter (`abcdefghijklmnoprstuvz`, length of 22) than the default one (`abcdefghijklmnopqrstuvwxyz`, length of 26).

Both lower case and upper case variants, of course:
- https://pravopis.hr/pravilo/zagrade/65/
- https://pravopis.hr/pravilo/desna-zagrada/67/.

Ref (the two longest lists):
- https://pravopis.hr/pravilo/ostala-imena/100/
- https://pravopis.hr/pravilo/malo-pocetno-slovo/89/.

There is no explicitly written rule on this matter but one can be implicitly derived.

Feature request: `localalph` option (activated by default).

It would be convenient to have a remark in the manual, something like:
```latex
\item \xpgboolkeytrue{localalph}
If \xpgvalue{true}, alphanumeric counters will use a localized version excluding characters q, w, x and y from the common set of English characters.
```

**Comment by jspitz** [comment]
> ```
> \item \xpgboolkeytrue{localalph}
> If \xpgvalue{true}, alphanumeric counters will use a localized version excluding characters q, w, x and y from the common set of English characters.
> ```

I'd say: "from the Latin alphabet" (as English is just one language using that script)

**Comment by jspitz** [comment]
Implemented, please test.

**Comment by ivankokan** [comment]
Tested, looks good.
