### ISSUE TITLE
Trouble with French/LuaLaTeX

### ISSUE THREAD

**Issue by ogerard** [reutenauer/polyglossia#49]
I suspect some trouble with the code for french support in LuaLaTeX.

This small trilingual example works fine with XeLaTeX in my installation (polyglossia 1.33.3 see main version numbers at the end)

``` \documentclass{minimal}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguages{french,german}

\usepackage{fontspec}

\fontspec{Latin Modern Roman}

\begin{document}

\begin{french}
Bonjour ! Une autre phrase.

\end{french}

\medskip

\begin{english}
Hello World ! Another sentence.
\end{english}

\medskip

\begin{german}
Guten Tag! Ein anderer Satz.
\end{german}

\end{document}
```

but gives the following error in LuaLaTeX

.../polyglossia/gloss-french.ldf:14: LuaTeX error .../polyglossia/polyglossia-frpt.lua:25: attempt to index local 'nodecodes' (a nil value)
stack traceback:
    .../polyglossia/polyglossia-frpt.lua:25: in main chunk
    [C]: in function 'require'
    .../polyglossia/polyglossia.lua:82: in function 'load_
frpt'
    <\directlua >:1: in main chunk.
l.14   \directlua{polyglossia.load_frpt()}
                                          %
? 

The example works as expected with LuaLaTeX if use of french is removed or 
replaced by other languages such as dutch, spanish, latin or italian.

I may be doing something wrong.

LuaTeX, Version beta-0.70.2-2012062819
XeTeX, Version 3.1415926-2.4-0.9998

**Comment by bastien-roucaries** [comment]
Should be done
