### ISSUE TITLE
Polyglossia and hyperref interference when using Hungarian language

### ISSUE THREAD

**Issue by magyarkuti** [reutenauer/polyglossia#493]
The code below provides a bug very similar to #469

    \documentclass{memoir}
    \usepackage{polyglossia}
    \setdefaultlanguage{hungarian}
    \usepackage[hungarian]{hyperref}

    \begin{document}
    \part{Tűz}
    \end{document}

The ``lualatex`` setup I use: TeXLive 2021, Polyglossia v1.52, Hyperref v7.00k. 
As the polyglossia documentation writes at pp30.
*'In Hungarian, some caption strings need to be in a different order than in other languages (e.g., 1. fejezet instead of Chapter 1). By default, polyglossia tries hard to provide the correct order for different classes and packages (standard classes, KOMA-script, memoir, and titlesec package should work, as well as fancyhdr and caption).'*

It is nice and it is correct. Except the caption sting of ``\part``. If the command ``\part{}`` is included and package ``hyperref``is loaded together, then we get some compilation time warnings, and the part name is not swapped with part number. The same phenomenon can be observed in case of other standard classes.

If the package ``hyperref`` is not loaded, then ``polyglossia`` is able to patch ``\@part`` and everything is working properly.

**Comment by jspitz** [comment]
Fixed. The warning is still there, but the output is correct. Please test,

**Comment by magyarkuti** [comment]
I confirm: the output is correct, one warning only remained. (Thank you for your time!!!)

**Comment by jspitz** [comment]
The warning is fixed as well. Actually, a valid warning. this was a stupid typo.

**Comment by magyarkuti** [comment]
Tested again. It is perfect. Everything is working properly. :)

**Comment by jspitz** [comment]
We'll close if the fix is released.
