### ISSUE TITLE
More on (Croatian) digraphs

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#498]
Related to #216.

Consider the following MWE and respective PDF:
```latex
\documentclass{article}

\usepackage{fontspec}

\usepackage{polyglossia}
\setmainlanguage[babelshorthands]{croatian}


\begin{document}

\setmainfont{Latin Modern Roman}
\section{Latin Modern}
\today{} -- ǉ -- lj -- "lj --

\setmainfont{Arial}
\section{Arial}
\today{} -- ǉ -- lj -- "lj --

\end{document}
```

[digraphs_again.pdf](https://github.com/reutenauer/polyglossia/files/6338463/digraphs_again.pdf)

One can notice that:
- Latin Modern surprisingly does not contain Croatian digraphs (https://github.com/reutenauer/polyglossia/issues/216#issuecomment-514410273) but Arial does
- Captions, dates and shorthands do what is expected: fallback to separate glyphs (Latin Modern), output the digraphs themselves for Arial.

However, no fallback mechanism is implemented for Unicode digraphs directly typeset in Latin Modern section.
1. Can it be at least hinted somewhere in the manual that the `newunicodechar` package (reliable, from recognized author) can be used to overcome this issue, e.g.
```latex
\newunicodechar{ǉ}{\iffontchar\font`ǉ ǉ\else lj\fi}
```
2. Is there any special reason for not implementing this digraphs support using the mentioned package (#216)?

Regards, Ivan

**Comment by jspitz** [comment]
I am leaning towards the position that this exceeds polyglossia's scope.

**Comment by ivankokan** [comment]
I'll try to prepare something next week.

**Comment by jspitz** [comment]
As I said I think this is not polyglossia's task.
