### ISSUE TITLE
footnoterule left aligned when using Persian as the main language

### ISSUE THREAD

**Issue by ghost** [reutenauer/polyglossia#5]
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{farsi}
\setotherlanguage{english}
\newfontfamily\farsifont[Script=Arabic]{XB Zar}
\begin{document}
\footnote{این یک زیرنویس است.}
\end{document}

This is because polyglossia does not make use of \autofootnoterule, \leftfootnoterule and \textwidthfootnoterule of bidi package.

**Comment by vafa** [comment]
I can not believe that this has not been fixed after 4 years; if you do not have time, please look for a new maintainer!

**Comment by ZvikaZ** [comment]
Hi.
Any news with this?
Thanks

**Comment by jspitz** [comment]
Could some RTL user check if this change would do what you'd expect?
```
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 7ee92f7..c284d5a 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -1022,8 +1022,11 @@
    \ifcsundef{#1hyphenmins}{}%
    {\expandafter\expandafter\expandafter\set@hyphenmins\csname #1hyphenmins\endcsname\relax}}
 
-
-\AtEndPreamble{\@ifpackageloaded{bidi}{\providecommand*{\aemph}[1]{$\overline{\hboxR{#1}}$}}{}}% TODO Make that work for luabidi too.
+% TODO Make that work for luabidi too.
+\AtEndPreamble{\@ifpackageloaded{bidi}{%
+   \providecommand*{\aemph}[1]{$\overline{\hboxR{#1}}$}}{}%
+   \autofootnoterule%
+}

```

or if you have trouble with applying the patch, just put `\autofootnoterule` in your preamble. Does that do the right thing? Also with English as a second language?
(Note that this currently only works for XeTeX, not LuaTeX).

**Comment by jspitz** [comment]
Footnoterule is now correct with luatex after https://github.com/reutenauer/polyglossia/commit/f4e32afca64655d74e001722d928f6b129b11e64. XeTeX needs the fix outlined above.

Note though that Farsi does not yet work with LuaTeX as it uses a XeTeX primitive (`\XeTeXcharglyph`)

**Comment by reutenauer** [comment]
That’s probably an easy fix: all that `\XeTeXcharglyph` call does is check if the current font supports Persian digits (specifically digit 0, U+06F0 ۰), and use them if that’s the case.  I can give a go at a LuaTeX equivalent.

**Comment by jspitz** [comment]
> That’s probably an easy fix: all that `\XeTeXcharglyph` call does is check if the current font supports Persian digits (specifically digit 0, U+06F0 ۰), and use them if that’s the case. I can give a go at a LuaTeX equivalent.

Please do. I know next to nothing of this.

**Comment by jspitz** [comment]
Not even bidi does set `\autofootnoterule` anymore with the `rldocument`/`RTLdocument` option. This is probably since this conflicts with other footnote-related packages and maybe classes, and once set, you cannot easily opt-out.

Given this, my proposal would be to leave things as they are but document the use of `\autofootnoterule` in the polyglossia manual.

**Comment by reutenauer** [comment]
[This](https://github.com/reutenauer/polyglossia/commit/5419e74) should be enough to support LuaTeX in `gloss-farsi.ldf` (only minimally tested).

**Comment by jspitz** [comment]
Great. I'd suggest you commit. The situation can only improve.

**Comment by jspitz** [comment]
I have added a section to the manual at https://github.com/reutenauer/polyglossia/commit/8f7cb8d5d23001d527c014df1edefd52bcf7a680 which documents the use of footnotes in RTL context and also explains `\autofootnoterule` and why why don't set it by default.

This assumes that luabidi already supports `\autofootnoterule`, `\RTLfootnote`, etc., which is does only in my local copy currently. See bidi-tex/luabidi#9 and bidi-tex/luabidi#10.
