### ISSUE TITLE
Missing \fi in babelsh.def?

### ISSUE THREAD

**Issue by mlgdominici** [reutenauer/polyglossia#50]
Compiling with xelatex the following document

```
\documentclass{article}

\usepackage{ifxetex}

\ifxetex
\usepackage{polyglossia}
\setmainlanguage{italian}
\else
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[italian]{babel}
\fi

\begin{document}

Test.

\end{document}
```

I get this error:

```
(/usr/local/texlive/2013/texmf-dist/tex/latex/polyglossia/gloss-italian.ldf
(/usr/local/texlive/2013/texmf-dist/tex/latex/polyglossia/babelsh.def))
! Extra \else.
l.8 \else

? 
```

I get the same error with other languages that define shorthands (e. g. german). The file compiles fine either with languages that don't define shorthands (e. g. french, english) or with `\setmainlanguage{italian}` commented out.

I suspect a missing `\fi` after line 65 of babelsh.def.

Massimiliano Dominici.

**Comment by bastien-roucaries** [comment]
Done
