### ISSUE TITLE
Serbian: alphanumeric counters

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#503]
Hi,

Based on Правопис српскога језика, Матица српска, 2010. (измењено и допуњено, четврто издање) (https://jelenaradomir.files.wordpress.com/2016/08/pravopis-ms_2010.pdf), т. 3 and т. 4, под 1. Писмо...

3. Основна латиница има 26 знакова. Ни у националним применама углавном није повећаван број основних словних фигура. Потребе националних писама решаване су на два начина: комбиновањем постојећих слова (каква су наша слова ǆ, ǉ, ǌ) или додавањем различитих знакова основној словној фигури (đ, č, ć, š, ž)...

4. Слова се дају у ћирилици азбучним а у латиници абецедним редом. Њихов редослед је за свако писмо одређен. За ћирилицу не треба примењивати латинички редослед и обрнуто – у латиници ћирилички, што значи на пример да се у лексикографским делима штампаним ћирилицом примењује азбучни, а у онима штампаним латиницом абецедни ред.

Напомена: У функцији разбрајања односно рашчлањавања текста (уместо редних бројева) употребљавају се азбучним редом сва ћириличка слова: а, б, в, г, д, ђ... У истој функцији, наравно абецедним редом, узимају се само слова из основне латинице: a, b, c, d, e... Понекад се у истој служби користе и слова грчког алфабета: α (алфа), β (бета), γ (гама), δ (делта)...

Google Translate (a bit improved):

3. Basic Latin has 26 characters. Even in national applications, the number of basic letter figures has not increased. The needs of national letters were solved in two ways: by combining existing letters (such as our letters ǆ, ǉ, ǌ) or by adding different symbols to the basic letter figure (đ, č, ć, š, ž)...

4. The letters for Cyrillic are given in Cyrillic alphabetical order (asbuk) and for Latin in Latin alphabetical order (alphabet). For Cyrillic, the Latin order should not be applied and vice versa, which means e.g. that in lexicographical editions printed in Cyrillic, the Cyrillic alphabetic order must be used, but in those printed in Latin, the Latin alphabetical order must be used.

Remark: In the function of structuring/enumeration in the text (instead of ordinal numbers) all Cyrillic letters are used in Cyrillic alphabetical order: а, б, в, г, д, ђ... In the same function, of course in Latin alphabetical order, only letters from the Basic Latin are taken: a, b, c, d, e... Sometimes the letters of the Greek alphabet are used in the same function: α (alpha), β (beta), γ (gamma), δ (delta)...

![image](https://user-images.githubusercontent.com/1058211/118661057-10b07a80-b7ef-11eb-8c3b-768b31959ac0.png)
![image](https://user-images.githubusercontent.com/1058211/118661094-1ad27900-b7ef-11eb-8a24-3157bc438a57.png)

So, this must be the setup:
- `script=Latin` should activate the following `alph`/`Alph` 26 alphanumeric counters (as in English):
```
a b c d e f g h i j k l m n o p q r s t u v w x y z
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
```
- `script=Cyrillic` should activate the following `asbuk`/`Asbuk` 30 alphanumeric counters:
```
а б в г д ђ е ж з и ј к л љ м н њ о п р с т ћ у ф х ц ч џ ш
А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш
```

I see that `numerals=cyrillic-trad` is also supported. I cannot find it explicitly mentioned within the referred section, but I guess it can be kept.

1. How should `polyglossia` behave if one uses `\alph`/`\Alph` within Cyrillic part?
2. How should `polyglossia` behave if one uses `\asbuk`/`\Asbuk` within Latin part?

I guess the answer for both is: "raise a warning" (consider the future aspects of auto transliteration)? Meaning that e.g. `\alph` within Cyrillic part should raise a warning and **produce Cyrillic alphanumeric counters**. Analogously for the `\asbuk` within Latin part.

I am not sure whether `localalph` (as in Slovenian and Croatian) should be introduced or not, somehow merged with existing `numerals`, or maybe fully replace existing `numerals` etc. If introduced (with `true` value as a default), what alphanumeric counters is `localalph=false` expected to produce for both Cyrillic and Latin?

**Comment by jspitz** [comment]
> * the following `asbuk`/`Asbuk` 30 alphanumeric counters:
> 
> 
> ```
> а б в г д ђ е ж з и ј к л љ м н њ о п р с т ћ у ф х ц ч џ ш
> А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш
> ```

This is fixed at https://github.com/reutenauer/polyglossia/commit/bb9dc95533c7f0d83b86de0518c7fb09229e5ee6. Please verify.

**Comment by jspitz** [comment]
> 1. How should `polyglossia` behave if one uses `\alph`/`\Alph` within Cyrillic part?
> 
> 2. How should `polyglossia` behave if one uses `\asbuk`/`\Asbuk` within Latin part?
 
I think they should both produce what the advertise. It is perfectly reasonable that one might want to output Cyrillic numbering within Latin and vice versa. If people want context-sensitive output, they have `\localnumeral` and `\Localnumeral`.

**Comment by jspitz** [comment]
Inviting @Fooftilly to the round table.

**Comment by Fooftilly** [comment]
The Cyrillic part is in correct order now. However I got this error:

```
! LaTeX Error: Command \serbiannumerals already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.165 ...{\serbiannumerals}[2]{\serbiannumber{#2}}

?
! Emergency stop.
 ...

l.165 ...{\serbiannumerals}[2]{\serbiannumber{#2}}

```

**Comment by jspitz** [comment]
@Fooftilly can you provide a MWE?

**Comment by Fooftilly** [comment]
Here:
```
%Compile with XeLaTeX
\documentclass[12pt,a4paper,serbian]{article}

\usepackage{fontspec}
\setmainfont{FreeSerif}
\setsansfont{FreeSans}
\setmonofont{FreeMono}
\usepackage{polyglossia}
\setdefaultlanguage{serbian}
\setotherlanguages{serbianc,english}

\usepackage[bibencoding=auto,backend=biber,language=auto,style=authortitle-ibid,autocite=footnote]{biblatex}
\addbibresource{mwe.bib}

\begin{document}

Heres a MWE with a few citations. Citing cyrillic text 1\autocite{biblijaLB}, text 2 \autocite{petarspc}, text 3 \autocite{cvetkovic16}, and text 4 \autocite{justin17}.

\printbibliography

\end{document}
```
and mwe.bib
```
@book{biblijaLB,
	title   	=	{Библија : Стари и Нови завет},
	translator  	=	{Лујо Бакотић},
	year        	=	{1994},
	publisher   	=	{Добра вест},
	location    	=	{Нови Сад},
	sortname    	=	{Biblija},
	langid      	=	{serbianc}
}
@online{petarspc,
	author		=	{Петар Василијадис},
	title		=	{Крст - центар павловске сотириологије и апостолског служења},
	translator	=	{Дарко Ђого},
	url		=	{http://www.spc.rs/sr/krst_centar_pavlovske_sotiriologije_i_apostolskog_sluzenja_petar_vasilijadis},
	urldate		=	{2021-12-12},
	langid		=	{serbianc},
	sortname	=	{Petar Vasilijadis}
}
@article{cvetkovic16,
	author		=	{Владимир Цветковић},
	title		=	{Сотириологија, христологија и тајна Христова код Светог Јустина Новог Ћелијског},
	journal		=	{Теологикон},
	year		=	{2016},
	volume		=	{5},
	pages		=	{162--170},
	location	=	{Велико Търново},
	sortname	=	{Vladimir Cvetković},
	langid		=	{serbianc}
}
@book{justin17,
	author		=	{Јустин Ћелијски},
	title		=	{Догматика Православне Цркве – Том II},
	publisher	=	{Svetosavlje.org},
	year		=	{2017},
	edition		=	{Интернет издање},
	sortname	=	{Justin Ćelijski},
	url		=	{https://svetosavlje.org/dogmatika-pravoslavne-crkve-tom2},
	langid		=	{serbianc},
}
```

**Comment by jspitz** [comment]
Thanks. This boils down to
```tex
% !TeX TS-program = xelatex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{serbian}
\setotherlanguages{serbianc}

\setmainfont{FreeSerif}

\begin{document}
	
 Hello.
	
\end{document}
```

**Comment by jspitz** [comment]
> However I got this error:

Fixed at 2593c0ab9a68.

**Comment by ivankokan** [comment]
I will test this.

**Comment by jspitz** [comment]
Everything fixes AFAICS.
