### ISSUE TITLE
Writing of \bgroup, \egroup to the aux file messes up page-reversal

### ISSUE THREAD

**Issue by eyalroz** [reutenauer/polyglossia#504]
This issue is filed following a discussion on TeX.SE:

[Hack for reversing page order after some point not working with recent TeXLive](https://tex.stackexchange.com/q/598581/5640)

At some point over the past 2 (?) years, polyglossia started writing `\bgroup` and `\egroup` to the aux file of the documents it processes. This creates problems when you want to print parts of your document in the reverse order of pages ... as the aux file ends up having the bgroup and egroup swapped, or one of them just missing.

I realize that's not a standard thing to do, but I would still like your help in one of the following:

1. Considering adding an option for the package to avoid the bgroup and egroup insertion
2. Finding a better way to let polyglossia interact with shipped-out-page-reordering documents
3. Suggest a potential workaround with extra code in the premable to somehow make this work.

Motivation: I'm the maintainer of my alma mater's Ph.D. thesis template; and since it needs to have a part in Hebrew and a part in English, opening each from a different side of the cover, and with nice gutters - this page-reordering is necessary. Right now I have to ask people to downgrade their TeXLive distributions to make it work :-(

**Comment by jspitz** [comment]
I have posted a solution at your TeX.SE question: https://tex.stackexchange.com/a/602704/19291

I think this should address you concern here.

**Comment by eyalroz** [comment]
Thank you so much!

I've asked for [feedback from users of my document class](https://github.com/eyalroz/technion-iit-thesis/), but I guess we can close this issue for now. If anybody reports a problem I'll comment here.
