### ISSUE TITLE
aux file gets \bgroup but no \egroup with no text on empty last page

### ISSUE THREAD

**Issue by eyalroz** [reutenauer/polyglossia#505]
Consider the following document:
```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{french}

\begin{document}
\begin{french}
Fou
\newpage
\end{french}
\end{document}
```
with TeXLive 2021's polyglossia, i.e. v1.53, we get:
```
! Missing } inserted.
<inserted text> 
                }
l.7 \begin{document}
```
This seems to happen because polyglossia inserts a `\bgroup` into the aux file, but not the final `\egroup`:
```
\relax 
\selectlanguage *{english}
\@writefile{toc}{\selectlanguage *{english}}
\@writefile{lof}{\selectlanguage *{english}}
\@writefile{lot}{\selectlanguage *{english}}
\bgroup 
\@writefile{toc}{\bgroup }
\@writefile{lof}{\bgroup }
\@writefile{lot}{\bgroup }
\selectlanguage *{french}
\@writefile{toc}{\selectlanguage *{french}}
\@writefile{lof}{\selectlanguage *{french}}
\@writefile{lot}{\selectlanguage *{french}}
\gdef \@abspage@last{1}
```
I believe the document should compile, and that polyglossia should handle this situation gracefully.

  [1]: https://tex.stackexchange.com/q/598581/5640

**Comment by jspitz** [comment]
As explained by Bruno Le Floch in a comment to [his TeX.SE answer](https://tex.stackexchange.com/a/598800/19291) this is due to the empty page being discarded on shipout. Nothing we can fix on polyglossia side. A solution is to add some non-visible element on the empty page, e.g. `~`.

**Comment by bastien-roucaries** [comment]
Le dim. 27 juin 2021 à 09:09, Jürgen Spitzmüller ***@***.***>
a écrit :

> As explained by Bruno Le Floch in a comment to his TeX.SE answer
> <https://tex.stackexchange.com/a/598800/19291> this is due to the empty
> page being discarded on shipout. Nothing we can fix on polyglossia side. A
> solution is to add some non-visible element on the empty page, e.g. ~.
>

\hbox{} will be better here.

**Comment by u-fischer** [comment]
> Nothing we can fix on polyglossia side.

Well you don't have to fill the aux-files with all this bgroup/egroup's. babel manages without it.

**Comment by jspitz** [comment]
Don't know how babel does it, but without the groups, we get leaking language options (see #320).

**Comment by u-fischer** [comment]
There is no official statement that one can't add groups to the aux file (or other auxiliary files), but I don't think that it is safe, I doubt that other packages expects them. I know at least one package (mparhack) which uses \def in the aux-file and will break with your groups.

**Comment by eyalroz** [comment]
If it can be easily determined where there's a missing hbox, then - I would guess there is something you can do about it: Detect this being the case and insert the `\egroup` where it's necessary. I would claim it's the responsibility of a package which inserts bgroups and egroups to ensure that they match - provided that the document author matched their own bgroups and egroups.

And if it's difficult to detect automatically, it is also be difficult for users / document class authors to understand where to put an hbox. I'm currently struggling with it on a document class of mine.

**Comment by eyalroz** [comment]
Also, looking at #320 , it doesn't seem true that the "only way to solve" the issue is to introduce egroups and bgroups. You could theoretically change the definition of `\selectlanguage` to overwrite things like "babelshorthands" with their default, when used. Or have `\begin{german}` and `\end{german}` result in a low-level command different than `\selectlanguage` (e.g. `\selectlanguage@inner` or whatever) to differentiate it from what document authors use, and have this command do what I said.

I'm not 100% sure that would solve it, but on the face of it, it seems pretty feasible.

**Comment by eyalroz** [comment]
To be more concrete - consider this document:
```
\documentclass{article}
\usepackage{atbegshi}
\usepackage{polyglossia}

\setmainlanguage{english} % Palestine was under British rule after all
\AtEndPreamble{
 \setotherlanguage{french}
}

\newif\ifRP%
\newbox\RPbox%
\setbox\RPbox\vbox{\vskip1pt}%
\AtBeginShipout{%
  \ifRP
    \AtBeginShipoutDiscard%
    \global\setbox\RPbox\vbox{\unvbox\RPbox
      \box\AtBeginShipoutBox\kern\c@page sp}%
  \fi
}%

\providebool{xpg@inbiditable}
\renewcommand{\RPtrue}{%
  \booltrue{xpg@inbiditable}
  \clearpage
    \ifRP\RPfalse\fi
    \global\let\ifRP\iftrue
}%

\renewcommand{\RPfalse}{%
  \boolfalse{xpg@inbiditable}
  \clearpage
  \global\let\ifRP\iffalse
  \setbox\RPbox\vbox{\unvbox\RPbox
    \def\protect{\noexpand\protect\noexpand}%
    \@whilesw\ifdim0pt=\lastskip\fi
      {\c@page\lastkern\unkern\shipout\lastbox}%
  }%
}%

\begin{document}
\RPtrue
\begin{french}
Some French here.
\end{french}
\RPfalse
\end{document}
```
This triggers the bug. Here, there is no fishy `\newpage` to complain about...

**Comment by eyalroz** [comment]
To be more concrete - consider this document:
```
\documentclass{article}
\usepackage{atbegshi}
\usepackage{polyglossia}

\setmainlanguage{english}
\AtEndPreamble{
 \setotherlanguage{french}
}

\makeatletter
\newif\ifRP
\newbox\RPbox
\setbox\RPbox\vbox{\vskip1pt}
\AtBeginShipout{
  \ifRP
    \AtBeginShipoutDiscard
    \global\setbox\RPbox\vbox{\unvbox\RPbox
      \box\AtBeginShipoutBox\kern\c@page sp}
  \fi
}

\providebool{xpg@inbiditable}
\renewcommand{\RPtrue}{
  \booltrue{xpg@inbiditable}
  \clearpage
    \ifRP\RPfalse\fi
    \global\let\ifRP\iftrue
}

\renewcommand{\RPfalse}{
  \boolfalse{xpg@inbiditable}
  \clearpage
  \global\let\ifRP\iffalse
  \setbox\RPbox\vbox{\unvbox\RPbox
    \def\protect{\noexpand\protect\noexpand}
    \@whilesw\ifdim0pt=\lastskip\fi
      {\c@page\lastkern\unkern\shipout\lastbox}
  }
}
\makeatother

\begin{document}
\RPtrue
\begin{french}
Some French here.
\end{french}
\RPfalse
\end{document}
```
This triggers the bug. Here, there is no fishy `\newpage` to complain about...

**Comment by jspitz** [comment]
> Also, looking at #320 , it doesn't seem true that the "only way to solve" the issue is to introduce egroups and bgroups. You could theoretically change the definition of `\selectlanguage` to overwrite things like "babelshorthands" with their default, when used. Or have `\begin{german}` and `\end{german}` result in a low-level command different than `\selectlanguage` (e.g. `\selectlanguage@inner` or whatever) to differentiate it from what document authors use, and have this command do what I said.
> 
> I'm not 100% sure that would solve it, but on the face of it, it seems pretty feasible.

Unfortunately this won't work as we are dealing here with the case of nested changes.

**Comment by jspitz** [comment]
> If it can be easily determined where there's a missing hbox, then - I would guess there is something you can do about it: 

Alas, it isn't (at least I don't see a way to do so).

**Comment by jspitz** [comment]
One thing we can try is to reset to the last language (options) in the aux files when a language is being closed. I'll try if I can make this work.

**Comment by eyalroz** [comment]
@jspitz : Thank you, Jurgen. I've simplified my second example further, slightly.

**Comment by bastien-roucaries** [comment]
Le lun. 28 juin 2021 à 14:06, Jürgen Spitzmüller ***@***.***>
a écrit :

> One thing we can try is to reset to the last language (options) in the aux
> files when a language is being closed. I'll try if I can make this work.
>
Better reset to "C" language then set to nested-1 language in aux file...

We only need to keep a stack of language in memory. With expl3 it is easy

**Comment by jspitz** [comment]
@bastien-roucaries go ahead if you have an idea. I failed to tackle it.

**Comment by jspitz** [comment]
The problem to address #320 is that within nested switches of the same language (german w/o shorthands > german w/ shorthands > german w/o shorthands) the language extras are not properly reset when the nested language is closed. This might be a special case. For the time being I am leaning towards removing the groupings and re-open #320 until we find a less intrusive fix for this case.

**Comment by eyalroz** [comment]
I'm no expl3 (or any kind of TeX engine) expert, but perhaps a simpler, cruder solution could be the "implementation" of a fixed-depth stack for these environments. Being generous, you might have an all-document language, then one per chapter/section, then perhaps one per float or box, then one for a paragraph, then one for sentence, then one for a word. So depth-6, and a couple more levels for caution. Like we used to have enumi, enumii, enumiii and so on.

**Comment by eyalroz** [comment]
@jspitz : ping... do you think you could find some time to devote to this issue (and/or #320), over the next month or two?

Not that it's your fault/responsibility, but polyglossia is used for my department's official thesis template - which has content in both English and Hebrew , and I'm getting some complaints about it failing to compile because of this issue.

**Comment by reutenauer** [comment]
I should have some time a few weeks from now.

**Comment by jspitz** [comment]
I'm too busy with other things (real life for the most part)

**Comment by eyalroz** [comment]
@reutenauer : ping...

**Comment by jspitz** [comment]
I have removed the groupings and implemented a stack. Now the previous languages are explicitly restored with all options in the aux file after a nested language has been closed.

Alas, this brings back #320. I am not sure why setting `babelshorthands=false` in the aux has no effect, but let's resolve this later.

**Comment by jspitz** [comment]
#320 is now fixed as well. Stupid thinko

**Comment by eyalroz** [comment]
How can I verify this if I have a TeXLive 2021 distribution?

**Comment by jspitz** [comment]
You can download the development version from this git repo and copy it to your local TEXMF tree.

**Comment by eyalroz** [comment]
@jspitz : Sorry for being a little dense, but - 

1. Which folders in the repository go into which folder under my TEXMF tree?
2. Am I supposed to delete some existing files, or will everything be overwritten by the copying?

(I've only ever installed TeXLive packages using the package manager, so I've not actually done something like this before.)

**Comment by jspitz** [comment]
(Assuming you use Linux)

1. create the directory `~/texmf/tex/latex/polyglossia-dev` (where `~` is your home directory)
2. copy the contents of https://github.com/reutenauer/polyglossia/tree/master/tex to this directory

Maybe copying `polyglossia.sty` alone suffices, but it is safer to copy eveything.

**Comment by ohadeytan** [comment]
Thank you @jspitz and @eyalroz, it seems it resolved the issue in https://github.com/eyalroz/technion-iit-thesis/issues/33 :clap:

**Comment by eyalroz** [comment]
Indeed, it seems to resolve the issue. Thank you, and I hope you can get this adopted in TeXLive ASAP. If there's anything we an do to promote that, please let us know.

**Comment by jspitz** [comment]
Let's keep this open until the fix is released.
