### ISSUE TITLE
Why not  exporting latex to \xpg@loaded 

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#507]
Hi,

I will like to simplify the polyglossia code by exporting the internal latex language.

I do not see why it is not exported. It simplify the code and it is like the C language in C that is always exported.

Bastien

**Comment by jspitz** [comment]
It is not exported since the latex language is not known outside polyglossia. It's just an internal helper language that should not be propagated.

**Comment by bastien-roucaries** [comment]
@jspitz other package does not care to have more language loaded and it simplify code so why not

**Comment by jspitz** [comment]
Let's keep this as is.
