### ISSUE TITLE
export bare language as \__xpg_alias[language][target] = language

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#508]
Hi,

It will hugely simplify the code to always export barelanguage as alias to self

Any objection ?

Bastien

**Comment by Udi-Fogiel** [comment]
@jspitz Is this still relevant?

**Comment by jspitz** [comment]
Not for me.

**Comment by Udi-Fogiel** [comment]
I don't know if I got this ticket correctly, but isn't it already the case?
```tex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\begin{document}
\ExplSyntaxOn
\xpg_alias_base_lang:n{english}
\end{document}
```

**Comment by Udi-Fogiel** [comment]
Yes, this is done at df761eb, closing.
