### ISSUE TITLE
Convert gloss file to ProvidesLanguageDefinitionExtension

### ISSUE THREAD

**Issue by bastien-roucaries** [reutenauer/polyglossia#509]
Hi,

I achieved to load .lde file using RequirePackage (or a modified version called \RequireLanguageDefinitionExtension) so it will be possible to pass option to gloss file using l3key2e.

But I need help in order to close this bug

**Comment by jspitz** [comment]
`*.lde` support has been ditched at 754cc7d9ac3cd4.
