### ISSUE TITLE
Why "Script=Arabic" not default with \arabicfont, \arabicfontsf, \arabicfonttt

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#511]
With this example we need to add `Script=Arabic` as font feature with `\arabicfont` I think it is better to make polyglossia add the feature automatically (same thing with `\arabicfontsf` and `\arabicfonttt`) 

```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont{Amiri} % make polyglossia add "Script=Arabic"

\begin{document}

سلام

\end{document}
```

**Comment by jspitz** [comment]
What is the problem exactly? Polyglossia should do the right thing here (and the example works for me both with XeTeX and LuaTeX.

**Comment by seloumi** [comment]
`Script=Arabic` feature should be added automatically with `\arabicfont` (`\arabicfontsf` and `\arabicfonttt` also)

**Comment by jspitz** [comment]
As I said, this should already be the case. What's the problem exactly (your test file works for me as is)?

**Comment by seloumi** [comment]
The output without `Script=Arabic` feature is  not correct ( Arabic letters are often connected ) 
![image](https://user-images.githubusercontent.com/8249073/130362765-efbcd2ea-30c5-49ad-bd23-9c743b67cf74.png)
So  users need to add the feature with arabicfont every time to get the correct result
![image](https://user-images.githubusercontent.com/8249073/130362939-9b3df260-eb7f-4820-aacf-a8b4dfa9f5ee.png)
My request is to add the feature by default so that users do not need to add it manually every time,
maybe by adding this line in the package `polyglossia`

```latex
\defaultfontfeatures+[\arabicfont,\arabicfontsf,\arabicfonttt]{Script=Arabic}
```

The same applies to  Persian Language

**Comment by jspitz** [comment]
I had a closer look at this, and I am afraid this is not possible. We only do the loading of the gloss files and thus the font setup at the beginning of the document, as the font setup relies on `\<script>font` already being defined. However, only in this method we could specify `\defaultfontfeatures` (as we only have the language and script information avalable at this point). But `\defaultfontfeatures` must precede `\<script>font`. So it's not possible. 

On the other hand, the documentation states that the script needs to be specified in such font definitions, and this is all we can do.
