### ISSUE TITLE
babelshorthands as package option

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#515]
Something is wrong with the `babelshorthands` global option.

The following document works for me:
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands]{german}

\begin{document}
"`abc"'
\end{document}
```

But if I use `babelshorthands` as a package option, the shorthands do not work, i.e., ``"` `` and `"'` are rendered verbatim.

```
\documentclass{article}
\usepackage[babelshorthands]{polyglossia}
\setmainlanguage{german}

\begin{document}
"`abc"'
\end{document}

**Comment by jspitz** [comment]
Fixed. Package options where processed after these booleans have been handled.
