### ISSUE TITLE
Version numbers in language modules

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#517]
Currently, the polyglossia package has no consistent policy concerning version numbers in language modules (ldf files).

Most language modules do not have a version number or something similar. However, the Latin, N’Ko, Occitane, and Piedmontese language modules have a version number and date. Kannada, Thai, and Tibetan have a copyright notice with a year. Kurdish has two dates: “created” and “last updated”.

As some language modules change from time to time, it is desirable to have some kind of version information in these files. There are different possibilities:

1. Each language module gets its own version number (and date).
2. The date of the last change is stated in the beginning of each ldf file, no formal version numbers are used.
3. The polyglossia version number is included in all ldf files. This would require to change many files in every polyglossia release.
4. Leaving everything as is.

I opt for 2. This would not require to change all ldf files at once, but if changes are made, a date should be inserted if missing so far. @reutenauer and @jspitz, what do you think?

**Comment by jspitz** [comment]
I have added version and date to all gloss (and lua) files, and submitted a python script that updates the version and date in all files of the distribution.
