### ISSUE TITLE
With nested language switches, any inner switch sets the font family that outer switch had “seen”, not the current font

### ISSUE THREAD

**Issue by tifv** [reutenauer/polyglossia#519]
```
\documentclass[10pt]{article}

\usepackage[no-math]{fontspec}
\setmainfont{CMU Serif}
\setsansfont{CMU Sans Serif}
\setmonofont{CMU Typewriter Text}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{russian}

\begin{document}

\sffamily
\begin{russian}
Should be sans.
\ttfamily
Should be monospaced.
\begin{english}
Sans, but should be monospaced?
\end{english}
\end{russian}

\end{document}

```
will produce
![image](https://user-images.githubusercontent.com/4668605/138724073-8501e0ed-0eb9-4e06-b125-9e5ca41c1f1e.png)
You can see that inner language switch resets the font back to sans. This is unexpected, as I intended to switch language, not the font.

Further tests show that the outer language switch somehow “memorizes” the font family that was used at the moment it was enabled, and any inner language switch will set it irregardless of subsequent font family changes. (Tested with TeXLive 2021. Using English inside `russian` environment is irrelevant, it will work the same with a Russian text. Probably related to #251.)

**Comment by Udi-Fogiel** [comment]
I'm reopening as it seems like we have a regression in master. The example no provided by the OP no longer produce a correct output.

**Comment by Udi-Fogiel** [comment]
Was this bug really fixed? If if reverse the rolls of russian and english in the example
```tex
\documentclass[10pt]{article}

\usepackage[no-math]{fontspec}
\usepackage{xcolor}
\setmainfont{CMU Serif}
\setsansfont{CMU Sans Serif}[Color=blue]
\setmonofont{CMU Typewriter Text}[Color=red]
\usepackage{polyglossia}
\setdefaultlanguage{russian}
\setotherlanguage{english}

\begin{document}

\sffamily
\begin{english}
Should be sans.
\ttfamily
Should be monospaced.
\begin{russian}
Sans, but should be monospaced?
\end{russian}
\end{english}

\end{document}
```
I get the same problem. In 8ef31ad I also stored font families in Latin fonts, which fixed it.

**Comment by jspitz** [comment]
The problem is fixed, AFAICS
