### ISSUE TITLE
Documentation misleads about \blockextras, \inlineextras and \noextras hook families

### ISSUE THREAD

**Issue by tifv** [reutenauer/polyglossia#522]
Documentation suggests using hooks such as `\captions<lang>` and `\blockextras<lang>`. But while the former hook works, appending something to the latter actually has no effect. Looking at the actual code of the package, I suspect that `\blockextras@<lang>` was implied, but `@` went missing. It is hard to deduce from the current text of the documentation that one should use `\captionsrussian` or `\blockextras@russian`, but not `\blockextrasrussian`.

https://github.com/reutenauer/polyglossia/blob/c68b5913f47ce6bb921f6a6a65d5df6e908a1eab/doc/polyglossia.tex#L1990-L2001

(Personally, I would prefer `\blockextrasrussian` to work, because language-specific changes may be necessary outside of a package, and `\makeatletter` feels cumbersome. But whatever.)

**Comment by jspitz** [comment]
Right, same for `\inlinextras` and `\noextras`. I corrected the docs.
