### ISSUE TITLE
New optional hyphenation patterns for Finnish language

### ISSUE THREAD

**Issue by tlikonen** [reutenauer/polyglossia#525]
Latex package [hyph-utf8](https://www.ctan.org/pkg/hyph-utf8) contains new optional hyphenation patterns for Finnish language. The patterns are called "school" and are defined in files:

    tex/generic/hyph-utf8/patterns/ptex/hyph-fi-x-school.ec.tex
    tex/generic/hyph-utf8/patterns/tex/hyph-fi-x-school.tex
    tex/generic/hyph-utf8/patterns/txt/hyph-fi-x-school.pat.txt

In Polyglossia, it seems that there is no easy option to use those optional Finnish hyphenation patterns. I suggest adding an option.

**Comment by jspitz** [comment]
@reutenauer?

**Comment by reutenauer** [comment]
The `fi-x-school` patterns are already available in `hyph-utf8`; all
Teemu needs from Polyglossia is a way to load them instead of the
default ones for Finnish.  I said (in private correspondence) that I
would add an option but haven’t had time yet, sorry.

**Comment by jspitz** [comment]
I have now added a new options `schoolhyphens` which loads these patterns. Please check if the documentation is adequate.

**Comment by tlikonen** [comment]
I think this (or similar) would be a better and simpler description for the new `schoolhyphens` option:

"Allow hyphenation at almost all possible Finnish hyphenation points. Not all hyphenation points are ideal in typography."

**Comment by jspitz** [comment]
I think the users should be also clearly informed about the **drawbacks** of these patterns, and if I understand the elaborations in https://github.com/hyphenation/basic-finnish correctly the basic patterns might produce wrong hyphenations in compound words.

Anyway, I have just released polyglossia 1.54, so we have plenty of time to improve the documentation for the next version.

**Comment by tlikonen** [comment]
Both, the default and schoolhyphens, produce wrong hyphenations often in compound words. The default option tries to prevent some wrong hyphenations so it's slightly better but the difference is small in compounds.

More consistent difference between the two hyphenation options is that the default option prevents hyphenation between two vowels which is recommended for typography. The default option gives typographically better results out of the box. Its drawback is that it gives less hyphenation points and prevents some correct ones.

The "school" version gives all the possible hyphenation points and doesn't try anything special. It gives more hyphenation points but in typographic conventions hyphenation between vowels is considered less ideal or bad.

**Comment by jspitz** [comment]
Thanks, updated at 2eb628d27a53fc6. Note that this update won't be included in the forthcoming 1.54 release.

**Comment by tlikonen** [comment]
Thank you. Only a small comment: <https://github.com/reutenauer/polyglossia/commit/2eb628d27a53fc68945a00a0405086c17c96ebee>.
