### ISSUE TITLE
Documentation for latesthyphen is missing

### ISSUE THREAD

**Issue by PeterMuellerr** [reutenauer/polyglossia#529]
Searching for “latesthyphen” in polyglossia.pdf leads to three occurrences in total, all in the line “latesthyphen in language German (latesthyphen now equals latesthyphen=true).”  However, the explanation of what this option does seems to be missing from the polyglossia.pdf. Please supply the documentation. Thanks in advance!

**Comment by jspitz** [comment]
The latesthyphen option has been defunc'ed at 000c8714506b7, after the revision log entry you mention has been written (but in the same release cycle). I've now removed the mention in that log entry.

**Comment by wehro** [comment]
> Btw., if XeLaTeX and LuaLaTeX use the “experimental” hyphenation by default, whatever “experimental” might mean exactly, then there is a little inconsistency between stable (and undeveloped and somewhat faulty) XeLaTeX and relatively stable (and developed) LuaLaTeX on the one hand and “experimental” hyphenation on the other hand.

If you want stable German patterns, then please read `dehyph-exptl.pdf`, especially question 5 on page 22.

**Comment by jspitz** [comment]
Not to my knowledge, by I think [tex-hyphen@tug.org](mailto:tex-hyphen@tug.org) would be the more appropriate place to ask this.
