### ISSUE TITLE
Missing character is substituted by space with LuaLaTeX

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#533]
The Latin Modern Roman font does not contain the *zero-width non-joiner* (U+200C) invoked by `\textcompwordmark` in LaTeX.
In the following document, this character is replaced by a space if it is compiled with lualatex. This does not happen with xelatex, nor with babel instead of polyglossia and xe/lualatex nor with fontspec without any language package with xe/lualatex.
So I wonder if something is wrong with polyglossia. The behaviour seems to be quite idiosyncratic.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setmainfont{Latin Modern Roman}

\begin{document}
Auf\textcompwordmark lage
\end{document}
```

**Comment by jspitz** [comment]
Inviting @dohyunkim

**Comment by dohyunkim** [comment]
This seem to be an issue of luaotfload.
The following gives me the same result.
```latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman}[Renderer=HarfBuzz]
\begin{document}
Auf\textcompwordmark lage
\end{document}
```

**Comment by wehro** [comment]
OK, I can report this at the luaotfload repository.
But why do I get the same erroneous behaviour even with `\usepackage[luatexrenderer=none]{polyglossia}`?

**Comment by jspitz** [comment]
> OK, I can report this at the luaotfload repository. But why do I get the same erroneous behaviour even with `\usepackage[luatexrenderer=none]{polyglossia}`?

This is due to a bug in `luatexrenderer` handling which is now fixed. The actual issue indeed is in luaotfload (the `HarfBuzz` renderer). You can see that by using `\setmainfont{Latin Modern Roman}[Renderer=Node]` which fixes the issue in all the examples given here.

**Comment by wehro** [comment]
> This is due to a bug in `luatexrenderer` handling which is now fixed.

Good. Thank you both for help.
