### ISSUE TITLE
Splithyphens for Portuguese

### ISSUE THREAD

**Issue by luis-crisostomo** [reutenauer/polyglossia#534]
Congratulations for the excellent work!
I am writing my thesis, and I use multiple languages. I have noticed that at least one hyphenation rule for Portuguese is not being applied.

In Portuguese, if a word with a hard hyphen (such as pára-brisas) is hyphenated at this hyphen, a second hyphenation
character is to be inserted at the beginning of the line that follows the hyphenation (pára-/-brisas).  

I've noticed that a similar option is already available for Czech and Slovak text, and this option can even be turned off. Could you implement this rule in Portuguese as well?

Thank you

**Comment by jspitz** [comment]
Valid request. For the time being, if you use LuaLaTeX, you can achieve that by
```tex
\usepackage{luavlna}
\enablesplithyphens{portuguese}
```

MWE:
```tex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{portuguese}
\usepackage{luavlna}
\enablesplithyphens{portuguese}
\usepackage[paperwidth=3.5in,paperheight=11in]{geometry}
\begin{document}
	Necessito de pensar em tomar um anti-inflamatório e bem depressa.
\end{document}
```
![grafik](https://user-images.githubusercontent.com/4538783/160078636-44c6aca0-a670-4ad0-bf2b-b4dec303d652.png)

**Comment by jspitz** [comment]
The next version of polyglossia (1.54) will feature `splithyphens` for Portuguese. While I was at it, I also introduced some `babelshorthands`.

**Comment by luis-crisostomo** [comment]
Thank you!
Keep up the excellent work!
