### ISSUE TITLE
splithyphens for Polish

### ISSUE THREAD

**Issue by jotbeel** [reutenauer/polyglossia#535]
Like Czech, Slovak and Portugese, Polish will be grateful for splithyphens.

Many thanks!

`\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{polish}
\usepackage{luavlna}
\enablesplithyphens{polish}
\begin{document}
Przyszła kolejna, z niecierpliwością oczekiwana, jesień z modą na czerwono-złote odcienie.
\end{document} `

-- Jerzy Ludwichowski
[splthyph.pdf](https://github.com/reutenauer/polyglossia/files/8373368/splthyph.pdf)

**Comment by jspitz** [comment]
I added the `splithyphens` options (for v. 1.55). While I was at it, I also added `vlna` and `babelshorthands`, and a missing translation for `\glossaryname`. I would be greatful if you could test all this.

**Comment by jotbeel** [comment]
I've tested splithyphes and \glosssaryname - these are fine, thank you very
much!

However, the vlna and babelshorthands as switched on need corrections: the
lists of vlna nonsyllabic (single letter) prepositions and babelshorthands
need correcting.  I do not feel myself competent enough, thus will consult
Marcin Woliński and Bogusław Jackowski.

śr., 30 mar 2022 o 14:36 Jürgen Spitzmüller ***@***.***>
napisał(a):

**Comment by jspitz** [comment]
> However, the vlna and babelshorthands as switched on need corrections: the lists of vlna nonsyllabic (single letter) prepositions and babelshorthands need correcting.

Does `vlna` correction apply to XeTeX and LuaTeX output? I am asking as these use different methods, and particularly LuaTeX should be adapted to Polish.

**Comment by jspitz** [comment]
I spoke too soon: With `luavlna`, with other languages than Czech or Slovak, the letters (and maybe compound initials) need to be declared explicitly. E.g.,
```tex
\singlechars{polish}{AIiVvOoUuSsZzKk}
```
If I have the correct list of chars, I can make `polyglossia` set this.

With XeTeX, I have taken the list from Czech. It needs to be checked whether this is correct or not.

**Comment by jotbeel** [comment]
AFAIK the list should be

\singlechars{polish}{AaIiOoUuWwZz}



sob., 2 kwi 2022 o 12:45 Jürgen Spitzmüller ***@***.***>
napisał(a):

**Comment by jspitz** [comment]
Thank you so much, I adapted both lua and xe. Could you try whether that's better now?

**Comment by jotbeel** [comment]
Perfect! Both xe and  lua.

sob., 2 kwi 2022 o 13:51 Jürgen Spitzmüller ***@***.***>
napisał(a):

**Comment by jspitz** [comment]
> Perfect! Both xe and lua. 

Great. So only the `babelshorthands` left to tackle.

**Comment by jspitz** [comment]
Due to an urgent issue, polyglossia 1.55 was released today. It includes these additions. Any `babelshorthands` drawbacks should be reported in a new ticket.
