### ISSUE TITLE
parenthesis direction in minted

### ISSUE THREAD

**Issue by bykhov** [reutenauer/polyglossia#536]
After the recent update, the direction of parenthesis in minted environment is wrong.

Example:
```
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{minted,color}

\usepackage{polyglossia,bidi}
\setmainlanguage{hebrew}
\setotherlanguage{english}

\setmainfont{Times New Roman}
\setmonofont{Courier New}

\begin{document}
\begin{minted}{python}
x = [x ]
\end{minted}
\end{document}
```

Resulting file attached
[a.pdf](https://github.com/reutenauer/polyglossia/files/8443512/a.pdf)

**Comment by jspitz** [comment]
Is this with XeTeX or LuaTeX?

**Comment by jspitz** [comment]
To answer myself: XeTeX. LuaTeX does not show the problem.

**Comment by jspitz** [comment]
I checked out an old polyglossia version and see the same problem. So the bug seems to be in `bidi` (where you also have reported the same issue without letting us know here; see https://github.com/tex-persian/bidi/issues/12)

**Comment by bykhov** [comment]
> I checked out an old polyglossia version and see the same problem. So the bug seems to be in `bidi` (where you also have reported the same issue without letting us know here; see [tex-persian/bidi#12](https://github.com/tex-persian/bidi/issues/12))

Sorry for not informing you.
Anyway, `bidi` maintainer shows that it is `polyglossia` issue.
Adding `english` environment solves the problem, but it previously worked fine without this environment.
```
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{minted,color}

\usepackage{polyglossia}
\setmainlanguage{hebrew}
\setotherlanguage{english}

\setmainfont{Times New Roman}
\setmonofont{Courier New}

\begin{document}
\begin{english}
\begin{minted}{python}
x = [x ]
\end{minted}
\end{english}
\end{document}
```

**Comment by bykhov** [comment]
> I checked out an old polyglossia version and see the same problem. 

It works fine for me with `polyglossia` version 1.51

**Comment by jspitz** [comment]
> It works fine for me with `polyglossia` version 1.52

Sorry I cannot confirm this. I checkout out older revisions of polyglossia back to v. 1.47, and all show the same output. So it must be a change in another package (such as `bidi` or maybe `minted`) that cause this. This is not to say that this isn't a problem that can/should be addressed by polyglossia, but it is certainly not a bug introduced by polyglossia.

**Comment by bykhov** [comment]
I was just trying to revive some old documents last week.
My workaround was `\begin{english} ...\end{english}` for each code block.
Or, with some automation:

```
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{minted,color}
\newminted{python}{}
\BeforeBeginEnvironment{pythoncode}{\setLR\begin{english}}
\AfterEndEnvironment{pythoncode}{\end{english}\setRL}
	
\usepackage{polyglossia,bidi}
\setmainlanguage{hebrew}
\setotherlanguage{english}

\setmainfont{Times New Roman}
\setmonofont{Courier New}

\begin{document}
\begin{english}
\begin{pythoncode}
x = [x ]
\end{pythoncode}
\end{english}
\end{document}
```

**Comment by jspitz** [comment]
> @jspitz This is caused by the fact that we pass the Hebrew Script feature to the font. Maybe we should ad an option to disable this for typewriter fonts, as they are often used for listings only.

This strikes me like an odd solution. IMHO the language needs to be reset for the listings. Ideally minted should deal with this.

**Comment by Udi-Fogiel** [comment]
> This strikes me like an odd solution. IMHO the language needs to be reset for the listings. Ideally minted should deal with this.

I don't think it is odd. Typewriter fonts are often treated differently. For example, fontspec does not add to them `Mapping=tex-text` or the `+tlig` features like to sans serif or serif fonts. Imagine I have only  hebrew in my document, I don't really want to load the english gloss just for listings, I don't need any of its features, not even hyphenation.

**Comment by jspitz** [comment]
I don't think you need to load English. Setting language `latex` would probably do.

**Comment by Udi-Fogiel** [comment]
Is this documented?

**Comment by jspitz** [comment]
No.
