### ISSUE TITLE
\setmainlanguage{en-US} raises an error with v. 1.55a

### ISSUE THREAD

**Issue by EricMarcon** [reutenauer/polyglossia#539]
This is a MWE:
```
\documentclass{article}
\usepackage{polyglossia}

% Comment out either French or English
%\setmainlanguage{fr-FR}
\setmainlanguage{en-US}

\begin{document}
OK!
\end{document}
```

Compilation fails with the message
`! Package xkeyval Error: 'babelname' undefined in families 'english'.`

This error does not happen with Polyglossia v. 1.53.

If you comment out `\setmainlanguage{en-US}` and activate `\setmainlanguage{fr-FR}`, compilation works fine.

**Comment by jspitz** [comment]
Thanks, the English aliases were completely wrong. Will be fixed in the next release.

**Comment by jspitz** [comment]
BTW this was broken at df761eb88830f20.

**Comment by jspitz** [comment]
I just uploaded v. 1.56 to CTAN.
