### ISSUE TITLE
Polyglossia no loner works with biblatex-apa

### ISSUE THREAD

**Issue by MadCatX** [reutenauer/polyglossia#54]
Ever since my linux distro (Arch Linux) updated to TL2013 I cannot use polyglossia together with APA citations. Compilation always fails with

```
    <argument> \mkbibdateapalongextra 
                              {labelyear}{labelmonth}{labelday}\iffieldu...
```

and the resulting file contains "labelyearlabelmonthlabelday" instead of the actual date. When I build the same file using babel, I can see that XeLaTeX uses the respective -apa.lbx files which does not seem to be the case with polyglossia. The problem persists even with the lastest biblatex-apa and polyglossia from CTAN and it used to work fine before I updated to TL2013. There is no problem unless I use "style=apa" in biblatex parameters.

MWE:

```
    \begin{filecontents}{mybib.bib}
     @BOOK{a,
      AUTHOR = {John Smith and others},
      TITLE = {Example},
      YEAR = {2004},
      }
    \end{filecontents}

    \documentclass[a4paper,10pt]{article}

    \usepackage{fontspec}
    \usepackage{polyglossia}
    \setdefaultlanguage{german}
    \usepackage{csquotes}
    \usepackage[backend=biber,style=apa]{biblatex}
    \DeclareLanguageMapping{german}{german-apa}
    \usepackage{xltxtra}

    \setromanfont[Mapping=tex-text]{Linux Libertine O}

    \bibliography{mybib.bib}

    \begin{document}
     abc \parencite{a}
     \printbibliography
    \end{document}
```

**Comment by bastien-roucaries** [comment]
Done
