### ISSUE TITLE
Inaccurate transliteration of Hebrew month names

### ISSUE THREAD

**Issue by eyalroz** [reutenauer/polyglossia#540]
There is an official transliteration of Hebrew month names by the Hebrew Language Academy, which you can find among other places on [Wikipedia](https://en.wikipedia.org/wiki/Hebrew_calendar); and it differs from what Polyglossia has right now:

| Polyglossia           | Standard transliteration | Difference? |
|-----------------------|--------------------------|-------------|
|  Tishrei              | Tishri                   | Yes         |
| Marcheshvan / Heshvan | Marẖeshvan               | kinda       |
| Kislev                | Kislev                   |             |
| Tebeth                | Tevet                    | Yes         |
| Shebat                | Shvat                    | Yes         |
| Adar I                | Adar I                   |             |
| Adar II               | Adar II                  |             |
| Nisan                 | Nisan                    |             |
| Iyar                  | Iyyar                    | Yes |
| Sivan                 | Sivan                    |             |
| Tammuz                | Tammuz                   |             |
| Av                    | Av                       |             |
| Elul                  | Elul                     |             |

Please change the month names to fit the standard. As for Marchesvan, there's that gutteral-h symbol that the academy suggests, which you may or may not want to ignore, I have no strong opinion here. 

If you want I could create a PR for this against a branch of your choice.

**Comment by jspitz** [comment]
> If you want I could create a PR for this against a branch of your choice.

Yes, please.

**Comment by eyalroz** [comment]
@jspitz : But which branch should I PR against? You have so many...

**Comment by reutenauer** [comment]
The ’ch’ in Marcheshvan was an explicit request by a user, please don’t change it.

**Comment by eyalroz** [comment]
@reutenauer : I don't want to spoil the other corrections over that, but - a "request" does not seem to be a basis for making a decision. `ch` corresponds to hebrew כ, not the gutteral ח. So, that user requested the use of incorrect transliteration which disagrees with the official one.

**Comment by reutenauer** [comment]
With all due respect, a user request is the only reason for making any change to a stable package.  We responded to several of your requests in the recent past, please don’t dismiss earlier ones from other users :-)

There is a wider issue, which is that the current names are obviously not a transliteration from Modern Hebrew, but rather some English rendering of (presumably) Biblical Hebrew, even though the spellings are not completely internally consistent either (I would expect “Ab”, for example, instead of ”Av”).

The correct way to address that is to have an option to use month names in the transliterated spellings, and keep the current ones by default.

**Comment by jspitz** [comment]
> @jspitz : But which branch should I PR against? You have so many...

The master branch of reutenauer/polyglossia.

**Comment by jspitz** [comment]
> Why not the other way around?

Because it is good practice in LaTeX programming to maintain backwards compatibility (i.e., document output should not change without user intervention if not absolutely necessary).

**Comment by eyalroz** [comment]
> backwards compatibility

Valid point. I am now fully convinced of your suggested bottom line.  T_T

**Comment by jspitz** [comment]
Will be fixed in the next release.
