### ISSUE TITLE
The language for entries in List of tables depends on the text they land on

### ISSUE THREAD

**Issue by giorgian** [reutenauer/polyglossia#542]
I set English as default language, and Arabic as other language. 
I have a table (default language) and a little further I have an Arabic environment.
If, by chance, the table is typeset among the Arabic text, the entry in the List of tables is typeset with Arabic language: page number on the left, English caption rendered with the wrong font (if I specify different fonts for English and Arabic) and aligned to the right, page number on the left.

I only understood what was going on by looking at the .lot file, that clearly shows the issue: 

    \selectlanguage *{english}
    \addvspace {10\p@ }
    \bgroup
    \selectlanguage *{arabic}
    \egroup
    \selectlanguage *{english}
    \bgroup
    \selectlanguage *{arabic}
    \contentsline {table}{\numberline {1.1}{\ignorespaces First table}}{2}{}%
    \egroup
    \selectlanguage *{english}
    \addvspace {10\p@ }

I tried creating a sample source, but couldn't manage to get it below 100 lines; I can paste it, or attach screenshots/PDFs if needed.

**Comment by jspitz** [comment]
MWE:
```tex
% !TeX TS-program = xelatex
\documentclass[10pt,a4paper]{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}
\begin{document}
	\begin{table}[b]
		\caption{Hello \tablename}
	\end{table}
	\selectlanguage{arabic}
	\today
	\cleardoublepage
	\selectlanguage{english}
	\listoftables
\end{document}
```

**Comment by jspitz** [comment]
A quick and dirty solution seems to be to patch the `\@caption` command to explicitly switch the language:
```tex
% !TeX TS-program = xelatex
\documentclass[10pt,a4paper]{article}
\usepackage{polyglossia}
\makeatletter
\pretocmd{\@caption}{\addtocontents{\csname ext@#1\endcsname}{\selectlanguage*{\languagename}}}{}{}
\makeatother
\setmainlanguage{english}
\setotherlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}
\begin{document}
	\begin{table}[b]
		\caption{Hello \tablename}
	\end{table}
	\selectlanguage{arabic}
	\today
	\cleardoublepage
	\selectlanguage{english}
	\listoftables
\end{document}
```

But then, I wonder whether the language of LOT and LOF shouldn't be the language which is current at `\listof...` (and only the caption language be switched inline).

**Comment by jspitz** [comment]
(Note, though, that this is bound to break as soon as a class or another package redefines `\@caption` as well. I am not sure there is a solid solution here)

**Comment by jspitz** [comment]
I have committed a fix which improves the situation. The only drawback is that the entry number might be set in a different font if such is assigned to the language switched to.

Please test, if you can, and report back.

**Comment by jspitz** [comment]
MWE showing the remaining glitch:
```tex
% !TeX TS-program = xelatex
\documentclass[10pt,a4paper]{article}
%\usepackage{caption}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}



\tracingpatches
\begin{document}
	\begin{table}[b]
		\caption{Hello \tablename}
	\end{table}
	\selectlanguage{arabic}
	\today
	\begin{table}
		\caption{\textenglish{Hello} \tablename}
	\end{table}
	\cleardoublepage
	\selectlanguage{english}
	\listoftables
\end{document}
```

![grafik](https://user-images.githubusercontent.com/4538783/179993857-92ee63a8-0069-4ae1-91de-c05d4bee5bed.png)
