### ISSUE TITLE
Polyglossia and hyperref interference when using french language (again)

### ISSUE THREAD

**Issue by EricMarcon** [reutenauer/polyglossia#546]
I'm afraid the issue #469  is back with polyglossia 1.56 and hyperref 7.00q.
This is a MWE:

```
\documentclass{article}

% Polyglossia
\usepackage{polyglossia}
\setmainlanguage{fr-FR}
%Hyperref
\usepackage{hyperref}

\begin{document}
Text.
\end{document}
```
I see
>Warning: Package polyglossia Warning: Failed to patch part for French on input line 16.
>Warning: Package polyglossia Warning: Failed to patch part for French on input line 9.
>Warning: Package polyglossia Warning: Failed to patch part for French on input line 16.

**Comment by ivanrothfr** [comment]
Hi Eric,

I think you have to declare it like that:

```
\usepackage{polyglossia}
\setdefaultlanguage[frenchpart=false]{french}
```

At least this is what I do and the warning is not here (same versions of polyglossia and hyperref as you, running texlive 2022 vanilla on debian).

Ivan

**Comment by jspitz** [comment]
Should be fixed in next version.
