### ISSUE TITLE
Latin language incompatible with four-hats notation

### ISSUE THREAD

**Issue by yannis1962** [reutenauer/polyglossia#547]
When I run the following with xelatex:

\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{latin}
\begin{document}
^^^^00d8
\end{document}

the four-hats notation is not recognized:

! Missing $ inserted.
<inserted text> 
                $
l.5 ^
     ^^^00d8
? x
No pages of output.
Transcript written on test.log.

This is a minimal example (the problem occurs only with the "latin" language), could you please check it? I'm attaching the log file so that you can the various versions
[test.log](https://github.com/reutenauer/polyglossia/files/8935015/test.log)
.

**Comment by wehro** [comment]
I will study it.
For now you can use the following workaround:
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{latin}
\begin{document}
\shorthandoff*{^}
^^^^00d8
\end{document}
```
Note the star.
