### ISSUE TITLE
Trouble building test documents

### ISSUE THREAD

**Issue by eyalroz** [reutenauer/polyglossia#549]
I'm using TL 2020 installed (manually) on a Devuan GNU/Linux Chimaera system.

I'm trying to build the test documents in `tests/`, and am encountering several problems:

1. Some fonts are expected to exist which I don't know where to get; specifically, Yas.
2. I get undefined control sequence errors, such as:
    ```
    ! Undefined control sequence.
    <recently read> \ifluatex 
                              
    l.5 \ifluatex
                 \RequirePackage{luabidi}\else\RequirePackage{bidi}\fi
    ```
   is it possible that `\RequirePackage{iftex}` is missing somewhere?

**Comment by jspitz** [comment]
Polyglossia loads `iftex`, but maybe your `iftex` version does not have this check yet? In general, current polyglossia very much relies on a recent LaTeX distribution.

**Comment by eyalroz** [comment]
@jspitz : Well, perhaps you could perform a version check and emit an error which tells the author this fact?

**Comment by muzimuzhi** [comment]
`\ifluatex` is added to `iftex` package [since v1.0a](https://ctan.org/ctan-ann/id/mailman.711.1572559371.2586.ctan-ann@ctan.org), which is released on Oct 31, 2019 and should be part of the texlive 2020 iso mirror. You may want to check the version and exact path of `iftex.sty` from log.

**Comment by eyalroz** [comment]
Log is attached. It looks like iftex does not even get loaded.

[test-hebrew-calendar.log](https://github.com/reutenauer/polyglossia/files/9014319/test-hebrew-calendar.log)

**Comment by muzimuzhi** [comment]
> It looks like iftex does not even get loaded.

nor `polyglossia`. I suspect there's some script that will insert sth like `\usepackage{polyglossia}` to test files, but find no clue.

**Comment by eyalroz** [comment]
@muzimuzhi : Hey, I just followed the instructions in the README... I know nothing about LuaTeX.

**Comment by eyalroz** [comment]
Awesome, thanks :-)

**Comment by eyalroz** [comment]
@jspitz : So, it's actually not fixed now. The problem persists - I still get:

! Undefined control sequence.
<recently read> \ifluatex 

even though
```
\RequirePackage{iftex}
``` appears right before that.

**Comment by kvafa** [comment]
> `\ifluatex` is added to `iftex` package [since v1.0a](https://ctan.org/ctan-ann/id/mailman.711.1572559371.2586.ctan-ann@ctan.org), which is released on Oct 31, 2019 and should be part of the texlive 2020 iso mirror. You may want to check the version and exact path of `iftex.sty` from log.

Being the original author of `iftex` package, I can say that the package provided luatex engine check since day 1 the package was released by me on CTAN but perhaps it provided `\ifLuaTeX` not `\ifluatex`.

**Comment by eyalroz** [comment]
@kvafa : The problem is only in ensuring iftex is loaded...

**Comment by kvafa** [comment]
> @kvafa : The problem is only in ensuring iftex is loaded...

@eyalroz If you look at my quoted text, you will notice that I was referring to @muzimuzhi comment above.

**Comment by jspitz** [comment]
> @jspitz : So, it's actually not fixed now. The problem is that, with the command suggested in the readme, `hebrewcal.sty` is not loaded from `../tex/hebrewcal.sty`, but from wherever a version of hebrewcal is installed on the current system (i.e. under texmf/whatever).

Well, OK. We can't move to the past and fix previous versions. So install hebrewcal in your local texmf until the fixed version is released.

**Comment by eyalroz** [comment]
@jspitz : But the tests should make sure and use the sty files in `../tex` , not the ones installed on the system...

**Comment by jspitz** [comment]
Ideas how to do that (OS-independent) are most welcome.

**Comment by eyalroz** [comment]
@jspitz : I'm really not a LaTeX expert... can't we set paths via environment/shell variables or something?

**Comment by jspitz** [comment]
> can't we set paths via environment/shell variables or something?

But this should work OS-independently (not only on Linux). As said, I very much welcome ideas on how to do that in the `test.lua` script

**Comment by muzimuzhi** [comment]
Only tested on macOS (by running `texlua run.lua test-hebrew-calendar`) and mostly stolen from https://github.com/latex3/l3build/blob/main/l3build-file-functions.lua:

```diff
diff --git a/tests/run.lua b/tests/run.lua
index 02e28d4..ae898a3 100644
--- a/tests/run.lua
+++ b/tests/run.lua
@@ -11,6 +11,26 @@ local nonslash = 1 - slash
 local ego = arg[0]
 local abspath = ego
 
+if os.type == "windows" then
+  os_concat  = "&"
+  os_null    = "nul"
+  os_pathsep = ";"
+  os_setenv  = "set"
+  os_dirsep  = "\\"
+  function normalize_path(path)
+    return gsub(path, "/", "\\")
+  end
+else
+  os_concat  = ";"
+  os_null    = "/dev/null"
+  os_pathsep = ":"
+  os_setenv  = "export"
+  os_dirsep  = "/"
+  function normalize_path(path)
+    return path
+  end
+end
+
 --[===[
 We provide a couple of switches on the command line, see usage.
 
@@ -35,7 +55,7 @@ Usage:
 -- TODO collapse stretches of '<dir>/..'
 local currdir = lfs.currentdir()
 if not match(slash, ego) then -- Path is not absolute
-  abspath = currdir .. '/' .. ego
+  abspath = currdir .. os_dirsep .. ego
 end
 
 
@@ -59,7 +79,7 @@ end
 if #arg > 0 then -- arg is a list of files
   if not match(slash, ego) then -- Path is not absolute
     for _, f in ipairs(arg) do
-      table.insert(files, currdir .. '/' .. f)
+      table.insert(files, currdir .. os_dirsep .. f)
     end
   else -- Path is absolute TODO
   end
@@ -67,7 +87,7 @@ end
 
 local function join(a, b)
   local aa = match(C((slash * nonslash^1)^0), a)
-  return aa .. '/' .. b
+  return aa .. os_dirsep .. b
 end
 
 local dirnamepatt = Cf(C(slash) * (C(nonslash^1) * slash)^0, join) * C(nonslash^1)
@@ -112,12 +132,17 @@ else
   end
 end
 
+texinputs = "." .. os_pathsep .. normalize_path("../tex") .. os_pathsep
+-- on *nix, env == "export TEXINPUTS=.:../tex:"
+-- on win,  env == "set TEXINPUTS=.;..\\tex;"
+env = os_setenv .. " TEXINPUTS=" .. texinputs
+
 for _, format in ipairs(formats) do
   for _, basename in ipairs(basenames) do
     local tex = basename .. '.tex'
-    os.execute(format .. " " .. testdir .. '/' .. tex)
-    os.execute("pdftotext -layout -enc UTF-8 " .. outdir .. '/' .. basename ..  '.pdf' .. ' >/dev/null')
-    local retvalue = os.execute("diff " .. testdir .. '/ref/' .. basename .. '.txt ' ..  testdir .. '/out/' .. basename .. '.txt')
+    os.execute(env .. os_concat .. format .. " " .. testdir .. os_dirsep .. tex)
+    os.execute("pdftotext -layout -enc UTF-8 " .. outdir .. os_dirsep .. basename ..  '.pdf' .. ' >' .. os_null)
+    local retvalue = os.execute("diff " .. normalize_path(testdir .. '/ref/' .. basename .. '.txt') .. ' ' .. normalize_path(testdir .. '/out/' .. basename .. '.txt'))
     if(retvalue == 0) then
       errors[format][tex] = false
       print('Test file ' .. tex .. ' OK.')
```

**Comment by jspitz** [comment]
@muzimuzhi excellent! Could you prepare a pull request (or alternatively post the diff as a text file)?
