### ISSUE TITLE
Two typos in Finnish shorthands

### ISSUE THREAD

**Issue by ahomansikka** [reutenauer/polyglossia#554]
In file gloss-finnish.ldf change lines

  \declare@shorthand{finnish}{"|}{\textormath{\penalty@M\discretionary{-}{}{\kern.03em}}{}}%
  \declare@shorthand{finnish}{"=}{\penalty@M-\hskip\z@skip}%

to

  \declare@shorthand{finnish}{"|}{\textormath{\penalty\@M\discretionary{-}{}{\kern.03em}}{}}%
  \declare@shorthand{finnish}{"=}{\penalty\@M-\hskip\z@skip}%

That is, add \ before @M

(Copied from gloss-german.ldf)

**Comment by jspitz** [comment]
Thanks, fixed for the next release.
