### ISSUE TITLE
Polyglossia and hyperref interference when using Hungarian language (again)

### ISSUE THREAD

**Issue by magyarkuti** [reutenauer/polyglossia#555]
The earlier solved bug #493 came back. Now it is completely the same as it was earlier.
If I follow the solution based on #546 interchanging every `@old@part` to `NR@part` in the file `gloss-hungarian.ldf` then 
everything is working properly.
I recommend to patch it again.
Thank you for your time!

**Comment by jspitz** [comment]
Can you make that a pull request, please?

**Comment by magyarkuti** [comment]
Dear Jürgen,
yes, yes I am glad to.
/Gyula

**Comment by jspitz** [comment]
Thanks, merged.
