### ISSUE TITLE
Dot follows chapter name in a Hungarian header 

### ISSUE THREAD

**Issue by magyarkuti** [reutenauer/polyglossia#557]
Polyglossia provides the correct order of the chapter counter and the chapter name in case of the Hungarian setup.
When we write `1. fejezet.` in the running head of a document, then the Hungarian typography requires a dot after the chapter name (fejezet).
Thus: `1. fejezet.` is required, but `1. fejezet` is the output now. 
The solution can be to change appropriate `\chapapps` to `\chapapps.` between row 227 and row 261--where the running headers are adjusted--of the file `gloss-hungarian.ldf`.

**Comment by jspitz** [comment]
Thanks, merged. Although I am a bit reluctant as this changes existing documents.

**Comment by jspitz** [comment]
Yes. If a `polyglossia` update changes existing documents' texts (here: adds a dot to the header) "behind" the back of users, this is always problematic, even of the change is more correct.

**Comment by magyarkuti** [comment]
Agreed. The problem is even more serious. Hungarian typography requires a lots of small similar changes.
Just two of randomly chosen problem:
1) Sections
`\section{Bla bla}` ouputs `1.1 Bla bla` today, but the correct is `1.1. Bla bla`.
Completely the same as the russian typography, and gloss-russian.ldf does it correctly.
2) Theorem like environments
The required output is `1.1. tétel (Pythagoras).` Again, the key is the dot after theorem counter.

In my opinion 1) belongs to the category what `polygossia` should be able to manage. Perhaps it is good idea if forcing a dot is not a parameter, as in the case of Russian setup, but `polyglossia` provides a function, for compatibility reasons, which reject the forcing of the dot after the section counters.  I think the default behavior of `polyglossia` must be the typographically correct output.

With respect to problem 2) I do not recommend similar patch, even if babel does it.
The theroem packages, for axample `amsthm` are flexible enough to be able to define a correct theorem style.
I think the Hungarian users must understand the problem.

But the fundamental question is here. 
Do we want to patch gloss-hungarian.ldf until the code fits all of Hungarian typographic conventions?
In an ideal word a Hungarian math related tex code  if `lualatex` or `xelatex` is the compiler 
can be the following:
`\documentclass{memoir}
\usepackage{polyglossia}\setdefaultlanguage{hungarian}
\usepackage{hyperref, amsthm}
\begin{document}
...
\end{document}`
This is what we want, or we accept that *some* user intervention will always be required.
The answer of `babel` is definitely yes. I really do not know. I could argue, and I could accept the negative and the positive answer as well. 
My personal opinion is closer to the negative answer, but a comprehensive document with all of requirements of Hungarian typography including `polyglossia` based solutions is warmly welcome. Perhaps it can be the part of the `polyglossia` documentation.
What do you think?

**Comment by jspitz** [comment]
I think we should provide an option for that, similar to Russian's `forceheadingpunctuation`. Though it should be false by default for backwards compatibility reasons. The option should also cover your recent punctuation to running headers.

**Comment by jspitz** [comment]
So I tend to revert https://github.com/reutenauer/polyglossia/commit/ff4654fa85076d0b863c12c5ab23f045ca270a57 until we have a more general solution with an option. Agreed?

**Comment by magyarkuti** [comment]
Agreed.
