### ISSUE TITLE
Detecting the current language

### ISSUE THREAD

**Issue by vincentb1** [reutenauer/polyglossia#56]
Hello,

I am one of the maintainer of fmtcount, and I am seeking how to load the fmtcount language definitions that are under use in a document.

The objective is simply to make the compilation faster by loading only those fmtcount language definition that are going to be used rather than all the supported language. When fmtcount is used, the current language is detected based on \languagename

See for instance the sort of code that we were considering to use to detect polyglossia loaded languages:

http://fr.comp.text.tex.narkive.com/PuN2MEF9/rendre-fmtcount-sty-compatible-a-la-fois-avec-babel-et-polyglossia

**Comment by jspitz** [comment]
The next polyglossia version will feature `\iflanguageloaded`
