### ISSUE TITLE
Czech polyglossia break en-dash ligature in some circumstances

### ISSUE THREAD

**Issue by msourada** [reutenauer/polyglossia#563]
Every now and then it happens to me, that „--“ is not substituted by „–“. Today I think I have narrowed it down to polyglossia in Czech language. It's worth noting that:
- it happens with xelatex, but not with lualatex
- the en dash need to be without spaces around
- polyglossia with Czech language must be used (babel does not exhibit this behaviour, polyglossia with English neither)
- en-dash can be forced if I enclose the hyphens in braces

Here’s minimal example:
```
% !TeX program = xelatex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{czech}

\begin{document}
	\begin{itemize}
		\item 1--5
		\item 1{--}5
		\item 1 -- 5
	\end{itemize}
\end{document}
```

With xelatex the first item is rendered wrong, with lualatex all of them are correct.

**Comment by msourada** [comment]
Maybe it’s worth noting that similar bug happens with em-dash where „--- “ without spaces is rendered as „-–“ (hyphen followed by en-dash).

**Comment by jspitz** [comment]
Works for me:
![grafik](https://user-images.githubusercontent.com/4538783/195404996-849a7146-b5f8-4389-a888-c5b10ff413f1.png)

Which version of polyglossia is this?

**Comment by msourada** [comment]
From TeXLive 2021 via Fedora, i.e. 2021/04/12 v1.53 (it's usually more than 1 year behind). But your reply prompted me to try this on Windows as well (miktex can update packages fairly easily to their latest versions), the same version is broken, but v1.57 looks OK. Looks like I should have tried newest version first… Thanks for your time and sorry for jumping the gun too early.
