### ISSUE TITLE
gloss-latin sets catcode of ^ to 12

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#566]
gloss-latin.def initiate the `^` shorthand and then deactivates it again with `\shorthandoff{^}`. But this resets the catcode to 12 and not to 7 as needed.
This didn't lead to problems in real documents as a following `\ExplSyntaxOff` did reset the catcode later. But a recent change in expl3 no longer does it and so the problem appeared: https://tex.stackexchange.com/q/663753/2388.
We will revert the change in expl3 for now, but it would be nevertheless better if polyglossia would use `\shorthandoff*{^}`  as it does also later in the code.

**Comment by jspitz** [comment]
Inviting @wehro

**Comment by wehro** [comment]
@u-fischer is right, of course. The missing star has been overlooked before.

**Comment by thomwiggers** [comment]
There seem some remaining issues with the catcode for `^` if you use them in `.aux` files: #582
