### ISSUE TITLE
Horizontal positioning of a TikZ Picture with a fitted frame in a right-to-left polygossia document doesn't work as expected

### ISSUE THREAD

**Issue by EvanAad** [reutenauer/polyglossia#570]
The following LaTeX code is saved in the file `~\test.tex`:

    \documentclass{article}
    \usepackage{lipsum,tikz}
    \usetikzlibrary{fit}
    
    \iffalse
    \usepackage{polyglossia}
    \setmainlanguage{hebrew}
    \setmainfont{Arial}
    \fi
    \begin{document}
    \lipsum[1-1]
    
    \noindent\hspace{0cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
    
    \noindent\hspace{3cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
    \end{document}

When the following commands are executed in the Terminal:

> cd ~  
> pdflatex test

a PDF file is generated at the path `~\test.tex`. When opened in a PDF viewer, the file displays as follows:

[![Without polyglossia][1]][1]

If now the two lines containing `\iffalse` and `\fi` are commented, and the command `xelatex test` (rather than `pdflatex test`) is run, a new PDF file is generated at the path `~/test.pdf`. Here's what I expected to see when the file were opened in a PDF viewer, essentially a horizontal mirror image of the version shown above:

[![Expected outcome][2]][2]

However, here's what the file actually displayed as when opened in a PDF viewer:

[![With polyglossia][3]][3]

Why isn't the distance of the lower rectangle from the right margin as specified, namely 3cm? How can this be fixed?

  [1]: https://i.stack.imgur.com/b1W6i.png
  [2]: https://i.stack.imgur.com/qNCCo.png
  [3]: https://i.stack.imgur.com/Mhhdu.png

**Comment by jspitz** [comment]
As shown by the following example, this is not a bug in polyglossia, but a bug in bidi. So please file a ticket at [kvafa/bidi/issues
](https://github.com/kvafa/bidi/issues)
```tex
\documentclass{article}
\usepackage{lipsum,tikz}
\usetikzlibrary{fit}

\usepackage[RTLdocument]{bidi}

\begin{document}
	\lipsum[1-1]
	
	\noindent\hspace{0cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
	
	\noindent\hspace{3cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
\end{document}
```

![grafik](https://user-images.githubusercontent.com/4538783/201466640-13f4a129-a5f3-4e59-b47b-418b8c809e51.png)
