### ISSUE TITLE
Custom hyphenation rules not respected for a teletype font

### ISSUE THREAD

**Issue by robertsawko** [reutenauer/polyglossia#573]
Hi,

I am writing a document where we use a lot of Python and C++ class names. We decided to use a teletype font so we tend to have a lot of `\texttt{camelCaseClassName}` inside our document. Unfortunately, some of them are quite long. I added some hyphenation rules for the ones which are causing trouble in the text. I did using `\hyphenation{a-b-c}`. This seems to work without the teletype font and in italics (`\textit`), but when I revert to teletype I end up having long words sticking out of the paragraph.

Can you please advise whether there is a way to fix it or if it is intentional or something that needs to be fixed in the package. Thanks.

**Comment by jspitz** [comment]
That's a TeX design decision. `\texttt` is not hyphenated at all by default. The `hyphenat` package provides a way to escape this.
