### ISSUE TITLE
Hook code inserted in caption affects spacing

### ISSUE THREAD

**Issue by davidcarlisle** [reutenauer/polyglossia#575]
See

https://tex.stackexchange.com/a/669374/1090

A write to the lof file is added by polygossia but this means

```
xxx
\caption{...}
```

has a paragraph ending `xxxSPACE\write...{...}`  so forces  a spurious line if `xxx` happens to be full width, including the common case of a full width image.

**Comment by jspitz** [comment]
Thanks, @davidcarlisle. I do not fully understand what is going on here. Would adding `\par` before the code we write be a sane fix or just an ugly workaround?

**Comment by davidcarlisle** [comment]
possibly better would be `\ifhmode\unskip\fi`  just in case someone has  a non standard caption that is not set in vmode.

what s happening is end of paragraph does one implicit \unskip to remove any space from a final end of line but if you have

```
aaaa
\write{}\par
```

the unskip just sees the write whatsit, so removes nothing. The space after `aaaa` may be "lost" with `\parfillskip` but if, as in the linked example it does not fit you get a final line that is all white, with just a space and parfillskip, so looks like vertical space.

I did not trace everywhere polyglossia is adding whatsits, just observed the behaviour here.

**Comment by jspitz** [comment]
Thanks for the explanation and the suggestion, committed.

Let's see whether there are other such cases (I don't think so).

**Comment by TheReallyDumbDane** [comment]
@jspitz Any idea when the patch will be released?

**Comment by TheReallyDumbDane** [comment]
> Thanks for the explanation and the suggestion, committed.
> 
> Let's see whether there are other such cases (I don't think so).

@jspitz Any idea when the patch will be released?

**Comment by jspitz** [comment]
No, there are no release plans yet. We just had a release recently.
