### ISSUE TITLE
About changing the default variants of Armenian, Norwegian and Portuguese

### ISSUE THREAD

**Issue by Y-Z-Chen** [reutenauer/polyglossia#576]
According to [https://en.wikipedia.org/w/index.php?title=Eastern_Armenian&oldid=1131063776], the predominant variant of Armenian in Armenia is the eastern one. Maybe it is better to set the eastern one as the default one in polyglossia. Besides, according to [https://en.wikipedia.org/w/index.php?title=Norwegian_language&oldid=1131074924], the predominant variant of Norwegian is Bokmål. Maybe it is better to set Bokmål as the default variant of Norwegian in polyglossia. For similar reason like Norwegian, it is better to set Brazilian Portuguese as the default variant of Portuguese in polyglossia (by the way, now Portugal and Brazil have started to use the same spelling, see [https://en.wikipedia.org/w/index.php?title=Portuguese_orthography&oldid=1130775968]).

**Comment by jspitz** [comment]
I don't think we should change defaults, for backwards compatibility reasons.
