### ISSUE TITLE
Right to left in beamer top progress navigation bar 

### ISSUE THREAD

**Issue by zalnahedh** [reutenauer/polyglossia#584]
Hello,

I want to make a Beamer Arabic presentation.
When I use Montpellier theme, items in the top progress navigation bar are aligned to the center. I want them to be aligned to the right.

Can you help me with this issue, please?

Thank you,
Zeyad

![beamer_arabic](https://user-images.githubusercontent.com/36653085/230335706-35fe10f0-9b52-4c53-9544-2c8a804e1f82.jpg)

**Comment by jspitz** [comment]
What makes you think this is a polyglossia bug?

**Comment by jspitz** [comment]
Closing. Please reopen if you think this is a polyglossia bug.

Otherwise, please ask on LaTeX help pages such as [tex.stackexchange](https://tex.stackexchange.com/)
