### ISSUE TITLE
\greeknumeral{6} use uppercase glyph instead of lowecase

### ISSUE THREAD

**Issue by Doc73** [reutenauer/polyglossia#587]
Dear devs,
I noticed, actually a long time ago, that the command in question `\greeknumeral{6}` (with its uppercase counterpart `\Greeknumeral{6}`) does not distinguish between uppercase (03DA) and lowercase (03DB) glyphs.

This happens with all fonts I tested.

Here is a sample with Libertinus:
```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass[11pt,b5paper,article]{memoir}
\usepackage[]{libertinus-otf}
\usepackage[babelshorthands=true]{polyglossia}
	\setdefaultlanguage[variant=ancient]{greek}

\begin{document}
	\greeknumeral{1}
	\Greeknumeral{1}
	
	\greeknumeral{6}
	\Greeknumeral{6}
	
	\greeknumeral{16}
	\Greeknumeral{16}
\end{document}
```

Many thanks in advance!

**Comment by jspitz** [comment]
Can you check if the commit I just pushed to master is correct?

**Comment by Doc73** [comment]
Perfect! Thanks!
Too bad I didn't think about reporting this bug years ago! :smile:

**Comment by jspitz** [comment]
Polyglossia 1.61 is on its way to CTAN.
