### ISSUE TITLE
\begin{<lang>} \include{<file>} \end{<lang>} not working at the end of a file

### ISSUE THREAD

**Issue by Letinain** [reutenauer/polyglossia#588]
Here is a MWE :

- test.tex
```latex
\documentclass{minimal}
\usepackage{polyglossia}
\setmainlanguage{english}
\begin{document}
\begin{english}
  \include{test2}
\end{english}
\end{document}
```
- test2.tex : dummy file with any text (currently `a`)

This example seems a bit dubious but I encountered this problem when I wanted to switch the last include in my file to another language than the main one.

The error given is : `! Missing } inserted. <inserted text> } l.9 \end{document}`

Notice that inserting `\null` right before the `\end{document}` seems to fix the compilation issue, and it adds an empty page.

My version of Polyglossia is 1.53 (2021/04/12).

**Comment by jspitz** [comment]
This works with a current version of polyglossia, su I assume the bug has been fixed in the meantime.

Please reopen if you can reproduce after upgrading.
