### ISSUE TITLE
equation number in Persian when equation is inside english environment

### ISSUE THREAD

**Issue by ghost** [reutenauer/polyglossia#6]
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{farsi}
\setotherlanguage{english}
\newfontfamily\farsifont[Script=Arabic]{XB Zar}
\begin{document}
\begin{english}
\begin{equation}
1+2=3
\end{equation}
\end{english}
\end{document}

Equation number gets printed as ۱ instead 1.

**Comment by vafa** [comment]
I can not believe that this has not been fixed after 4 years; if you do not have time, please look for a new maintainer!

**Comment by jspitz** [comment]
Fixed via https://github.com/reutenauer/polyglossia/commit/959a388bba74459789fe2e440923031463333c8c
