### ISSUE TITLE
indentfirst=false may affect section's format in some languages

### ISSUE THREAD

**Issue by mdourmousoglou** [reutenauer/polyglossia#60]
There seems to be a bug in the way the first paragraph after a section is handled.

In languages where `indentfirst=true` the first paragraph after any section is indented. However setting the value to `false` using the undocumented internal `\PolyglossiaSetup` command seems to affect section and footnote formatting.

Here is a minimal example:

```
\documentclass{article}

 \usepackage{fontspec}
 \usepackage{polyglossia}
  \setmainlanguage{greek}
  \setotherlanguage{english}
  \newfontfamily\greekfont{Arial} % Or any other font
  \newfontfamily\englishfont{Arial}
  \PolyglossiaSetup{greek}{indentfirst=false} % <-- Offending line

\begin{document}

 \section{Section in english}
  \begin{english}
   Just some text in english here.\footnote{English footnote.}
  \end{english}
 \section{Ενότητα στα ελληνικά}
  \begin{greek}
   Κείμενο στα ελληνικά.\footnote{Υποσημείωση στα ελληνικά.}
  \end{greek}

\end{document}
```

Compiling this example under xelatex and lualatex (I'm using TL2013) fails to render greek section name properly and it even uses Computer Roman for english section font. It also fails to render greek footnote text.

Switching languages (ie having english as main) or wrapping all greek text in a `\begin{greek} ... \end{greek}` environment doesn't seem to help either. Protecting the offending command also fails to make a difference.

**Comment by jspitz** [comment]
I think this is expected behavior. Your `\PolyglossiaSetup` overwrites the one in the Greek gloss file, which has some apparently necessary font settings. So you would need to write in your document:
```
\PolyglossiaSetup{greek}{
  script=Greek,
  scripttag=grek,
  frenchspacing=true,
  indentfirst=false,% <-- Modified  setting
  fontsetup=true
}
```
Since `\PolyglossiaSetup` is introduced as a "SETUP INTERFACE FOR GLOSS FILES" (quoting polyglossia.sty), I suspect that the behavior is intended that it overwrites previous settings (by using default values if not explicitly specified).

**Comment by bastien-roucaries** [comment]
it is a feature not a bug
