### ISSUE TITLE
Typo in Doc

### ISSUE THREAD

**Issue by Doc73** [reutenauer/polyglossia#602]
At pag. 29 are documented the commands `\greeknumber` and `\Greeknumber`, but at pag. 51 (section 8.3) they become `\greeknumeral` and `\Greeknumeral`.
The last two are the correct ones.

Best regards,
Domenico

**Comment by jspitz** [comment]
Actually these commands are synonyms, see `gloss-greek.ldf`, l. 360f.:
```tex
\let\greeknumeral=\greeknumber
\let\Greeknumeral=\Greeknumber
```

I'll adapt the documentation to make this more apparent.

**Comment by Doc73** [comment]
Thanks! 
I remembered wrong and I have not made new tests.
