### ISSUE TITLE
wrong handeling of \normalfont

### ISSUE THREAD

**Issue by Udi-Fogiel** [reutenauer/polyglossia#603]
I don't really understand the purpose of `\resetfontlatin`, but it tampers with `\normalfont`.  For example, see how the section head in the following code has the wrong font:

```TeX
\documentclass{article}
\usepackage{xcolor}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{french}
\newfontfamily\frenchfont{Latin Modern Roman}[Color=red]
% \def\resetfontlatin{}
\begin{document}
	 \selectlanguage{french}
	 Test \textenglish{Test} Test
	 \section{Test}
\end{document}
``` 

If I uncomment the line `\def\resetfontlatin{}` everything looks ok... Is there a need for this `\resetfontlatin`?

**Comment by Udi-Fogiel** [comment]
Still does not work if the other language is non-Latin: 

```TeX
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{xcolor}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{hebrew}
\newfontfamily\hebrewfont{David CLM}[Color=red, Script=Hebrew]
% \def\resetfontlatin{}
\begin{document}
	 \selectlanguage{hebrew}
	 Test \textenglish{Test} Test
	 \section{Test}
\end{document}
```



> `\resetfontlatin` is needed particularly when switching between different scripts. 

Isn't switching the fonts should be enough? or just adding the correct Script with `\addfontfeature`?

**Comment by jspitz** [comment]
> Still does not work if the other language is non-Latin:

Thanks, should be fixed now as well.

> Isn't switching the fonts should be enough? or just adding the correct Script with `\addfontfeature`?

No. I can't go into details now, but it is needed in many cases IIRC.

**Comment by jspitz** [comment]
> Thanks, should be fixed now as well.

At e8734536a0dbefdb for that matter

**Comment by Udi-Fogiel** [comment]
> Thanks, should be fixed now as well.

Thanks For the quick fix.

> > Isn't switching the fonts should be enough? or just adding the correct Script with `\addfontfeature`?
> 
> No. I can't go into details now, but it is needed in many cases IIRC.

Ok, I'll try to investigate a little more, but maybe I shouldn't fix something that isn't broken...

**Comment by jspitz** [comment]
> maybe I shouldn't fix something that isn't broken...

That would be my advise as well. The whole language/script switching business is really sensitive area.

**Comment by Udi-Fogiel** [comment]
@jspitz  Is there any chance to load the new version to ctan soon? I encountered several users who had confusing error messages about missing glyphs in their fonts, because they wrote in hebrew and the font was Latin Modern as a consequence of this bug. 

I don't want to tell to many people to add a temporary patch to their documents, but this is not really urgent, so don't feel obliged if you don't currently have the time.

**Comment by jspitz** [comment]
I'm quite busy with RL currently, but I see if I can prepare a release in due time.

**Comment by jspitz** [comment]
I have just submitted `polyglossia` 1.65 to CTAN.
