### ISSUE TITLE
Warning: empty features added to latin font when using Chinese

### ISSUE THREAD

**Issue by sievertst** [reutenauer/polyglossia#606]
Each time I try to enter text tagged as Chinese, I get the following warning, sometimes multiple of them:

    `Package polyglossia Warning: Asking to add empty feature to latin font (Language="Chinese" to langtag "") on input line xxx.`

Here is an MRE:

```latex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{chinese}
% \setotherlanguage{english}

% load a CJK font, otherwise we get an error
\newfontfamily\cJKfont[Script=CJK]{Noto Serif CJK SC}

\begin{document}
你好

% uncommenting the following line does not produce additional warnings
% \textenglish{hi}

% uncommenting the following three lines produces one additional warning on the
% line with `\end{english}`
% \begin{english}
% hi
% \end{english}

\end{document}
```

This MRE causes three of the above warnings (once on line with `\begin{document}` and twice on the one with `\end{document}`), plus

If I switch it around and use English as the main language and Chinese as the secondary one, I get a single warning per use of `\textchinese` or the `chinese` environment, always on the line that switches back out of the Chinese context.

Not sure if this is related to #284?

I am compiling using lualatex (v1.17) and Polyglossia v.1.65.

**Comment by jspitz** [comment]
Should be fixed in the repo. Please test if you can (exchanging [gloss-chinese.ldf](https://raw.githubusercontent.com/reutenauer/polyglossia/master/tex/gloss-chinese.ldf) suffices)

**Comment by sievertst** [comment]
That seems to have done the trick, thank you very much!

**Comment by jspitz** [comment]
Thanks for testing. Let's keep this open until 1.66 is released.

**Comment by sievertst** [comment]
Sure, sorry for the premature close.
