### ISSUE TITLE
Inconsitency among LDF files

### ISSUE THREAD

**Issue by pauloney** [reutenauer/polyglossia#611]
We are parsing the gloss-*.ldf files for another project, a speller driver for multilingual documents and we noticed a few things that I would like to bring up:

All "master" LDF files contain the section "% BCP-47 compliant aliases" with the exception of two of them:

gloss-khmer.ldf
gloss-nko.ldf

The majority of languages in Polyglossia are supported by Babel, but only 18 LDF files contain the "Babel aliases". 

Any reason for these?

**Comment by jspitz** [comment]
> All "master" LDF files contain the section "% BCP-47 compliant aliases" with the exception of two of them:
> 
> gloss-khmer.ldf 

Oversight. Done at 56adc44abd48

> gloss-nko.ldf

Here the BCP47 identifier and the language name are equal, so no need to set an alias.

> The majority of languages in Polyglossia are supported by Babel, but only 18 LDF files contain the "Babel aliases".
> 
> Any reason for these?

We only need the alias if the babel name differs from the polyglossia name. I haven't checked with the recently added babel languages, do you know of cases we are missing?

**Comment by pauloney** [comment]
If they are needed only in the case the names differ, then there is nothing missing. The whole situation is the following:

This is the list of the 62 missing the Babel aliases:

 gloss-afrikaans.ldf
 gloss-albanian.ldf
 gloss-amharic.ldf
 gloss-arabic.ldf
 gloss-armenian.ldf
 gloss-asturian.ldf
 gloss-basque.ldf
 gloss-belarusian.ldf
 gloss-bengali.ldf
 gloss-bosnian.ldf
 gloss-breton.ldf
 gloss-bulgarian.ldf
 gloss-catalan.ldf
 gloss-chinese.ldf
 gloss-coptic.ldf
 gloss-croatian.ldf
 gloss-czech.ldf
 gloss-danish.ldf
 gloss-divehi.ldf
 gloss-dutch.ldf
 gloss-esperanto.ldf
 gloss-estonian.ldf
 gloss-finnish.ldf
 gloss-galician.ldf
 gloss-georgian.ldf
 gloss-hebrew.ldf
 gloss-hindi.ldf
 gloss-icelandic.ldf
 gloss-interlingua.ldf
 gloss-italian.ldf
 gloss-japanese.ldf
 gloss-kannada.ldf
 gloss-korean.ldf
 gloss-lao.ldf
 gloss-latvian.ldf
 gloss-lithuanian.ldf
 gloss-macedonian.ldf
 gloss-malayalam.ldf
 gloss-marathi.ldf
 gloss-mongolian.ldf
 gloss-occitan.ldf
 gloss-piedmontese.ldf
 gloss-polish.ldf
 gloss-punjabi.ldf
 gloss-romanian.ldf
 gloss-romansh.ldf
 gloss-russian.ldf
 gloss-sanskrit.ldf
 gloss-slovak.ldf
 gloss-swedish.ldf
 gloss-syriac.ldf
 gloss-tamil.ldf
 gloss-telugu.ldf
 gloss-thai.ldf
 gloss-tibetan.ldf
 gloss-turkish.ldf
 gloss-turkmen.ldf
 gloss-ukrainian.ldf
 gloss-urdu.ldf
 gloss-uyghur.ldf
 gloss-vietnamese.ldf
 gloss-welsh.ldf

Out of these I can see that Babel has the same name -- and LDF support -- for 37:

afrikaans.ldf
albanian.ldf
basque.ldf
belarusian.ldf
bosnian.ldf
breton.ldf
bulgarian.ldf
catalan.ldf
croatian.ldf
czech.ldf
danish.ldf
dutch.ldf
esperanto.ldf
estonian.ldf
finnish.ldf
galician.ldf
georgian.ldf
hebrew.ldf
icelandic.ldf
interlingua.ldf
italian.ldf
japanese.ldf
latvian.ldf
lithuanian.ldf
macedonian.ldf
mongolian.ldf
occitan.ldf
piedmontese.ldf
polish.ldf
romanian.ldf
romansh.ldf
slovak.ldf
swedish.ldf
thai.ldf
turkish.ldf
vietnamese.ldf
welsh.ldf

And these have support via the Locale -- ini files:

gloss-amharic.ldf
gloss-arabic.ldf
gloss-armenian.ldf
gloss-asturian.ldf
gloss-bengali.ldf
gloss-chinese.ldf
gloss-coptic.ldf
gloss-hindi.ldf
gloss-kannada.ldf
gloss-korean.ldf
gloss-lao.ldf
gloss-malayalam.ldf
gloss-marathi.ldf
gloss-punjabi.ldf
gloss-russian.ldf
gloss-sanskrit.ldf
gloss-syriac.ldf
gloss-tamil.ldf
gloss-telugu.ldf
gloss-tibetan.ldf
gloss-turkmen.ldf
gloss-ukrainian.ldf
gloss-urdu.ldf
gloss-uyghur.ldf

So the only one really missing is:

gloss-divehi.ldf

but this one does NOT have Babel support.

**Comment by jbezos** [comment]
> gloss-divehi.ldf
> 
> but this one does NOT have Babel support.

There is a locale `ini` for Divehi, too.

**Comment by pauloney** [comment]
Javier, what file is it? I have not been able to locate it.

**Comment by jbezos** [comment]
Under `/TeXLive/texmf-dist/tex/generic/babel/locale/dv`. Maybe your system needs an update.

**Comment by jspitz** [comment]
So nothing to do if I didn't misunderstand your argumentation.

**Comment by pauloney** [comment]
Correct!
