### ISSUE TITLE
\SetLanguageKeys not documented.

### ISSUE THREAD

**Issue by Udi-Fogiel** [reutenauer/polyglossia#616]
I'm don't fully understand yet the purpose of (which key should be allowed to change), so I don't feel comfortable documenting it.

**Comment by Udi-Fogiel** [comment]
I meant it wasn't documented in the user manual, should it be there?

**Comment by jspitz** [comment]
No, this command is not meant to be used in documents. It is meant to be used in gloss files.

**Comment by Udi-Fogiel** [comment]
Ok, so not related to this ticket, but if I understand correctly, any setup is made during the processing of the .ldf files. So I have two questions:

* Should the assignments in `\polyglossia@keys_define_lang:n` be global? after all, we assume that everything is done during the processing of the .ldf file and it should not happen inside a group.
* Should we use \key_define just for setting up a language? maybe we can use more efficient method

**Comment by jspitz** [comment]
I'd have to check that. On a general note, I am wondering whether we shouldn't do a release with the bug fixes we have before we start a major code rewrite which always entails the risk of introducing bugs.

**Comment by jspitz** [comment]
Fine with me

**Comment by jspitz** [comment]
> Sure, I'll stop with the commits for the time being.

1.66 is released, so you can go ahead.
