### ISSUE TITLE
Moving repository

### ISSUE THREAD

**Issue by jspitz** [reutenauer/polyglossia#618]
Hello, github user @polyglossia! Sorry for approaching you in this way, but we didn't find any contact information on your account.

The polyglossia team who develops a LaTeX package of the same name is interested to move its github repository to the more suitable `polyglossia` space. This is not possible since this space is taken by your account.

Since you have not been active on that account yet for some years, we are wondering whether you would be willing to change your user name, which would allow us to enregister a `polyglossia` organization.

We would appreciate your feedback!

**Comment by jspitz** [comment]
No response. Closing.

**Comment by jspitz** [comment]
@reutenauer @Udi-Fogiel I went ahead and finally created https://github.com/xpg-devel

Shall we move the polyglossia repo over there? If so, I think you need to do that, Arthur.

**Comment by Udi-Fogiel** [comment]
Thanks! I believe it makes sense to move it there, if there no objections.
