### ISSUE TITLE
`frenchfootnote` doesn't work

### ISSUE THREAD

**Issue by dbitouze** [reutenauer/polyglossia#620]
The documentation reads that `frenchfootnote` should make the footnotes start with a non-superscripted number followed by a dot, as common in French typography. As pointed out by the following MCE, this is not the case with `polyglossia` v1.65:
```latex
\documentclass{article}
\usepackage[paperwidth=4cm,paperheight=2cm]{geometry}
\usepackage{polyglossia}
\setmainlanguage[frenchfootnote]{french}
\begin{document}
French text\footnote{French footnote.}.
\end{document}
```
![image](https://github.com/reutenauer/polyglossia/assets/1032633/4e413402-760f-4db5-b478-89e11c582f29)

**Comment by Udi-Fogiel** [comment]
Thanks for the repoert, I just pushed what I believe to be a fix. Can you test if it is working for you?

I think it was a copy paste mistake in [here](https://github.com/reutenauer/polyglossia/commit/8e4a5c027390b69911f16e8554fd910d3f65fabc#diff-8e0c2af1985f77386ad405e8447f746c3b10877e4874a1e227cf27ad8f95e5faR148-R149)

**Comment by jspitz** [comment]
Thanks, @Udi-Fogiel. The fix looks good. I wonder how that slipped in.

**Comment by dbitouze** [comment]
> Can you test if it is working for you?

It works like a charm: thanks!
