### ISSUE TITLE
Missing cjkfont error incorrect

### ISSUE THREAD

**Issue by bjhijmans** [reutenauer/polyglossia#621]
I upgraded to 1.66, and I got the following error that I didn't have before:

```
 Package polyglossia Error: The current latin roman font does not contain the 
"CJK" script!
(polyglossia)                Please define \cJKfont with \newfontfamily command
```

I was confused because I did define `\cJKfont`. Turns out it's now `\cjkfont` with lowercase letters. Thankfully, I figured it out pretty quickly, but the error could lead people astray.

**Comment by Udi-Fogiel** [comment]
Thanks for the report. @jspitz  it is caused by https://github.com/reutenauer/polyglossia/commit/3ae354adb75176fa5419c0bc7ab35a3e17a5fc6c , can you have a look?

**Comment by jspitz** [comment]
The lowercasing of just the first token in the string was always a bug that forgot about the possibility of acronyms such as CJK (that haven't been used when that code was introduced).

But then, the odd `cJK` is now in the world, so we could either
* add an alias in case \cjkfont is beeing defined (a bit kludgy, but well) or
* keep things as they are and force users to change their setting (which they need to do now anyway unless we released a hotfix version, which is probably risky given all the heavy code rewrite now underway).

What is your preference?

**Comment by jspitz** [comment]
At least the error message is now correct.

**Comment by reutenauer** [comment]
On Sat, Dec 16, 2023 at 03:55:06AM -0800, Jürgen Spitzmüller wrote:
> But then, the odd `cJK` is now in the world, so we could either
> * add an alias in case \cjkfont is beeing defined (a bit kludgy, but well) or
> * keep things as they are and force users to change their setting (which they need to do now anyway unless we released a hotfix version, which is probably risky given all the heavy code rewrite now underway).
> 
> What is your preference?

  You didn’t ask me, but definitely the latter :-)

	Arthur

**Comment by jspitz** [comment]
Thanks, let's mark this resolved, then.

**Comment by Udi-Fogiel** [comment]
> What is your preference?

I agree with Arthur.
