### ISSUE TITLE
Mismatch between documentation and actual behavior of babelshorthand `"-`

### ISSUE THREAD

**Issue by tlikonen** [reutenauer/polyglossia#623]
There is a mismatch between the documentation and actual behavior of `babelshorthands` character `"-`, at least in the Finnish language. The option `babelshorthands` and its character `"-` is documented like this:

    "-  adds a hyphenation point that does still allow for hyphenation at the
        points preset in the hyphenation patterns (as opposed to \-).

The above quoted text seems to suggest that `"-` is like Tex `\-` (i.e. possible hyphenation point) except that `"-` permits hyphenation anywhere in the word. But the actual behavior of `"-` is like the next documented character `"~` which is explained like this:

    "~  for a hyphen sign without a breakpoint. Useful for cases where the
        hyphen should stick at the following syllable.

Both `"-` and `"~` do the same: create an explicit hyphen character with no hyphenation point after the character. Hyphenation is allowed elsewhere in the word.

Babel package's documentation for Finnish (`finnish.pdf`) is a bit different but it has characters `"-` and `"=` which work seemingly identically as Polyglossia's `"-` and `"~`. See: https://ctan.org/pkg/babel-finnish

**Comment by jspitz** [comment]
Thanks, fixed for the next release. The irritation came from the fact that `babel-finnish` heavily derives from the shorthand definitions common in other languages, which we overlooked.

**Comment by tlikonen** [comment]
You added `"=` in the documentation but it seems to behave like plain `-`. I'm using Polyglossia version 1.59 (as packaged by Debian).

**Comment by jspitz** [comment]
No, `"=` does not allow a break after the hyphen, while plain `-` does.

**Comment by jspitz** [comment]
(that is, after 3b51ea8ac9e6)

**Comment by jspitz** [comment]
> (that is, after [3b51ea8](https://github.com/reutenauer/polyglossia/commit/3b51ea8ac9e61030367ab05769ef22db8629dffc))

Before that, we used the definition as common e.g. in German: Add an explicit hyphen with a breakpoint, but as opposed to plain `-`, also allow for hyphenation at the other points defined in the hyphenation patterns. I changed it to have this shorthand behave as in `babel-finnish`, and since it was not yet documented, we could safely do it.
