### ISSUE TITLE
gloss-english.ldf (line 132) Use of \__prop_put_linked:wnnN doesn't match its definition. 

### ISSUE THREAD

**Issue by vipowueb** [reutenauer/polyglossia#626]
I just updated via the "TeX Live Utility" app to the version:

> revision:    69093
sizes:       src: 1049k, doc: 1037k, run: 1601k
relocatable: No
cat-version: 1.66

The minimal example

```
\documentclass{article}

\usepackage[protrusion=true]{microtype}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{English}

\begin{document}
	Hello World!
\end{document}
```

generates a PDF containing the lines:

> variantvariantukbritish
Hello World!

My typesetter lists the following issues:

> gloss-english.ldf (line 132)
Use of \__prop_put_linked:wnnN doesn't match its definition. (...as@values{english}{variant}{us}{american} ...)

> gloss-english.ldf (line 132)
LaTeX Error: Missing \begin{document}. (...as@values{english}{variant}{us}{american} ...)

and the log file

>  (/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-latex.lde
Package: gloss-latex 2023/12/11 v1.66 polyglossia: module for default language
)
Package polyglossia Info: Default language is latex.
) (/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-english.ldf
File: gloss-english.ldf polyglossia: module for English
Package polyglossia Info: Option: English, variant=american.

> /usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-english.ldf:132: Use of \__prop_put_linked:wnnN doesn't match its definition.
<recently read> ...alias@keyvals@english@american 
                                                  
> l.132 ...as@values{english}{variant}{us}{american}
                                                  
> If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.

> /usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-english.ldf:132: LaTeX Error: Missing \begin{document}.

> See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
> l.132 ...as@values{english}{variant}{us}{american}
                                                  
> You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

> )
Package polyglossia Info: Option: english variant=british.
Package polyglossia Info: Option: english variant=british.
Package polyglossia Info: Default language is english.
Package polyglossia Info: Option: english variant=british.

Within a bigger document, the same line as above is generated, followed by a blank page and the actual content thereafter.

Thanks in advance.

**Comment by LPR121** [comment]
I face the same issue since I updated TexLive yesterday from 2022 to 2023.

**Comment by jspitz** [comment]
Thanks, this is fixed for the next version.

**Comment by jspitz** [comment]
Workaround:
```tex
\documentclass{article}

\usepackage{polyglossia}

% work around a bug in polyglossia
\makeatletter
\ExplSyntaxOn
\pretocmd\xpg@set@alias@values{%
	\prop_if_exist:cF { xpg@alias@keyvals@#1@#4 }
	{ \prop_new:c {xpg@alias@keyvals@#1@#4} }
}{}{}
\ExplSyntaxOff
\makeatother
% end of workaround

\setmainlanguage[variant=british]{english}

\begin{document}
	Hello World!
\end{document}
```

**Comment by vipowueb** [comment]
Works, thanks!

**Comment by jspitz** [comment]
Please keep open until the fix is released.

**Comment by jspitz** [comment]
The reason is a latex3 kernel change that seemed to have affected several packages who didn't check whether a property list is defined before attempting to write to it. See
https://github.com/latex3/latex3/issues/1458

I suppose we need to make a soonish release as this hits users hard.

**Comment by davidcarlisle** [comment]
@jspitz  sorry about the lack of notice. The check that prop variables are declared was always intended to be there (and all expl3 variables are documented as needing to be declared with `\New..` ) but the check was missed in the code, a refactorisation caused the check to get enabled, but as we hadn't noticed the check was previously missing we didn't search contributed packages for affected use.  If you could release before the texlive 2024 code freeze  (2nd March) that would be really helpful, if you can't we could look at pushing out a first-aid, but if you could update that would be best

**Comment by jspitz** [comment]
@davidcarlisle no problem, after all, it was our own oversight. I am about to release now. The only concern I have is that we are in the midst of a major code rewrite and I would have loved to have that settled a bit more. But all checks pass, so I am rather confident.

**Comment by reutenauer** [comment]
On Sat, Feb 17, 2024 at 01:39:33AM -0800, David Carlisle wrote:
> @jspitz  sorry about the lack of notice. The check that prop variables are declared was always intended to be there (and all expl3 variables are documented as needing to be declared with `\New..` ) but the check was missed in the code, a refactorisation caused the check to get enabled, but as we hadn't noticed the check was previously missing we didn't search contributed packages for affected use.  If you could release before the texlive 2024 code freeze  (2nd March) that would be really helpful, if you can't we could look at pushing out a first-aid, but if you could update that would be best

  To be precise, 2 March is the code freeze for binary builds, CTAN
updates continue until 10 March.  But of course, the sooner, the better :-)

**Comment by jspitz** [comment]
Version 2.0 (sic!) has been uploaded to CTAN now. This might give us the opportunity to iron out remaining glitches or regressions of the code rewrite before the TL freeze.

**Comment by reutenauer** [comment]
On Sat, Feb 17, 2024 at 02:11:58AM -0800, Jürgen Spitzmüller wrote:
> Version 2.0 (sic!) has been uploaded to CTAN now. This might give us the opportunity to iron out remaining glitches or regressions of the code rewrite before the TL freeze.

  Great!  Congratulations and well done :-)

**Comment by Udi-Fogiel** [comment]
@davidcarlisle would testing against `latex-dev` catch such problems in advance?

**Comment by davidcarlisle** [comment]
@Udi-Fogiel  well it can't hurt: we encourage package developers to test against latex-dev as much as they can to avoid surprises all round. Of course we can't catch everything, in particuar I'm not sure if this would have been caught by the previous dev release (and don't want to try to build such a system to check) As I commented above this change wasn't exactly planned (as the documented behavior didn't change, just the old code didn't have the checks documented) so it's always possible that some problems only arise when everything is really put together for a release from the main branch, but in general testing latex-dev should give some months or weeks advance warning of any planned changes.
