### ISSUE TITLE
N'ko improvements

### ISSUE THREAD

**Issue by ghost** [reutenauer/polyglossia#63]
Hi
There are some errors in n'ko support. 
- In generated/examples.pdf, the parentesis are not correctly handled.
- In tex/gloss-nko.ldf, to correctly show the date, please apply the following corrections :
  - replace "ߕߟߋ߬" by "ߕߋ߬ߟߋ߫" if and only if day = 2 or day = 3 or day = 9 or (day >= 20 and day <= 29), otherwise, keep "ߕߟߋ߬"
  - if day = 1, put above "߁", NKO_COMBINING_SHORT_RISING_TONE. Then, you will have : ߁߭

can you add \nkodigits command and inform it in "Non-western decimal digits" section of the manual (generated/polyglossia.pdf) ?
how to use nko digits for page number in a tex file ?

**Comment by bastien-roucaries** [comment]
@reutenauer  Could you do something here ?

**Comment by reutenauer** [comment]
Yes, will do.
