### ISSUE TITLE
Change first item in  alph counter for Algeria, Morocco and Tunisia.

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#640]
In North African countries we usually use letter أ rather then ا as first element in arabic alph counter, please kindly take this into consideration.

```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\abjadmaghribi{1} %  this should be أ not ا 

\end{document}
```

**Comment by jspitz** [comment]
Should be fixed for the next version (with respective `locale` option set).
Please text if possible.

**Comment by seloumi** [comment]
Error `Undefined control sequence \InitializeGlossOptions` appears

```latex 
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage[locale=algeria]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}


\begin{document}
test 
\end{document}

```

**Comment by jspitz** [comment]
You need to download at least `polyglossia.sty` and `arabicnumbers.sty` as well. Best is to test on the whole development repository.

**Comment by seloumi** [comment]
For this example alph counter in second  list  appears `ا`, isn't  supposed to be `أ` ?

```latex 
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage[locale=algeria]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}


\begin{document}

\begin{enumerate}
\item
\begin{enumerate}
\item
\end{enumerate}
\end{enumerate}

\end{document}

```

**Comment by jspitz** [comment]
This employs the `\adjad` counter (not `\abjadmaghribi`). I have added a new commit that addresses the other counter, too. Please test again.

**Comment by seloumi** [comment]
Same issue.

**Comment by jspitz** [comment]
> Same issue.

I don't understand. Here is the output I get from your test document:
![grafik](https://github.com/reutenauer/polyglossia/assets/4538783/a964cb19-05d0-4d3f-9605-e88378edacda)

**Comment by Udi-Fogiel** [comment]
I just realized I gave priority to the initialized key values rather than the users ones in my latest commit, it might be the problem if you are experiencing the problem with a less minimal document, for example with 
```tex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage[locale=algeria]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}


\begin{document}
\selectlanguage{arabic}
\begin{enumerate}
\item
\begin{enumerate}
\item
\end{enumerate}
\end{enumerate}

\end{document}
```
should be fixed now.

**Comment by seloumi** [comment]
Sorry @jspitz it was my fault,  the code work fine, thanks.
