### ISSUE TITLE
wrong script used after \<bcp47-script>font was defined localy

### ISSUE THREAD

**Issue by Udi-Fogiel** [reutenauer/polyglossia#645]
```tex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{hebrew}
\setmainfont{Hadasim CLM}

\begin{document}
\LTR
\fontname\font


{\newfontfamily\hebrewfont{David CLM}
\selectlanguage{hebrew}
\LTR
\fontname\font}

\selectlanguage{hebrew}
\LTR
\fontname\font
\end{document}
```
![image](https://github.com/reutenauer/polyglossia/assets/110533647/26c2e10a-f957-490a-9e3c-e9fbb1af8c69)
If I replace `\hebrewfont` with `\hebrfont` I get
![image](https://github.com/reutenauer/polyglossia/assets/110533647/414599a0-0780-4bc2-961d-21071523e310)

**Comment by jspitz** [comment]
So this is resolved, right? I actually don't know what I could test here.

**Comment by Udi-Fogiel** [comment]
The problem here was that tracing of used scripts was global, lines like `\seq_gput_right:Ne \__xpg_used_script_fonts_rm` were the problem. Should be fixed now.
