### ISSUE TITLE
Enhancement: support Chinese

### ISSUE THREAD

**Issue by cscott** [reutenauer/polyglossia#65]
I'm using `polyglossia` as part of a PDF rendering backend for Wikipedia (see https://npmjs.org/package/mw-ocg-latexer).  It would be nice if polyglossia had even rudimentary support for CJK languages, so I could support ko.wikipedia.org, ja.wikipedia.org, zh.wikipedia.org and embedded CJK text in the other wikis.

**Comment by jspitz** [comment]
Note that Korean and Japanese are supported (at least rudimentally). Thus changing title.

**Comment by hpvd** [comment]
+1

**Comment by jmcelroy01** [comment]
Currently ctex is my workaround.

**Comment by t-tk** [comment]
I tried to create ldf files for Chinese by referring Japanese ldf and tex/latex/ctex/config/ctex-name-utf8.cfg
I do not speak Chinese and I'm not sure whether they are appropriate or not.

https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-chinese.ldf
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-zh-CN.ldf
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-zh-TW.ldf

**Comment by jspitz** [comment]
Thanks, @t-tk! As I do not speak Chinese either, we need a volunteer to audit and test these files.

**Comment by t-tk** [comment]
I added examples of XeLaTeX & polyglossia with multilingual texts:

https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/city0.tex
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/china002.tex
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/china002.pdf

**Comment by jspitz** [comment]
@t-tk, @reutenauer what do you think: shall we add Tanaka-san's gloss file and flag them experimental? This way we probably get most chance for testing and feedback.

**Comment by t-tk** [comment]
@zepinglee in [CTeX-org](https://github.com/CTeX-org) kindly sent a feedback: https://github.com/CTeX-org/ctex-kit/issues/639#issuecomment-1265011929
I can send pull request if you do not mind.

**Comment by jspitz** [comment]
Excellent. Yes, please do. If you could also add documentation, it would be perfect.
