### ISSUE TITLE
conflict with user defined normal size

### ISSUE THREAD

**Issue by Udi-Fogiel** [reutenauer/polyglossia#653]
I've just noticed [this comment](https://tex.stackexchange.com/questions/709820/return-to-the-previous-version-of-polyglossia#comment1765376_709825), can anyone cook a recipe?

**Comment by jspitz** [comment]
I cannot reproduce but I asked back on stackexchange.

**Comment by Udi-Fogiel** [comment]
Thanks, but the user is deleted...

**Comment by jspitz** [comment]
Then I don't think it makes sense to have this ticket open. If there is a real issue, we need a report and a recipe.

**Comment by Udi-Fogiel** [comment]
Ok, I couldn't reproduce so I'll close. There was a valid bug which this user has "reported" before in a random comment in the past, so I thought It might be worth trying.
