### ISSUE TITLE
possible regression for `\pghyphenation` with version 2.2 (2024-07-15)

### ISSUE THREAD

**Issue by dirtyhawk** [reutenauer/polyglossia#654]
Hi,

first and foremost: I'm a happy user of `polyglossia` since many years, and I'm very thankful for the great contribution to LaTeX world. However, for the first time, I stumbled upon a problem I can't resolve myself, and I have the feeling it could be a regression or bug in the package itself, not on my “user” side.

I recently upgraded `polyglossia` to version 2.2 (TeX live 2024 environment, all other packages up to date), as published on 15 July 2024. Now, my documents that use `polyglossia`'s command `pghyphenation` won't compile, throwing the following error:

```
! Undefined control sequence.
<argument> \familytype 
            
l.4 ...-nau-dampf-schiff-fahrts-ka-pi-täns-müt-ze}
```

The result is the same for compiling with `xelatex` and `lualatex`. Here is a minimal example that reproduces the error for me:
```LaTeX
\documentclass{scrartcl}
\usepackage{polyglossia}
\setdefaultlanguage{german}
\pghyphenation{german}{Do-nau-dampf-schiff-fahrts-ka-pi-täns-müt-ze}
\begin{document}
Test.
\end{document}
```

Maybe there is a regression in the current version of `polyglossia`, or a missing package dependency? If not, I'm grateful for any ideas how I can fix this on my side.

All the best, and 1000 thanks for the great work on `polyglossia`
Bela

**Comment by jspitz** [comment]
yes, it's a bug. Workaround is to write before polyglossia is loaded:
```tex
\def\familytype{rm}
```
Thanks for reporting!

**Comment by jspitz** [comment]
Fixed for the next release. The issue here was that the command execution needed to be postponed after the languages have been loaded, as with `\disablehyphenation`

**Comment by jspitz** [comment]
>  I can confirm the workaround works perfectly well.

Note that a better workaround for now is to use
```tex
\AddToHook{begindocument/end}{
  \pghyphenation{german}{Do-nau-dampf-schiff-fahrts-ka-pi-täns-müt-ze}
}
```
since `\pghyphenation` also requires the languages to be loaded, and we do this only at document begin.

**Comment by Udi-Fogiel** [comment]
The language is loaded in the preamble, it is just set after `begindocument`. The only problem is that `\familytype` is not defined, couldn't we just add the line `\tl_new:N \familytype` somewhere in the package instead of postponing everything?

**Comment by jspitz** [comment]
I thought about this but I think it make more sense to initiate the hyphenation exceptions after the languages have been set.

**Comment by jspitz** [comment]
Maybe. I wanted to fix the regression, and that's what I did.

**Comment by Udi-Fogiel** [comment]
> I thought about this but I think it make more sense to initiate the hyphenation exceptions after the languages have been set.

sure, that is the point of `\pghyphenation`, it sets to language locally to make `\hyphenation` work. Why is there a need to postpone the language switch to after `begindocument`?

**Comment by jspitz** [comment]
Go ahead if you think you can improve it.

**Comment by jspitz** [comment]
OK, I have an idea. Hang on.

**Comment by Udi-Fogiel** [comment]
I only thought about taking `qghyphenation` out of the hook and adding `\tl_new:N \familytype` somewhere (which should probably be done anyway).

**Comment by Udi-Fogiel** [comment]
Actually, how about also replacing `\xpg_select_language:nn` with `\__xpg_use_localhyphenmins:nn` in `pghyphentation`?

**Comment by jspitz** [comment]
You probably mean `hyphenrules`. That's what I am currently trying.

**Comment by Udi-Fogiel** [comment]
I'm not sure what is the purpose of all the things `hyphenrules` does besides `\__xpg_use_localhyphenmins:nn` and setting the language options, if it is important, shouldn't we use that inside `\selectlanguage` as well, instead of the raw `\__xpg_use_localhyphenmins:nn`?

**Comment by jspitz** [comment]
`hyphenrules` simply switches the patterns (which `\selectlanguage` does as well, next to other things)
`\__xpg_use_localhyphenmins:nn` initiates the local `hyphenmins` settings, which we do not need for setting up hyphenation exceptions.

**Comment by jspitz** [comment]
I have pushed a simplification

**Comment by jspitz** [comment]
> `hyphenrules` simply switches the patterns (which `\selectlanguage` does as well, next to other things) `\__xpg_use_localhyphenmins:nn` initiates the local `hyphenmins` settings, which we do not need for setting up hyphenation exceptions.

(I mean that we would not need the `\__xpg_use_localhyphenmins:nn` call inside `hyphenrules` for `pghyphenation`, but it doesn't cost us much and the coding of `pghyphenation` is way nicer this way)

**Comment by Udi-Fogiel** [comment]
> `hyphenrules` simply switches the patterns (which `\selectlanguage` does as well, next to other things) `\__xpg_use_localhyphenmins:nn` initiates the local `hyphenmins` settings, which we do not need for setting up hyphenation exceptions.

Oh ok, its the line `\__xpg_use_or_warn:c{\use:c{l_tmp_lang_tl}@language}` which calls `\SetupPolyglossiaLangPatterns` to setup the patterns...

**Comment by Udi-Fogiel** [comment]
> > `hyphenrules` simply switches the patterns (which `\selectlanguage` does as well, next to other things) `\__xpg_use_localhyphenmins:nn` initiates the local `hyphenmins` settings, which we do not need for setting up hyphenation exceptions.
> 
> (I mean that we would not need the `\__xpg_use_localhyphenmins:nn` call inside `hyphenrules` for `pghyphenation`, but it doesn't cost us much and the coding of `pghyphenation` is way nicer this way)

Yes I agree, I like the last commit.

**Comment by jspitz** [comment]
One thing we should probably clarify in the documentation is that the exceptions apply per pattern. This means that language variants that use the same pattern (via `\adddialect`) share the same exceptions. So in practice
`\pghyphenation[spelling=old,variant=austrian]{german}{Fuß-ball-schu-le}`
also applies to `variant=german` (because both use `\l@german`), whereas it does not apply to `spelling=new,variant=austrian` as this employs `\l@ngerman` or `spelling=old,variant=swiss` (which uses `\l@swissgerman`)

**Comment by Udi-Fogiel** [comment]
Section 5.1 is also wrong. 
>These exceptions, however, apply to all languages

as you mentioned, exceptions only applies to the current active patterns.

**Comment by jspitz** [comment]
both fixed at 5849358da2f1c

**Comment by dirtyhawk** [comment]
Thanks for the quick reaction and appropriate fix. The new version on CTAN / in TeX live works like a charm again.

All the best!

**Comment by jspitz** [comment]
Thanks for the feedback.
