### ISSUE TITLE
Typo in doc pag. 14

### ISSUE THREAD

**Issue by Doc73** [reutenauer/polyglossia#655]
In doc we read
```
(as well as the equivalent \begin{lang}[⟨options⟩]{⟨lang⟩} … \end{lang} ←),
```
but we would expect, even from the next example:
```
(as well as the equivalent \begin{lang}[⟨options⟩] … \end{lang} ←),
```
I hope I'm not wrong, anyway thank you very much,
Domenico

**Comment by jspitz** [comment]
No, this is correct. It refers to examples such as
```tex
\begin{lang}[variant=austrian]{german}
...
\end{lang}
```
note the difference between `{lang}` (meant literally) and `{<lang>}` (with `<lang>` being a placeholder for a concrete language)

**Comment by Doc73** [comment]
Thank you very much.
In this case, I would suggest to correct the following example.

**Comment by jspitz** [comment]
> Thank you very much for the clarification! In this case, I would suggest to correct the following example.

The example is correct as well. The paragraph is mainly on the `{<lang>}` environment, which is exemplified here. The equivalent `{lang}` environment is only mentioned in passing (in parantheses).

**Comment by Doc73** [comment]
Ah, yes!
Due to the font the `<` is almost indistinguishable from `(`, at least for me! :smile: 

Thank you very much again, and sorry for the inconvenience.
