### ISSUE TITLE
The language [ is not loaded. 

### ISSUE THREAD

**Issue by daemonenstall** [reutenauer/polyglossia#656]
Using Texlive 2023 with polyglossia 2.0 my document is compiling just fine, but with Texlive 2024 (polyglossia 2.2) I get the following error:

**! Critical Package polyglossia Error: The language [ is not loaded. You must
(polyglossia) load it in order to use it.**

And no, I did not try to load a language called "[". In my preambel it looks like this:

```
\usepackage{polyglossia}
\setmainlanguage{de-DE-1996}
\setotherlanguage{en-US}
```

The error also occurs when I try to compile an empty document.

**Comment by jspitz** [comment]
Please give a full minimal example. The following is working for me:
```tex
% !TeX TS-program = xelatex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{de-DE-1996}
\setotherlanguage{en-US}

\begin{document}
	Test. \textlang{en-US}{hello}.
\end{document}
```

**Comment by daemonenstall** [comment]
Your example is working at my system. The issue seems is related to reledpar. When I comment it out, the error is gone.
https://github.com/maieul/ledmac/issues/974
```
% !TeX TS-program = xelatex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{de-DE-1996}
\setotherlanguage{en-US}
\usepackage[series={},nocritical,noend,noeledsec,nofamiliar,noledgroup]{reledmac}
\usepackage{reledpar}

\begin{document}
	Test. \textlang{en-US}{hello}.
\end{document}
```

**Comment by daemonenstall** [comment]
Since the reledpar team is already working on the issue, this one can be closed.

**Comment by jspitz** [comment]
OK, thanks.
