### ISSUE TITLE
\autoref labels from hyperref package are not translated with polyglossia, but with babel

### ISSUE THREAD

**Issue by castilma** [reutenauer/polyglossia#658]
Polyglossia's documentation says it is a complete replacement for the babel package.
However if I use babel, the labels with \autoref from hyperref get translated:
```
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage{hyperref}

\begin{document}
\begin{table}
 \caption{beschreibung}
\label{tab}
\end{table}
\autoref{tab}  % outputs Tabelle 1
\end{document}
```
But with polyglossia, without babel, they don't
```
\documentclass{article}
%\usepackage[ngerman]{babel} % works as intended if uncommented
\usepackage{polyglossia}
\setdefaultlanguage{ngerman}

\usepackage{hyperref}
%\hypersetup{pdflang={ngerman}} % doesn't help

\begin{document}
\begin{table}
 \caption{beschreibung}
\label{tab}
\end{table}
\autoref{tab} % outputs Table 1
\end{document}
```
It works if import babel in addition to polyglossia, but I fear this might not be optimal/break something or waste cpu time (since polyglossia claims to be a complete replacement). Is this unproblematic to do?

I'm using lualatex and use the texlive-* 2024.2-2 packages from archlinux.

**Comment by mbertucci47** [comment]
The support for autoref translations is provided by hyperref, not babel. They way hyperref automatically picks up the language works only for babel. But you can still provide the `ngerman` option directly to hyperref, or as a class option.
```tex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{ngerman}
\usepackage[ngerman]{hyperref}

\begin{document}
\begin{table}
 \caption{beschreibung}
\label{tab}
\end{table}
\autoref{tab}  % outputs Tabelle 1
\end{document}
```

**Comment by jspitz** [comment]
Please report at hyperref
