### ISSUE TITLE
Spurious spaces in Serbian

### ISSUE THREAD

**Issue by Derek61** [reutenauer/polyglossia#660]
Consider
```
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguages{serbian,spanish}

\newfontfamily{\cyrillicfont}{Palatino}

\begin{document}
A\textserbian{B}C

A\textspanish{B}C
\end{document}
```
Compiling with XeLaTeX yields
<img width="132" alt="image" src="https://github.com/user-attachments/assets/026ba7af-beb2-487f-8f8c-4ba031e821e5">
It would seem likely that a missing "%" is to blame.

**Comment by Udi-Fogiel** [comment]
Good catch, thanks! I think it is fixed now if you want to test.

**Comment by kae-vm** [comment]
This issue also exists in Sanskrit! 
![image](https://github.com/user-attachments/assets/097fe23d-0d48-4c8c-b6e3-644e2802b292)

**Comment by jspitz** [comment]
> This issue also exists in Sanskrit! 

Not for very much longer.

**Comment by kae-vm** [comment]
it's perfect now, thank you!
