### ISSUE TITLE
Error if polyglossia is used with LuaLaTeX, a font with a name containing a space and a 'book-like' class

### ISSUE THREAD

**Issue by cfr42** [reutenauer/polyglossia#667]
The following example fails if compiled with `lualatex`. It seems any font with a space in the name will trigger the problem, but only if the class is 'book-like'. So e.g. `article` is fine. 

```latex
\documentclass{book}
\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}
\setmainfont{Minion Pro}
\begin{document}
test
\end{document}
```
The example works if:
- `fontspec` is loaded, but not `polyglossia`,
- `article` is substituted for `book`,
- default fonts are used,
-  XeTeX is used rather than LuaTeX,
- a font without a space in the name such as `Crimson` is substituted for `Minion Pro`.

ref.: https://tex.stackexchange.com/q/730204/ [but there's some sort of fontconfig weirdness there, which isn't relevant to LuaTeX anyhow and XeTeX has no problem].

The log (attached) seems to show `fontspec` sets the family up correctly, but LaTeX ends up looking for `MinionPro` rather than `Minion Pro`. So some interaction with `polyglossia` causes the space to be lost.

[prawf-2.log](https://github.com/user-attachments/files/17651927/prawf-2.log)

**Comment by Udi-Fogiel** [comment]
I think you already encountered that issue :) 
https://github.com/reutenauer/polyglossia/issues/650

Is there anything new?

**Comment by cfr42** [comment]
> Is there anything new?
No. I just didn't remember `polyglossia` changed the renderer until David Carlisle reminded me. I would have deleted this, but that doesn't seem to be possible. Apologies for the noise.

**Comment by Udi-Fogiel** [comment]
@cfr42 All good. I which `luaotfload` would release a fix already...
