### ISSUE TITLE
French conventions are not reset

### ISSUE THREAD

**Issue by mredaelli** [reutenauer/polyglossia#68]
The following file:

``` tex
\documentclass[a4paper]{article}
\usepackage{luatextra}
\usepackage{polyglossia}
\setmainlanguage{italian}
\setotherlanguage{french}
\begin{document}
ciao: ecco

\begin{french}
ciao: ecco
\end{french}

ciao: ecco
\end{document}
```

gives a correct space before the column in the second paragraph, but an incorrect space in the third paragraph.

I have a feeling that \nofrench@punctuation (i.e., \noextrascurrent) is not called when \end{french} is called. And in fact adding that after \end{french} everything works again.

(Actually, I also uncommented the line with       \directlua{polyglossia.desactivate_frpt()}
in loss-french.ldf. I'm not sure if that's necessary - but from the comments just above it, I'd say so :) )

**Comment by hugoroy** [comment]
I cannot reproduce this with XeLaTeX (removing the `luatextra` package)

**Comment by adunning** [comment]
I can confirm that this does not occur under XeTeX. It also happens when using `\textfrench`, as in this example:

```tex
\documentclass[english]{article}
\usepackage{polyglossia}
\setmainlanguage[]{english}
\setotherlanguage[]{french}

\begin{document}

What a jolly idea! Let us do this at 8:00.

\textfrench{essai}

What a jolly idea! Let us do this at 8:00.

\end{document}
```

**Comment by eg9** [comment]
Related to this problem:

http://tex.stackexchange.com/questions/186156/changing-language-back-and-forth-with-polyglossia

http://tex.stackexchange.com/questions/234487/polyglossia-and-hookrightarrow

**Comment by matteocoder** [comment]
Are there any updates on this issue?
