### ISSUE TITLE
Bengali numerals not working.

### ISSUE THREAD

**Issue by haseebmahmud** [reutenauer/polyglossia#69]
Consider the answer from this post
http://tex.stackexchange.com/questions/99606/how-to-write-bengali-in-latex

The Bengali numerals should look like
০, ১, ২, ৩, ৪, ৫, ৬, ৭, ৮, ৯, ১০

Not like this.
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

**Comment by chudur-budur** [comment]
same here, I am setting the options like this --

\setdefaultlanguage[numerals=Bengali]{bengali}
\setotherlanguage{english}
\setmainfont[Script=Bengali]{Lohit Bengali}

I am getting everything nicely except the numerals, please let us know how to fix, we like polyglossia.

**Comment by bastien-roucaries** [comment]
@chudur-budur  Could you get a glimpse at tex/gloss-greek.lds and do the same for bengali ?
