### ISSUE TITLE
no equation number for dmath inside english environment

### ISSUE THREAD

**Issue by ghost** [reutenauer/polyglossia#7]
\documentclass{article}
\usepackage{breqn}
\usepackage{polyglossia}
\setmainlanguage{farsi}
\setotherlanguage{english}
\newfontfamily\farsifont[Script=Arabic]{XB Zar}
\begin{document}
\begin{english}
\begin{dmath}
1+2=3
\end{dmath}
\end{english}
\end{document}

No equation number, in addition you get incorrect parentheses around equation number. I can not comment on the first issue but second issue is because polyglossia package does not make use of \if@Latin boolean of bidi package. This boolean should be true for LTR scripts (like english) and false for RTL scripts (like Persian).

**Comment by vafa** [comment]
I can not believe that this has not been fixed after 4 years; if you do not have time, please look for a new maintainer!
