### ISSUE TITLE
hebrewcal - missing quotes in hebrewday and year

### ISSUE THREAD

**Issue by idoh** [reutenauer/polyglossia#73]
When generating hebrew date there are missing quotes in hebrew day and year.

Changing all \hebrewnumeral in hebrewcal.sty into \Hebrewnumeral solved it.

**Comment by guyru** [comment]
I've encountered the same issue as well and made a [pull request](https://github.com/reutenauer/polyglossia/pull/94) that fixes it.

**Comment by reutenauer** [comment]
Thanks for the report, it’s now fixed by Guy’s pull request.
