### ISSUE TITLE
Enable indentfirst for Russian

### ISSUE THREAD

**Issue by alexshpilkin** [reutenauer/polyglossia#78]
Typesetting in Russian (and probably languages with related typesetting conventions such as Ukrainian and Belorussian) always uses indented paragraphs, including the first one of the section. So `indentfirst=true` should be set in `gloss-russian`.

If we’re to be pedantic, the Russian tradition differs in that the indent occurs even after a centered heading, where it would be omitted in French. (I believe `polyglossia` doesn’t currently handle this case anyway.)

**Comment by bastien-roucaries** [comment]
@alexshpilkin  Do you have reference of this on usual manual of style of russian ?

**Comment by alexshpilkin** [comment]
@bastien-roucaries I’m afraid not; I’m not even sure where I’d go looking for a Russian style guide. You probably need to consult someone who’s actually in the business of making books, I’m afraid.

That said, I can photograph some pages from actual Russian books:

1. Ландау и Пятигорский, _Механика_, ГИТТЛ 1940: ![1](https://user-images.githubusercontent.com/1010468/61750385-ee45a580-adad-11e9-8bea-38ba986de0a4.jpg)
2. Курош, _Курс высшей алгебры_, Физматгиз 1959: 
![2](https://user-images.githubusercontent.com/1010468/61750523-4f6d7900-adae-11e9-9fb7-66174550dbf7.jpg)
3. Арнольд, _Математические методы классической механики_, Наука 1979: 
![3](https://user-images.githubusercontent.com/1010468/61750565-6ad88400-adae-11e9-8803-7c94da06fef9.jpg)
4. Эйдельман, _Твой 18-й век / Прекрасен наш союз..._, Мысль 1991: ![4](https://user-images.githubusercontent.com/1010468/61750618-83489e80-adae-11e9-9aa2-fe0f477dbb8f.jpg)
5. Березин, _Лекции по статистической физике_, МЦНМО 2008: 
![5](https://user-images.githubusercontent.com/1010468/61750716-b7bc5a80-adae-11e9-99cb-1d1cb7eab051.jpg)

**Comment by ivankokan** [comment]
Hi, I would obey Alexandra Korolkova. Living typography. - IndexMarket, 2010. - 224 p. - ISBN 978-5-9901107-5-5, check its page 186 (https://mooc.lektorium.tv/asset-v1:Lektorium+KDOK1+2017_09+type@asset+block@LiveTypo4_small-compressed.pdf), and translate it for us.

Printed books themselves do not necessarily follow the typographic rules, hence I find the referred bibliography most reliable, whatever its says.

Kind regards, Ivan

**Comment by ivankokan** [comment]
> Hi @alexshpilkin,
> 
> I would obey Alexandra Korolkova. Living typography. - IndexMarket, 2010. - 224 p. - ISBN 978-5-9901107-5-5, check its page 186 (https://mooc.lektorium.tv/asset-v1:Lektorium+KDOK1+2017_09+type@asset+block@LiveTypo4_small-compressed.pdf), and translate it for us.
> 
> Printed books themselves do not necessarily follow the typographic rules, hence I find the referred bibliography most reliable, whatever it says.
> 
> Kind regards, Ivan

Hi @alexshpilkin, can you translate what it says?

**Comment by jspitz** [comment]
According to DeepL, it doesn't say much other than there are specific ways to separate paragraphs (including indentation). According to a quick web search, indentation of paragraphs after headings seem to be a frequent request of Russian LaTeX users.

Babel-russian had the feature but disabled it again in v. 1.2:
```
    * russian/russianb.dtx, v1.2a : Indentation of 1st paragraph removed;
      use the indentfirst package to automatically indent first paragraph
      after sectioning commands.
```

**Comment by jspitz** [comment]
I think @alexshpilkin provided enough evidence that this is common in Russian typesetting, and we've seen no counter-evidence. So I added the feature. I also added an option indentfirst, though, for people to opt-out easily.

Note that this is not in `polyglossia 1.45` (released today), but only in the next version.
