### ISSUE TITLE
Improve Armenian support

### ISSUE THREAD

**Issue by axper** [reutenauer/polyglossia#79]
Currently the package uses Western Armenian month names. Is it possible to add support for Western Armenian month names as well?

```
\def\datearmenian{%
   \def\today{\ifcase\month\or
    Հունվար\or
    Փետրվար\or
    Մարտ\or
    Ապրիլ\or
    Մայիս\or
    Հունիս\or
    Հուլիս\or
    Օգոստոս\or
    Սեպտեմբեր\or
    Հոկտեմբեր\or
    Նոյեմբեր\or
    Դեկտեմբեր\fi
    \number\day,\space\number\year}}
```

By the way, is there a need for translating other things like caption names to Armenian?

**Comment by bastien-roucaries** [comment]
@axper  Yes they are a need. Pull request are welcome. see gloss-armenian.lds
