### ISSUE TITLE
LuaTeX-Support

### ISSUE THREAD

**Issue by zephyr** [reutenauer/polyglossia#8]
polyglossia should work with the LuaTeX engine as well as now with XeTeX.

This is important because LuaTeX is going to be the most important future engine (and not XeTeX) – and certainly we don’t want to go back to babel.

See also: https://github.com/fc7/polyglossia/issues/12

**Comment by jspitz** [comment]
LuaTeX generally is supported. Only in some languages there are deficiencies.

I propose to close this general ticket and file specific reports which can then be more easily identified and addressed.

**Comment by reutenauer** [comment]
Indeed it is!
