### ISSUE TITLE
problem to show labels using enumerate package with polyglossia

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#80]
with this MWE

```
\documentclass{article}
\usepackage{enumerate}
\usepackage{fontspec}
\usepackage{polyglossia}
\newfontfamily\arabicfont[Script=Arabic,Scale=1.3]{Amiri}
\setdefaultlanguage{arabic}
\setotherlanguage{english}
\begin{document}

\begin{english}
\begin{enumerate}[{example}- a)]
\item text
\item text
\item text
\item text
\end{enumerate}
\end{english}

\end{document}
```

compiled with `XeLaTeX` labels 'a','b',... Does not appear in the output 

take a look at : http://tex.stackexchange.com/questions/194424/problem-to-show-labels-using-enumerate-package-with-polyglossia

**Comment by jspitz** [comment]
This is fixed in master with https://github.com/reutenauer/polyglossia/commit/e8aa0c59a6e5ab910984e95b0c78010eb46a10bc

Someone who can please close this ticket.

**Comment by reutenauer** [comment]
Closing!
