### ISSUE TITLE
German babelshorthands & fontawesome produce an error

### ISSUE THREAD

**Issue by freeo** [reutenauer/polyglossia#81]
Here's my minimal example:

```
% arara: lualatex
\documentclass{article}
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{german}
% \setmainlanguage{german}
\usepackage{fontawesome}

\begin{document}
Test \faPhone test
\end{document}
```

Which results in the following error:

```
! Missing number, treated as zero.
<to be read again>
\penalty
l.12     Test \faPhone
                     test
```

German babelshorthands seem to be the issue, as I couldn't reproduce the error with dutch and catalan shorthands.

**Comment by jspitz** [comment]
Alas, shifting the activation to (etoolbox's) `\AfterPreamble` does not help in this case.

Incidentally, the package fontawesome5 does not seem to show the same problem.

**Comment by wehro** [comment]
Note that the following code works.
```
\documentclass{article}
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{german}
\shorthandoff{"}
\usepackage{fontawesome}

\begin{document}
Test \faPhone test
\end{document}
```
It is worth to experiment with `\shorthandoff` within the gloss files.

**Comment by jspitz** [comment]
Sure. But why? We only activate shorthands at the beginning of the document (in the `\polyglossia@AtBeginDocument@selectlanguage` hook), so why are they active already before?

**Comment by jspitz** [comment]
OK, I tried now, and indeed, the following seems to help:
```diff
diff --git a/tex/gloss-german.ldf b/tex/gloss-german.ldf
index 969cfd3..e562ba5 100644
--- a/tex/gloss-german.ldf
+++ b/tex/gloss-german.ldf
@@ -80,6 +80,7 @@
 \ifcsundef{initiate@active@char}{%
 \input{babelsh.def}%
 \initiate@active@char{"}%
+\shorthandoff{"}
 }{}
 
 \def\german@shorthands{%
```

Same for #200

**Comment by jspitz** [comment]
I committed this fix for all glosses except latin.
