### ISSUE TITLE
Variant in other language causes error

### ISSUE THREAD

**Issue by AndrewSwann** [reutenauer/polyglossia#86]
Unfortunately the following loading of `english` with `variant=british` causes an error under `lualatex` when the `.aux` file is read on the second run.  Removing the `variant` option stops the problem.  Adding a `variant=british` to the language environment does not help.

    \documentclass{article}
    
    \usepackage{polyglossia}
    
    \setdefaultlanguage{danish}
    \setotherlanguage[variant=british]{english}
    
    \begin{document}
    
    Dansk.
    
    \begin{english}
      Test.
    \end{english}
    
    \end{document}

The specific error is 

```
(./b1.aux
! LuaTeX error ...e/2014/texmf-dist/tex/luatex/hyph-utf8/luatex-hyphen.lua:60: l
uatex-hyphen: \language0 should be dumped in the format
stack traceback:
	[C]: in function 'error'
	...e/2014/texmf-dist/tex/luatex/hyph-utf8/luatex-hyphen.lua:21: in function 'er
r'
	...e/2014/texmf-dist/tex/luatex/hyph-utf8/luatex-hyphen.lua:60: in function 'lo
adlanguage'
	...ve/2014/texmf-dist/tex/latex/polyglossia/polyglossia.lua:28: in function 'lo
adlang'
	...ve/2014/texmf-dist/tex/latex/polyglossia/polyglossia.lua:33: in function 'se
lect_language'
	[\directlua]:1: in main chunk.
\select@language ...\the \csname l@#1\endcsname )}
                                                  \fi \fi \xpg@initial@setup...
l.6 \select@language {english}
```

I am running

    This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971) 

with

    Package: polyglossia 2014/05/21 v1.33.5

**Comment by jspitz** [comment]
I just want to highlight (since this is not very clear from the report) that this error _only_ happens with variant=british, not with any other english variant, nor with other languages and their variants.

So this must be due to the special code in gloss-english.ldf.

**Comment by reutenauer** [comment]
Thanks for the precision, Jürgen, and for the initial report.  I will try and have a look this week.

**Comment by jspitz** [comment]
Arthur, the error is triggered by line 55 in `gloss-english.ldf`:

    \setkeys[xpg@setup]{english}{hyphennames={ukenglish,british,UKenglish}}%

Removing it cures the problem for me.

Is this line really needed? I thought that line 60 would be enough to set the correct hyphenation pattern:

    \gdef\english@language{\language=\l@ukenglish\xpg@set@language@luatex@ii{ukenglish}}

**Comment by reutenauer** [comment]
Thank you, I just pushed a fix for that.  The key-value mechanism is originally by François and I wasn't sure how to adapt it to LuaTeX where you need to load patterns at runtime.  For the moment I'm just deactivating when running LuaTeX.

I'll make an upload to CTAN in the next few days.

**Comment by jspitz** [comment]
Thanks. There is a typo in line 55 (\f: > \fi):
    \ifluatex\else\setkeys[xpg@setup]{english}{hyphennames={ukenglish,british,UKenglish}}\f:

**Comment by reutenauer** [comment]
Oh dear, how embarrassing :-)  My tests did pick it up, but thank you anyway.

**Comment by reutenauer** [comment]
The release with the fix is on CTAN.  Please test if you can and report.

**Comment by jspitz** [comment]
Works for me (unsurprisingly).

**Comment by AndrewSwann** [comment]
Works well.  Many thanks for the fix.

**Comment by reutenauer** [comment]
Great to hear, Andrew, closing the issue.
