### ISSUE TITLE
french and footnotes : babel imitation

### ISSUE THREAD

**Issue by maieul** [reutenauer/polyglossia#87]
Hi, 

with Babel, there is an option (active by default) to print the footnote number not in uperscript, but in normal case with a dot. Like this 

```
\documentclass{article}
\usepackage[french]{babel}
\begin{document}

~
\vfill

Lorem Ipsum Dolor Amet\footnote{Ceci est une note de bas de page.}.
\end{document}
```

Should it be possible to have the same feature in polyglossia?

**Comment by johannesbottcher** [comment]
Related and close enough to add it here. 

With `babel`, a thin space is inserted right before the footnotemark (usually a superscript) in the body text. This space is not available with `polyglossia`. Should it be, may be *opt-in*?

**Comment by jspitz** [comment]
See also issue #12.

**Comment by hugoroy** [comment]
I think this is fixed. @reutenauer ?

**Comment by maieul** [comment]
We can close, I think. cf #174 #157
