### ISSUE TITLE
With hebrew language, LaTeX keeps suggesting to rerun to get cross-references right.

### ISSUE THREAD

**Issue by giordano** [reutenauer/polyglossia#88]
Consider the following document

``` latex
\documentclass{article}
\usepackage{libertine}
\usepackage{polyglossia}
%\setdefaultlanguage{hebrew}
\begin{document}
Hello, world!
\end{document}
```

Everything goes as expected as long as the default language is not set, but if you uncomment the `

``` latex
\setdefaultlanguage{hebrew}
```

line the output log will always emit a

```
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
```

message.

This has been reported on Emacs Stack Exchange http://emacs.stackexchange.com/q/7134/620 because this bug fools AUCTeX making it believe the user always need to rerun LaTeX.

**Comment by jspitz** [comment]
Someone who can please close this ticket.
