### ISSUE TITLE
\sffamily and other font commands made fragile

### ISSUE THREAD

**Issue by davidcarlisle** [reutenauer/polyglossia#90]
As reported on tex.sx

http://tex.stackexchange.com/questions/227960/clash-polyglossia-and-pagenote/227966#227966

`\sffamily` is made fragile as it has `\def\familytype{sf}` appended.

The intention was to append it to the internal macro `sffamily_` 

```latex
% This robustifies the redefinitions of \<xx>family (suggestion by Enrico Gregorio)
% e.g. to prevent expansion of the \familytype redefinition in auxiliary files
\csgappto{rmfamily }{\def\familytype{rm}}
\csgappto{sffamily }{\def\familytype{sf}}
\csgappto{ttfamily }{\def\familytype{tt}}
```

But this file is using `\ExplSyntaxOn` so the space is not seen, you need `\csgappto{sffamily~}`

Although actually this comment seems wrong

```latex
% fontspec now uses LaTeX3 packages such as expl3, so we need this:
\ExplSyntaxOn
```

I can't see any need to use L3 syntax in this file?

**Comment by eg9** [comment]
`\ExplSyntaxOn` is needed only for the definitions of `\xpg@addfontfeature@lang` and `\xpg@addfontfeature@script` (lines 298 and 318) respectively.

**Comment by adimit** [comment]
This is also a problem when `\sffamily` occurs in a title. You'll need to run xetex twice to trigger it, since the `.toc` file has to be compiled first, and then included.

Minimal working example to trigger it:

    \documentclass{article}
    \usepackage{polyglossia}
    %\typeout{\meaning\sffamily}
    %\protected\edef\sffamily{\expandafter\unexpanded\expandafter{\sffamily}}
    %\typeout{\meaning\sffamily}
    \setdefaultlanguage{english}
    \begin{document}
    \tableofcontents
    \section{\bfseries\sffamily TODO}
    \end{document}

The following line in the `.toc` file is the problem:

    \contentsline {section}{\numberline {1}\bfseries \sffamily \def rm{sf}TODO}{1}

The exact error message is:

    (./test.toc
    ! Missing control sequence inserted.
    <inserted text> 
                   \inaccessible 
    l.2 ... {1}\bfseries \sffamily \def rm{sf}TODO}{1}

(I'm leaving this here so people can Google for it.)
    
Uncomment the three commented lines in the above example to work around this bug.

**Comment by reutenauer** [comment]
Thanks for the report and the details, I’ve just pushed a commit from one month ago that fixes it.  Please confirm it solves the issue.

**Comment by adimit** [comment]
Can confirm it works with latest polyglossia. Thanks for fixing the issue! (the above workaround is no longer required.)

**Comment by reutenauer** [comment]
Great, glad to hear it!
