### ISSUE TITLE
Code for French punctuation breaks math with LuaLaTeX

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#92]
This minimal example shows the problem (see http://tex.stackexchange.com/questions/234487/polyglossia-and-hookrightarrow)

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\begin{document}
$\hookrightarrow$
\showoutput
\end{document}
```

![screen shot 2015-03-22 at 18 08 44](https://cloud.githubusercontent.com/assets/302839/6770383/afb9149e-d0be-11e4-962d-b1f79e214971.png)

The relevant information from `\showoutput` is

```
....\mathon
....\OML/cmm/m/it/10 ,
....\hbox(0.0+0.0)x-1.66663, direction TLT
.....\kern -1.66663
....\penalty 10000
....\kern1.6667
....\OMS/cmsy/m/n/10 !
....\mathoff
```

where it's clearly visible that `\rightarrow`, which occupies the slot of the exclamation mark in OMS encoded fonts, is treated as if it was a textual exclamation mark. The definition of `\hookrightarrow` is `\lhook\joinrel\rightarrow`. In particular, the backup produced by `\joinrel` is nullified by the “before exclamation mark” kern.

The effect of `polyglossia.activate_frpt()` should not influence math mode at all.

Other characters from OML and OMS encodings are affected as seen in http://tex.stackexchange.com/a/234494/4427 ; usage of characters from an OMX encoded font could produce even worse results.

**Comment by reutenauer** [comment]
Thanks for the report, Enrico, and for investigating the root cause.  Interesting bug :-)  I’ll see what I can do about that.  There are a number of issues with French support in Polyglossia, especially with LuaTeX.

**Comment by eg9** [comment]
I have updated the report; the problem with `\hookrightarrow` seems due to `\rightarrow`, rather than `\lhook`, but the result is the same.
