### ISSUE TITLE
Bugs in gloss-hebrew.ldf and babel-hebrewalph.def

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#93]
As defined, the `\hebrewnumeral` command will write the argument literally in auxiliary files; a command such as `\chapter{title}` will write

```
\hebrewnumeral{\c@chapter}
```

A two step approach is needed: `\hebrewnumeral{<arg>}` expands to

```
\expandafter\@hebrew@numeral\expandafter{\the\numexpr<arg>}
```

so that the annotation in the `.aux` files will be correct. The command to make robust is `\@hebrew@numeral`.

Also `\hebrewnumber`, `\hebrew@globalnumbers` and `\nohebrew@globalnumbers` have faulty definitions with `\protect` that is out of place.

Suggested edits in `gloss-hebrew.def`: lines 103 to 109 should become

```
\def\hebrewnumber#1{%
   \if@hebrew@numerals
     \hebrewnumeral{#1}%
   \else
     \number#1%
   \fi
}
```

Lines 122 to 130 should become

```
\def\hebrew@globalnumbers{%
   \let\orig@arabic\@arabic%
   \let\@arabic\hebrewnumber%
   \renewcommand\thefootnote{\hebrewnumber{\c@footnote}}%
}
\def\nohebrew@globalnumbers{%
  \let\@arabic\orig@arabic%
  \renewcommand\thefootnote{\@arabic\c@footnote}%
}
```

Changes in `babel-hebrewalph.def`: lines 7 to 25 should become

```
\newcommand*\hebrewnumeral[1]{%
  \expandafter\@hebrew@numeral\expandafter{\the\numexpr#1}%
}
\newcommand*\Hebrewnumeral[1]{%
  \expandafter\@Hebrew@numeral\expandafter{\the\numexpr#1}%
}
\newcommand*\Hebrewnumeralfinal[1]{%
  \expandafter\@Hebrew@numeralfinal\expandafter{\the\numexpr#1}%
}
\newrobustcmd*{\@hebrew@numeral}[1]      % no apostrophe, no final letters
 {{\@gim@finalfalse\@gim@apostfalse\@hebrew@@numeral{#1}}}
\newrobustcmd*{\@Hebrew@numeral}[1]      % apostrophe, no final letters
 {{\@gim@finalfalse\@gim@aposttrue\@hebrew@@numeral{#1}}}
\newrobustcmd*{\@Hebrew@numeralfinal}[1] % apostrophe, final letters
 {{\@gim@finaltrue\@gim@aposttrue\@hebrew@@numeral{#1}}}
\newcommand*{\@hebrew@@numeral}[1]{%
  \ifnum#1<\z@\space\xpg@warning{Illegal value (#1) for Hebrew numeral}%
  \else
    \@tempcnta=#1\@tempcntb=#1\relax
    \divide\@tempcntb by 1000
    \ifnum\@tempcntb=0\gim@nomil\@tempcnta\relax
    \else{\@gim@apostfalse\@gim@finalfalse\@hebrew@numeral\@tempcntb}׳%
          \multiply\@tempcntb by 1000\relax
          \advance\@tempcnta by -\@tempcntb\relax
          \gim@nomil\@tempcnta\relax
    \fi
  \fi
}
```

Line 78 should become

```
\providecommand*{\@Alphfinal}[1]{\Hebrewnumeralfinal{#1}}
```

Reference for an example file: http://tex.stackexchange.com/questions/112890/numbering-in-toc-does-not-work-with-hebrew-numerals

**Comment by jspitz** [comment]
I think we have a similar issue in arabic (with footnotes at least). @eg9 do have an idea?

**Comment by jspitz** [comment]
> I think we have a similar issue in arabic (with footnotes at least). @eg9 do have an idea?

Never mind. Fixed at https://github.com/reutenauer/polyglossia/commit/a2305ccdc599016b1dfc370a63d98acae859460e.
