### ISSUE TITLE
german and tikz-cd incompatibility

### ISSUE THREAD

**Issue by stev47** [reutenauer/polyglossia#95]
I'm compiling

``` latex
\documentclass{standalone}

\usepackage{tikz}
\usepackage{tikz-cd}
\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}

\begin{tikzcd}
    a \ar[r,"c"] & b
\end{tikzcd}

\end{document}
```

and getting the error

```
! Package pgfkeys Error: I do not know the key '/tikz/"c"' and I am going to ig
nore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help
...
l.11 I think the culprit is a tikzcd arrow in cell 1-1.
\errmessage ...currentrow -\tikzcd@currentcolumn }

l.12 \end{tikzcd}
```

Note that changing `\setmainlanguage{german}` to `\setmainlanguage{english}` works.
The line `\initiate@active@char{"}%` in `tex/gloss-german.ldf` seems to be the culprit: uncommenting it solves the problem.

Note that this happens regardless of the `babelshorthands` options and even setting `\bbl@deactivate{"}` manually afterwards doesn't work.

**Comment by jspitz** [comment]
Note that the example file compiles if you load
`\usetikzlibrary{babel}`
before loading tikzcd (as advised in section 3.4 of the tikzcd manual).

I am not sure this is a polyglossia bug.

**Comment by stev47** [comment]
Thank you for pointing me to the right place, that is indeed a good workaround.

I'd still argue, that polyglossia shouldn't mess around with the catcodes as long as I'm not telling it to do so. Isn't that why the `babelshorthands` option was introduced in the first place (instead of just adopting babels defaults)?

**Comment by gnull** [comment]
@jspitz, I'm experiencing a similar issue with Russian language. I can't compile (using xelatex) the following example:

```latex
\documentclass[a4paper,12pt]{article}

\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{russian}
\setotherlanguage{english}
\setkeys{russian}{babelshorthands=true}

\defaultfontfeatures{Ligatures=TeX}
\setmainfont{Times New Roman}
\newfontfamily\cyrillicfont{Times New Roman}

% \usepackage{tikz}
% \usetikzlibrary{babel}

\usepackage{tikz-cd}

\begin{document}

\[
\begin{tikzcd}[column sep=small]
X \arrow[r, "f"] & Y
\end{tikzcd}
\]

\end{document}
```

Neither enabling `\usetikzlibrary{babel}` nor removing the line `\setkeys{russian}{babelshorthands=true}` fixes compilation errors. (Although the errors messages themselves change.)

But, if I replace the part

```latex
\setmainlanguage{russian}
\setotherlanguage{english}
\setkeys{russian}{babelshorthands=true}
```

with `\setmainlanguage{english}` the document compiles perfectly.

Do you have any idea what could cause this problem? (I'm not sure if it is polyglossia bug.)

**Comment by jspitz** [comment]
No idea, sorry.

**Comment by jspitz** [comment]
I had a closer look at this once more. The problem comes from the line
```tex
\initiate@active@char{"}%
```
which we issue in the gloss files that use shorthands. As this command can only be used in the preamble, we need to do it unconditionally, as babel shorthands might be activated only locally in the body, and this does not work without the above activating.

We could do the activation later in the preamble, but this does not help for tikz. So the only solution, as advised in the tikz and tikzcd manuals, is to load the babel tikz library, indeed. This seems to be the same with babel.

Thus, we can only close this report.

**Comment by wehro** [comment]
Possible solution: Say `\shorthandoff{"}` and `\AtBeginDocument{\shorthandon{"}}` in `gloss-german.ldf` and similar files after `\initiate@active@char{"}`.
This is what I plan to do for the active `=` in `gloss-latin.ldf`, because an active `=` is even more dangerous than an active `"`.

**Comment by jspitz** [comment]
> Possible solution: Say `\shorthandoff{"}` and `\AtBeginDocument{\shorthandon{"}}` in `gloss-german.ldf` and similar files after `\initiate@active@char{"}`.

This does not help here either.

**Comment by eg9** [comment]
This is similar to #200 
Besides loading the `babel` library, packages should be loaded _before_ doing setup.
```latex
\documentclass{standalone}

\usepackage{polyglossia}
\usepackage{tikz}
\usetikzlibrary{babel}
\usepackage{tikz-cd}

\setmainlanguage{german}

\begin{document}

\begin{tikzcd}
    a \ar[r,"c"] & b
\end{tikzcd}

\end{document}
```

**Comment by jspitz** [comment]
> @gnull, in your case, loading tikzcd before polyglossia helps:
> 
> ```
> \documentclass[a4paper,12pt]{article}
> 
> \usepackage{tikz}
> \usetikzlibrary{babel}
> \usepackage{tikz-cd}
> 
> \usepackage{polyglossia}
> \setmainlanguage{russian}
> \setotherlanguage{english}
> \setkeys{russian}{babelshorthands=true}
> 
> \defaultfontfeatures{Ligatures=TeX}
> \setmainfont{Times New Roman}
> \newfontfamily\cyrillicfont{Times New Roman}
> 
> \begin{document}
> 	
> 	\[
> 	\begin{tikzcd}[column sep=small]
> 	X \arrow[r, "f"] & Y
> 	\end{tikzcd}
> 	\]
> 	
> \end{document}
> ```

After 0cb40fca6cf6a3e496, this example also works in the original order. But still the babel tiks library is mandatory.

**Comment by gnull** [comment]
> @gnull, in your case, loading tikzcd before polyglossia helps:
> 
> ```
> \documentclass[a4paper,12pt]{article}
> 
> \usepackage{tikz}
> \usetikzlibrary{babel}
> \usepackage{tikz-cd}
> 
> \usepackage{polyglossia}
> \setmainlanguage{russian}
> \setotherlanguage{english}
> \setkeys{russian}{babelshorthands=true}
> 
> \defaultfontfeatures{Ligatures=TeX}
> \setmainfont{Times New Roman}
> \newfontfamily\cyrillicfont{Times New Roman}
> 
> \begin{document}
> 	
> 	\[
> 	\begin{tikzcd}[column sep=small]
> 	X \arrow[r, "f"] & Y
> 	\end{tikzcd}
> 	\]
> 	
> \end{document}
> ```

@jspitz, thank you for this solution! Yes, I tried it now and it works out of the box on my Archlinux.
