### ISSUE TITLE
Typo in the CTAN documentation of one of the Latin language's variants

### ISSUE THREAD

**Issue by kalrish** [reutenauer/polyglossia#98]
[The documentation for this package](http://osl.ugr.es/CTAN/macros/latex/contrib/polyglossia/polyglossia.pdf), as offered at [its CTAN page](https://www.ctan.org/pkg/polyglossia?lang=en), lists `classical` as one of the variants of the Latin language. However, as of the 2015 version of TeX Live, this isn't correct. The correct name of that variant, as coded in the file `tex/gloss-latin.ldf`, is `classic`. I have had a look at `doc/polyglossia.tex`, and, surprisingly, it seems that the section corresponding to Latin is not there. Nevertheless, I think the CTAN documentation should be fixed. Please, excuse me if this issue does not correspond to this list.

**Comment by reutenauer** [comment]
Many thanks for the report, it’s an oversight in my part.  I was about to correct it at some point but it slipped my mind.  I’ve just corrected it and will make an upload to CTAN shortly with the updated PDF.
